### ISSUE TITLE
There's no way to know deployment state without output window open

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#100]
If I have the output window closed, I have no way to know my app is being deployed or if it succeeds. Here are some possible improvements:
1. Use `vscode.window.withProgress` (this displays in the status bar, which isn't that visible either. But it's better than nothing - and maybe we could file a bug on VSCode to make it more obvious)
1. Use `vscode.window.showErrorMessage` instead of displaying errors in the output window
1. Show '(Deploying...)' on the node itself (related to https://github.com/Microsoft/vscode-azureappservice/issues/78)

**Comment by EricJizbaMSFT** [comment]
We automatically pop up the output window now.

We still want to implement #3, but it's lower priority

**Comment by whiskeyjay** [comment]
Similar customer feedback: https://github.com/Microsoft/vscode-azureappservice/issues/213

**Comment by EricJizbaMSFT** [comment]
Closing as dupe of https://github.com/Microsoft/vscode-azureappservice/issues/213
