### ISSUE TITLE
Deployment fails with no error message when switching GitHub deployment to Git deployment

### ISSUE THREAD

**Issue by demostheneslld** [microsoft/vscode-azureappservice#1003]
Repro steps:

1. Publish my application to an Azure App Service (Python Linux) via Git from VS Code with Azure App Service Extension. This is a Django App.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "eapcustomerportal" failed. See output channel for more details.

Version: 0.14.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:477324
o extension.bundle.js:1:475315
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @demostheneslld,

Are you following a tutorial or is this your own code??  Are you able to get this project running locally? Have you tried looking at the deployment logs for the failed deployment?  That can sometimes offer a more detailed error message.

You can find deployment logs in the Deployments node and clicking the log button on the right:

![image](https://user-images.githubusercontent.com/5290572/58356931-c9749680-7e2d-11e9-9518-d3839347f51e.png)

Or by looking under Logs node.

**Comment by demostheneslld** [comment]
Hi @nturinski. This was my own code. I was able to get the project running locally.
I ended up determining that this was due to the following steps:

1. Connect to Github Repository in Portal under Deployment Center
2. Switch deployment source to "local git" in VS Code Azure App Service with "Configure Deployment Source" option.
3. Attempt to deploy via local git with "Deploy to Web App" option

I was able to get this to work by turning off the github repository connection in the portal.
I don't see any deployment logs from before I fixed this issue, so I'm not sure if it was saying anything there.

It might be good to either have the "Configure Deployment Source" do the equivalent of disconnecting the GitHub publish option in the portal, or at least give a nicer error message in the popup? Would have saved a good bit of time. If this isn't a good idea for some other reason, feel free to close, or just mark as a feature request.

**Comment by nturinski** [comment]
@demostheneslld Thanks a bunch for reporting this.  Originally we didn't want to delete the Deployment Source so that the deployment history would persist, but if it's causing errors in deployment, then we'll have to approach this differently.

I'm really sorry about all the time you had to spend to debug this-- but again thanks again for bringing this up to our attention as I'm sure a lot of users face this frustration.

**Comment by nturinski** [comment]
Hi @demostheneslld

We've been trying to reproduce this, but haven't had any luck.  

I wonder if the Azure team has resolved this issue.  Could you let me know if you're able to repro this issue anymore?

**Comment by nturinski** [comment]
Closing due to lack of response.  Please let me know if you're still experiencing this issue.
