### ISSUE TITLE
Detect and support SPA apps

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#1006]
I'm still seeing a lot of folks from the tutorials running into issues when deploying an angular or react app via App Service so I'd like to come up with a good way to put them on a good path. Now that there's a free tier, it's seems okay to help them deploy on App Service so..

@burkeholland created a nice [writeup ](https://github.com/burkeholland/dead-simple-vue-azure)on how to make this with with a couple of config files.

I'm thinking the extension can detect when an app is a SPA app (parse package.json or look at the directory structure) and prompt the user. Give them the option to try something else or "Configure and deploy anyway" in which case the config files are added and the app is deployed.

Some challenges: the correct directory (dist or build) need to be deployed; oryx will run the build script, but that makes the deployment much slower..

**Comment by burkeholland** [comment]
We can infer where the "dist" folder is based on convention and then auto-fill a "Where is your build directory" prompt.

We should also think about folks deploying via Git. If they check their whole project into Azure Git, will Oryx do a build? If so, can we drop an ecosystem.config.js file into their project root that points at their "dist"?

**Comment by fiveisprime** [comment]
Could this be an image that's available from App Service? Maybe an generic nginx image with a default config that routes everything to index.html?

**Comment by burkeholland** [comment]
This is a good idea. Someone pointed out on Twitter that you can use the existing Java image which has Tomcat, so we might be able to just tie into that one. 

https://twitter.com/an0xff/status/1134155689667043328

I guess the answer would be "What is easiest for developers to configure". I guess nginx might be considered the "canonical" web server.

**Comment by burkeholland** [comment]
What sort of settings would a static site web server need to have? Thinking out loud...

* Mimetype mapping
* gzip/brotli compression
* Request timeouts
* Max request size

If we have a preconfigured nginx server, how could we allow developers to easily override the `nginx.conf` that we provide with their own without having to wipe out all of our settings?

**Comment by ejizba** [comment]
In theory it would be nice to direct users to static web apps. However, in practice it would be too difficult to accurately determine what is a static app and when to warn users
