### ISSUE TITLE
Error when using Azuer App Service extension and deploy to an existing App Services in ASE from VSCode

### ISSUE THREAD

**Issue by tedescomicchidev** [microsoft/vscode-azureappservice#1008]
Repro steps:

1. Install Azure App Services extension
2. Load or create ASP.NET Core project into VSCode
3. Use the extension to deploy to Azure existing Web App in an existing ASE

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND aseapp1.scm.mitedescase2.appserviceenvironment.net aseapp1.scm.mitedescase2.appserviceenvironment.net:443

Version: 0.14.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:50:26
```

</details>

**Comment by nturinski** [comment]
Hi @tedescomicchidev,

Sorry that you're having issues.  Is this issue recurring?  Sometimes Azure has outages that are beyond our control, unfortunately.  

Also, do you happen to know what your deployment source is configured to?

**Comment by tedescomicchidev** [comment]
Hi - Where can I check the details for my "deployment source"? 
Update: I needed to add the domain to the hosts file. Now at least I don't get an error, but the deployment goes on forever and never finishes. From the console I get:
`7:51:47 AM aseapp1: Creating zip package… `
`7:52:04 AM aseapp1: Starting deployment… `

**Comment by nturinski** [comment]
Are you using a custom domain?  If so, have you set this all up in the portal?
