### ISSUE TITLE
error deploy app in azure

### ISSUE THREAD

**Issue by gserra75** [microsoft/vscode-azureappservice#1010]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "janas-webapp" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.14.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:262:3454929
module.exports.n extension.bundle.js:262:3453562
module.exports.n extension.bundle.js:262:3453339
module.exports.t.deploy.i.window.withProgress extension.bundle.js:262:3454790
c._withProgress extensionHostProcess.js:448:323
c.withProgress extensionHostProcess.js:448:77
Object.withProgress extensionHostProcess.js:715:635
Object.<anonymous> extension.bundle.js:262:3454633
o extension.bundle.js:262:3453395
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @gserra75 If your app is connected to a GitHub repo, you should make a push to that branch.  It will trigger a build on your web app and continuously integrate.
