### ISSUE TITLE
Unable to establish connection to application: App is started, but port is unreachable

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1011]
**OS:** Win 10\Mac\Linux
**Build Version**: [20190527.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6338)

**Repro Steps:**
1. Create a Linux web app and make sure that you have not deployed any website to it.
2. Select "SSH into Web App" from the context menu.

**Expect:**
Succeed to execute the item without errors.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/58454996-bece4000-8152-11e9-8c32-e8af128ef5af.png)

**Comment by nturinski** [comment]
waiting for telemetry and/or customer feedback

**Comment by v-dantch** [comment]
Got you 🙆‍♀️

**Comment by EricJizbaMSFT** [comment]
This repro-ed for me consistently, but it works in the portal. Need to figure out what the portal is doing differently

**Comment by devlife** [comment]
Any update on this? It's happening for me consistently as well.

**Comment by EricJizbaMSFT** [comment]
Nothing yet. Current workaround is to do it at least once in the portal and then it seems to work in VS Code as well
