### ISSUE TITLE
ENOTFOUND management.microsoftazure.deproviders 

### ISSUE THREAD

**Issue by jfalameda** [microsoft/vscode-azureappservice#1018]
Repro steps:
Using a german subscription
When trying to create a new app for that subscription the following error shows.

Action: appService.CreateWebApp
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.microsoftazure.deproviders management.microsoftazure.deproviders:443

Version: 0.14.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
new n extension.bundle.js:262:3447779
$.callback extension.bundle.js:262:3446465
$.module.exports.e.exports.u.init.e.callback.t.callback [as _callback] extension.bundle.js:262:3445911
module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.EventEmitter.emit domain.js:442:20
$.module.exports.$.onRequestError extension.bundle.js:238:14516
ClientRequest.emit events.js:187:15
ClientRequest.EventEmitter.emit domain.js:442:20
TLSSocket.socketErrorListener _http_client.js:382:9
TLSSocket.emit events.js:182:13
TLSSocket.EventEmitter.emit domain.js:442:20
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @jfalameda

Thanks for reporting this issue.  Were you ever able to create web apps in that subscription with our extension?  Are you able to create web apps via the portal?
