### ISSUE TITLE
Generated from Visual Studio Code

### ISSUE THREAD

**Issue by chenlcacentury** [microsoft/vscode-azureappservice#1019]
Repro steps:

1. install azure app service extension
2. connect and deploy to app service

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND xxxxx.scm.azurewebsites.net xxxxxx.scm.azurewebsites.net:443

Version: 0.14.0
OS: win32
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:50:26
```

</details>

**Comment by nturinski** [comment]
Hi @chenlcacentury,

Thanks for reporting this issue. 

-  Is this issue recurring?  
- And is this a new app?

I've seen this error occurring if people are using a proxy.  You might have to configure a custom domain.  

This could be helpful: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-configure-custom-domain
