### ISSUE TITLE
Local git deploy should inform user when changing scmType

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#102]
I deployed local git for the first time and it took longer than expected. Subsequent deployments didn't take as long. This leads me to believe the culprit was updating the configuration from 'None' to 'LocalGit'.

We should show some sort of message (info message, warning message, or even just a log in the output window - I don't have a strong opinion) to let the user know what's happening.

**Comment by nturinski** [comment]
I think it took longer because it was a clean deploy and had to send and install all the files whereas subsequent deployments only send the delta.  I had a console log display with configs were finished updating and I don't believe that it took more than a couple of seconds.

**Comment by EricJizbaMSFT** [comment]
Hmm I did some further investigation and [this call](https://github.com/Microsoft/vscode-azureappservice/blob/master/src/explorer/siteNodeBase.ts#L184) took 35-45 seconds to complete the first time trying git deploy on a web app (later ones were faster).

I think you're correct that the first deployment will take longer regardless, but I wonder if the message "Local Git repo is current with ..." is worth the possible delay of 45 seconds on the first deploy? (assuming you can repro the issue)

**Comment by nturinski** [comment]
Fixed with latest Local Git Deploy merge
