### ISSUE TITLE
[Suggestion] Add more notification after turning on in User Setting

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1028]
**OS:** All
**Build Version:** [20190606.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6612)

**Repro Steps:**
1. Make sure that there are 3 Linux web app at least.
2. Try to create a  new Linux web app again.
3. Pop up a dialog --> Select "Turn on advanced creation".

**Actual:**
Open the user setting and the action terminates.

**Suggestion:**
Add more notification after turning on advanced creation in User Setting like "Please reload the VS Code" or anything else.
![image](https://user-images.githubusercontent.com/34729092/59021729-f2117d00-887e-11e9-8136-8109de603b88.png)

**Comment by nturinski** [comment]
With the new advanced creation, this does not apply anymore so I'll go ahead and close this
