### ISSUE TITLE
"Don't warn again" doesn't work

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1029]
**OS:** All
**Build Version:** [20190606.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6612)

**Repro Steps:**
1. Make sure that there are 3 Linux web app at least.
2. Try to create a  new Linux web app again.
3. Pop up a dialog --> Select "Don't warn again".

**Expect:**
This dialog doesn't pop up when creating another new Linux web app.

**Actual:**
"Don't warn again" doesn't work and this dialog still pops up when creating another new Linux web app.

**More **Info:****
The setting is still checked after selecting "Don't warn again".
![image](https://user-images.githubusercontent.com/34729092/59022159-d064c580-887f-11e9-98f0-dd34af9c268e.png)

**Comment by nturinski** [comment]
@v-dantch I'm assuming that this is because you don't have a workspace opened.  Thanks for reporting, making a fix now 😃

**Comment by v-dantch** [comment]
Hi Nathan, yes, you are right😲. There is no opened workspace when logging this issue. 
And "Don't warn again" works well if there is a opened workspace. 
Today we verified this issue on the latest build [20190606.30](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6648
), it works well even though there is no opened workspace.
