### ISSUE TITLE
[Suggestion] Support to auto navigate to the correct tag in Output Window

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1031]
**OS:** All
**Build Version:** [20190606.16](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6612)

**Repro Steps:**
1. Select "Start Streaming Logs" from the context menu -->Check the tag in Output window.
2. Select "Configure the Deployment Source..." from the context menu --> Check the tag in Output window.
3. Check whether it will auto navigate to the correct tag or not.

**Actual:**
It doesn't auto navigate to the correct tag "Azure App Service ".
![image](https://user-images.githubusercontent.com/34729092/59022966-57666d80-8881-11e9-9ce1-7e75d5419735.png)

**Suggestion:**
Support to auto navigate to the correct tag in Output window.

**Comment by nturinski** [comment]
We used to open the output channel for the users but received feedback that it was annoying and intrusive.

If I'm understanding correctly, the suggestion is to automatically open the Azure App Service channel for the user, right?

**Comment by v-dantch** [comment]
Correct :).

**Comment by nturinski** [comment]
@v-dantch

Thanks for your suggestion!  But as I mentioned, users said that opening the output channel for them was a little bit annoying so I'll close this unless we get user feedback.
