### ISSUE TITLE
use the vs code create app service meet the below error

### ISSUE THREAD

**Issue by abulu** [microsoft/vscode-azureappservice#1040]
Repro steps:

1. create the app service in vs Code.

Action: appService.Deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: location

Version: 0.14.0
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
s extension.bundle.js:1:148498
Object.i [as nonNullProp] extension.bundle.js:1:148440
Object.<anonymous> extension.bundle.js:262:3450666
o extension.bundle.js:262:3449236
```

</details>

**Comment by nturinski** [comment]
Hi @abulu 

Sorry that you're running into this issue. If you change your VS Code settings to enable appService.advancedCreation, you can select the location for your app. 

If you're not familiar with settings in VS Code, it's under File > Preferences > Settings
And then filter for appService.advancedCreation.

https://user-images.githubusercontent.com/5290572/52449108-f0ab9000-2aea-11e9-8791-782f3f4450c6.png

Let me know if this resolves your issue!
