### ISSUE TITLE
Error Message: Failed to get status of deployment.

### ISSUE THREAD

**Issue by lakhanpalv** [microsoft/vscode-azureappservice#1046]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @lakhanpalv

Sorry that you're having issues with deployment.  Could you add repro steps, please?
