### ISSUE TITLE
App Service nodes appear and disappear

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azureappservice#1050]
When i toggle to open some app service instances, the others disappear. See the GIF  below.

![2019-06-23_19-55-05](https://user-images.githubusercontent.com/1202528/59988761-1d22fd00-95f1-11e9-88a1-83b3031327e4.gif)

version ... 
![image](https://user-images.githubusercontent.com/1202528/59988799-3e83e900-95f1-11e9-89ce-dcb63a761b83.png)

**Comment by nturinski** [comment]
Hi @johnpapa

Do you know if this is still happening?  I'm not able to reproduce this on my Mac with the current VS Code build.

**Comment by nturinski** [comment]
Closing due to lack of response.

**Comment by johnpapa** [comment]
Just saw this. No it doesn’t happen anymore.
