### ISSUE TITLE
choose-repository

### ISSUE THREAD

**Issue by Ladiesoftheweb** [microsoft/vscode-azureappservice#1051]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Conflict
Error Message: There was a conflict. AlwaysOn cannot be set for this site as the plan does not allow it.

Version: 0.15.0
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.36.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.Ts.l.pipeline extension.bundle.js:262:2544801
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @Ladiesoftheweb 

What type of SKU are you using for your App Service Plan?  I believe Shared plans do not support the AlwaysOn setting.

**Comment by Ladiesoftheweb** [comment]
module.exports.Ts.l.pipeline extension.bundle.js:262:2544801
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19

**Comment by nturinski** [comment]
Hi @Ladiesoftheweb,

Thanks for this stack trace, but this doesn't help resolve the issue.  Could you tell me what your app service plan's SKU is?
