### ISSUE TITLE
Error deploying Nuxtjs

### ISSUE THREAD

**Issue by lewyuburi** [microsoft/vscode-azureappservice#1052]
Repro steps:

1. Create a Nuxtjs App with expressjs
2. Deploy

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "x" failed. See output channel for more details.

Version: 0.15.0
OS: linux
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:477530
o extension.bundle.js:1:475521
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @lewyuburi,

Is this a new web app?  Does this issue recur?  Sometimes new apps take a while to provision.

**Comment by lewyuburi** [comment]
Hi @nturinski, yes! I was able to deploy correctly :D
