### ISSUE TITLE
Failed to Get Status of Deployment

### ISSUE THREAD

**Issue by demostheneslld** [microsoft/vscode-azureappservice#1053]
Repro steps:

1. Publish Application from Azure App Service Extension

I had this same error before (this issues: https://github.com/microsoft/vscode-azureappservice/issues/1003); however, this time nothing has changed since yesterday when I published changes twice with no issues.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

![image](https://user-images.githubusercontent.com/8669241/60104539-87818d80-9716-11e9-95b0-1f9e331f2422.png)

![image](https://user-images.githubusercontent.com/8669241/60104620-b435a500-9716-11e9-9038-59ca8d74f9f1.png)

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
@demostheneslld Do you know if the portal lists any of your published changes?  You can check by following this document (https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-common-deployment-errors#deployment-errors)

**Comment by demostheneslld** [comment]
@nturinski there were no changes listed in the Portal, and no notifications of failed deployment per the document you sent. It failed several times in a row with the same result. I ended up making a new commit last night and it published just fine. Is it possible that there was some sort of issue on the Azure side with connecting or something?

**Comment by nturinski** [comment]
@demostheneslld Yeah, sometimes there are just strange outages.  If the portal wasn't indicating that any of these deployments failed, it could be webhook was down for the .git repository or something too.  Glad it's resolved, but I'll leave this open to see if there's something we can do on our end to mitigate this error.
