### ISSUE TITLE
Cannot add Application Settings (environment variables) in VS Code using Azure App Service extension

### ISSUE THREAD

**Issue by aehe** [microsoft/vscode-azureappservice#1058]
Repro steps:

1.
2.

Action: appService.appSettings.Add
Error type: BadRequest
Error Message: AppSetting with name 'MICROSOFT_APP_ID=942d6fbe-f8c1-40ed-83e3-67fcad5fc86d' is not allowed.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.E.l.pipeline extension.bundle.js:262:1454812
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @aehe

For the app setting, I believe that you are pasting the entire app setting into the "key". 

You should do as "MICROSOFT_APP_ID" the key and "942d6fbe-f8c1-40ed-83e3-67fcad5fc86d" as the value.  Here's an example:

![appsetting](https://user-images.githubusercontent.com/5290572/60608215-ca291280-9d73-11e9-885f-c30c884a41d3.gif)
