### ISSUE TITLE
Is it compulsory to have proper git repo url commited ?

### ISSUE THREAD

**Issue by RJK23** [microsoft/vscode-azureappservice#1059]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: your current branch 'master' does not have any commits yet

Version: 0.13.1
OS: win32
VS Code Version: 1.25.1

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:333:824733)
Generator.throw (<anonymous>)
a (dist/extension.bundle.js:333:824407)
<anonymous>
```

</details>

**Comment by nturinski** [comment]
Hi @RJK23

It's only required if you are using Git deployment.  If you right-click the Deployments node, you can configure the deployment source.  If set to none, there is no requirement for a git repo.

**Comment by nturinski** [comment]
Closing due to lack of response.

**Comment by RJK23** [comment]
> Hi @RJK23
> 
> It's only required if you are using Git deployment. If you right-click the Deployments node, you can configure the deployment source. If set to none, there is no requirement for a git repo.

Yes agreed Thanks :)
