### ISSUE TITLE
I see this message when I create azure web app in vscode. (I try to deploy loopback app to azure)

### ISSUE THREAD

**Issue by onwebcity** [microsoft/vscode-azureappservice#1062]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: BadRequest
Error Message: Exceeded the limit of 1 free tier linux server farm per subscription.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.l.pipeline extension.bundle.js:262:3299936
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @onwebcity

Unfortunately Azure only offers one free Linux app service plan per subscription.  You can either create your web app in the existing plan or you can create a free Windows app service plan.

Please let me know if that resolves your issue!

**Comment by onwebcity** [comment]
Hi @nturinski 
In my case, @kms-binhtran do that on DevOps and it is resolved, Thank you for helps

**Comment by onwebcity** [comment]
Hi @nturinski , Can you help me to change the config of virtual paths in the devops? What is the key for that and directory i wanted to change is /home/site/wwwroot/frontend/dist/frontend. How can i make it to that path?

**Comment by nturinski** [comment]
Hi @onwebcity,

What kind of project are you deploying?  I'm not sure if this is handled by Dev Ops as much as your project's settings.  For instance, in a node.js project, I believe the `package.json`'s "main" property is used as the start-up script.

If you just want your directory to look like that when you deploy, you will need to deploy your project with that structure beforehand.
