### ISSUE TITLE
Cannot deploy web app from VSCode

### ISSUE THREAD

**Issue by leecottrellPTC** [microsoft/vscode-azureappservice#1064]
Repro steps:

I followed the steps from https://code.visualstudio.com/docs/java/java-webapp
I worked with the complete folder in the GitHub clone
I left their code alone (did not change the return)
1. open the terminal
2. cd complete
3. mvn clean package
package built successfully
4. rt click .jar file and select Deploy to web app
5. Select my existing Azure web app (both with the service running and stopped)
![Capture](https://user-images.githubusercontent.com/44240965/60986515-a0409480-a30d-11e9-8bf6-64c5407aa7a0.PNG)

I have the same problem with both the basic spring-boot sample and more complex ones that I have written

For completeness, I attached a  .zip of the project.
[gs-spring-boot.zip](https://github.com/microsoft/vscode-azureappservice/files/3378478/gs-spring-boot.zip)

Action: appService.Deploy
Error type: Error
Error Message: spawn c:\Users\lee\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.deserializeSearchError workbench.main.js:3924:413
Promise.all.then.t workbench.main.js:4558:215
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @leecottrellPTC,

Thanks for reporting this.  Sorry for the late response.  I'll investigate this, but would also like to add @jdneo as he did most of the work involving Java.

**Comment by jdneo** [comment]
Hi @leecottrellPTC,

I'm guessing that the .jar file you have deployed is not named as `app.jar` which is a requirement from the server side. We have an issue tracking for this: https://github.com/microsoft/vscode-azureappservice/issues/783. Would you mind to rename your jar to `app.jar` and try again?

Thanks.
