### ISSUE TITLE
When I try to deploy I get this error message {} the error is not informative.

### ISSUE THREAD

**Issue by Fabian02** [microsoft/vscode-azureappservice#1065]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: {}

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.27.2
Language: en

**Comment by nturinski** [comment]
Hi @Fabian02,

I whole-heartedly agree that is not useful!  Could you please provide repro steps on how you are getting this error?
