### ISSUE TITLE
an issue

### ISSUE THREAD

**Issue by zhouchaoyuan** [microsoft/vscode-azureappservice#1067]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription 'de201c79-be81-431a-873b-208223162d0c' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:262:505405
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @zhouchaoyuan,

Sorry for this issue. If you were using a free 30-day trial, your trial may have expired. I believe that this documentation will be helpful in resolving your issue: https://docs.microsoft.com/en-us/azure/billing/billing-subscription-become-disable.

If your problem isn't resolved by this, please re-open this issue with some more details on how I can assist you.
