### ISSUE TITLE
Angular JS to Azure

### ISSUE THREAD

**Issue by 4rcherry** [microsoft/vscode-azureappservice#1068]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @4rcherry,

Could you provide repro steps, please?
