### ISSUE TITLE
Failed to deploy app from Local Git via VScode

### ISSUE THREAD

**Issue by AtinMaiti** [microsoft/vscode-azureappservice#1070]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @AtinMaiti 

Thanks for reporting.  Could you provide repro steps?
