### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SaideepReddy6** [microsoft/vscode-azureappservice#1071]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: your current branch 'master' does not have any commits yet

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
```

</details>

**Comment by nturinski** [comment]
Hi @SaideepReddy6 

Thanks for reporting.  Looks like you're doing a git deployment with a repo that doesn't have any commits.  Please try this in your project's working directory:

```
git add .
git commit -m 'First commit'
```

And then try deploying again.  If this doesn't resolve your issue, please reopen with repro steps.
