### ISSUE TITLE
Deployment error, Nodejs/React, deployment source local git

### ISSUE THREAD

**Issue by Kelpieracer** [microsoft/vscode-azureappservice#1074]
Repro steps:

1.Deploying Nodejs/React webapp to azure linux 
2.

Action: appService.Deploy
Error type: Error
Error Message: getaddrinfo ENOTFOUND XXX.scm.azurewebsites.net XXX.scm.azurewebsites.net:443

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @Kelpieracer

Thanks for reporting this issue.

Is this issue recurring?
And is this a new app?
I've seen this error occurring if people are using a proxy. You might have to configure a custom domain.

**Comment by Kelpieracer** [comment]
Hi, I haven't received this error again (but I have only deployed once after receiving this error).

**Comment by Kelpieracer** [comment]
Forgot... yes this is a new app. I'm not sure if it was the first deployment. Possibly.

**Comment by nturinski** [comment]
@Kelpieracer Okay, I'll keep monitoring this.  Let me know if you run into this issue again.
