### ISSUE TITLE
Failed to get status of azure deployment

### ISSUE THREAD

**Issue by Kelpieracer** [microsoft/vscode-azureappservice#1075]
Repro steps:

1. NodeJs/React app to azure web app from local git
2. This happens every third time. Restarting deployment often helps. This is similar to #1046 (which is closed)

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @Kelpieracer,

Thanks for reporting.  When you say every third time, are the deploys in quick succession, or is it typically over the course of a days/weeks?  

Also, what method are you using to deploy?

Thanks!

**Comment by Kelpieracer** [comment]
Hi, I am using the azure services extension in vs code. I deploy currently once a day. It feels like the first deployment always terminates in this error. When I try again, it is quite often a success, but sometimes another error comes up. Anyway, I have always been able to deploy after all, just need to re-start the process once or twice.

**Comment by nturinski** [comment]
@Kelpieracer Do you know what your deployment source is.  You can check by expanding the web app node and looking next to the Deployments node.  If there is nothing, then that is consider "None" which uses a zipdeploy method.

![image](https://user-images.githubusercontent.com/5290572/61973066-0416be80-af98-11e9-8d9c-425c0e605577.png)

**Comment by Kelpieracer** [comment]
Hi, sorry took so long to come back.
Yes, deployment source is local git, as I wrote in my opening post.

**Comment by nturinski** [comment]
@Kelpieracer Oh, sorry, totally missed that.  Hmm, do you know what tier of app service plan you're on?  

I think there might be a chance on the first deployment, your web app needs to do a cold start.  Could you try browsing to your web app first to ensure that it has started up before you do your next deploy?
