### ISSUE TITLE
NodeJS/React deployment, vscode/gui-git failed to detect renaming of source files

### ISSUE THREAD

**Issue by Kelpieracer** [microsoft/vscode-azureappservice#1076]
Failed to compile
./src/page.js
Cannot find file: 'RecordAssetValues.js' does not match the corresponding name on disk: './src/recordassetvalues.js'.
This error occurred during the build time and cannot be dismissed.

For some reason file rename (by F2) in VS code source files directory is not always detected by local Git, and deployment fails. 
Repro steps:
1 file name RecordAsset.js -> commit git -> deploy -> works
2 rename file to recordasset.js and modify imports to point to 'recordasset' -> commit git -> deploy -> error like above
This may have something to do with the fact that VS code editor has the file open when renaming?

**Comment by nturinski** [comment]
Hi @Kelpieracer

Thanks for reporting this.  Just to make sure I understand the problem, it seems like you're having issues with the Source Control view recognizing your changes.  If that's correct, please file an issue on VS Code (https://github.com/microsoft/vscode) since we don't have any control over this view.

If that's incorrect, then let me know and we'll try to resolve this issue!

**Comment by Kelpieracer** [comment]
Hi @nturinski, I think the problem is in VS Code side (Win). Just guessing, that maybe VS Code caches the file name change when the file is open in the editor, but not edited. So I see that the filename has changed in VS Code folder view, and in the editor tab. But is not actually saved yet to the file system, and therefore Git cannot know about it. I can try to reproduce it again sometime soon.

**Comment by nturinski** [comment]
@Kelpieracer Could you leave an issue on the VS Code repo located here: https://github.com/microsoft/vscode?  They should be the one managing that view.  Unfortunately, our extension has no control over that.

Thanks again for reporting. Closing as external.
