### ISSUE TITLE
Not able to create new web app for deploying test code from VS Code Node project

### ISSUE THREAD

**Issue by kokkoon** [microsoft/vscode-azureappservice#1084]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Conflict
Error Message: The pricing tier 'LinuxFree' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.l.pipeline extension.bundle.js:262:3299936
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
$.module.exports.t.create.o.statusCode.t.registerRP.n [as _callback] extension.bundle.js:157:27249
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:182:13
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @kokkoon 

Thanks for reporting this.  I'm currently investigating the cause of this error.  For now, the workaround would be to create a Free Windows app.  You can do this by going into your VS Code settings and enabling appService.advancedCreation to be true.

**Comment by nturinski** [comment]
Hi @kokkoon,

This issue should be resolved now.  Could you please try and let me know?

Thanks!

**Comment by nturinski** [comment]
Closed due to lack of response.  Please reopen if you're still having issues.
