### ISSUE TITLE
Deploy angular 8 with visual studio code

### ISSUE THREAD

**Issue by Dagabad** [microsoft/vscode-azureappservice#1088]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "GameOfDronesDag" failed. See output channel for more details.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:477530
o extension.bundle.js:1:475521
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @microsoft/flumapmodel 
Could you provide repro steps please?
