### ISSUE TITLE
ignoredFolder does not contains appropriate content for each runtime

### ISSUE THREAD

**Issue by jasmingoh** [microsoft/vscode-azureappservice#1091]
![image](https://user-images.githubusercontent.com/20333350/62727156-ae95d500-b9cd-11e9-957c-277508db4f5c.png)

When runtime is node, the ignoredFolders does not contain 'node_module{,/**}`.
Seems like there should be `break` for each of the switch cases.

**Comment by nturinski** [comment]
@jasmingoh Thanks for reporting this issue.  Definitely is a bug, should have break statements there.
