### ISSUE TITLE
Azure deployment ENOENT error

### ISSUE THREAD

**Issue by dshafique** [microsoft/vscode-azureappservice#1092]
Repro steps:

1. right click on Jar file under complete folder deploy to web
2.

Action: appService.Deploy
Error type: Error
Error Message: spawn c:\Users\dawud\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.deserializeSearchError workbench.main.js:4033:189
Promise.all.then.t workbench.main.js:4680:682
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @dshafique,

Is this problem recurring? It seems like your VS Code directory could be corrupted.  Could you try uninstalling and reinstalling?

**Comment by SteelCodeJacoboQuiroz** [comment]
I have the same problem with the same config:
spawn c:\Users\Rodrigo Vera\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

the file exist.

**Comment by nturinski** [comment]
@SteelCodeJacoboQuiroz 

Do you know if your VS Code directory is corrupted?  Have you tried uninstalling and reinstalling?

**Comment by bipinmangwani1** [comment]
I've the same problem. VSCode directory seems ok to me, and I can see that this file exists: VSCode1.37.1\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe. I'm trying to deploy an already created war file via VSCode Azure app service extension, and repeatedly get

Error: spawn c:\dev\apps\VSCode1.37.1\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

**Comment by nturinski** [comment]
Hi @bipinmangwani1 

Looking at these threads, it doesn't seem like the cause of this issue is very clear:
https://github.com/Microsoft/vscode/issues/63305
https://www.gitmemory.com/issue/microsoft/vscode-azureappservice/1092/521828227

I recommend uninstalling VS Code and then reinstalling it.

**Comment by bipinmangwani1** [comment]
Hi - reinstalled VSCode - still the same problem!
Error: spawn c:\dev\apps\VSCode1.38.0\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe ENOENT

**Comment by nturinski** [comment]
Okay, maybe this behavior is related to it being a Java deployment.  I will investigate further-- thanks for reporting!

**Comment by EricJizbaMSFT** [comment]
We never got a repro on this - if it's still a problem for you guys please let us know
