### ISSUE TITLE
Support to execute "Launch Logpoints Debug Session" from Command Palette

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1093]
**OS:** Win10
**Build Version:** [20190808.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8651)
**Regression**: Not a Regression

**Repro Steps:**
1. F1 --> Type "Launch Logpoints Debug Session".
2. Check the result.

**Expect:**
List "Launch Logpoints Debug Session".

**Actual:**
No commands match.
![image](https://user-images.githubusercontent.com/34729092/62757172-3c55dc80-ba2f-11e9-8c7d-379a0b931127.png)

**Comment by nturinski** [comment]
Closing due to https://github.com/microsoft/vscode-azureappservice/issues/1100

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
