### ISSUE TITLE
Only display the version of runtime in error when executing "Launch Logpoints Debug Session"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1094]
**OS:** Win10
**Build Version:** [20190808.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8651)
**Regression**: Not a Regression

**Repro Steps:**
1. Create a Linux web app with Node.js 10.14 runtime.
2. Right click this app --> Select "Launch Logpoints Debug Session".
3. Pop up an error due to it is not supported.
4. Check the error.

**Expect:**
List a complete runtime information: runtime name and version.

**Actual:**
Only display the version of runtime.
![image](https://user-images.githubusercontent.com/34729092/62758093-3a414d00-ba32-11e9-916b-d4ae3549c3f0.png)

**Comment by nturinski** [comment]
Hi Megan,

Thanks for reporting this.  It turns out that Logpoints is going to be removed from the extension so don't worry about this.

See this issue for more information: Launch Logpoints Debug Session
