### ISSUE TITLE
Fail to create a Linux web app due to the default pricing tier "LinuxFree" with basic creation

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1099]
**OS:** Mac
**Build Version:** [20190815.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8863)

**Repro Steps:**
1. Right click the applied subscription --> Select "Create New Web App...".
2. Enter a name --> Select an OS --> Select a runtime according to the notification.
![image](https://user-images.githubusercontent.com/34729092/63089887-02835980-bf8c-11e9-8ac6-b345435b2510.png)
3. Check the result.

**Expect:**
Succeed to create the Linux web app.

**Actual:**
Fail to create the Linux web app due to the default configurations.
![image](https://user-images.githubusercontent.com/34729092/63089922-29da2680-bf8c-11e9-83fb-b43ef83a2a69.png)

**Comment by nturinski** [comment]
Hi @v-dantch,

I believe this was due to an issue on the platform side.  It should be resolved now, so could you please test this out again and let me know?

I created a few times to verify that it was working, but always good to have a second opinion 😄

**Comment by v-dantch** [comment]
Verified on Mac and Windows with the latest build [20190818.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8950). This issue does not repro. Could you help to close it 😄?

**Comment by nturinski** [comment]
👍
