### ISSUE TITLE
"resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+[^.]$/

### ISSUE THREAD

**Issue by kataday** [microsoft/vscode-azureappservice#1105]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+[^.]$/

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: ja

<details>
<summary>Call Stack</summary>

```
WebApps.V [as _getConfiguration] extension.bundle.js:262:1531359
module.exports.e.exports.getConfiguration.Promise extension.bundle.js:262:2795056
WebApps.getConfiguration extension.bundle.js:262:2795034
SiteClient.<anonymous> extension.bundle.js:332:362597
module.exports.n extension.bundle.js:332:359717
module.exports.n extension.bundle.js:332:359494
SiteClient.getSiteConfig extension.bundle.js:332:362420
Object.<anonymous> extension.bundle.js:157:229903
o extension.bundle.js:157:228103
```

</details>

**Comment by nturinski** [comment]
Hi @kataday,

Could you provide repro steps?  What name did you use for the resource group?

**Comment by kataday** [comment]
Hi @nturinski,

I'm sorry...,

When I checked the name of the resource group that I created, it contained Japanese.
Close because there is no problem.
