### ISSUE TITLE
Navigate to "Overview" tab when selecting "Open in Portal" from the context menu of "Application Settings"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1107]
**Version:** 1.38.0-insider (user setup)
**Commit**: c8d44e24dd250d416475a10efe64e35c9e2c65b3
**OS**: Windows_NT x64 10.0.17763
**Build Version**: [20190820.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8986)

**Repro Steps:**
1. Drill down form the applied subscription -> one web app -> Application Settings.
2. Right click the "Application Settings" node  --> Select "Open in Portal".

**Expect:**
Open the Azure Portal and navigate to the "**Application Settings**" tab.

**Actual:**
Open the Azure Portal, but navigate to the "**Overview**" tab.
![image](https://user-images.githubusercontent.com/34729092/63409935-b2414700-c424-11e9-8eb9-0bcc9c1f8d76.png)

**Comment by nturinski** [comment]
Thanks for reporting @v-dantch.  This is actually fixed by this PR https://github.com/microsoft/vscode-azuretools/pull/568 😄 It should be included in App Service soon.

**Comment by v-dantch** [comment]
Got you. Thanks for your share 😄.
