### ISSUE TITLE
[Suggestion]Add a button to open the target project folder in the deploying error notification 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1108]
**Version:** 1.38.0-insider (user setup)
**Commit**: c8d44e24dd250d416475a10efe64e35c9e2c65b3
**OS**: Windows_NT x64 10.0.17763
**Build Version**: [20190820.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8986)

**Repro Steps:**
1. Make sure the target project folder is not opened in VS Code.
2. Click "Deploy to Web App..." in App Service Explorer--> Browse the open the target project according to the prompting.
3. Pop up an error.

**Actual:**
There is no button to support the users to open the target project folder directly.
![image](https://user-images.githubusercontent.com/34729092/63410408-d3566780-c425-11e9-9978-c012ec7cea92.png)

**Suggestion:**
Add a button to open the target project folder in the deploying error notification.

**More Info:**
About "Browse...", is there any possible to remove it and add a dialog/notification after selecting "Deploy to Web App..."?
Due to it will trigger the deploying error if the users browse and open a project which is not contained in workspace.
And it is not necessary if the users browse and open a project which has been contained in workspace.
![image](https://user-images.githubusercontent.com/34729092/63410690-77401300-c426-11e9-80e3-6365a2fce5a8.png)

**Comment by nturinski** [comment]
@v-dantch I think that this is a very good point 

@EricJizbaMSFT.  I think we kept `Browse..` in case they wanted to deploy a subpath, but it's confusing for users to browse to a different folder and have it fail immediately.

**Comment by EricJizbaMSFT** [comment]
@nturinski what's your suggested alternative?

Also is there telemetry on how often people use browse for a sub path vs. a folder outside the workspace?

NOTE: This prompt should _not_ be shown if they have deploySubpath set

**Comment by v-dantch** [comment]
Hi Nathan / Eric, how about adding a dialog with 3 butons like below screenshot:
![image](https://user-images.githubusercontent.com/34729092/63482296-f71fb900-c4ca-11e9-85ae-ed59a49bcd19.png)

**Deploy the Outside:** The VS Code will reload after selecting it--> Then prompt to browse the outside workspace --> Continue to deploy the outside workspace to web app. And prompt the users to save the current workspace before reloading VS Code.
**Deploy a Open Workspace**: Select the target workspace directly from the list after selecting it --> Deploy.
**Deploy a Subpath:** Browse the sub-path --> deploy.

**Comment by EricJizbaMSFT** [comment]
Let's at least investigate adding telemetry to see how often people browse to a subfolder vs. external folder
