### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Jdure** [microsoft/vscode-azureappservice#1110]
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: Error
Error Message: Entry not found in cache.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457extension.js:229:171457
extension.js:229:43512extension.js:229:43512
extension.js:229:41505extension.js:229:41505
extension.js:229:41127extension.js:229:41127
i.module.exports.i.find extension.js:229:75620
module.exports.find.init.then extension.js:229:22917
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @Jdure,

Thanks for reporting. We are still tracking the external issue here:
AzureAD/azure-activedirectory-library-for-nodejs#199

Please add some 👍's to give the team feedback that this is an issue worth resolving!
