### ISSUE TITLE
The overrode progress is terminated before canceling/completing the new progress

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1115]
**OS:** Win10
**Build Version:** [20190825.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9162)

**Repro Steps:**
1. Right click one web app --> Select "Configure Deployment Source...".
2. Right click another one web app --> Select "Configure Deployment Source..." --> Complete the action according to the notification.
3. Check the result.

**Expect:**
There is a prompting to tell the users the current progress is in progress.

**Actual:**
The first process is terminated and there is no any prompting.

**Comment by nturinski** [comment]
Thanks for reporting this!  But this seems like a pretty edge case though, so we won't fix it.
