### ISSUE TITLE
Can't create Azure App Service in VSCode on Raspberry Pi

### ISSUE THREAD

**Issue by codescoast** [microsoft/vscode-azureappservice#1121]
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: object
Error Message: {}

Version: 0.15.0
OS: linux
Product: Code - OSS (headmelted)
Product Version: 1.29.0
Language: en

**Comment by nturinski** [comment]
Sorry, but we don't test/support for Raspberry Pi.  If you really want to use your Raspberry Pi as a dev machine, you can set up a VM and use VS Code SSH https://code.visualstudio.com/docs/remote/ssh

**Comment by codescoast** [comment]
@nturinski , thanks for your reply!

I don't think VS Code does not support Raspberry Pi. 
Actually I already using it for a while on my Raspberry Pi, it runs pretty well. It's a great code editor on Raspberry Pi for Python or other language. Along with Raspberry Pi 4 release, it can be used as a great light weight dev machine!

The issue is just about a function in the Azure extension for VS Code. It's okay as it's an edge case, and I can workaround it by using portal or another windows machine.

**Comment by nturinski** [comment]
Hi @codescoast

It's awesome that you're able to use VS Code on your Raspberry Pi!  I meant that our extension, the Azure App Service extension, doesn't have the resources to test for it though.  But I'm glad that you are able to work around this issue.
