### ISSUE TITLE
Issue while deploying Angular App using VS Code as Web App on Microsoft Azure

### ISSUE THREAD

**Issue by maheshsabnis** [microsoft/vscode-azureappservice#1124]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: socket hang up

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
createHangUpError _http_client.js:322:15
TLSSocket.socketOnEnd _http_client.js:425:23
TLSSocket.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @maheshsabnis

Thanks for reporting.  Could you provide repro steps?

**Comment by maheshsabnis** [comment]
Hi nturinski ,

 I am sorry for not replying in time because I was deployed on some other project. I will so this again and provide you details.
