### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by daniporras** [microsoft/vscode-azureappservice#1127]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457
extension.js:229:43573
extension.js:229:41975
extension.js:229:41127
i.module.exports.i.find extension.js:229:75620
module.exports.find.init.then extension.js:229:22917
```

</details>

**Comment by nturinski** [comment]
Hi @daniporras,

Thanks for reporting. We are still tracking the external issue here:
AzureAD/azure-activedirectory-library-for-nodejs#199

Please add some 👍's to give the team feedback that this is an issue worth resolving!
