### ISSUE TITLE
issue azure vscode

### ISSUE THREAD

**Issue by ManuelOrdonez** [microsoft/vscode-azureappservice#1130]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSWrap.onStreamRead stream_base_commons.js:111:27
```

</details>

**Comment by nturinski** [comment]
Hi @ManuelOrdonez 

Thanks for reporting.  Could you provide repro steps?
