### ISSUE TITLE
Service is Unavailable

### ISSUE THREAD

**Issue by kikemx78** [microsoft/vscode-azureappservice#1134]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 503
Error Message: The service is unavailable.

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline extension.bundle.js:332:742409
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by kikemx78** [comment]
Hi @nturinski , just follow your own tutorial here 

https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs

:)

**Comment by nturinski** [comment]
@kikemx78 

Are you still having issues? I can't repro it, but sometimes a new subscription or web app will run into this problem.  Have you tried again?

**Comment by kikemx78** [comment]
@nturinski 

I was able to deploy but now there is this error

:( Application Error
If you are the application administrator, you can access the diagnostic resources.

Again, to reproduce you just have to follow the tutorial at https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs

Thank you !

**Comment by EricJizbaMSFT** [comment]
This is a somewhat common error out of our control in VS Code. Please take a look at these troubleshooting tips: https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503
