### ISSUE TITLE
What happens when you click "yes" to the notification that runs npm install on the target server?

### ISSUE THREAD

**Issue by shanberg1** [microsoft/vscode-azureappservice#1137]
How can i replicate it in the azure portal?

**Comment by nturinski** [comment]
Hi @shanberg1

In our extension, we generate a `.deployment` file that sets the config to include this setting: `SCM_DO_BUILD_DURING_DEPLOYMENT = true`.  The target server reads that file and then knows to run the build command (`dotnet build/npm install`)

If you want to replicate that on the Portal, you can edit the App Setting manually.  This is explained here: https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions

**Comment by shanberg1** [comment]
Thanks!

**Comment by shanberg1** [comment]
Sorry, one more question.  The
