### ISSUE TITLE
Deploy to Azure App Service Deployment Slot Fails

### ISSUE THREAD

**Issue by rkralston** [microsoft/vscode-azureappservice#1150]
Repro steps:

1.Right click Deploymnet slot
2.Choose Deploy to Slot
3.Pick local directory
4.Log shows zipping and starting deployment and then it fails.

Action: appService.DeploySlot
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1049:34
TLSSocket.emit events.js:182:13
TLSSocket._finishInit _tls_wrap.js:631:8
```

</details>

**Comment by nturinski** [comment]
@rkralston are you behind a proxy?

There is a setting (http.systemProxy) which defaults to force and may fix your issue. See microsoft/vscode-azure-account#27 for more info.
