### ISSUE TITLE
Error that resource group can't be found, when in fact it is created.

### ISSUE THREAD

**Issue by brianrandell** [microsoft/vscode-azureappservice#1153]
Repro steps:
1. Create a new asp.net core 2.2 mvc app.
2. Publish the app to a publish folder:
dotnet publish -c Release -o ./publish
3. Right click on the publish folder and select Deploy to Web App.
4. Error is displayed.
5. Accessing the Azure Portal shows the resource group, app service plan, and web app were in fact created. However, other times just the resource group and app service plan are there.

After repeated attempts it just fails.

Action: appService.Deploy
Error type: ResourceGroupNotFound
Error Message: Resource group 'appsvc_windows_centralus' could not be found.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.Ts.l.pipeline extension.bundle.js:262:2544801
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:534414
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
@brianrandell This is a bizarre error.  Is it still happening?  I'm wondering if Azure was just having a weird outage where resources weren't being properly created.

**Comment by brianrandell** [comment]
@nturinski Yeah, it was weird. My work-around was to switch on the **App Service: Advanced Creation** flag. Moving forward over the next two days (Sunday and Monday) it worked fine every time.

In all honesty I want the advanced option 99% of the time. But I figure some folks want things to "just work". I can try again if you'd like.

**Comment by nturinski** [comment]
@brianrandell

Glad you were able to find a workaround.  

The new release actually removes the advancedCreate setting.  The new entry points are:

1. Click Deploy blue arrow -> select project -> `+ Create New Web App... (Advanced)`
1. Right-click subscription -> click `Create New Web App... (Advanced)` context action

Appreciate the offer, but don't worry about it! Thanks for using the extension.

**Comment by brianrandell** [comment]
@nturinski OK, sounds good. I'll check out the update and follow up if I see the problem again.
