### ISSUE TITLE
ETag does not represent the latest state of the resource (Auto upload on save error)

### ISSUE THREAD

**Issue by piphansdk** [microsoft/vscode-azureappservice#1154]
Repro steps:
1. Open a document from the AzureAppService integration in visual studio code (Mac) 
2. Edit and save the document a few times
3. VScode cannot upload the file due to error message: ETag does not represent the latest state of the resource.
4. File must be closed and reopened/redownloaded. 

(Bug is found for the following filetypes: ".js, .php, .html, .css, .htaccess, .xml". No further filetypes has been testet).

Action: appService.fileEditor.onDidSaveTextDocument
Error type: 412
Error Message: ETag does not represent the latest state of the resource.

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:332:788567
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
extension.bundle.js:157:27276
o extension.bundle.js:208:7054
extension.bundle.js:157:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] extension.bundle.js:1:534379
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:238:18274
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:238:17116
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
@piphansdk Thanks for reporting and providing detailed repro steps.  I'll look into this soon.
