### ISSUE TITLE
Can't understand this error

### ISSUE THREAD

**Issue by swaroopis** [microsoft/vscode-azureappservice#1155]
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.l.pipeline extension.bundle.js:262:3299936
s extension.bundle.js:262:112563
s extension.bundle.js:157:26036
module.exports.t.create.o.statusCode.t.registerRP extension.bundle.js:157:27167
module.exports.t.registerRP.n.post.n.statusCode.t.getRegistrationStatus extension.bundle.js:157:28037
$.module.exports.t.getRegistrationStatus.n.get [as _callback] extension.bundle.js:157:28143
module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:238:5461
$.emit events.js:182:13
$.module.exports.$.onRequestError extension.bundle.js:238:14516
ClientRequest.emit events.js:187:15
TLSSocket.socketErrorListener _http_client.js:391:9
TLSSocket.emit events.js:182:13
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @swaroopis

The steps in this document may resolve your problem: 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors
