### ISSUE TITLE
Pop up the duplicate dialog after opening the .NET Core project in VS Code and selecting one web app to deploy

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1157]
**OS:** All
**Build Version:** [20190916.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10047)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a .NET Core project by "dotnet new web".
2. Open the project in VS Code--> Pop up below dialog.
![image](https://user-images.githubusercontent.com/34729092/65030285-dcc5e780-d971-11e9-9a12-f76f5f527ac6.png)
3. Click "Deploy to Web App..." --> Select the folder to zip and deploy --> Select one web app.
4. Pop up below dialog.
![image](https://user-images.githubusercontent.com/34729092/65030716-96bd5380-d972-11e9-8d36-fc4b636dbfa2.png)

**Expect:**
Pop up one dialog to add required assets.

**Actual:**
Pop up a duplicate dialog after opening the .NET Core project in VS Code and selecting one web app to deploy.

**Comment by nturinski** [comment]
Thanks for reporting @v-dantch,

The first prompt is from the C# extension, while the second is from our extension.  

Our prompt only appears when a user deploys a .NET project.  The prompts are actually slightly different.  The first one emphasizes **debug** and the second prompt emphasizes **deploy**.

We can discuss whether or not this is a jarring experience though as having two similar prompts is pretty confusing.

**Comment by EricJizbaMSFT** [comment]
Should we make it "publish and deploy" or just "deploy"? Slightly more accurate and slightly more different than the C# message

**Comment by EricJizbaMSFT** [comment]
Also if the assets are truly required as we say, why do we allow "Don't Show Again" right before a deploy? It makes a little more sense in the C# scenario since I might not want to build or debug (not sure why) and that dialog happens when I open VS Code instead of right before debugging

**Comment by nturinski** [comment]
Dialogs have been changed and are less duplicate-y.
