### ISSUE TITLE
Open a new tab after selecting "Browse Website" at the second time on Windows & Linux but not on Mac

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1158]
**OS:** Mac
**Build Version:** [20190916.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10047)
**Regression:** Not a Regression

**Repro Steps:**
1. Right click one web app --> Select "Browse Website".
2. Select "Open Link" when asked whether want to open the external website or not.
3. Repeat Step1--2.

**Expect:**
The behavior is same and open a new tab when browsing the website at the second time.

**Actual:**
The behavior is different and navigate to current open tab on Mac and navigate to a new tab on Windows and Linux when browsing the website at the second time.

**Comment by nturinski** [comment]
@v-dantch I haven't been able to repro this.  What browser are you using?  Maybe it's related to your browser's settings?

Also, to be clear, you mean that it is opening in the same tab and not the same window, right?
