### ISSUE TITLE
An error occurs after cancelling the project selecting

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1159]
**OS:** Windows/Mac
**Build Version:** [20190916.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10047)
**Regression:** Not a Regression

**Repro Steps:**

1. Open one project in VS Code.
2. Deploy to Web App->Select 'Browser...'->Click 'Cancel' to cancel the selecting.
3. Check the result.

**Expect:**
There is no error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/65032629-17ca1a00-d976-11e9-8f0e-3d77772988dc.png)

**Comment by nturinski** [comment]
Hi @v-ruizh 

We are unable to repro this error.  Could you give us more information about your configurations?

1. Your VS Code version
1. Project and app runtimes
1. Screenshots of your User and Workspace settings

**Comment by v-ruizh** [comment]
Hi @nturinski   

1. The project is [nodejs-docs-hello-world](https://github.com/Azure-Samples/nodejs-docs-hello-world/archive/master.zip).
2. This is the information of my VS Code.
![image](https://user-images.githubusercontent.com/45614674/65103487-fe21e480-da00-11e9-8401-9281d492b973.png)

**A simple repro steps show as below.**

1. Open VS Code **without** any workspace and project opened. 
2. Click 'Deploy to Web App....'.
3. Click 'Cancel'/'X' button in the prompt 'Select Folder' dialog.
4. An error occurs in notification.
![image](https://user-images.githubusercontent.com/45614674/65103421-cd41af80-da00-11e9-8b6d-4b5d762fb1d1.png)

**Comment by nturinski** [comment]
I still can't repro this.  Could you share your User settings, please?

Hit ctrl/cmd + , to open the user settings:
![image](https://user-images.githubusercontent.com/5290572/65173271-4fcb6e80-da03-11e9-999f-cf1aaac02b17.png)

**Comment by EricJizbaMSFT** [comment]
Repros on VS Code Insiders with current and previous release of extension

**Comment by nturinski** [comment]
Yeah, sorry @v-ruizh, we found that this repros only on the most recent VS Code Insiders.  Will have a fix soon
