### ISSUE TITLE
[Suggestion] Add a 'Deploy' button to the notification after creating a new deployment slot

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1160]
**OS:** All
**Build Version:** [20190916.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10047)
**Regression:** Not a Regression

**Repro Steps:**
Create a new Deployment slot.
Check the notification message after creating.

**Expect:**
The notification message is similar with creating web app.

**Suggestion:**
Add a 'Deploy' button to the notification.
![image](https://user-images.githubusercontent.com/45614674/65033928-988a1580-d978-11e9-88a0-811f269f3731.png)

**Comment by nturinski** [comment]
Investigate how many people use the "Deploy" button after Create Web App.

**Comment by v-ruizh** [comment]
Verified this issue on the [20191125.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12677), it has been fixed. There is a 'Deploy' button in the notification after creating a deployment slot.
