### ISSUE TITLE
There is no auto-refresh for web app after installing the Cosmos DB extension

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1161]
**OS:** All
**Build Version:** [20190916.20](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10047)
**Regression:** Not a Regression

**Repro Steps:**

1. Make sure there is no Cosmos DB Extension installed.
2. Expand one Web app->Connections->Cosmos DB node.
3. Click 'Install Cosmos DB Extension...' to install Cosmos DB extension.
4. Refresh the Web App and check the Cosmos DB node.

**Expect:**
It changes to 'Add Cosmos DB Extension...'.

**Actual:**
Refresh web app doesn't work, it still shows 'Install Cosmos DB Extension...'.
![image](https://user-images.githubusercontent.com/45614674/65035013-c708f000-d97a-11e9-8c35-d91af403314d.png)

**More Info:**
Refresh the App Service explorer can fix this issue.

**Comment by nturinski** [comment]
Offline discussion: Maybe poll for a little bit after.

**Comment by v-dantch** [comment]
Verified on the [20191125.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12677). Now App Service Explorer auto refreshes when the Cosmos DB Extension has been installed, so this bug has been fixed.
