### ISSUE TITLE
Error asking to commit before deploying, nothing to commit.

### ISSUE THREAD

**Issue by euvin3582** [microsoft/vscode-azureappservice#1163]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "angular-cli-tw" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:262:3460452
module.exports.n extension.bundle.js:262:3458872
module.exports.n extension.bundle.js:262:3458649
module.exports.t.deploy.i.window.withProgress extension.bundle.js:262:3460313
c._withProgress extensionHostProcess.js:476:464
c.withProgress extensionHostProcess.js:476:218
Object.withProgress extensionHostProcess.js:673:358
Object.<anonymous> extension.bundle.js:262:3460139
o extension.bundle.js:262:3458705
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
It seems like you're trying to deploy to a web app that is connected to a GitHub repo.  Rather than deploying directly to the app, you can just push any changes to your GitHub remote repo and it should automatically create a new build.

**Comment by euvin3582** [comment]
The app is not working at the moment. I wanted to deploy directly to see if it would work that way. Is an Angular 6 app.

**Comment by nturinski** [comment]
@euvin3582 In order do to that, you would need to change the Deployment Source to None or Local Git and then deploy directly.

Alternatively, you could create a deployment slot and deploy your changes there, but that requires you to be on at least a S1 app service plan.
