### ISSUE TITLE
Update icons per new VS Code guidelines

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azureappservice#1164]
@nturinski @fiveisprime Might be worth slipping some new icons in for 0.16.0? Even if it's just the main title bar icons... 

![Screen Shot 2019-09-17 at 1 47 58 PM](https://user-images.githubusercontent.com/11282622/65078447-db84c280-d951-11e9-9bd1-61485303d650.png)

https://github.com/microsoft/vscode-icons

**Comment by EricJizbaMSFT** [comment]
Partially fixed in https://github.com/microsoft/vscode-azureappservice/pull/1169

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureappservice/pulls?q=is%3Apr+is%3Aclosed

**Comment by v-dantch** [comment]
Verified on Win10 & Mac with [20191125.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12677), all icons display well like below:
![image](https://user-images.githubusercontent.com/34729092/69726350-555bd800-115b-11ea-9acb-06d712635e13.png)
