### ISSUE TITLE
Learn more link for SCM_DO_BUILD warning doesn't work

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azureappservice#1165]
![Screen Shot 2019-09-17 at 1 57 04 PM](https://user-images.githubusercontent.com/11282622/65079011-1dfacf00-d953-11e9-87fe-541f76d64c8c.png)

Takes you to this link which doesn't exist any more:
https://github.com/Microsoft/vscode-azureappservice/blob/master/README.md#configuring-zip-deploy

**Comment by nturinski** [comment]
Resolved by changing the aka.ms link.  Thanks for diligent testing! 😸
