### ISSUE TITLE
SCM_DO_BUILD warning silently blocks deploy

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azureappservice#1167]
Repro steps:
1. Open a simple node web app
1. Deploy with blue up arrow
1. Create a new web app with basic create
1. Look away for a little while

Actual:
The following warning popped up, prevented the deploy from starting, and went away. I had to open the notification bell just to know why it didn't finish.
![Screen Shot 2019-09-17 at 1 57 04 PM](https://user-images.githubusercontent.com/11282622/65079102-44206f00-d953-11e9-85fe-c2897276fffb.png)

Expected:
I feel like this dialog should either be modal so that it doesn't disappear after a few seconds or it shouldn't block deploy from continuing

**Comment by nturinski** [comment]
@fiveisprime TODO: Oryx might do this by default so investigate that

**Comment by fiveisprime** [comment]
It doesn't. :( Sent mail to get a better understanding of if/when this is coming.

**Comment by v-dantch** [comment]
Verified on Win 10 & Mac with build [20191125.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12677), there is no warning dialog pops up when deploying.
