### ISSUE TITLE
informe

### ISSUE THREAD

**Issue by raulzarzadev** [microsoft/vscode-azureappservice#1174]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Cannot read property 'constructor' of undefined

Version: 0.15.0
OS: linux
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350604
a extension.bundle.js:332:350244
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @raulzarzadev,

Could you add repro steps, please?  This is a highly unusual error.

**Comment by raulzarzadev** [comment]
If you say !!!

**Comment by nturinski** [comment]
Repo steps would be greatly appreciated.  `Cannot read property 'constructor' of undefined` isn't an error that users should see.
