### ISSUE TITLE
No error message when a `dependsOn` task fails during `runPreDeployTask`

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureappservice#1180]
The long-running 'deploying' notification persists after `dotnet` command isn't found with no error message.

**Comment by nturinski** [comment]
While that is an example of when this happens, the crux of the problem is that we are not checking for failures of any tasks other than the `preDeployTask` itself.  So if it `dependsOn` another task and that fails, the UI hangs.

**Comment by nturinski** [comment]
Related PR https://github.com/microsoft/vscode-azuretools/pull/591

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azuretools/pull/591
