### ISSUE TITLE
CosmosDB connection Timedout when trying to connect from VS Code

### ISSUE THREAD

**Issue by azimshaik** [microsoft/vscode-azureappservice#1182]
Repro steps:

1. Created a Web app from App Services VS Code extension, I can deploy and and the app works
2. When tried to Add Cosmos DB connection, I am getting this error. 
3. I tried both the ways
   a. By creating CosmosDB from VS Code Extension 
   b. By creating from Azure Portal. (No luck either ways)
Any suggestions?

Action: appService.AddCosmosDBConnection
Error type: Error
Error Message: failed to connect to server [azimstickercdb.documents.azure.com:10255] on first connect [MongoError: connection 37 to azimstickercdb.documents.azure.com:10255 timed out]

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Pool.eventHandler mongodb-core/server.js:336:35
Pool.emit events.js:182:13
Pool.EventEmitter.emit domain.js:442:20
Connection.<anonymous> mongodb-core/pool.js:280:12
Object.onceWrapper events.js:273:13
Connection.emit events.js:182:13
Connection.EventEmitter.emit domain.js:442:20
TLSSocket.timeoutHandler mongodb-core/connection.js:199:10
Object.onceWrapper events.js:273:13
TLSSocket.emit events.js:182:13
TLSSocket.EventEmitter.emit domain.js:442:20
TLSSocket.Socket._onTimeout net.js:449:8
ontimeout timers.js:425:11
tryOnTimeout timers.js:289:5
listOnTimeout timers.js:252:5
Timer.processTimers timers.js:212:10
```

</details>

**Comment by azimshaik** [comment]
I tried another time, It seems the CosmosDB account is getting created, but then when I try to select the created account I am getting this error.
![image](https://user-images.githubusercontent.com/2375559/65198720-31409400-da52-11e9-9d1c-e88592b2a398.png)
Please suggest!

**Comment by nturinski** [comment]
Hi @azimshaik 

Sorry that you're running into this issue.  I haven't been able to repro this problem, but have you tried looking in the portal and seeing what the connection string is?  I'm wondering if the credentials aren't being attached correctly.

Once you have the connection string, replace the App Setting "MONGO_URL" with the connection string.
