### ISSUE TITLE
Azure Pipelines integration

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#1188]
Related to proposed changes in #1176 from @hiyadav

**Comment by fiveisprime** [comment]
Rather than taking a hard dependency on the Pipelines extension, this should work similar to how the connections node works. This ensure that only customers who are interested in using Pipelines need to install the extension, while also providing a path to the Pipelines experience.

**Comment by hiyadav** [comment]
@bishal-pdMSFT @pulkitaggarwl 

Okay, following the `Connections Node` example, I could think of the following implementation:

1. Create new commands: `appService.configure-azureWebApp-pipeline` and `appService.browse-azureWebApp-pipeline` in AppService extension. 
2. Register these commands in extension.ts file, to call a function configure/browse.
3. These function checks if the extension is installed
- If not: Open Azure-Pipelines extension install page in VS Code or if this can't be done for some reason, then open marketplace url of the extension.
- If yes: Invoke 'configure-pipeline'/'browse-pipeline' command registered by Azure-pipelines extension. This will give control to Azure Pipeline extension and Azure App Service command will exit.

Do let me know if this is the recommended approach.
Meanwhile, I have updated the PR to use the above approach.

**Comment by fiveisprime** [comment]
We've closed to PR so we can discuss the experience a bit more. Your current proposal only covers have of the experience - what is the experience for customers who have configured their CI/CD with the Azure Pipelines extension?

How about a new node under "deployments" that exposes Azure Pipelines?

![image](https://user-images.githubusercontent.com/1186948/65729523-79c00900-e073-11e9-85a6-98bd282cd3ee.png)

Clicking that without the Pipelines extension installed, takes the customer to the extension view in VS Code.

If the customer has already configured a pipeline, show the builds and their status:

![image](https://user-images.githubusercontent.com/1186948/65729825-7e38f180-e074-11e9-89c8-3efbe9e53bff.png)

Right-click the build node to "View in Azure Pipelines Extension". This would launch into the pipelines extension with the build details.
