### ISSUE TITLE
A few days ago I was able to create a New Web app using the same instructions. Now this error pops up. I also tried deleting all the resources and starting again, same thing happens. Using Azure for Students subscription.

### ISSUE THREAD

**Issue by salarx** [microsoft/vscode-azureappservice#1192]
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: Conflict
Error Message: The pricing tier 'LinuxFree' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764

Version: 0.16.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.l.pipeline extension.bundle.js:218:3614823
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:576782
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by salarx** [comment]
Also if I try using the advanced option to create a web app, I can create the web app but none of the site packages specified in requirements.txt are installed. I'm trying to deploy Django web app on linux.

**Comment by salarx** [comment]
Also to mention selecting Windows as the OS, I don't face any issue. Issue is only with Linux as the OS

**Comment by nturinski** [comment]
Hi @salarx

Could you try using `Create Web App...(Advanced)`?  I believe if you just use a different rg name, you can workaround this problem.

**Comment by salarx** [comment]
Hi!
I was using able to create web app using the advanced option. The problem was that I was trying to create the web app on Linux VM from my local windows machine. The problems was solved after I created the web app switching to WSL in VS Code. But I feel the web app should be created regardless of the platform (OS) used, since the app creation process creates its own antenv folder for the web app from the requirements mentioned in requirements.txt. All other files are same on both windows and linux, so selecting Linux as OS should make a Linux app. But this doesn't happen right. The requirements are not installed if I don't activate the WSL and use the probject folder located in WSL.

**Comment by EricJizbaMSFT** [comment]
The local OS shouldn't affect the OS used for the Azure web app. Some subscriptions just have fewer permissions, which is why we have the "Advanced" option to give those users more control. Closing this since you said you were successfully able to create with "Advanced"
