### ISSUE TITLE
cannot deploy app service-angular app 

### ISSUE THREAD

**Issue by roeidalm** [microsoft/vscode-azureappservice#1193]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 403
Error Message:  Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here [https://go.microsoft.com/fwlink/?linkid=2095007]. For further troubleshooting tools and recommendations, please visit Azure Portal [https://portal.azure.com/].

Version: 0.16.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.r.pipeline extension.bundle.js:323:397590
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:576720
$.module.exports.$.init.t._callback.t.callback.t.callback [as callback] extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
```

</details>

**Comment by nturinski** [comment]
Hi @roeidalm 

Thanks for reporting.  It seems as if your app is stopped.  Please right-click a web app node and hit Start:

![image](https://user-images.githubusercontent.com/5290572/65902946-5695a200-e370-11e9-8af8-9c612d627d1e.png)

Please re-open if that doesn't fix your issue!
