### ISSUE TITLE
Issue while deploying azure web app

### ISSUE THREAD

**Issue by AnupBhagwat7** [microsoft/vscode-azureappservice#1200]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "justupload1" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.16.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:253:13234
module.exports.n extension.bundle.js:253:11600
module.exports.n extension.bundle.js:253:11374
module.exports.t.deploy.i.window.withProgress extension.bundle.js:253:13094
c._withProgress extensionHostProcess.js:476:464
c.withProgress extensionHostProcess.js:476:218
Object.withProgress extensionHostProcess.js:673:358
Object.<anonymous> extension.bundle.js:253:12920
o extension.bundle.js:253:11431
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
@AnupBhagwat7 Thanks for reporting.  If you're connected to a GitHub repo, you don't need to use the deploy command.  Just push to your GitHub repository 😄
