### ISSUE TITLE
Linux runtimes don't render properly when creating web app

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azureappservice#1202]
This happens in basic & advanced create.

![Screen Shot 2019-10-02 at 4 05 24 PM](https://user-images.githubusercontent.com/22795803/66088034-74106a80-e52e-11e9-94c3-cafe4a6c5b29.png)

**Comment by fiveisprime** [comment]
From the App Service team:

> A Stack with Particular Version can be identified by “Stack Name”+” ”+displayVersion (previously display version had stack name in it as well). 

So the extension needs updating to use this method as well.
