### ISSUE TITLE
Error deploying Aurelia project to App Service in Azure

### ISSUE THREAD

**Issue by kintela** [microsoft/vscode-azureappservice#1203]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 404
Error Message: An error has occurred.

Version: 0.16.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: es

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:323:412462
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:576782
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @kintela,

Thanks for reporting.  Please provide repro steps so I can further assist you.

**Comment by kintela** [comment]
HI Nathan

 

After reboot the machine all works fine again

 

Magic…..

 

No What I don’t know is how to publish my app to the staging slot of mi appservice

 

 

When I publish I don’t see my slot to select it

 

 

Any idea please?

 

Thanks

 

De: Nathan <notifications@github.com>
Responder a: microsoft/vscode-azureappservice <reply@reply.github.com>
Fecha: jueves, 3 de octubre de 2019, 22:23
Para: microsoft/vscode-azureappservice <vscode-azureappservice@noreply.github.com>
CC: kintela <roberto.quintela@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [microsoft/vscode-azureappservice] Error deploying Aurelia project to App Service in Azure (#1203)

 

Hi @kintela,

Thanks for reporting. Please provide repro steps so I can further assist you.

**Comment by nturinski** [comment]
Hi @kintela 

Slots are under the "Deployment Slots" node like as shown:
![image](https://user-images.githubusercontent.com/5290572/66227797-c9fe2300-e692-11e9-84e6-c25920d04d5b.png)

Unfortunately, if you have a non-production plan, your tree will look like this:
![image](https://user-images.githubusercontent.com/5290572/66227840-df734d00-e692-11e9-8cf6-b47a93a05d7c.png)

If you're not running a production plan, unfortunately, there isn't anything that I can do to assist you 😦

**Comment by kintela** [comment]
Hi Nathan

 

I’m using this production plan

I have the slot created

 

The problem is that when I Publish from VS Code I can’t select it because does not appear to select it

 

Thanks

 

De: Nathan <notifications@github.com>
Responder a: microsoft/vscode-azureappservice <reply@reply.github.com>
Fecha: viernes, 4 de octubre de 2019, 19:37
Para: microsoft/vscode-azureappservice <vscode-azureappservice@noreply.github.com>
CC: kintela <roberto.quintela@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [microsoft/vscode-azureappservice] Error deploying Aurelia project to App Service in Azure (#1203)

 

Hi @kintela

Slots are under the "Deployment Slots" node like as shown:

Unfortunately, if you have a non-production plan, your tree will look like this:

If you're not running a production plan, unfortunately, there isn't anything that I can do to assist you 😦

**Comment by nturinski** [comment]
How are you trying to deploy it?  Where does it not appear?  Right now, slots do not appear in the command palette, so to deploy, you need to right-click the slot under your web app.

**Comment by kintela** [comment]
How are you trying to deploy it? 

Where does it not appear? 

Right now, slots do not appear in the command palette, so to deploy, you need to right-click the slot under your web app.

Deploy to slot no?

 

Thanks

**Comment by nturinski** [comment]
Right-click your deployment slot
![image](https://user-images.githubusercontent.com/5290572/66503966-11aef100-ea7d-11e9-8c9f-54fc6a65fc7f.png)

Click "Deploy to Slot..."
![image](https://user-images.githubusercontent.com/5290572/66504009-27241b00-ea7d-11e9-9e42-9dbd96fdf5f2.png)
