### ISSUE TITLE
 Error: ETag does not represent the latest state of the resource.

### ISSUE THREAD

**Issue by straightcore** [microsoft/vscode-azureappservice#1209]
This error has been thrown during an updating '"App Service" azure resource. 
I just created this webapp by Azure portal. And I updated the hostingstart.html file directly by VS Code.

Repro steps:

1. Go to Azure (VS Code menu)
2. Go to App Service tab
 2.1 Go to Subcription
 2.2 Go to WebAPP ( myWebAppInAzure)
3. Open file: myWebAppInAzure -> Files -> hostingstart.html
4. Modify the file
5. Save the file
6. Click on Updating button on the popup window.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: 412
Error Message: ETag does not represent the latest state of the resource.

Version: 0.16.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:323:803050
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] extension.bundle.js:1:576747
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.EventEmitter.emit domain.js:442:20
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
$.EventEmitter.emit domain.js:442:20
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
IncomingMessage.EventEmitter.emit domain.js:442:20
endReadableNT _stream_readable.js:1092:12
asyncWrap async-listener/glue.js:188:31
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @straightcore

Did you happen to edit this file anywhere else?  Or how long did you wait between steps?  The Etag was stale which means you were not working with the most update to date file.  If you redownload the file and try saving it again, does that resolve the issue?
