### ISSUE TITLE
Add .NET Core 3.0

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#1210]
Maybe nothing is required to update the runtime list, but creating this issue to track just in case. Looks like .NET Core 3.0 is rolling out now.

https://github.com/Azure/app-service-announcements/issues/204

**Comment by wwlorey** [comment]
.NET Core 3.0 is included after fixing #1202

![Screen Shot 2019-10-10 at 9 55 36 AM](https://user-images.githubusercontent.com/22795803/66593635-3b831900-eb4c-11e9-93ef-59bfd11a1900.png)
