### ISSUE TITLE
The available runtimes version is not consistent between the Output Window and Runtime List

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1213]
**OS:** Win 10 & Mac
**Build Version:** [20191007.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10871)

**Repro Steps:**
1. Create a new Linux node.js web app --> Deploy a project to this new web app.
2. Check the Output Window about the available Node.js version.

**Expect:**
The available Node.js version are same.

**Actual:**
The available runtimes version is not consistent between the Output Window and Runtime List.
![image](https://user-images.githubusercontent.com/34729092/66386929-88081080-e9f5-11e9-8aac-8f5163b198f5.png)

**Comment by EricJizbaMSFT** [comment]
Not much we can do here since we get these node version dynamically from Azure ARM apis. There might be minor differences occasionally since the other log is coming from kudu

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing.
