### ISSUE TITLE
Update all Azure icons

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1214]
**OS:** Win 10 & Mac
**Build Version:** [20191007.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10871)

**Repro Step:**
Create a new web app --> Expand it and check the icon of "Application Settings" node.

**Actual:**
The color of "Application Settings" node are different between the App Service Explorer and Azure Portal.
![image](https://user-images.githubusercontent.com/34729092/66387336-59d70080-e9f6-11e9-9bc1-e058ef2999f0.png)

**Suggestion:**
The color are same of "Application Settings" node icon between the App Service Explorer and Azure Portal.

**Comment by EricJizbaMSFT** [comment]
We use a mix of Azure icons and [VS Code icons](https://github.com/Microsoft/vscode-icons). In this case, the app settings icon matches VS Code, not Azure - which is fine
