### ISSUE TITLE
Miss the "Download Remote Settings…/Upload Local Settings…" from the context menu of web apps and slots

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1215]
**OS:** Win 10 & Mac
**Build Version:** [20191007.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10871)

**Repro Steps:**
1. Drill down from one web app --> Application Settings.
2. Right click one application setting --> Check the context menu.

**Expect:**
Display "Download Remote Settings…/Upload Local Settings…".

**Actual:**
Miss "Download Remote Settings…/Upload Local Settings…".
![image](https://user-images.githubusercontent.com/34729092/66387642-f00b2680-e9f6-11e9-97d1-115cfa9f073a.png)

**More Info:**
These 2 actions can be run using command.

**Comment by nturinski** [comment]
🎋 This is by design.  We don't support uploading/downloading one setting at a time.  You would have to download/upload the entire app settings at once by right-clicking `Application Settings`🌲

**Comment by v-dantch** [comment]
Got it 👍 .
