### ISSUE TITLE
You don't have authorization

### ISSUE THREAD

**Issue by yanligao** [microsoft/vscode-azureappservice#1216]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: AuthorizationFailed
Error Message: The client 'live.com#yanli.gao@gmail.com' with object id 'e740bc50-e544-4403-9f23-edee77a5df1d' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/8342d1cd-65a5-4457-997a-248a8d0b8480/resourceGroups/appsvc_windows_centralus/providers/Microsoft.Web/serverfarms/appsvc_windows_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.16.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline extension.bundle.js:218:3522734
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:576782
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
```

</details>

**Comment by EricJizbaMSFT** [comment]
Sorry for the delay in response. If you're still having issues, please try the `Create new web app... (Advanced)` option as your subscription doesn't seem to have permissions for something
