### ISSUE TITLE
Redeploy error

### ISSUE THREAD

**Issue by whitefc87** [microsoft/vscode-azureappservice#1223]
Repro steps:

1.
2.

Action: appService.Redeploy
Error type: object
Error Message: Could not find file '/home/site/deployments/4f8086ba402d7716811fbfbac1e009df26334953/log.log'.

Version: 0.16.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:409148
extension.bundle.js:218:111699
extension.bundle.js:157:26069
extension.bundle.js:157:27311
extension.bundle.js:164:7075
extension.bundle.js:157:24982
extension.bundle.js:1:576720
extension.bundle.js:194:5449
events.js:182:13
domain.js:442:20
extension.bundle.js:194:18309
events.js:187:15
domain.js:442:20
extension.bundle.js:194:17141
events.js:273:13
events.js:187:15
domain.js:442:20
_stream_readable.js:1092:12
next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @whitefc87 
Could you provide repro steps please?
