### ISSUE TITLE
Display "Node" rather than "Node.js" when selecting Node.js runtimes 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1224]
**OS:** All
**Build Version:** [20191010.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11151)

**Repro Steps**:
1. F1 --> Type and select "Azure App Service: Create New Web App... (Advanced)".
2. Enter a valid name --> Select a resource group --> Select Linux OS --> Check the runtimes of Node.js.

**Expect:**
Display "Node.js xxx".

**Actual:**
Display "Node xxx".
![image](https://user-images.githubusercontent.com/34729092/66645612-825d3580-ec56-11e9-8deb-144478bb913d.png)

**Comment by wwlorey** [comment]
The `display` property returned from the Azure API is now "Node" instead of "Node.js".

@fiveisprime is keeping this new display name OK? We can insert the ".js" if needed

**Comment by fiveisprime** [comment]
Node without the .js is fine with me. Going to close this since there's no action required.
