### ISSUE TITLE
No error dialog pops up when deploying project to web app without any workspace opening

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1225]
**OS:** All
**Build Version:** [20191010.4](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11151)

**Repro Steps:**
1. Make sure the target project folder is NOT opened in VS Code.
2. Create a new app service.
3. There is a notification after creation, click "Deploy" button from this notification--> Browse to open the target project according to the prompting.

**Expect:**
An error dialog pops up to remind opening workspace first.
![image](https://user-images.githubusercontent.com/45614674/66645570-66599400-ec56-11e9-81e1-8a9e749e2cc1.png)

**Actual:**
There is no error dialog after selecting the target project.

**More Info:**
This bug does not reproduce if deploy by clicking 'Deploy to web app...' from toolbar or context menu.

**Comment by nturinski** [comment]
Great catch!
