### ISSUE TITLE
[Suggestion] Display the inputted name after clicking "Back" button

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1226]
**OS:** All
**Build Version:** [20191010.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11151)

**Repro Steps**:
1. F1 --> Type and select "Azure App Service: Create New Web App... (Advanced)".
2. Enter a valid name --> Press "Enter" --> Select "+Create new resource group" --> Enter a new resource group name --> Click "Back" button.
3. Check the resource group name.

**Actual:**
Display the default name rather than inputted name.

**Suggestion:**
Display the inputted name.

**More Info:**
1. This issue also reproduces when creating a new App Service Plan and Application Insights Resource.
2. Clear the inputted web app after clicking "Back" button.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/microsoft/vscode-azuretools/pull/688
