### ISSUE TITLE
Display "Application Error" after deploying a .NET Core 3.0 project to a .NET Core 3.0 web app

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1227]
**OS:** Windows
**Build Version:** [20191010.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11151)

**Repro Steps**:
1. Make sure you have installed .NET Core 3.0 --> Create a new .NET Core 3.0 web app.
2. Create a Linux web app with .NET Core 3.0 runtime.
3. Deploy this project to the new web app.

**Expect:**
Succeed to deploy and the website displays well.

**Actual:**
Succeed to deploy but the website displays "Application Error".
![image](https://user-images.githubusercontent.com/34729092/66648375-f3ecb200-ec5d-11e9-8377-4fe498e69512.png)

**Comment by EricJizbaMSFT** [comment]
I tried to repro and hit "Application Error" because my csproj was actually targeting 3.1. Once I switched it to 3.0, it worked fine for me.

If this still repros, check the target framework in csproj and copy it here. Also do "Start Streaming Logs" after deploying and copy those logs here.
