### ISSUE TITLE
SCM_DO_BUILD warning looks for, generates .deployment in wrong folder

### ISSUE THREAD

**Issue by nickwalkmsft** [microsoft/vscode-azureappservice#1228]
Discovered when using Web Template Studio (generates a full stack app, with `appService.deploySubpath` in the workspace settings set to `server`).

Deploying a newly generated WebTS Node app pops the notification about running build commands on the server, but shouldn't, because the folder being zipdeployed (`/server`) already contains a `.deployment` with `SCM_DO_BUILD_DURING_DEPLOYMENT=true`.

If you click Yes on the notification, it creates a new `.deployment` at the root of the workspace that doesn't get used for anything.

Linking #1167 - no direct relation but same feature and the last comment indicates that there might be some potentially related discussion.

**Comment by nturinski** [comment]
@nickwalkmsft Thanks for reporting this.  We should look/generate the `.deployment` file in the deploySubpath

**Comment by nturinski** [comment]
This should be resolved with the latest release, v0.16.2.

Please let me know if it hasn't! 😃

**Comment by nickwalkmsft** [comment]
Confirmed fixed. Thanks!
