### ISSUE TITLE
Error: Failed to get status of deployment after attempting to deploy via LocalGit

### ISSUE THREAD

**Issue by nnja** [microsoft/vscode-azureappservice#1230]
Repro steps:

1. Create a new app service instance through the vs code extension
2. Select LocalGit as deployment source
3. Start deployment

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.16.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:323:357962
a extension.bundle.js:323:357598
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @nnja

Thanks for reporting.  Is this repro consistently?  I find that sometimes new web apps have trouble deploying immediately after creation, but then begin working eventually on their own.

**Comment by nnja** [comment]
Hi @nturinski. I wasn't able to repro this particular issue, but it was frustrating to experience as a first impression of trying to deploy a web app.
