### ISSUE TITLE
Treenikauppa

### ISSUE THREAD

**Issue by SamiSuihkonen** [microsoft/vscode-azureappservice#1232]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy because the path is not part of an open workspace. Open in a workspace and try again.

Version: 0.16.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:354245
o extension.bundle.js:157:353308
```

</details>

**Comment by nturinski** [comment]
@SamiSuihkonen Please open your project in VS Code before you deploy.  The "Browse" button is intended to browse to subfolders in your root directory.
