### ISSUE TITLE
Adjust Detector startTime and endTime values

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#1235]
We are seeing a good number of requests for LinuxContainerStartFailure detector coming from our VS Code extension that fail with 500 Internal Server Error. Let me explain the reason behind this:
1.	startTime values in the requests are hardly 30 mins less than current UTC datetime (in many cases even equal to UTC datetime).
2.	endTime values in the requests are futuristic i.e. more than current UTC datetime.
Because of these time values, we do not find any logs in kusto tables for the app/environment (as the logs are delayed by 15 minutes), which results in an empty tenant list and malformed detector query.

**As a correct usage I would recommend that:
endTime values in the requests should be at most 15 mins less than current UTC datetime. (and startTime value should be anything less than endTime)**

**Comment by EricJizbaMSFT** [comment]
This will change when Nathan does https://github.com/microsoft/vscode-azureappservice/issues/1249 anyways
