### ISSUE TITLE
Error when clicking the "+" button

### ISSUE THREAD

**Issue by asuiu** [microsoft/vscode-azureappservice#1237]
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: object
Error Message: {}

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.27.1
Language: en

**Comment by nturinski** [comment]
Hi @asuiu 

Thanks for reporting.  Could you provide repro steps?  

Perhaps more information about your subscription?  Do you have restricted permissions?

**Comment by asuiu** [comment]
Sorry, I don't have repro steps nomore. I've been expecting VSCode/Appservice to send all needed debug information
