### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by MUKESHNITP** [microsoft/vscode-azureappservice#1238]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "TestApp" failed. See output channel for more details.

Version: 0.16.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:497362
o extension.bundle.js:1:495337
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @MUKESHNITP 

Thanks for reporting.  Please provide repro steps so I can further assist you.
