### ISSUE TITLE
can't connect via ssh in Visual Studion

### ISSUE THREAD

**Issue by yaroslav-mygal** [microsoft/vscode-azureappservice#1241]
Repro steps:

1.
2.

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: App is started, but port is unreachable

Version: 0.16.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: ru

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:99743
a extension.bundle.js:157:95441
```

</details>

**Comment by nturinski** [comment]
Hi @yaroslav-mygal 

Sorry, you're running into this issue.  Can you provide repro steps?  You may also be able to connect to SSH via the portal.
