### ISSUE TITLE
appService.Deploy

### ISSUE THREAD

**Issue by nickykiet83** [microsoft/vscode-azureappservice#1243]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "shelfappangular" failed. See output channel for more details.

Version: 0.16.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:497300
o extension.bundle.js:1:495275
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @nickykiet83 

Could you provide repro steps?

**Comment by nickykiet83** [comment]
> Hi @nickykiet83
> 
> Could you provide repro steps?

Hi nturinski,

Below is the output when deploy.... 

10:15:05 AM: WARNING: Ignoring deploySubPath "dist" for non-zip deploy.
10:15:05 AM shelfappangular: Creating zip package...
10:20:44 AM shelfappangular: Starting deployment...
10:21:07 AM shelfappangular: Fetching changes.
10:21:07 AM shelfappangular: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\rmpfgbav.zip (172.96 MB) to D:\local\Temp\zipdeploy\extracted
10:21:22 AM shelfappangular: Waiting for long running command to finish...
10:22:27 AM shelfappangular: Waiting for long running command to finish...
10:23:31 AM shelfappangular: Waiting for long running command to finish...
10:23:32 AM: Error: Deployment to "shelfappangular" failed. See output channel for more details.


--> I fixed the problem. It relates to the permission on the current folder. Azure cannot zip package....

Thanks

**Comment by nturinski** [comment]
Great, thanks for following up with me.  I'll go ahead and close this, please reopen if you have another issue! :)
