### ISSUE TITLE
Deployment Source None configured, but still no Zip Deploy

### ISSUE THREAD

**Issue by LMSSonos** [microsoft/vscode-azureappservice#1250]
I have set the Deployment source to "none", after i tried to publish the webapp. What happens is, that i it ignores the deploySubPath and in my case it then uploads the whole directory (including .git, and nother projects in that folder). 

It worked initially, but after rebooting my PC the "None" settings from the deployment source seems to be ignored. PS, would be nice if the source could be configured as well in the settings.

```
09:45:00: Deployment source for "mywebapp" has been updated to "None".
09:45:08: WARNING: Ignoring deploySubPath "mywebapp\bin\Debug\netcoreapp2.2\publish" for non-zip deploy.
09:45:08 mywebapp: Creating zip package...
```

Works when deleting settings.json and making installation manual. 
```
{
    "appService.defaultWebAppToDeploy": "/subscriptions/guid/resourceGroups/mywebapp-resources/providers/Microsoft.Web/sites/mywebapp",
    "appService.deploySubpath": "mywebapp\\bin\\Debug\\netcoreapp2.2\\publish",
    "appService.preDeployTask": "publish-mywebapp",
}
```

VSCode: 1.39.2
AppService: 0.16.1

**Comment by nturinski** [comment]
Hi @LMSSonos 

Sorry for this issue.  What was your app's deployment source prior to updating it to "None"? 

Could you list the exact order that you're executing these commands in?

Thanks!

**Comment by LMSSonos** [comment]
Thanks for your quick reply, I think it was already on NONE, because that's the default. I tried to reproduce the issue but was not able anymore. It always worked as expected.

Just for my understanding, the deployment source is stored on Azure, it's not something that is configured within VScode.

Sorry for the issue - I think you can close it. If it comes up again, I will let you know.
