### ISSUE TITLE
Unable to find the full deployment log

### ISSUE THREAD

**Issue by kichalla** [microsoft/vscode-azureappservice#1251]
I kicked off a deployment and following is the screen shot of it:
![image](https://user-images.githubusercontent.com/6559784/67393038-74f95280-f556-11e9-9ec0-cc976c5bb16b.png)

As you can see the deployment log is truncated. Where can I find the full deployment log? This can be helpful in diagnosing issues in following cases:
- Recently I filed a bug against App Service where the build actually failed due to the app using a private npm registry, but the app still continued deploying and it was hard to figure out why the app was not running successfully. Had I been able to see the full deployment log, the issue would have been highlighted quickly.
- A deployment could be successful but the steps could have been wrong resulting in incorrect runtime behavior.

I only see the following content in my App Service extension, how can I access the full deployment log?

![image](https://user-images.githubusercontent.com/6559784/67393432-344e0900-f557-11e9-99ea-c30873a366e3.png)

cc @fiveisprime @gpcastro

**Comment by EricJizbaMSFT** [comment]
The deployment logs are more easily accessible from under the "Deployments" node:
![Screen Shot 2019-10-23 at 12 01 09 PM (2)](https://user-images.githubusercontent.com/11282622/67425468-e5bb6180-f58c-11e9-8dca-2a693814b105.png)

**Comment by kichalla** [comment]
Thanks @EricJizbaMSFT I didn't know that about the little icon under the Deployemnts node. I think this experience should be improved. The files are spread over 3 places now. Deployment log (build log) under `Deployments` node, log stream under `Logs` node and runtime container logs under the root.

**Comment by EricJizbaMSFT** [comment]
Discussed in triage: Add "View Logs" to right click menu, too
