### ISSUE TITLE
Display user friendly UI to App Service's artifacts

### ISSUE THREAD

**Issue by kichalla** [microsoft/vscode-azureappservice#1252]
I feel we currently dump the information that App Service exposes into the UI but this information is not intuitive to an end user.
For example, below is a snapshot of an app that was deployed by me:
![image](https://user-images.githubusercontent.com/6559784/67393748-d3730080-f557-11e9-856a-ea59469b2eaa.png)

- How can a user find build/deployment log
- Tool tips explaining what each node is about
- The highlighted files in the above snapshot is not helpful to an end user at all. The naming and the content of them keeps an end user guessing. They are runtime container logs but it is not very obvious to an end user.
- Nodes like 'kudu' and 'webssh' probably can be hidden by default if they are not going to be used widely.

cc @fiveisprime @gpcastro @JennyLawrance @sanchitmehta

**Comment by EricJizbaMSFT** [comment]
The deployment logs are more easily accessible from under the "Deployments" node:
![Screen Shot 2019-10-23 at 12 01 09 PM (2)](https://user-images.githubusercontent.com/11282622/67425468-e5bb6180-f58c-11e9-8dca-2a693814b105.png)

**Comment by EricJizbaMSFT** [comment]
I think there's a valid debate here between transparency and making it more intuitive. Personally I like the transparency of the Logs/Files nodes. We already have deployment logs available under the deployments node (as mentioned [here](https://github.com/microsoft/vscode-azureappservice/issues/1251#issuecomment-545590250)). I would vote to keep Logs as the "transparent" option and highlight the deployments node as the "intuitive" option (and make that more discoverable if need be).
