### ISSUE TITLE
Error publishing in a Azure slot

### ISSUE THREAD

**Issue by kintela** [microsoft/vscode-azureappservice#1256]
Hi 

When I have tried to deploy my Aurelia project to the slot I got this error. yesterday this worked well.

Action: appService.DeploySlot
Error type: object
Error Message: An error has occurred.

Version: 0.16.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: es

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:409148
extension.bundle.js:218:111699
extension.bundle.js:157:26069
extension.bundle.js:157:27311
extension.bundle.js:164:7075
extension.bundle.js:157:24982
extension.bundle.js:1:576782
extension.bundle.js:194:5449
events.js:182:13
extension.bundle.js:194:18309
events.js:187:15
extension.bundle.js:194:17141
events.js:273:13
events.js:187:15
_stream_readable.js:1092:12
next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @kintela

Thanks for reporting.

Is this still recurring?  Sometimes Azure has outages and random errors will occur.  Please try again and let me know if it's still happening.  In that case, please leave repro steps as well.

**Comment by kintela** [comment]
Nos works fine thanks
