### ISSUE TITLE
unable to deploy first sample express application to azure app service

### ISSUE THREAD

**Issue by varunsingh8780** [microsoft/vscode-azureappservice#1257]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Permission denied writing to file (file:///Users/Varun/myExpressWork/myExpressApp/.vscode/settings.json)

Version: 0.16.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.32.2
Language: en

<details>
<summary>Call Stack</summary>

```
checkFileBeforeWriting.then.then.t workbench.main.js:3288:756
```

</details>

**Comment by nturinski** [comment]
Hi @varunsingh8780 

It looks like VS Code is trying to write a setting for you and is being denied writing permissions.  Could you try moving the folder to somewhere VS Code would have write access?
