### ISSUE TITLE
Zip deploy failed

### ISSUE THREAD

**Issue by KulikovDO** [microsoft/vscode-azureappservice#1259]
Repro steps:

1. Click Button "Deploy to Web App..."

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.pipeline extension.bundle.js:323:757026
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:576782
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Hi @KulikovDO 

Thanks for reporting.  Could you provide repro steps?

**Comment by KulikovDO** [comment]
Hi Nathan,

Thank you very much for your reply! But fortunately for me the problem
disappeared the next day.
I was performing the same actions to deploy my Angular application to Azure
App Services but the extension threw errors without much details. And now
it works fine again.

Kind regards,
Denis Kulikov
