### ISSUE TITLE
teste_app

### ISSUE THREAD

**Issue by wevertonjfarias** [microsoft/vscode-azureappservice#1268]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:323:357962
a extension.bundle.js:323:357598
```

</details>

**Comment by nturinski** [comment]
Hi @wevertonjfarias

Looks like you're trying to do a local git deploy.  However, you need to run these commands in your repo:

1. `git init`
2. `git add .`
3. `git commit -m 'First commit'`

Then try to deploy again.

**Comment by wevertonjfarias** [comment]
Hi,

thanks.

I will try that way...



Em seg, 4 de nov de 2019 16:15, Nathan <notifications@github.com> escreveu:

**Comment by nturinski** [comment]
Okay, let me know if this resolved the issue or if my steps were unclear 😄
