### ISSUE TITLE
Error 404 On Deployment of NodeJS app

### ISSUE THREAD

**Issue by JoshAnderson123** [microsoft/vscode-azureappservice#1270]
I have deployed a 'Hello World' Windows NodeJS app through the Azure App Service in VSCode. The output of Azure App Service suggests that the deployment was successfull. However, when you go on the website, a 404 error is returnedd by the browser. Here is the output of Azure App Service in VSCode:

```
13:08:09 JA-6MP-Portfolio2: Creating zip package...
13:08:17 JA-6MP-Portfolio2: Starting deployment...
13:08:22 JA-6MP-Portfolio2: Fetching changes.
13:08:22 JA-6MP-Portfolio2: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\meyykuaq.zip (4.39 MB) to D:\local\Temp\zipdeploy\extracted
13:08:35 JA-6MP-Portfolio2: Waiting for long running command to finish...
13:08:36 JA-6MP-Portfolio2: Updating submodules.
13:08:36 JA-6MP-Portfolio2: Preparing deployment for commit id '5825a2c9d7'.
13:08:36 JA-6MP-Portfolio2: Generating deployment script.
13:08:36 JA-6MP-Portfolio2: Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "D:\local\Temp\zipdeploy\extracted" -o "D:\home\site\deployments\tools" --basic --sitePath "D:\local\Temp\zipdeploy\extracted"').
13:08:36 JA-6MP-Portfolio2: Running deployment command...
13:08:36 JA-6MP-Portfolio2: Command: "D:\home\site\deployments\tools\deploy.cmd"
13:08:38 JA-6MP-Portfolio2: Handling Basic Web Site deployment.
13:08:40 JA-6MP-Portfolio2: Creating app_offline.htm
13:08:40 JA-6MP-Portfolio2: KuduSync.NET from: 'D:\local\Temp\zipdeploy\extracted' to: 'D:\home\site\wwwroot'
13:08:40 JA-6MP-Portfolio2: Copying file: '.vscode\settings.json'
13:08:40 JA-6MP-Portfolio2: Deleting app_offline.htm
13:08:40 JA-6MP-Portfolio2: Finished successfully.
13:08:40 JA-6MP-Portfolio2: Running post deployment command(s)...
13:08:40 JA-6MP-Portfolio2: Triggering recycle (preview mode disabled).
13:08:40 JA-6MP-Portfolio2: Deployment successful.
13:08:43: Deployment to "JA-6MP-Portfolio2" completed.
```

Below is the image of the workspace
![image](https://user-images.githubusercontent.com/23026627/68248162-3367ad80-0014-11ea-89f9-22f6ad8eb471.png)

The simple app works as expected when trialing on localhost, so I'm struggling to see immediately what has caused this error to occur.

**Comment by nturinski** [comment]
Hi @JoshAnderson123 

Sorry you're running into so many issues 😦 Hopefully we can resolve this.

Could you verify that you are creating a Linux Node app?  If you click the blue deploy arrow, there should be a `+ Create new Web App... (Advanced)` option.  From there, you can manually select the OS and the runtime.

Could you also send me a screenshot of your workspace?

**Comment by JoshAnderson123** [comment]
Hi @nturinski 

Thanks for getting back to me. This app, unlike the deployment to Linux in #1267 is a Windows Node app. I have updated #1270 to clarify this. Would you suggest changing the OS to Linux? I have also added a screenshot of the workspace to #1270

**Comment by nturinski** [comment]
Yeah, I think for Node.js development, we tend to recommend running Linux OS. I'd recommend giving that a shot!
