### ISSUE TITLE
Struggling to fix Azure Start Remote debugging error. I am using windows 10 and running the commands using bash.

### ISSUE THREAD

**Issue by LTDO** [microsoft/vscode-azureappservice#1271]
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js version >= 8.11 on Linux.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.checkForRemoteDebugSupport extension.bundle.js:157:366496
extension.bundle.js:323:880961extension.bundle.js:323:880961
o extension.bundle.js:323:880314
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @LTDO

What app runtime are you trying to remote debug?
