### ISSUE TITLE
Linux Node.js deployments ignoring .deployment files

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#1274]
When I deploy to a Node.js 12LTS app, I see this message from the output channel:

![image](https://user-images.githubusercontent.com/5290572/68256305-93466000-ffe4-11e9-9418-8fa3a9cdb1f0.png)

Should we not be including .deployment files anymore?  Do we have to make an app setting instead or is building on the server the default behavior now?

**Comment by nickwalkmsft** [comment]
"Ignoring" here is only in the context of KuduSync, the utility that copies files from the deployment package to the deployment directory. It's [hard-coded](https://github.com/Azure-App-Service/KuduLite/blob/3f033f0ee588b29ed112d2694f8cfbcb26e8902f/Kudu.Core/Deployment/Generator/OryxBuilder.cs#L42) to avoid copying files named `.git`, `.hg`, `.deployment` and `.deploy.sh`. Settings in `.deployment` are still respected by the deployment process.
