### ISSUE TITLE
Auto stop the streaming log after executing 'Start Streaming Logs' for the empty web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1280]
**OS:** Mac
**Build Version:** [20191106.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12127)

**Repro Steps:**
1. Create an empty web app.
2. Right click this web app and select 'Start Streaming Logs'.
3. Click 'Yes' in the prompting dialog, then check the activity log.

**Expect:**
There is no 'Disconnected from log-streaming service' until stop streaming log for this web app.

**Actual:**
Auto stop the streaming Log and display 'Disconnected from log-streaming service'.
![image](https://user-images.githubusercontent.com/45614674/68467541-5501a880-0251-11ea-9e45-946b7e0c89fa.png)

**More info:** 
This bug does not reproduce after deploying to web app.

**Comment by nturinski** [comment]
Won't fix pending customer feedback.
