### ISSUE TITLE
Remove the python on windows option

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/vscode-azureappservice#1282]
It is possible to deploy a Python app (e.g. Flask) on Windows using this extension.

This is deprecated (https://docs.microsoft.com/en-us/visualstudio/python/publishing-python-web-applications-to-azure-from-visual-studio?view=vs-2019), leading to an error when trying to run the app.

This leads to confusion with users as they try to deploy a Python app to Widows and see a permissions error on their web site, then they have to google the answer only to find in the docs its deprecated. This was observed at a hackathon this weekend.

Can we remove the option for Windows if they select Python (and maybe add a note in the command palette that windows is deprecated for Python)?

**Comment by nturinski** [comment]
In web app creation, we prompt for OS before runtime.  In the Windows scenario, the user doesn't select the runtime and deploys whatever their project is.  In the Linux scenario, we prompt for a runtime.   We default to Linux runtime if the user is deploying a Python project.

Could you further elaborate on what you mean by removing the option for Windows if they select Python?  As far as I can tell, there really isn't a clear path for the user to use Python on Windows today.

**Comment by jimbobbennett** [comment]
Sorry - clumsily written.

Although the extension defaults to linux, users can still select Windows, and this has happened at a number of hackathons. The Windows option is there and users go for it as they know Windows better than linux.

Seeing as the project type is detected to set the default, could the Windows option just be removed for Python projects? Or even better remove that step and just automatically choose linux?
