### ISSUE TITLE
teste inoarb

### ISSUE THREAD

**Issue by wevertonjfarias** [microsoft/vscode-azureappservice#1283]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:323:357962
a extension.bundle.js:323:357598
```

</details>

**Comment by nturinski** [comment]
Hi @wevertonjfarias 

Please follow the steps in https://github.com/microsoft/vscode-azureappservice/issues/1268.  Closing as duplicate.

**Comment by wevertonjfarias** [comment]
Hi,

I am having trouble publishing my system.

Any suggestions for help?

Att,

Em seg, 11 de nov de 2019 16:13, Nathan <notifications@github.com> escreveu:

**Comment by nturinski** [comment]
Have you initialized a git repo in the directory that you are trying to deploy?

**Comment by wevertonjfarias** [comment]
Yes.

Deployment error occurs, not how to resolve.

Em seg, 11 de nov de 2019 18:55, Nathan <notifications@github.com> escreveu:

**Comment by nturinski** [comment]
Could you send me a screenshot of your workspace?
