### ISSUE TITLE
Unable to SSH into Web App from vscode

### ISSUE THREAD

**Issue by ecc256** [microsoft/vscode-azureappservice#1284]
Repro steps:
1. Deploy app into exiting webapp via vscode (python flask hello)
2. Open URL - everything works fine
3. SSH into Web App from vscode / Azure
4. vscode shows "initializing SSH..." message for ~1-2 min, than show error below
5. SSH works fine from portal
```
Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:99880
o extension.bundle.js:157:95390
```
</details>

```

**Comment by nturinski** [comment]
Hi @ecc256

Have you tried SSHing into the web app again, after it succeeded from the Portal?  Sometimes the port doesn't respond to the request, but the Portal is doing something that enables access to it.
