### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by saulwolfdev** [microsoft/vscode-azureappservice#1285]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy because the path is not part of an open workspace. Open in a workspace and try again.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:354461
o extension.bundle.js:157:353478
```

</details>

**Comment by saulwolfdev** [comment]
New Environment

**Comment by nturinski** [comment]
@saulwolfdev

You need to have the workspace opened in order to deploy it.  There are settings that are used by the extension that requires the project to be opened when deploying.
