### ISSUE TITLE
Enable logging when creating apps.

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#1287]
Logging will eventually get disabled by the platform and that's okay, just make sure that customers can get to the logs as easily as possible for fresh apps. There are two reasons for this:

### 1. The first deployment is the most likely deployment to fail

We see most deployment failures on the initial deployment so anything we can do to improve that experience is a benefit to the customer. 

### 2. We immediately direct customers to the logs after a deployment

After a deployment, the notification includes a "stream logs" button, which, when clicked, launches into a modal to verify that logging needs to be set and the app needs restarting. This is unnecessary.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/microsoft/vscode-azureappservice/pull/1370
