### ISSUE TITLE
Unable to deploy Node.js webapp by following the tutorial

### ISSUE THREAD

**Issue by sureshja** [microsoft/vscode-azureappservice#1289]
Repro steps:

1. Follow [this ](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs)tutorial to deploy a local express (node.js) web app
2. Deploy site to see "service is unavailable" always. Here is the local. Retry deployment will yield the same result. Here is the output log:
9:50:54 AM: Creating resource group "appsvc_linux_centralus" in location "centralus"...
9:50:55 AM: Successfully created resource group "appsvc_linux_centralus".
9:50:55 AM: Ensuring App Service plan "appsvc_linux_centralus" exists...
9:50:56 AM: Creating App Service plan "appsvc_linux_centralus"...
9:53:21 AM: Successfully created App Service plan "appsvc_linux_centralus".
9:53:21 AM: Verifying that Application Insights is available for this location...
9:53:22 AM: Creating new Application Insights resource "gelocal"...
9:55:00 AM: Created new Application Insights resource "gelocal"...
9:55:00 AM: Creating new web app "gelocal"...
9:55:18 AM: Created new web app "gelocal": https://<removed>.azurewebsites.net
9:55:52 AM gelocal: Creating zip package...
9:56:37 AM gelocal: Starting deployment...
10:03:47 AM: Starting "gelocal"...
10:03:48 AM: "gelocal" has been started.
10:12:59 AM gelocal: Creating zip package...
10:13:12 AM gelocal: Starting deployment...
10:15:15 AM: Error: The service is unavailable.

Action: appService.Deploy
Error type: 503
Error Message: The service is unavailable.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.pipeline extension.bundle.js:323:757026
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:576782
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

**Comment by nturinski** [comment]
Hi @sureshja

Sorry that you're having issues with the tutorial.  Sometimes when deploying to a newly created app, it can take a while for it to properly spin up.  Could you please give it another shot and see if it'll deploy?
