### ISSUE TITLE
Cannot SSH to app service

### ISSUE THREAD

**Issue by songpr** [microsoft/vscode-azureappservice#1291]
Repro steps:

1.
2.

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: App is started, but port is unreachable

Version: 0.16.1
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:99743
a extension.bundle.js:157:95441
```

</details>

**Comment by nturinski** [comment]
Hi @songpr 

Is this consistently happening?  Could you try connecting to SSH via the Portal?

**Comment by nturinski** [comment]
Closing as dupe of https://github.com/microsoft/vscode-azureappservice/issues/1011
