### ISSUE TITLE
Error while deployment 

### ISSUE THREAD

**Issue by jainp1** [microsoft/vscode-azureappservice#1292]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "ElbertWeb" failed. See output channel for more details.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:497269
o extension.bundle.js:1:495244
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Hi @jainp1

Thanks for reporting. Could you provide repro steps?
