### ISSUE TITLE
try

### ISSUE THREAD

**Issue by HoangVrian** [microsoft/vscode-azureappservice#1294]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: InvalidResourceNameTrailingCharacters
Error Message: The provided resource name 'mobileshop.cloud.' has these invalid trailing characters: '.'. The name can not end with characters: '. '.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2859688extension.bundle.js:218:2859688
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:576689
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @HoangVrian 

Please try renaming your resource from mobileshop.cloud. to mobileshop.cloud
Resource group names cannot end with a '.' (period)
