### ISSUE TITLE
azure app service  deploy error with Error Message: {}

### ISSUE THREAD

**Issue by liuyang27** [microsoft/vscode-azureappservice#1297]
Repro steps:

1.click  blue up arrow to deploy
2. select folder
3.error popup

Action: appService.Deploy
Error type: object
Error Message: {}

Version: 0.15.0
OS: win32
Product: Visual Studio Code
Product Version: 1.26.1
Language: en

**Comment by nturinski** [comment]
Hi @liuyang27 

Thanks for reporting.  When you're selecting a folder, is it a folder that is in your current workspace?  Are you browsing to it?  What kind of project is contained in your folder?

**Comment by liuyang27** [comment]
yes, I selected my current workspace fold, it contains a common nodeJS
project

**Comment by nturinski** [comment]
Could you try updating your VS Code?  The latest App Service extension v0.16.1 relies on VS Code v1.31.0.

It seems you're using v0.15.0 and 1.26.1 respectively.
