### ISSUE TITLE
Node v12.13.1 is on local PC, Node 12 LTS is running on Azure

### ISSUE THREAD

**Issue by AlDjo** [microsoft/vscode-azureappservice#1298]
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js version >= 8.11 on Linux.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.checkForRemoteDebugSupport extension.bundle.js:157:366496
extension.bundle.js:323:880961extension.bundle.js:323:880961
o extension.bundle.js:323:880314
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
This should be resolved with the latest release, v0.16.2.

Please let me know if it hasn't! 😃
