### ISSUE TITLE
got error while creating deployment slot for kubernetes

### ISSUE THREAD

**Issue by bharathiN** [microsoft/vscode-azureappservice#1301]
Repro steps:

1.
2.

Action: appService.CreateSlot
Error type: Error
Error Message: No matching resources found.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.39.0
Language: en

<details>
<summary>Call Stack</summary>

```
DeploymentSlotsNATreeItem.<anonymous> extension.bundle.js:1:572992
o extension.bundle.js:1:567503
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Closing as a dupe as https://github.com/microsoft/vscode-azureappservice/issues/1310

But to sum it up, your ASP doesn't support deployment slot creation.  You'll have to upgrade to a Standard SKU to have deployment slot creation available to you, unfortunately.
