### ISSUE TITLE
Fail to enable remote debugging for a Linux web app with Python runtime

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1304]
**OS:** Win10
**Build Version:** [20191125.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12677)
**Regression:** Not a Regression

**Repro Steps:**
1. Create a Linux web app with Python runtime.
2. Deploy a project to this web app.
3. Enable "App Service: Enable Python Remote Debugging".
4. Right click the new created Python web app --> Select "Start Remote Debugging."

**Expect:**
Succeed to enable and start the remote debugging for Python web app.

**Actual:**
Fail to start tunnel proxy during starting and enabling python remote debugging.
![image](https://user-images.githubusercontent.com/34729092/69618600-1e12fb80-1075-11ea-9234-2938db3d207a.png)
![image](https://user-images.githubusercontent.com/34729092/69620212-f1141800-1077-11ea-8d55-e1f8b5fe288a.png)

And sometimes display "Timed out"
![image](https://user-images.githubusercontent.com/34729092/69620150-d9d52a80-1077-11ea-966b-0d3b5323c7d6.png)

**Comment by nturinski** [comment]
Can you confirm that the Python web app deployed successfully and is running on Azure?

**Comment by v-dantch** [comment]
Hi Nathan, succeed to deploy the project to the Python web app like below:
![image](https://user-images.githubusercontent.com/34729092/69686049-696eed80-10f9-11ea-93f9-58b1733527ef.png)
And the website displays well:
![image](https://user-images.githubusercontent.com/34729092/69686073-80154480-10f9-11ea-9f9d-cd4ba27d8de2.png)
Then select "Start Remote Debugging", pop up an error "Timed out".
![image](https://user-images.githubusercontent.com/34729092/69686139-b6eb5a80-10f9-11ea-92f5-aabf87f1e202.png)
**More Info:**
Refresh the website again after selecting "Start Remote Debugging", display "Application Error".
![image](https://user-images.githubusercontent.com/34729092/69686504-ed75a500-10fa-11ea-9377-45aa0bb970ab.png)

**Comment by purva-vasudeo** [comment]
I was taking a look at this. What kind of app is being used? If it is a flask app, can you try setting the FLASK_RUN setting as an app setting and try again?

eg. FLASK_RUN=application

**Comment by v-mengwe** [comment]
Verified on the latest build 20200917.5, this issue still reproduces, I will continue to track this issue.
