### ISSUE TITLE
Deploy angular8 basic authentication in azure with visual studio code, azure app service

### ISSUE THREAD

**Issue by dfnocode** [microsoft/vscode-azureappservice#1309]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "webempresa" failed. See output channel for more details.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:497269
o extension.bundle.js:1:495244
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting.  Could you provide repro steps and provide what the output channel contains? Though be sure to remove sensitive information!
