### ISSUE TITLE
Improve error message for when ASP doesn't support Deployment Slots

### ISSUE THREAD

**Issue by jnurit** [microsoft/vscode-azureappservice#1310]
Repro steps:

1. Open a nodejs Project
2. Créate a Linux app service 
3. try to deploy from VS code => Fail

When we try code create app service first in azure portal, and deploy from VSCode
OR
when we try to create + deploy app service from VSCode 

Action: appService.CreateSlot
Error type: Error
Error Message: No matching resources found.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
DeploymentSlotsNATreeItem.<anonymous> extension.bundle.js:1:572899
o extension.bundle.js:1:567410
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
It seems like you are trying to create a slot and then deploy to it?  Unfortunately, if you're running a free or basic SKU, deployment slots are not supported and you will have to upgrade to a standard SKU.

If this is not the issue, could you please elaborate a bit more?
