### ISSUE TITLE
I can't edit file from the azure deploy with vs code

### ISSUE THREAD

**Issue by FilipLaurentiu** [microsoft/vscode-azureappservice#1316]
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: 409
Error Message: Could not write to local resource 'D:\home\site\wwwroot\web.config' due to error 'Access to the path is denied.'.

Version: 0.16.1
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:803184extension.bundle.js:323:803184
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:576654
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @FilipLaurentiu 

Thanks for reporting!

Do you have all permissions and access rights to this web app?  Are you the one who deployed to this web app?

A 409 error usually means that there was a conflict between the server and the client.  Could you try downloading the file and saving it again?
