### ISSUE TITLE
Location Issue with VS code  extension

### ISSUE THREAD

**Issue by a3-debasishdas** [microsoft/vscode-azureappservice#1317]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: MissingRegistrationForLocation
Error Message: The subscription is not registered for the resource type 'components' in the location 'southindia'. Please re-register for this provider in order to have access to this location.

Version: 0.16.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:877988
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7075
extension.bundle.js:157:24982
$._callback extension.bundle.js:1:576689
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @a3-debasishdas 

Could you try creating the app with Advanced Create and hit `Skip for now` when prompted for the Application Insights component?  I think that might be related to your issue.
