### ISSUE TITLE
Azure Remote Debugging is currently only supported for Node.js apps on Linux.

### ISSUE THREAD

**Issue by ereeneid** [microsoft/vscode-azureappservice#1325]
Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js apps on Linux.

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

**Comment by nturinski** [comment]
@ereeneid Thanks for reporting.  If you're trying to remote debug, it's currently only supported on Node.js.  What are you trying to remote debug?
