### ISSUE TITLE
Error publish

### ISSUE THREAD

**Issue by pabloarranz** [microsoft/vscode-azureappservice#1327]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400 Bad Request
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:357801
a extension.bundle.js:288:357437
```

</details>

**Comment by nturinski** [comment]
Does this repro consistently?  Could you provide repro steps?
