### ISSUE TITLE
Service Unavailable when attempting to deploy nodejs app on linux

### ISSUE THREAD

**Issue by tanders111** [microsoft/vscode-azureappservice#1330]
Intermittently get this "service unavailable"   when attempting to  deploy a nodejs app on linux.    The exact code will deploy and run correctly, but then sometime later the app will start return the 503 error and attempting to redeploy the same app also give service unavailable

Action: appService.Deploy
Error type: 503
Error Message: The service is unavailable.

Version: 0.16.2
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:392866extension.bundle.js:323:392866
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:579969
$.t._callback.t.callback.t.callback [as callback] extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@tanders111 please take a look at these docs for debugging 503 errors: https://docs.microsoft.com/azure/app-service/troubleshoot-http-502-http-503

Unfortunately I think this is out of our hands on the VS Code side of things so I'll go ahead and close. That page should have more links about how to get help from the Azure side if necessary.
