### ISSUE TITLE
failed create  

### ISSUE THREAD

**Issue by namhihi237** [microsoft/vscode-azureappservice#1333]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.AddCosmosDBConnection
Error type: Error
Error Message: You must have the "Cosmos DB" extension installed to perform this operation.

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
CosmosDBTreeItem.<anonymous> extension.bundle.js:1:716966
extension.bundle.js:1:714015extension.bundle.js:1:714015
n extension.bundle.js:1:713789
CosmosDBTreeItem.getCosmosDBApi extension.bundle.js:1:716654
CosmosDBTreeItem.<anonymous> extension.bundle.js:1:715721
extension.bundle.js:1:714015extension.bundle.js:1:714015
n extension.bundle.js:1:713789
CosmosDBTreeItem.createChildImpl extension.bundle.js:1:715668
CosmosDBTreeItem.<anonymous> extension.bundle.js:1:571865
extension.bundle.js:1:570921extension.bundle.js:1:570921
n extension.bundle.js:1:570695
CosmosDBTreeItem.createChild extension.bundle.js:1:571651
extension.bundle.js:323:497518extension.bundle.js:323:497518
o extension.bundle.js:323:496969
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@namhihi237 please add repro steps. I'm guessing the bug will go away if you just re-load VS Code, but I'm still curious how you hit this error in the first place
