### ISSUE TITLE
error when deploying a subfolder of angular 8app

### ISSUE THREAD

**Issue by victor-lara** [microsoft/vscode-azureappservice#1334]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code - Insiders
Product Version: 1.41.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46222extension.js:229:46222
extension.js:229:44624extension.js:229:44624
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Nice avatar!

Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: https://github.com/microsoft/vscode-azure-account/issues/53
