### ISSUE TITLE
Error deploy django app

### ISSUE THREAD

**Issue by elequiel** [microsoft/vscode-azureappservice#1336]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.16.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:357801
a extension.bundle.js:288:357437
```

</details>

**Comment by EricJizbaMSFT** [comment]
@elequiel please add repro steps
