### ISSUE TITLE
Cannot deploy python app to Azure App Service

### ISSUE THREAD

**Issue by tronghuy2807** [microsoft/vscode-azureappservice#1337]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 404
Error Message: No log found for '6e575dde0271420d89c64b169efe224d'.

Version: 0.16.2
OS: linux
OS Release: 4.15.0-72-generic
Product: Visual Studio Code
Product Version: 1.32.3
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline extension.bundle.js:323:45122
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] extension.bundle.js:1:580124
$.module.exports.$.init.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:182:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1090:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azureappservice/issues/1324. Seems like this might be an intermittent error. @tronghuy2807 can you try again and see if it works? We can investigate if we get consistent repro steps
