### ISSUE TITLE
Error when creating two web app service from the azure app service extension in vscode

### ISSUE THREAD

**Issue by zzhxiaofeng** [microsoft/vscode-azureappservice#1342]
## VS Code Insiders Info:
Electron: 6.1.5
Version: 1.41.1(system setup)
V8: 7.6.303.31-electron.0
Node.js: 12.13.0
App Service Extension Version: 0.16.2

## Issue Description:
The issue happens when creating two app service using the same service plan

## Reproduce Steps:
1. Install App Service Extension in vscode
2. Create a Linux web app.
3. Create another one Linux web app when the above creation is in progress.
4. Check the result.

Expect:
Succeed to create the second Linux web app even though the first creation is in progress.

Actual:
Pop up below error when starting to create the second Linux web app.
![63821248-d51caf80-c97e-11e9-8f99-94de32bbf9a5](https://user-images.githubusercontent.com/20970631/71607880-23a1bb00-2bb8-11ea-9861-bc38b80fca99.png)

## More Info:
1. Original Issue Link: azure/azure-sdk-for-js#4921
2. Make sure creating the new resource group and new App Service plan when creating the app service in vscode

**Comment by zzhxiaofeng** [comment]
@nturinski Can you take a look?

**Comment by EricJizbaMSFT** [comment]
Yeah we'll look into it

**Comment by EricJizbaMSFT** [comment]
Closing this as won't-fix. The workaround is just to wait and create later
