### ISSUE TITLE
not able to update web.config 

### ISSUE THREAD

**Issue by sameerbk** [microsoft/vscode-azureappservice#1343]
Does this occur consistently? Yes
Repro steps:

1. Create Web App, upload file changes
2. Edit web.config and try to save.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: 409
Error Message: Could not write to local resource 'D:\home\site\wwwroot\web.config' due to error 'Access to the path is denied.'.

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:439024extension.bundle.js:323:439024
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:579996
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @sameerbk

Are you able to edit any other files in your web app?
