### ISSUE TITLE
Failed to deploy because the path is not part of an open workspace issues

### ISSUE THREAD

**Issue by oscarrod5** [microsoft/vscode-azureappservice#1344]
Does this occur consistently? 

1. In the AZURE APP SERVICE explorer, select the blue up arrow icon to deploy your app to Azure.
2. Choose the directory that you currently have open, myExpressApp.
(I'm currently working a Macbook pro)

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy because the path is not part of an open workspace. Open in a workspace and try again.

Version: 0.16.2
OS: darwin
OS Release: 17.7.0
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:719808
o extension.bundle.js:1:719007
```

</details>

**Comment by EricJizbaMSFT** [comment]
@oscarrod5 We need you to have the folder open as a part of the workspace, but it seems like you said that's already the case? Could you send a screenshot of your workspace? Maybe there's something unique going on
