### ISSUE TITLE
issues updating

### ISSUE THREAD

**Issue by justinl14215** [microsoft/vscode-azureappservice#1347]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND rounddaway.scm.azurewebsites.net rounddaway.scm.azurewebsites.net:443

Version: 0.16.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:57:26
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting.  Please provide repro steps.
