### ISSUE TITLE
Azzure App Service Extensions issue

### ISSUE THREAD

**Issue by Ashitk1997** [microsoft/vscode-azureappservice#1349]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:323342
o extension.bundle.js:157:318852
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
