### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Finallyclean** [microsoft/vscode-azureappservice#1353]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "wxapp133569" failed. See output channel for more details.

Version: 0.16.2
OS: darwin
OS Release: 19.0.0
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:503230
o extension.bundle.js:1:500515
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
@Finallyclean Thanks for reporting. Could you please provide repro steps?
