### ISSUE TITLE
vscode problem

### ISSUE THREAD

**Issue by Aression** [microsoft/vscode-azureappservice#1354]
The issue text was copied to the clipboard.  Please paste it into this window.

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: AuthorizationFailed
Error Message: The client 'vita@dl444outlook.onmicrosoft.com' with object id '4e8d122d-8e4f-4193-a2be-44dfed657131' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/124aa4a7-76e9-4f99-95e4-01e08fefe37a/resourceGroups/appsvc_windows_centralus/providers/Microsoft.Web/serverfarms/appsvc_windows_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:3522735extension.bundle.js:218:3522735
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @Aression

Thanks for reporting.  Please try the "Advanced Create" available so that you can change what App Service Plan your resource is being created in.  It seems you don't have proper permissions for the default plan.
