### ISSUE TITLE
Name not valid

### ISSUE THREAD

**Issue by AmritaSarjana** [microsoft/vscode-azureappservice#1355]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: BadRequest
Error Message: Name Pizza Order Assistant is not valid.

Version: 0.16.2
OS: linux
OS Release: 5.0.0-37-generic
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:2859689
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.EventEmitter.emit domain.js:471:20
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
$.EventEmitter.emit domain.js:471:20
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
IncomingMessage.EventEmitter.emit domain.js:471:20
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Is the name of your app Pizza Order Assistant?  I tried to name a web app the same thing, but our name validator catches it.

![image](https://user-images.githubusercontent.com/5290572/72299128-caed0c00-3614-11ea-949b-6a081ff7d87d.png)
