### ISSUE TITLE
Update defaults when creating new apps

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#1357]
- [ ] Enable verbose/application logging (related to #1287)
- [x] Enable HTTP logging
- [ ] Set `SCM_DO_BUILDING_DURING_DEPLOYMENT` to `true` (need this when creating Windows too)
- [ ] Set `logsDirectorySizeLimit` to `100`

I still need to verify that `WEBSITE_HTTPLOGGING_RETENTION_DAYS` is being honored in Linux so that may need to be set as well.

**Comment by nturinski** [comment]
Is `WEBSITE_HTTPLOGGING_RETENTION_DAYS` not honored in Windows?  We've been setting it to 7 whenever we enabled log streaming in the past.

**Comment by nturinski** [comment]
@fiveisprime

Can you confirm that all logging isn't enabled by this one setting?
![image](https://user-images.githubusercontent.com/5290572/73314880-75535a80-41e3-11ea-8f27-3eeac09c9a28.png)

https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs

This documentation seems to imply that to get all this logging, you just enable Application Logging, but I haven't been able to confirm that.

This PR https://github.com/microsoft/vscode-azureappservice/pull/1370 only enables httpLogs in the code, but when I go to the portal, Application Logging seems to be enabled.

Also, we might not want to default `retentionInDays` to 7.  According to this tooltip, by default, logs are never deleted:

![image](https://user-images.githubusercontent.com/5290572/73315090-0aeeea00-41e4-11ea-81e7-cd4066184470.png)

Maybe we should pass in undefined for that property?

**Comment by fiveisprime** [comment]
I'm not sure about the UI element, but you should be able to see this in the web app object (these should be defaults that the extension sets): 

```js
{
  "httpLoggingEnabled": true
  "logsDirectorySizeLimit": 100
  "virtualApplications": ["preloadEnabled": true]
}
```

**Comment by fiveisprime** [comment]
I added a note that the SCM_DO_BUILD... app setting should also be set for Windows apps. This comes from feedback from the docs team where the Windows workflow (via local git) run npm install by default.

**Comment by fiveisprime** [comment]
Discussed offline: check and re-enable file logging on deploy.
