### ISSUE TITLE
Failed to find pre-deploy task "publish-release"

### ISSUE THREAD

**Issue by srcsakthivel** [microsoft/vscode-azureappservice#1360]
Does this occur consistently? Yes.
Repro steps:

1. Created the new project (dotnet new mvc -n movie)
2. Tried to do the deploy webapp

Action: appService.Deploy
Error type: Error
Error Message: Failed to find pre-deploy task "publish-release". Modify your tasks or the setting "appService.preDeployTask".

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:366020
o extension.bundle.js:288:363366
```

</details>

**Comment by nturinski** [comment]
HI @srcsakthivel 

Thanks for reporting.  Could I see your workspace you're deploying and your `tasks.json`?  If you are deploying a new .NET project, you should see this prompt:

![image](https://user-images.githubusercontent.com/5290572/72836948-7b28c900-3c42-11ea-8437-2c62bd8c0b32.png)

Which should set up the pre-deploy tasks for you.
