### ISSUE TITLE
I cannot deploy an angular spa to azure web app

### ISSUE THREAD

**Issue by leonardobottadeo** [microsoft/vscode-azureappservice#1362]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.16.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:392866extension.bundle.js:323:392866
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting!

To deploy an Angular SPA app, we actually recommend using the [Azure Storage extension.](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage)

It's possible to do it via Azure App Service, but you need to set up virtual directories.  This tutorial goes into detail on how to do that: https://levelup.gitconnected.com/deploy-angular-application-on-azure-web-service-960e441bb13d
