### ISSUE TITLE
No log found

### ISSUE THREAD

**Issue by rico3d2001** [microsoft/vscode-azureappservice#1365]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Redeploy
Error type: 404
Error Message: No log found for 'c30ad453099615e08b3ea766575ed5c1bfd126cc'.

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:45122extension.bundle.js:323:45122
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @rico3d2001 

Thanks for reporting.  Could you provide repro steps?  Does this happen consistently?  Could you try redeploying it again?

**Comment by EricJizbaMSFT** [comment]
I've seen this occasionally. Maybe we can ignore a single failed log and display the best we can
