### ISSUE TITLE
visual studio code

### ISSUE THREAD

**Issue by maqalaqil** [microsoft/vscode-azureappservice#1366]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN azora.scm.azurewebsites.net

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by nturinski** [comment]
Hi @maqalaqil 

Thanks for reporting.  Could you provide repro steps?
