### ISSUE TITLE
Cant deploy anymore my app

### ISSUE THREAD

**Issue by jilusan** [microsoft/vscode-azureappservice#1368]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.16.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:392866extension.bundle.js:323:392866
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982extension.bundle.js:157:24982
$._callback extension.bundle.js:1:579996
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by jilusan** [comment]
Yes. Consistently. I can't deploy my app anymore.

**Comment by nturinski** [comment]
Hi @jilusan 

Sorry that you're running into this problem.  It sounds very frustrating.  Have you been able to try restarting the app and then deploying again?  Sounds like something is hung up somewhere.

**Comment by jilusan** [comment]
No, could not solve the issue.

I restarting the app service, even create another one, deploying. Same
issue.
Even I created a fresh new app and deployed too. Same issue.

What is the next step?

Thanks

Gil

**Comment by nturinski** [comment]
Could you let me know what deployment method are you using?  Zip deploy, local git, or GitHub?

**Comment by jilusan** [comment]
Hi Nathan,
I created a Node,js App services in Azure,
I am following the tutorial:
https://docs.microsoft.com/fr-fr/azure/app-service/containers/quickstart-nodejs
I presume, it is a Zip deploy.
Thanks
Gil

**Comment by nturinski** [comment]
Sorry for the delayed response.  I'm investigating this, but unfortunately, this is most likely a platform issue, so I'm not sure how much control we have over it.

**Comment by EricJizbaMSFT** [comment]
Unfortunately we don't have enough info to investigate on the VS Code side. I'd recommend getting support directly from the Azure team - there should be options in the portal to do so
