### ISSUE TITLE
Deleted app service plan still shows up in the portal

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#137]
Repro steps:
1. Create a new web app with a new app service plan
1. Delete that web app
1. Select 'Yes' when it prompts you about deleting the app service plan
1. Go to the portal and navigate to either the resource group containing the plan or to the 'App Service Plans' section

Expected: The app service plan does not show up in the portal
Actual: The app service plan is still listed in the portal, but it's in a weird state (You can't view any details or perform any operations)

**Comment by EricJizbaMSFT** [comment]
I just tried performing all the same steps in the portal and I'm seeing the same behavior. We will likely have to follow up with portal team

**Comment by BenAffleckIsBatman** [comment]
Any news on this ? Still the same for me. How can we get rid of these orphaned App Service Plans ?

**Comment by EricJizbaMSFT** [comment]
Nope - no news. The only workaround I know of is to delete the resource group containing the plans. That being said - the orphaned plans should _not_ be incurring any charges or anything like that.

I'm going to go ahead and close this issue since it doesn't affect the VS Code extension at all and can't be fixed in VS Code anyways. It would have to be fixed in the portal

**Comment by EricJizbaMSFT** [comment]
According to the app service team: "it's an ARM sync issue, the ARM layer caches all of that stuff and it will eventually go away"
