### ISSUE TITLE
Error: Deployment

### ISSUE THREAD

**Issue by w1rya** [microsoft/vscode-azureappservice#1376]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "macdkatalog" failed. See output channel for more details.

Version: 0.16.2
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:503230
o extension.bundle.js:1:500515
o extension.bundle.js:1:255993
extension.bundle.js:1:256490extension.bundle.js:1:256490
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@w1rya please add repro steps and copy the logs from the output channel here
