### ISSUE TITLE
my issue 

### ISSUE THREAD

**Issue by Seriouskill** [microsoft/vscode-azureappservice#1378]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN hachy-web.scm.azurewebsites.net

Version: 0.16.2
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by nturinski** [comment]
EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.  Could you please try again and let me know if it is still occurring?
