### ISSUE TITLE
Error: XML error: not well-formed (invalid token) error: no DAV locking support on

### ISSUE THREAD

**Issue by osinpl** [microsoft/vscode-azureappservice#1379]
Does this occur consistently? 
Repro steps:

1.  deployment source set LocalGit - choose folder
2. push button Deploy to Web app
 
Action: appService.Deploy
Error type: Error
Error Message: XML error: not well-formed (invalid token)
error: no DAV locking support on https://***:***@***.scm.azurewebsites.net:443/***.git/
fatal: git-http-push failed
error: failed to push some refs to ttps://***:***@***.scm.azurewebsites.net:443/***.git/

Version: 0.16.2
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:357801
a extension.bundle.js:288:357437
```

</details>

**Comment by EricJizbaMSFT** [comment]
@osinpl please add repro steps, including what type of local app you're deploying and how you created the web app in azure

**Comment by osinpl** [comment]
Sorry upated, but I see now the sam problem is when I use Git from command line.

**Comment by nturinski** [comment]
Seems like something is up with your authentication. What command are you running to deploy from the command line?  Do you have a profile saved for pushing to the azure remote?

**Comment by osinpl** [comment]
Hi,

I follow the instructions, but simple it’s - git push azure master

Yes I have profile for deploy but don’t know exactly what do you mean SAVED?

Br, Kris

**Comment by nturinski** [comment]
Don't post it here, but what does `git remote -v` show?  Does it have credentials attached to the url?  If not, are you manually typing in credentials when you git push?

**Comment by osinpl** [comment]
Yep, tried everything (think so) git remote set-url, only username, username and password, then https to ssh, then with port 443 and without, nothing works so far.

**Comment by nturinski** [comment]
Hi @osinpl 

Sorry for the late response.  I was thinking about what else it could be.  Have you set up a publishing profile for the Azure repository? Do you have the option to try deploying to a new app?
