### ISSUE TITLE
Error while deploying using Azure App Service Extension

### ISSUE THREAD

**Issue by chhavikishore** [microsoft/vscode-azureappservice#1380]
Tried to deploy using the instructions given. First time it deployed properly, from next time onwards the deployment is having an error and not deploying using the extension.

Does this occur consistently? Yes

Action: appService.Deploy
Error type: 404
Error Message: An error has occurred.

Version: 0.16.2
OS: linux
OS Release: 5.3.0-26-generic
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:323:48436
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @chhavikishore 

Thanks for reporting.  Have you changed any settings or your project between deployments?  Have you tried to deploy again or to a new app?  Sometimes the platform has outages that are beyond the extension's control.
