### ISSUE TITLE
Disconnected from log-streaming service directly after starting streaming log for a Linux web app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1388]
**OS:** Win 10
**Build Version:** [20200210.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14547&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression

**Repro Steps:**
1. Create/Select a Linux Web app --> Start Streaming Logs
2. Create/Select a Windows Web app --> Start Streaming Logs
3. Check the result.

**Expect:**
Display the details as the below both Linux Web app and Windows Web app after clicking Start Streaming Logs. Didn't disconnect automatically.
![image](https://user-images.githubusercontent.com/57662131/74298604-3269b900-4d85-11ea-8d38-0df5c08bb8c9.png)

**Actual:**
Linux web app: Disconnected from log-streaming service directly.
Windows web app: The default timeout is 2 hours.
![image](https://user-images.githubusercontent.com/57662131/74298868-f08d4280-4d85-11ea-9f3a-66fd22120f7c.png)

**Comment by neelip** [comment]
Cannot reproduce this scenario. Both Log streams for Linux and Windows apps are running together and only disconnecting with `Stop Log Streaming` command for each app.

**Comment by v-xinda** [comment]
Verified this issue on the latest build 20210415. 7, it doesn't reproduce. So I close it.

**Comment by ericis** [comment]
Getting this issue on latest build 

![image](https://user-images.githubusercontent.com/974919/116758723-ab7f1b80-a9de-11eb-8e37-b76a34255998.png)
