### ISSUE TITLE
vscode azure

### ISSUE THREAD

**Issue by falash143** [microsoft/vscode-azureappservice#1393]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy because the path is not part of an open workspace. Open in a workspace and try again.

Version: 0.16.2
OS: darwin
OS Release: 19.0.0
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:719808
o extension.bundle.js:1:719007
```

</details>

**Comment by EricJizbaMSFT** [comment]
@falash143 try opening the folder in a workspace before deploying. If you need more help or want to propose a change in behavior, please add more detailed repro steps
