### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by prinsiahirwar1995** [microsoft/vscode-azureappservice#1399]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy because the path is not part of an open workspace. Open in a workspace and try again.

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:719808extension.bundle.js:1:719808
o extension.bundle.js:1:719007
```

</details>

**Comment by nturinski** [comment]
Hi @prinsiahirwar1995 

Thanks for reporting.  We require that you have the workspace that you are deploying open due to project settings that we use when deploying.  If that doesn't resolve your issue, please reopen and provide repro steps.
