### ISSUE TITLE
Zip Deploy

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azureappservice#14]

**Comment by fiveisprime** [comment]
Ran into a couple of issues while attempting to deploy (running on Windows).

- [ ] kudu-api isn't included in package.json
- [ ] The archive doesn't appear to have been created, got an ENOENT on package.zip

**Comment by whiskeyjay** [comment]
Solved missing kudu-api reference.
Archive not created because I am still working on it.
As for the bad state issue, deployment slots shall be able to help, something we should support soon.

**Comment by whiskeyjay** [comment]
https://github.com/Microsoft/vscode-azureappservice/pull/21
