### ISSUE TITLE
Deploying NodeJS app on azure

### ISSUE THREAD

**Issue by AyePar** [microsoft/vscode-azureappservice#1400]
1.trying to deploy my NodeJS app on azure using Web App service and this error happen

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1

**Comment by EricJizbaMSFT** [comment]
@AyePar did you configure your web app for local git? If so, make sure that the folder you're trying to deploy is a git repository. If that's not your problem, please add more details to the repro steps
