### ISSUE TITLE
Not Publishing to Azure

### ISSUE THREAD

**Issue by Kylar182** [microsoft/vscode-azureappservice#1407]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "tally-io-testing" failed. See output channel for more details.

Version: 0.16.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:503230
o extension.bundle.js:1:500515
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Hi @Kylar182 

Thanks for reporting.  Could you provide the output channel error details and repro steps, please?

**Comment by Kylar182** [comment]
In all honesty I just clicked the “report this error” thing. I did get it working on VS Community and it turns out my target environment was set incorrectly so that may have been the issue, I’m not sure.

Thanks,
Andrew J. Beeman
PH Cell:  (217) 549-5995
https://tally-io.com/
[cid:image001.jpg@01D5EB2F.30FB6630]

Note: To protect against computer viruses, e-mail programs may prevent sending or receiving certain types of file attachments.  Check your e-mail security settings to determine how attachments are handled

This message contains confidential information and is intended only for recipient. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately if you have received this e-mail by mistake and delete this e-mail from your system. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by EricJizbaMSFT** [comment]
Closing since they got it working
