### ISSUE TITLE
unable to auto-deploy angular app into azure

### ISSUE THREAD

**Issue by snehasalla** [microsoft/vscode-azureappservice#1409]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: error: RPC failed; HTTP 409 curl 22 The requested URL returned error: 409
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

Version: 0.16.2
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:357801
a extension.bundle.js:288:357437
```

</details>

**Comment by EricJizbaMSFT** [comment]
Looks related to https://github.com/microsoft/vscode-azureappservice/issues/1006. If not, @snehasalla please add repro steps
