### ISSUE TITLE
Error while trying to remote debug

### ISSUE THREAD

**Issue by codebizness** [microsoft/vscode-azureappservice#1410]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.16.2
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:157:323342
o extension.bundle.js:157:318852
```

</details>

**Comment by EricJizbaMSFT** [comment]
@codebizness please add repro steps

**Comment by codebizness** [comment]
@EricJizbaMSFT  I was not able to reproduce it.
