### ISSUE TITLE
Error Message: Failed to find pre-deploy task "publish-release". Modify your tasks or the setting "appService.preDeployTask".

### ISSUE THREAD

**Issue by Mac2m** [microsoft/vscode-azureappservice#1413]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to find pre-deploy task "publish-release". Modify your tasks or the setting "appService.preDeployTask".

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:366020
o extension.bundle.js:288:363366
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Mac2m please add detailed repro steps
