### ISSUE TITLE
Suggestion: options 

### ISSUE THREAD

**Issue by PeterWone** [microsoft/vscode-azureappservice#1421]
Supporting the use of an existing app as a template when creating a web app.

You'll be able to crib all sorts of details like 
* Resource group
* App Service Plan
* Operating system
* Stack

**Comment by EricJizbaMSFT** [comment]
This is pretty open ended at the moment. Do you have any suggestions on the experience here? It would hard to know which details someone wanted us to copy over and which ones they didn't want.

We already support "Generate Azure CLI Script" which you could use to replace certain details and deploy a similar web app

**Comment by PeterWone** [comment]
Oh yes, I didn't think of that. As you say, a generated CLI script would meet the need _and_ give an opportunity for review and customization. On that basis I'm going to close this myself.

Thanks for giving this your attention.
