### ISSUE TITLE
issue on deployment

### ISSUE THREAD

**Issue by ArunBhalavi** [microsoft/vscode-azureappservice#1424]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription 'f91fbe51-89b9-47af-9d35-3fc41b4d090b' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.16.2
OS: linux
OS Release: 5.3.0-40-generic
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:504785
s extension.bundle.js:218:111699
s extension.bundle.js:157:26069
extension.bundle.js:157:27311
o extension.bundle.js:164:7076
extension.bundle.js:157:24982
$._callback extension.bundle.js:1:580031
$.t._callback.t.callback.t.callback extension.bundle.js:194:5449
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18309
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17141
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
Hi @ArunBhalavi

Looks like you'll have to re-enable your subscription.  This should aid you with that:
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/subscription-disabled

Please let me know if this doesn't address your issues.
