### ISSUE TITLE
Problem to deploy angular app into Azure Linux box 

### ISSUE THREAD

**Issue by langdeng** [microsoft/vscode-azureappservice#1429]
The issue text was copied to the clipbo

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: remote: Deploy Async        
remote: Updating branch 'master'.        
remote: Updating submodules.        
remote: Preparing deployment for commit id '36341c894a'.        
remote: Repository path is /home/site/repository        
remote: Running oryx build...        
remote: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx        
remote: You can report issues at https://github.com/Microsoft/Oryx/issues        
remote: 
remote: Oryx Version      : 0.2.20191105.2, Commit: 67e159d71419415435cb5d10c05a0f0758ee8809, ReleaseTagName: 20191105.2        
remote: Build Operation ID: |tbACI4BBm5k=.320f6941_        
remote: Repository Commit : 36341c894a021e47ff57b7566831f17f26a80bf4        
remote: 
remote: Warning: An outdated version of node was detected (10.17.0). Consider updating.\nVersions supported by Oryx: https://github.com/microsoft/Oryx        
remote: 
remote: Using intermediate directory '/tmp/8d7c17ec7bfa79d'.        
remote: 
remote: Copying files to the intermediate directory...        
remote: Done in 0 sec(s).        
remote: 
remote: Source directory     : /tmp/8d7c17ec7bfa79d        
remote: Destination directory: /home/site/wwwroot        
remote: 
remote: 
remote: Using Node version:        
remote: v10.17.0        
remote: 
remote: Using Npm version:        
remote: 6.11.3        
remote: 
remote: Running 'npm install'...        
remote: 
remote: ..............................................................................................................
remote: 
remote: > core-js@3.6.4 postinstall /tmp/8d7c17ec7bfa79d/node_modules/core-js        
remote: > node -e "try{require('./postinstall')}catch(e){}"        
remote: 
remote: [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m        
remote: 
remote: [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m        
remote: [96m>[94m https://opencollective.com/core-js [0m        
remote: [96m>[94m https://www.patreon.com/zloirock [0m        
remote: 
remote: [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m        
remote: 
remote: 
remote: > core-js@2.6.11 postinstall /tmp/8d7c17ec7bfa79d/node_modules/karma/node_modules/core-js        
remote: > node -e "try{require('./postinstall')}catch(e){}"        
remote: 
remote: 
remote: > @angular/cli@8.3.25 postinstall /tmp/8d7c17ec7bfa79d/node_modules/@angular/cli        
remote: > node ./bin/postinstall/script.js        
remote: 
remote: ......
remote: added 1193 packages from 1123 contributors and audited 19435 packages in 125.671s        
remote: found 0 vulnerabilities        
remote: 
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/webpack-dev-server/node_modules/fsevents):        
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})        
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/watchpack/node_modules/fsevents):        
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})        
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/karma/node_modules/fsevents):        
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})        
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):        
remote: 
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})        
remote: Running 'npm run build'...        
remote: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/@angular/compiler-cli/node_modules/fsevents):        
remote: 
remote: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})        
remote: 
remote: 
remote: > gauges-demo@0.0.0 build /tmp/8d7c17ec7bfa79d        
remote: > ng build        
remote: 
remote: ..............................................................................
remote: Generating ES5 bundles for differential loading...        
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To https://lang-angular-test.scm.azurewebsites.net:443/lang-angular-test.git
   5c41373..36341c8  HEAD -> master

Version: 0.16.2
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:288:357801
a extension.bundle.js:288:357437
```

</details>
ard.  Please paste it into this window.

**Comment by EricJizbaMSFT** [comment]
Looks related to https://github.com/microsoft/vscode-azureappservice/issues/1006. If not, please add repro steps
