### ISSUE TITLE
Git deploy right after creating the Web App fails

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#143]
Repro steps:
1. Create a web app
1. Open the node-js hello world repo for app services
1. Local git deploy to web app soon after creating

Expected: success

Actual:
![image](https://user-images.githubusercontent.com/11282622/31917103-b430ecfa-b80a-11e7-8cf8-1bbf193dfeb4.png)

NOTE: Because of #142, you can't see the whole message. It's something to do with 'Remote End hung up unexpectedly'

**Comment by nturinski** [comment]
Same issue with Deploy to Web App.   The deployment will say it has succeeded, but it doesn't display the deployed website.

**Comment by nturinski** [comment]
I think that this may have to be fixed before we can implement #70

**Comment by nturinski** [comment]
This doesn't repro anymore-- deploying immediately after web app creation works now.
