### ISSUE TITLE
Prompt to install C# extension when opening a .cs file even though the C# extension has been installed

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1430]
**OS**: All
**Build Version**: [20200228.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15458&view=artifacts&type=publishedArtifacts) 

**Repro Steps:**
1. Make sure the C3 extension has been installed.
2. Open a .NET Core application --> Open a xx.cs file in VS Code.

**Expect:**
There is no prompting told the users to install C# extension due to it has been installed.

**Actual:**
Prompt to install C# extension -->Install -->Display "no extension found".
![image](https://user-images.githubusercontent.com/34729092/76068263-b3137380-5f45-11ea-87ac-9d79f9d32c52.png)

**Comment by EricJizbaMSFT** [comment]
Yeah this is annoying, but looks like it's already being tracked in the C# extension and in VS Code:

https://github.com/OmniSharp/omnisharp-vscode/issues/3623

https://github.com/microsoft/vscode/issues/92153
