### ISSUE TITLE
Ixi deu bug inovo

### ISSUE THREAD

**Issue by jiraspiom** [microsoft/vscode-azureappservice#1432]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "meconte" failed. See output channel for more details.

Version: 0.16.2
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:503230
o extension.bundle.js:1:500515
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jiraspiom please check the output window for more details and add detailed repro steps here if that doesn't help
