### ISSUE TITLE
deploy test

### ISSUE THREAD

**Issue by remoju** [microsoft/vscode-azureappservice#1434]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "RemojuWeb" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.16.3
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: ja

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:218:3756621
extension.bundle.js:218:3754488
i extension.bundle.js:218:3754174
extension.bundle.js:218:3756338
t.ExtHostProgress._withProgress extensionHostProcess.js:495:724
t.ExtHostProgress.withProgress extensionHostProcess.js:495:478
Object.withProgress extensionHostProcess.js:787:930
Object.<anonymous> extension.bundle.js:218:3756270
fulfilled extension.bundle.js:218:3754242
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@remoju it seems like you configured your web app for GitHub deploy, meaning the deploy button in our extension cannot be used. Instead, just push a commit to GitHub
