### ISSUE TITLE
Azure App Service Python remote debugging

### ISSUE THREAD

**Issue by rajata07** [microsoft/vscode-azureappservice#1435]
Azure App Service supports Python remote debugging. However, the extension still throws the following error: 

Error Message: Azure Remote Debugging is currently only supported for Node.js apps on Linux.

**Comment by EricJizbaMSFT** [comment]
@rajata07, Python should be supported under a feature flag at the moment. Try setting `appService.enablePythonRemoteDebugging` to true

**Comment by rajata07** [comment]
@EricJizbaMSFT thanks for your reply. It does not throw this error any more with the setting you mentioned. I will close this issue. However, I get now:

"Unable to establish connection to application: App is started, but port is unreachable"

My app is running on 8000 port in Azure and its reachable. Any idea?

**Comment by EricJizbaMSFT** [comment]
There's a few known issue around this, could be related to https://github.com/microsoft/vscode-azureappservice/issues/1304 or https://github.com/microsoft/vscode-azureappservice/issues/1011

Unfortunately those still need investigation and don't have a known workaround at the moment
