### ISSUE TITLE
No log info indicates that process has been terminated when canceling enabling remote debugging

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#1437]
**OS:** Windows
**Build Version:** [20200309.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16012&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a Linux web app with node.js runtime --> Deploy a project to it.
2. Select "Start Remote Debugging" from the web app context menu --> Select "Enable" when prompting to enable remote debugging.
![image](https://user-images.githubusercontent.com/34729092/76295973-74d4d600-62f0-11ea-989c-bca1d3f1cb3d.png)
3. Select "Cancel" during the process --> Check the log info in Output window.

**Expect:**
There are obvious info indicating the process has been terminated.

**Actual:**
No log info indicates the process that has been terminated.

**More Info:**
Also reproduces when canceling "SSH into Web App".

**Comment by EricJizbaMSFT** [comment]
The progress dialog goes away when the user clicks cancel and that's the only feedback that's necessary
