### ISSUE TITLE
taking tow much time to deploy

### ISSUE THREAD

**Issue by anupampahari** [microsoft/vscode-azureappservice#1438]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "as-iop-ui-dev-001" failed. See output channel for more details.

Version: 0.16.2
OS: win32
OS Release: 10.0.10586
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:503230
o extension.bundle.js:1:500515
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting @anupampahari.  Could you provide the details in the output channel and repro steps please?
