### ISSUE TITLE
Streaming Log Service is not working when rigth-clicking on the app service in Azure Extension

### ISSUE THREAD

**Issue by gyurisc** [microsoft/vscode-azureappservice#1441]
Does this occur consistently? Yes
Repro steps:

I right-click on my app service to start streaming logs and this error happens. I expect the streaming log to open instead.

I can open it by navigating to Streaming Log inside the appservice

Action: appService.startStreamingLogs
Error type: Error
Error Message: Entry not found in cache.

Version: 0.16.3
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078extension.js:229:174078
extension.js:229:46161extension.js:229:46161
extension.js:229:44154extension.js:229:44154
extension.js:229:43776extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
