### ISSUE TITLE
Error vscode with azure

### ISSUE THREAD

**Issue by cesarvil4** [microsoft/vscode-azureappservice#1448]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "appinvestco" failed. See output channel for more details.

Version: 0.16.3
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:540634
fulfilled extension.bundle.js:1:537773
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting @cesarvil4.  Could you add repro steps and the output channel details?

**Comment by cesarvil4** [comment]
Sure @nturinski, the following steps:

1. Login in vscode with azure credentials
2. Create a new web app
3. Deploy to this web app created 
4. Error to deploy "Error: An error has occurred."

**Comment by nturinski** [comment]
Is there additional output?  What kind of web app?  The OS?  The runtime?  What kind of project are you trying to deploy?  Have you tried deploying to another web app?
