### ISSUE TITLE
Node.js service deploy issue

### ISSUE THREAD

**Issue by aantonov80** [microsoft/vscode-azureappservice#1452]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: EPERM
Error Message: EPERM: operation not permitted, scandir 'c:\Users\olga\Work\export\export-server\bin\mac\chromium\mac-564778\chrome-mac\Chromium.app\Contents\Versions\69.0.3452.0\Chromium Framework.framework\Helpers'

Version: 0.16.3
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

**Comment by nturinski** [comment]
Hi @aantonov80 

It seems like you might not have permission to a file in this directory or the entire directory itself.  Could you try moving the project to a location that you definitely have permissions for?
