### ISSUE TITLE
resourceGroupName issue

### ISSUE THREAD

**Issue by squarezw** [microsoft/vscode-azureappservice#1453]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+[^.]$/

Version: 0.16.3
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
WebApps._getConfiguration extension.bundle.js:218:1884606
extension.bundle.js:218:3167300
WebApps.getConfiguration extension.bundle.js:218:3167278
SiteClient.<anonymous> extension.bundle.js:316:13399
extension.bundle.js:316:10417
i extension.bundle.js:316:10103
SiteClient.getSiteConfig extension.bundle.js:316:13221
extension.bundle.js:157:396411
fulfilled extension.bundle.js:157:395201
```

</details>

**Comment by nturinski** [comment]
Hi @squarezw 

Thanks for reporting.  Are you able to use your resource group name in the Azure Portal?

**Comment by squarezw** [comment]
Yes. I am able to use it on Portal, but for VSCode is not work now.

**Comment by nturinski** [comment]
Could you provide the resource group name that you are trying to use for repro purposes?

**Comment by squarezw** [comment]
The group name is "squareenix". it doesn't show on portal somehow. but only show on my VSCode.

**Comment by nturinski** [comment]
Hi @squarezw

I was able to create and deploy an app with the resource group name "squareenix" with no issues.  Could you provide more steps to repro this? Are you using some special characters along with "squareenix"?
