### ISSUE TITLE
Error appears when starting deploy again after previous deploy was completed

### ISSUE THREAD

**Issue by aantonov80** [microsoft/vscode-azureappservice#1454]
Does this occur consistently? Yes
Repro steps:
1. Start deploying

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.16.3
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:316:399870
retryCallback extension.bundle.js:218:116490
retryCallback extension.bundle.js:157:31058
extension.bundle.js:157:32671
handleRedirect extension.bundle.js:164:7747
extension.bundle.js:157:29843
Request._callback extension.bundle.js:1:629227
Request.r._callback.r.callback.r.callback extension.bundle.js:194:6012
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:194:19284
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:194:18074
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
@aantonov80

Could you try deploying again or restarting your app?  Sometimes the app gets a little hung up, but this shouldn't be a recurring issue.
