### ISSUE TITLE
error when deploy on app service

### ISSUE THREAD

**Issue by walmikiarjun** [microsoft/vscode-azureappservice#1459]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "admin-klassakt-staging" failed. See output channel for more details.

Version: 0.16.4
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:519759
fulfilled extension.bundle.js:1:516898
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@walmikiarjun please check the output channel and copy the contents here if you're still having issues

**Comment by walmikiarjun** [comment]
yes pls i got the solution for it



*Best Regards*
Arjun Subhash Walmiki
Senior Software Developer
(MCSE - Certified)

Current Company:-
