### ISSUE TITLE
Error Deploying React App to App Services

### ISSUE THREAD

**Issue by VitalieStirbu** [microsoft/vscode-azureappservice#1460]
Does this occur consistently? Yes. Only the first deploy went through.
Repro steps: 
1. In VS Code Right Click on App Service
2. Select Deploy To Web App...
3. Select the build folder
4. Get an error

Action: appService.Deploy
Error type: ECONNREFUSED
Error Message: connect ECONNREFUSED 127.0.0.1:8888

Version: 0.16.4
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

Output results
```
10:31:01 PM {appname}: Creating zip package...
10:31:01 PM {appname: Starting deployment...
10:32:57 PM: Error: connect ECONNREFUSED 127.0.0.1:8888
```

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1056:14
```

</details>

**Comment by VitalieStirbu** [comment]
For me, the fix was to Restart VS Code and VS (not sure if it's really needed).

**Comment by EricJizbaMSFT** [comment]
Hmm yeah this doesn't reproduce for us with just those steps, but glad you found a workaround! For now I'm going to close this issue, but if it starts happening again let us know
