### ISSUE TITLE
write EPIPE

### ISSUE THREAD

**Issue by shinexavier** [microsoft/vscode-azureappservice#1461]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: EPIPE
Error Message: write EPIPE

Version: 0.16.3
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:83:16
```

</details>

**Comment by EricJizbaMSFT** [comment]
@shinexavier please add detailed repro steps
