### ISSUE TITLE
There is a deployment currently in progress. Please try again when it completes.

### ISSUE THREAD

**Issue by guardian-holdings-limited** [microsoft/vscode-azureappservice#1462]
Does this occur consistently?  **Yes** (Since its first occurrence)

Repro steps:

1. Within _VS Code_, navigate to _Azure_ (Note: Azure extension must be installed)
2. Right-click on the _Linux App Service_ then select _Deploy to Web App_
3. Choose the _Linux App Service_ from the _Command Palette_ 
4. Click _Deploy_ on the confirmation popup

![Deployment Error](https://user-images.githubusercontent.com/57636129/77828296-e6829180-70f0-11ea-95df-915856c7b151.PNG)

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.16.4
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399870extension.bundle.js:309:399870
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:579252
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by guardian-holdings-limited** [comment]
When you attempt to expand the _Deployments_ feature, it spins (loads) indefinitely.
There is no automated deployment (CI/CD), only manual deployments.

![Deloyments Waitig Cursor](https://user-images.githubusercontent.com/57636129/77828475-fd75b380-70f1-11ea-8a62-6843ff472a3c.PNG)

**Comment by EricJizbaMSFT** [comment]
@guardian-holdings-limited by chance what tier app service plan are you on? And how many web apps have you deployed to that plan? The default is the free option, but that can have performance issues the more apps you have, possibly leading to the problems you noticed

**Comment by randelllamontgroup** [comment]
@EricJizbaMSFT thanks for your question. 
We currently on the **Premium 1v2** tier, with (9) apps in total, (8) of which are dormant and (1) low traffic.

**Comment by randelllamontgroup** [comment]
@EricJizbaMSFT We worked around the issue by creating a new **deployment slot** and swapping it with the broken deployment. Once swapped, we re-deployed our code and now we're back up.

**Comment by EricJizbaMSFT** [comment]
Glad to hear you got it working! Going to close this - I'm pretty sure it's a problem in Azure, not the VS Code extension, so unfortunately there's not much we could do to help
