### ISSUE TITLE
Issues that I met

### ISSUE THREAD

**Issue by Lapwai** [microsoft/vscode-azureappservice#1463]
Does this occur consistently? 
Repro steps:

1.
2.

Action: postCreateWebApp
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.16.4
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:518639
fulfilled extension.bundle.js:1:516898
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1425
