### ISSUE TITLE
ERROR: Azure web services - creating python web app (from vscode)

### ISSUE THREAD

**Issue by Acafueri** [microsoft/vscode-azureappservice#1476]
Does this occur consistently? Yes
Repro steps:

1.Open VSCode in the web app sourcecode directory
2.Log in to azure through VSCode
3.Open command palette and "Create new Web App ... (advanced)"
4.Enter NAME
5.Select Resource group (already created - west Europe)
6.Select OS: Linux
7.Select runtime: Python 3.7
8.Select service plan
9.Create service plan: F1 Free
10.Application Insight (skip)
11.Chose region: west Europe

Action: appService.CreateWebAppAdvanced
Error type: Unauthorized
Error Message: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

Version: 0.16.4
OS: win32
OS Release: 10.0.16299
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3677746extension.bundle.js:225:3677746
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:579252
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Unfortunately, there's quite a few restrictions on regions right now. You can read more [here](https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/) and just try a different region to see if it works

> As demand continues to grow, if we are faced with any capacity constraints in any region during this time, we have established clear criteria for the priority of new cloud capacity. Top priority will be going to first responders, health and emergency management services, critical government infrastructure organizational use, and ensuring remote workers stay up and running with the core functionality of Teams. We will also consider adjusting free offers, as necessary, to ensure support of existing customers.
