### ISSUE TITLE
Stuck at preDeployTask message even though task executes successfully

### ISSUE THREAD

**Issue by NortonIce** [microsoft/vscode-azureappservice#1478]
While deploying azure app service extension always stop working at preDeployTask. Stangest thing about it is that it has worked well until tomorrow. This is contents of my settings.json file:
```
{
    "appService.defaultWebAppToDeploy": "***",
    "appService.deploySubpath": "***",
    "appService.preDeployTask": "testTask",
    "appService.showDeployConfirmation": false,
}
```
Trying to isolate problem I reduced my pre deploy task to just echo. This is how my test task look like:
```
        {
            "label": "testTask",
            "type": "shell",
            "command": "echo 'hi'"
        }
```
Task executes successfully but even with that extension is always showing "running preDeployTask" and not moving from here. I waited for an hour and then just closed vs code.

Mac OS 10.15.4
Vs code 1.44.0
Azure app service 0.16.4

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azureappservice/issues/1428.

Yeah we've already fixed this, but haven't released yet. Until that happens, you're welcome to use [this insider build](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17393&view=results) with [these instructions](https://aka.ms/azcodeinsiders)

**Comment by EricJizbaMSFT** [comment]
FYI - v0.16.5 has been released with a fix for this
