### ISSUE TITLE
 "GSSServiceAPI" is connected to a GitHub repository. Push to GitHub repository to deploy.

### ISSUE THREAD

**Issue by brandonmichaelhunter** [microsoft/vscode-azureappservice#1483]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "GSSServiceAPI" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.16.5
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3758739
extension.bundle.js:225:3756603
i extension.bundle.js:225:3756289
extension.bundle.js:225:3758462
t.ExtHostProgress._withProgress extensionHostProcess.js:544:963
t.ExtHostProgress.withProgress extensionHostProcess.js:544:717
Object.withProgress extensionHostProcess.js:867:255
Object.<anonymous> extension.bundle.js:225:3758394
fulfilled extension.bundle.js:225:3756357
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@brandonmichaelhunter it seems like you configured your web app for GitHub deploy, meaning the deploy button in our extension cannot be used. Instead, just push a commit to GitHub. Alternatively, you can right click on the web app and "Configure Deployment Source..." back to "None" if you want to deploy without GitHub
