### ISSUE TITLE
failed-to-deploy

### ISSUE THREAD

**Issue by ti17m006** [microsoft/vscode-azureappservice#1484]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.connectToGitHub
Error type: Unauthorized
Error Message: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

Version: 0.16.5
OS: linux
OS Release: 4.19.0-8-amd64
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3677746
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Unfortunately, there's quite a few restrictions on regions right now. You can read more [here](https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/)

> As demand continues to grow, if we are faced with any capacity constraints in any region during this time, we have established clear criteria for the priority of new cloud capacity. Top priority will be going to first responders, health and emergency management services, critical government infrastructure organizational use, and ensuring remote workers stay up and running with the core functionality of Teams. We will also consider adjusting free offers, as necessary, to ensure support of existing customers.
