### ISSUE TITLE
unable to create service

### ISSUE THREAD

**Issue by joelPangop** [microsoft/vscode-azureappservice#1485]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription 'c523f673-16ab-42be-96f5-927bf9a7fc4d' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.16.5
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:527180extension.bundle.js:225:527180
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:200:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@joelPangop please take a look at these docs on how to re-enable your subscription: https://docs.microsoft.com/azure/billing/billing-subscription-become-disable
