### ISSUE TITLE
Deployment failed for ASP.NET CORE 3.1 WEB API from Visual Studio Code

### ISSUE THREAD

**Issue by dsenthilkumar** [microsoft/vscode-azureappservice#1487]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Task not found

Version: 0.16.5
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:3665:990
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @dsenthilkumar 

Thanks for reporting.  Is there more to that error message in the output channel?  Could you look at your `settings.json` in your project? It seems like you might have a preDeploy or postDeploy task that can't be found in your `task.json`

**Comment by dsenthilkumar** [comment]
I resolved this issue. Thanks for your followup on this.
