### ISSUE TITLE
Create web app fails when access is restricted to plan

### ISSUE THREAD

**Issue by SpencerKaiser** [microsoft/vscode-azureappservice#1490]
Does this occur consistently? Yes
Repro steps:
1. Sign into the azure extension
2. Try and deploy a new app service

Action: appService.CreateWebApp
Error type: AuthorizationFailed
Error Message: The client 'xxxxxx@xxx.com' with object id 'XXXXXXXXXXXXXXXX' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/XXXXXXX/resourceGroups/appsvc_linux_centralus/providers/Microsoft.Web/serverfarms/appsvc_linux_centralus' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.16.5
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3585174
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by SpencerKaiser** [comment]
I figured it out... the extension was defaulting to an old resource group to which I no longer had permissions. Is there a way to chose the default rg other than using the `Advanced` approach and specifying which one you want to use?

**Comment by nturinski** [comment]
If you have the Azure CLI installed, you can set the CLI defaults to be used rather than the extension's defaults though you will need the Azure CLI installed for this functionality.

That was added in this PR. https://github.com/microsoft/vscode-azureappservice/commit/37a54d518668282cff00b9a9563f20b1bf4a9cf2

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azureappservice/issues/769 and https://github.com/microsoft/vscode-azuretools/pull/651 - let's see if we can improve this experience
