### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DevBrightMinds** [microsoft/vscode-azureappservice#1496]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: EPIPE
Error Message: write EPIPE

Version: 0.16.5
OS: darwin
OS Release: 19.2.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:83:16
```

</details>

**Comment by DevBrightMinds** [comment]
trying to publish an asp.net site to azure, using VSCode - and the azure app service extension, and i got this error:

1:09:34 PM sitename: Creating zip package...
1:11:09 PM sitename: Starting deployment...
1:39:12 PM: Error: write EPIPE

**Comment by nturinski** [comment]
Does this happen consistently?  I would expect the platform is just having issues and is dropping the request.  Sometimes restarting the app can help resolve this.

If this does happen consistently, could you provide repro steps?
