### ISSUE TITLE
Upgraded app to 3.1 but azure app service thinks its still on 2.2

### ISSUE THREAD

**Issue by n-alex-white** [microsoft/vscode-azureappservice#1497]
Today I've upgraded an app from dotnet core 2.2 to 3.1

Everything is fine when running locally, but when I attempt to right-click "Deploy to web app..." I get a message that it failed to deploy path that does not exist 

/Users/Alex/Sites/Pegcon4/Pegcon/bin/Release/netcoreapp2.2/win-x86/publish

I can't see where it is getting that old path from?

<img width="470" alt="Screenshot 2020-04-20 at 20 29 03" src="https://user-images.githubusercontent.com/2327254/79792383-b3759b80-8346-11ea-88fd-814eeac8b3fc.png">

**Comment by EricJizbaMSFT** [comment]
@n-alex-white check the `.vscode` folder at the root of your workspace. The setting "appService.deploySubpath" controls what folder is deployed and the setting "appService.preDeployTask" controls what task is run before deploy. You probably need to update the subPath setting and the tasks in tasks.json
