### ISSUE TITLE
Error deploying nodejs app to Linux F1 in Central US region

### ISSUE THREAD

**Issue by prashantma** [microsoft/vscode-azureappservice#1500]
Does this occur consistently? 
Repro steps:

1. Use VS Code App Service extension to deploy nodejs app.
2. Deploy to node 10.14 app to F1 Linux in Central US region.

Action: appService.Deploy
Error type: BadRequest
Error Message: Requested feature is not available in resource group Default-Web-CentralUS. Please try using a different resource group or create a new one.

Version: 0.16.5
OS: win32
OS Release: 10.0.14393
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3677746extension.bundle.js:225:3677746
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Hi @prashantma

I wasn't able to reproduce this error.  Do you have full access to the subscription that you are using?  Could you try to create a new web app in a different resource group?
