### ISSUE TITLE
Can't ssh connect and can't get container to start.  If I can't ssh how do I fix my container?

### ISSUE THREAD

**Issue by apolfj123** [microsoft/vscode-azureappservice#1502]
Does this occur consistently? Yes
Repro steps:

1. Try to SSH connect from Visual Studio Code by right click and use of menus off of jobs

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.16.5
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:154448
fulfilled extension.bundle.js:164:149848
```

</details>

**Comment by nturinski** [comment]
Hi @apolfj123 

Thanks for reporting.  This is actually a duplicate of #1011. 

The only workaround at the moment is to use the portal, unfortunately.  After that, it should work from the extension as expected.
