### ISSUE TITLE
Console application does not successfully deploy to the App Service

### ISSUE THREAD

**Issue by FlavioDiasPs** [microsoft/vscode-azureappservice#1503]
Does this occur consistently? Yes
Repro steps:

1º Right-Click the code folder
2º Choose Deploy to Web App...

I only managed to deploy my code by uploading it in a zip file in the portal.
The failure only occurs when trying to do it from VSCode, but the error message doesn't help at all

Action: appService.Deploy
Error type: 5
Error Message: Task to execute is undefined

Version: 0.16.5
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@FlavioDiasPs what type of app is this? Dotnet? Do you have "appService.preDeployTask" set in ".vscode/settings.json" - you might want to check.

That being said - the error message is a little gross, so we still want to improve that if you can give us more detailed repro steps
