### ISSUE TITLE
[Suggestion] Disable the 'Restart' and 'Stop' actions after stopping the web app 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1505]
**OS:** Win 10
**Build Version:** [20200425.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18312&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a web app.
2. Right click it and execute 'Stop' action.
3. Check the context menu.

**Actual:**
The 'Restart' and 'Stop' actions are enabled.

**Suggestion:**
Disable the 'Restart' and 'Stop' actions, keep consistent with portal.
![image](https://user-images.githubusercontent.com/45614674/80302593-83624880-87dd-11ea-9e71-6b9779143052.png)

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/1944
