### ISSUE TITLE
upload magento to azure failed??

### ISSUE THREAD

**Issue by 1712859** [microsoft/vscode-azureappservice#1507]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "hcmus1712859" failed. See output channel for more details.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:522593
fulfilled extension.bundle.js:1:519732
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @1712859 

Thanks for reporting.  Please look at the output channel for more details and paste them here. If that doesn't resolve your issue, could you provide repro steps?

**Comment by 1712859** [comment]
Uncaught TypeError: Argument 5 passed to PhpMyAdmin\Export::getFilenameAndMimetype() must be of the type string, null given, called in D:\XAMPP\phpMyAdmin\export.php on line 380 and defined in D:\XAMPP\phpMyAdmin\libraries\classes\Export.php:270 Stack trace: #0 D:\XAMPP\phpMyAdmin\export.php(380): PhpMyAdmin\Export->getFilenameAndMimetype('database', '', Object(PhpMyAdmin\Plugins\Export\ExportSql), '', NULL) #1 {main} thrown in D:\XAMPP\phpMyAdmin\libraries\classes\Export.php on line 270

**Comment by nturinski** [comment]
Looks like your project has an error.  Something about your `export.php` file and not passing the right parameters.  It says it accepts type string, but null was given.
