### ISSUE TITLE
Updating action will go on after canceling it by closing the notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1508]
**OS:** Win 10
**Build Version:** [20200425.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18312&view=results)

**Repro Steps:**
1. Expand one web app->Files->Open one file.
2. Make some change for this file.
3. "Ctrl+S", then one notification prompt to select to upload or not.
4. Click 'X' button to close this notification.
![image](https://user-images.githubusercontent.com/45614674/80338514-14452c80-888f-11ea-9b0a-26d418b2b833.png)

**Expect:**
It will not update this file.

**Actual:**
The update will go on.
![image](https://user-images.githubusercontent.com/45614674/80338727-a3524480-888f-11ea-8517-0262290e3b27.png)
 
**More info:**
The icon for the file will change to saved state after clicking "Ctrl+S".
![image](https://user-images.githubusercontent.com/45614674/80339264-d6490800-8890-11ea-9c08-985f9a820914.png)

**Comment by EricJizbaMSFT** [comment]
This is a limitation of the current design using local files in the temp folder. It'll be fixed if we switch to the virtual file system provider like we did for Storage: https://github.com/microsoft/vscode-azurestorage/issues/438
