### ISSUE TITLE
A dialog prompt to enable file logging for deployment slot but not prompt for web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1510]
**OS:** Win 10
**Build Version:** [20200425.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18312&view=results)

**Repro Steps:**
1. Create a new web app.
2. Create a deployment slot for this web app.
3. Right click the deployment slot and execute 'Start Streaming Logs' action.
4. Right click the web app and execute 'Start Streaming Logs' action.

**Expect:**
The behaviors are consistent for web app and slot.

**Actual:**
The behaviors are inconsistent for web app and slot. A dialog prompt to enable file logging for deployment slot but not prompt for web app.
The below dialog prompt for slot but not for web app:
![image](https://user-images.githubusercontent.com/45614674/80344753-aacb1b00-889a-11ea-97ba-04d754c84fd8.png)

**Comment by nturinski** [comment]
This is because by default, file logging is already enabled when creating web apps.  It would prompt if the logging were to disable.

That being said, we may want to turn logging on by default for slots as well.
