### ISSUE TITLE
VsCode Error After Network Issue

### ISSUE THREAD

**Issue by sreeramachandran** [microsoft/vscode-azureappservice#1513]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.16.5
OS: linux
OS Release: 4.15.0-76-generic
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179477
extension.js:229:174092
extension.js:229:46227
extension.js:229:45094
B._callback extension.js:1:181869
t._callback.t.callback.t.callback extension.js:181:5470
B.emit events.js:203:13
B.onRequestError extension.js:181:14525
ClientRequest.emit events.js:208:15
TLSSocket.socketErrorListener _http_client.js:399:9
TLSSocket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
