### ISSUE TITLE
unable to deploy website

### ISSUE THREAD

**Issue by tlboone0074** [microsoft/vscode-azureappservice#1516]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)

Version: 0.16.5
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Process.ChildProcess._handle.onexit child_process.js:264:19
onErrorNT child_process.js:456:16
processTicksAndRejections task_queues.js:77:11
Object.<anonymous> extension.bundle.js:164:411388
rejected extension.bundle.js:164:410913
```

</details>

**Comment by nturinski** [comment]
Hi @tlboone0074 

It looks like you don't have Git set on your PATH variable.  Are you trying to do a local git deploy?  If you don't want to install Git on your machine, you can change the Deployment Source to None, which does not rely on Git.

**Comment by tlboone0074** [comment]
Thanks for the response. I would like to install Git to gain more experience with it. Just didnt know what next step to take.

**Comment by nturinski** [comment]
You can download Git [here](https://git-scm.com/downloads).

I'm going to go ahead and close this issue, but please feel free to reopen if you have any more questions that I can help you with 😃
