### ISSUE TITLE
App Services: Entry not found in cache.

### ISSUE THREAD

**Issue by ashwanidv100** [microsoft/vscode-azureappservice#1520]
Does this occur consistently? 
Repro steps:

1. Has to refresh and show the apps in the subscription account
2. Not able to found the App services

Action: appService.CreateWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.16.5
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179477
extension.js:229:174092extension.js:229:174092
extension.js:229:46175extension.js:229:46175
extension.js:229:44168extension.js:229:44168
extension.js:229:43790extension.js:229:43790
i.find extension.js:229:78283
extension.js:229:25219extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
