### ISSUE TITLE
Remove feature flag for python remote debugging

### ISSUE THREAD

**Issue by cdeil** [microsoft/vscode-azureappservice#1523]
The tutorial at https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/4-publish-app-azure-app-service-vs-code has a Python/Flask variant and suggests to use remote debugging via VS Code.

Looks like this isn't implemented yet, I currently get this error:

![Screenshot 2020-05-05 at 18 49 04](https://user-images.githubusercontent.com/852409/81092800-73dfaf80-8f01-11ea-9482-7ecb47bb33a3.png)

Can you implement remote app debugging for Python?
If no or not shortly - maybe add a note to the tutorial to say that this is only available for JS?

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js apps on Linux.

Version: 0.16.5
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.getRemoteDebugLanguage extension.bundle.js:164:199860
extension.bundle.js:309:544093
fulfilled extension.bundle.js:309:543329
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
We have some support already - you can change the VS Code setting "appService.enablePythonRemoteDebugging" to try it out

**Comment by ejizba** [comment]
Closing in favor of https://github.com/microsoft/vscode-azureappservice/issues/2074
