### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BradP99** [microsoft/vscode-azureappservice#1524]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.viewDeploymentLogs
Error type: Error
Error Message: cannot open azureextensionuiReadonly:/2d6eb03024d24763f45c29187a726145a8fc12ade3a13266f2f9944141e8ff6a/0ace6d1%20-%20Created%20via%20a%20push%20deployment.log. Detail: Internal error: Expected value to be neither null nor undefined: ReadOnlyContentProvider._contentMap.get

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:4437:262
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @BradP99

Thanks for reporting.  Does this happen consistently?  Seems like maybe the file didn't download properly or something?  If it does, could you provide repro steps?
