### ISSUE TITLE
Debugging and start application error

### ISSUE THREAD

**Issue by vgpastor** [microsoft/vscode-azureappservice#1525]
Does this occur consistently? Yes
Repro steps:

1. Local: npm start (Build and work succesful)
2. Deploy the code developed in node with nuxt, deploy sucesful
3. When try to see the webpage, this return an application general error, and don't works
4. When try to debug the application, the application only show [Tunnel] Checking status, body: {"port":49494,"state":"STARTING","canReachPort":true,"msg":""}

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:154448
fulfilled extension.bundle.js:164:149848
```

</details>

**Comment by nturinski** [comment]
Hi @vgpastor

Thanks for reporting.  What folder are you deploying for your nuxt app?  I'm not sure if App Service can support nuxt.js out of the box without a proper custom build script.  You may have to deploy just the build artifact that is generated by the build.

If you look at the Diagnose and solve problems pane in the [Portal](https://ms.portal.azure.com/), and check the "Application Logs", you may be able to see some insight on to what went wrong.  Please let me know what the logs say.

**Comment by vgpastor** [comment]
I try to deploy an empty nuxt project and doens't works
1. npx create-nuxt-app <project-name>
2. npm install
3. npm build
4. npm start (locally works)
5. Deploy to azure WebApp with node 10LTS o 12LTS doen't works.

Any possible solution?

**Comment by nturinski** [comment]
Hi @vgpastor

Sorry for the delayed response.  When you deploy, do you get a notification that looks like this?

![image](https://user-images.githubusercontent.com/5290572/81991436-154bbd00-95f6-11ea-806b-5f2a4ccf3a87.png)

Please click Yes here.  It seems like your node_modules aren't being installed on the remote server.

If the prompt doesn't appear, do you have a .deployment file in the folder that you are deploying with the following?
```
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=true
```

**Comment by vgpastor** [comment]
Hi!

Yep, when i deployed the package received this alert, and accept this, and
the .deploy file it's created into my workspace.

The solution that i found it's that nuxt in a default configuration enable
the server in the public ip address founded to the machine, but with azure
this don't works.

To solve the issue it's necessary add into the nuxt configuration the few
configuration:
  server: {
    host: '0.0.0.0'
  }


This configuration make that the server for the nuxt are listen in all ips,
because the configuration of the azure and dockers are with multiple
internal ip.

Thanks for your help and i hope you can add this configuration to any
documentation to help other users.

Regards!

PD: I have other issue with azure webapps and the header Authorization
https://docs.microsoft.com/en-us/answers/questions/25907/authorization-header-missing-in-webapp.html?childToView=26607

**Comment by nturinski** [comment]
Hi @vgpastor 

When you tried setting the host, which IP did you use?  There's an IP address listed under "Custom Domains" in the Azure Portal.  I think for a testing environment, it's okay to configure your web app to accept all public IPs, but it can be a security issue with production apps.  

I don't know if you heard the news, but Microsoft has released a new Azure product called Static Web Apps!  There's documentation here to deploy a nuxt.js app with SWA: https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nuxtjs

SWA might be better suited for managing your SPA.  It's built around GitHub Actions and it should be easier to maintain your nuxt.js app with it.  You can download the new extension here: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestaticwebapps

**Comment by EricJizbaMSFT** [comment]
Closing since it sounds like you got it figured out for you situation and in the future we plan to recommend Static Web Apps for users in situations like this
