### ISSUE TITLE
Deploy to Web App... took a very long time then failed.

### ISSUE THREAD

**Issue by LinearDynamics** [microsoft/vscode-azureappservice#1528]
Earlier today it didn't take all that long. VSCode gave me a popup with a link and auto started this post for me.

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "LD-app-1" failed. See output channel for more details.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:522593
fulfilled extension.bundle.js:1:519732
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by LinearDynamics** [comment]
Might be:
2020-05-07T18:42:16.755Z - Fetching changes.
2020-05-07T18:42:16.755Z - Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\psfdbxwe.zip (131.61 MB) to D:\local\Temp\zipdeploy\extracted
2020-05-07T18:44:40.751Z - There is not enough space on the disk.\r\n

**Comment by EricJizbaMSFT** [comment]
Yeah that "space on the disk" error definitely looks like a problem. What size plan are you on? If it's free/basic - you might want to try upgrading or reducing the amount of sites on that plan.

Otherwise I would recommend contacting Azure support directly (there should be a help link in the portal). Our VS Code extension is just printing that error directly from Azure and there's not much we can do from our side

**Comment by LinearDynamics** [comment]
Thanks, @EricJizbaMSFT 
It's free (F1, 1GB) storage. However, in the Home>'appname'>Quotas>File system storage> I have 34.16MB of 1Gib used. But if I open the Kudu terminal and do a dir on D:\ I see 24 Dirs with 540,430,336 bytes free.
The odd thing I discovered that is if in Kudu, I dir(repeatedly) on D:\local\Temp\zipdeploy while the command in VSCode is running, I see the bytes free line start at a different number and go down continuously until 40,960 bytes free.
Is the D:\local\Temp\zipdeploy on a different filesystem or something? Wondering why I am seeing a difference in the dir command's output for bytes free when I dun it in the root of D: vs in the zipdeploy folder.

I have deleted the \extracted\ folder and the uhmggst.zip file there and in VSCode in the deployment tab under SUBSCRIPTIONNAME>APPNAME>Deployments, I right click the 'temp-aa Deploying from pushed zip file (Failed)' and select Redeploy but the result is the same as above.
There were a few successful deployments earlier yesterday. We're practicing our develop, deploy workflow for when we had off our app to our customer.

I looked into simply updating to the next tier for the App Service Plan but the D1 also has only 1GB of storage.

Output of the redeployment command
0:51:43 a.m. LD-app-1: Creating zip package...
10:58:40 a.m. LD-app-1: Starting deployment...
11:02:24 a.m. LD-app-1: Fetching changes.
11:02:24 a.m. LD-app-1: Cleaning up temp folders from previous zip deployments and extracting pushed zip file D:\local\Temp\zipdeploy\uvhmggst.zip (131.61 MB) to D:\local\Temp\zipdeploy\extracted
11:02:59 a.m. LD-app-1: Waiting for long running command to finish...
11:04:01 a.m. LD-app-1: Waiting for long running command to finish...
11:04:51 a.m.: Error: Deployment to "LD-app-1" failed. See output channel for more details.

**Comment by LinearDynamics** [comment]
More research indicates that on my plan, the D:\local\ directory IS a different filesystem and is allotted 500MB. There are loads of files in there and the only ones I felt safe removing were in the zipdeploy directory. 
https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system#temporary-files
Would it be possible to have the zipdeploy folder be elsewhere on the filesystem(NOT within D:\local\)

**Comment by EricJizbaMSFT** [comment]
You're asking the wrong person at this point 😬Our team only works on the VS Code extensions and I'm not involved in all that file system stuff up in Azure. As mentioned, I feel like Azure support in the portal is probably the best avenue for help on this

**Comment by LinearDynamics** [comment]
Thanks, @EricJizbaMSFT .
Update for anyone coming in from search:
I spoke with MS azure support:
They wanted to help but basically could not and advised purchasing one of the other plans(a rather pricey one was advised but while we are developing our solution, it was much too pricey!).

My attempt to solve on my own:
try mounting(symlink) D:\abiggerfolder\ as D:\local\Temp\zipdeploy\ <- didn't work. mklink ran without error but didn't actually do anything.
tried WEBSITE_DISABLE_SCM_SEPARATION but no go

Azure should allow a bigger temp storage size for their f1 and the next one up(d1?). 

Probably this particular extension is great but we could not use it at this time.
