### ISSUE TITLE
Deploy to Web App

### ISSUE THREAD

**Issue by guillermobadia** [microsoft/vscode-azureappservice#1529]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Task not found

Version: 0.16.5
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:4010:286
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@guillermobadia please add repro steps
