### ISSUE TITLE
entry not found

### ISSUE THREAD

**Issue by norene9** [microsoft/vscode-azureappservice#1535]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.16.5
OS: win32
OS Release: 10.0.10240
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54224extension.js:229:54224
extension.js:229:52217extension.js:229:52217
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
```

</details>

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
