### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rubeminconnect** [microsoft/vscode-azureappservice#1536]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.16.5
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by nturinski** [comment]
Hi @rubeminconnect 

- Does this happen consistently?
- Are you on normal Azure or a sovereign account like Azure Government, Azure China, Azure Germany, etc.?
- Was this a brand new app or an existing app?
