### ISSUE TITLE
Whats the minimum level of access required to authorize azure subscription

### ISSUE THREAD

**Issue by Jijogeorge69** [microsoft/vscode-azureappservice#1538]
The issue text was copied to the clipboard.  Please paste it into this window.

**Comment by nturinski** [comment]
Hi @Jijogeorge69.  I'm sorry, but I'm not sure what you are asking.  The message indicates there was some text on your clipboard that you haven't pasted into the issue.

Could you please provide that issue text?

**Comment by Jijogeorge69** [comment]
Error highlighted in yellow.

[cid:image003.jpg@01D62A19.BF979660]

**Comment by nturinski** [comment]
It looks like you have to be an Administrator, but this is the VS Code Azure App Service extension repo.

I think you might want to contact support here: https://dev.azure.com/mseng/AzureDevOps/_wiki/wikis/AzureDevOps.wiki/1616/Azure-DevOps-Support
