### ISSUE TITLE
I am getting EAI_AGAIN error consistently while trying to deploy to App Service

### ISSUE THREAD

**Issue by bot101** [microsoft/vscode-azureappservice#1540]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN management.azure.com

Version: 0.16.5
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@bot101 are you behind a proxy? If so - take a look at VS Code's proxy settings and see if that helps: https://code.visualstudio.com/docs/setup/network

Otherwise please add more detailed repro steps
