### ISSUE TITLE
Text editor error

### ISSUE THREAD

**Issue by heyimyunyl** [microsoft/vscode-azureappservice#1541]
The issue text was copied to the clipboard.  Please paste it into this window.

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model38) has been disposed

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.disposed workbench.desktop.main.js:47:343
e.$tryApplyEdits workbench.desktop.main.js:4777:306
e._doInvokeHandler workbench.desktop.main.js:4026:1013
e._invokeHandler workbench.desktop.main.js:4026:705
e._receiveRequest workbench.desktop.main.js:4025:344
e._receiveOneMessage workbench.desktop.main.js:4024:156
file:/workbench.desktop.main.js:4022:416
e.fire workbench.desktop.main.js:95:801
v.fire workbench.desktop.main.js:424:97
t.PersistentProtocol._receiveMessage workbench.desktop.main.js:428:451
file:/workbench.desktop.main.js:425:635
e.fire workbench.desktop.main.js:95:801
g.acceptChunk workbench.desktop.main.js:421:532
file:/workbench.desktop.main.js:420:832
Socket.t workbench.desktop.main.js:431:812
Socket.emit events.js:203:13
addChunk _stream_readable.js:295:12
readableAddChunk _stream_readable.js:276:11
Socket.Readable.push _stream_readable.js:210:10
Pipe.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by EricJizbaMSFT** [comment]
@hajimbae please add repro steps. I'm hoping this is a transient error that doesn't happen consistently. We've seen similar issues in the past #611
