### ISSUE TITLE
vscode-app

### ISSUE THREAD

**Issue by Qubercomsa** [microsoft/vscode-azureappservice#1542]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: UNKNOWN
Error Message: UNKNOWN: unknown error, read

Version: 0.16.5
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by EricJizbaMSFT** [comment]
@Qubercomsa please add repro steps
