### ISSUE TITLE
Fail to deploy Python project to a Linux web app with Python 3.7 runtime

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1545]
**OS:** Windows
**Build Version:** [20200516.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19564&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Open the python-docs-hello-world project in VS Code
2. Deploy it to a Linux web app with Python 3.7 runtime

**Expect:**
Deploy successfully without any error.

**Actual:**
Fail to deploy with an error "The service is unavailable".
![image](https://user-images.githubusercontent.com/62053665/82199030-bc4e9280-992f-11ea-890d-2810ac43e3ec.png)

**More info**
1. This issue does not reproduce when deploying to Python 3.8 web app.
2. This issue also reproduces when deploying to node12.9/LTS web app.

**Comment by EricJizbaMSFT** [comment]
@v-mengwe take a look at the troubleshooting tips in the link. This could happen for a variety of reasons. Also the nightly test against Python 3.7 seems to be working fine

**Comment by v-mengwe** [comment]
Verified on the new build [20200518.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19590&view=artifacts&type=publishedArtifacts), this issue doesn't reproduce for now. So close it. Thanks for your sharing!
