### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dolzah** [microsoft/vscode-azureappservice#1560]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "ideasbox" failed. See output channel for more details.

Version: 0.16.5
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:522531
fulfilled extension.bundle.js:1:519670
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @dolzah

Please provide repro steps.
