### ISSUE TITLE
facing issue to upload the code

### ISSUE THREAD

**Issue by mohitkamboj-sdd** [microsoft/vscode-azureappservice#1564]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Start
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription '6c7b3d71-2c74-40e0-8af5-38bfbb2897c8' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.16.5
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2831831extension.bundle.js:225:2831831
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:582086
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Hi @mohitkamboj-sdd

It looks like your subscription is in read-only mode, which means you won't be able to perform any actions on web apps.  Please read this for more information: https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/reactivate-your-subscription?view=o365-worldwide
