### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by sekarraman** [microsoft/vscode-azureappservice#1565]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: Authentication failed for 'https://bvgangpoker.scm.azurewebsites.net:443/bvgangpoker.git/'

Version: 0.16.5
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:411388
rejected extension.bundle.js:164:410913
```

</details>

**Comment by nturinski** [comment]
Hi @sekarraman

Do you have full access to this subscription and app?  It seems like the publishing credentials that we are retrieving are being rejected.  You should be able to do this through the Portal under the "Deployment Center"

![image](https://user-images.githubusercontent.com/5290572/83058823-cf3b2400-a00d-11ea-9467-a49651b70462.png)
