### ISSUE TITLE
Add the web app or slot info to output logs when executing commands for them

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1567]
**OS:** All
**Build Version:** 20200520.14

**Repro Steps:**
1. Execute "Start streaming logs" command for one slot.
2. Execute "Start/Stop/Restart" commands for web app or slot.
3. Deploy to web app/slot.
4. Check the output logs.

**Expect:**
The log is clear to check the detailed resource info, like below screen.
![image](https://user-images.githubusercontent.com/45614674/82876536-87fc5700-9f6b-11ea-9078-a81b9d5f0c69.png)

**Actual:**
The log is unclear, only contains the resource name.
![image](https://user-images.githubusercontent.com/45614674/82876384-42d82500-9f6b-11ea-8762-ddaed5c6c074.png)

**More info:**
This issue also reproduces when swapping slot.

**Comment by EricJizbaMSFT** [comment]
Gonna close this one as won't-fix. It's slightly different from your "expected" example, but it still has all the most important information about the resource/slot name
