### ISSUE TITLE
Whenever i create an App this happens.

### ISSUE THREAD

**Issue by Shahnwazh170** [microsoft/vscode-azureappservice#1570]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: BadRequest
Error Message: Exceeded the limit of 1 free tier linux server farm per subscription.

Version: 0.17.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3676006extension.bundle.js:225:3676006
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584810
Request.r._callback.r.callback.r.callback [as callback] extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Hi @Shahnwazh170 

Did you already create a free app service plan in the Portal?  Our extension tries to create a default app service plan for you.

Could you try right-clicking the subscription tree item and use the advanced create?  Then when prompted, select the app service plan that already exists.
