### ISSUE TITLE
Deploys hanging on "creating zip package

### ISSUE THREAD

**Issue by ikteru** [microsoft/vscode-azureappservice#1571]
I'm seeing this on WSL 2, azure app service extention v0.17.0.

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2108

**Comment by ikteru** [comment]
I have an update on this issue, now it works 50% of the time. Mainly due to the fact that I installed the "zip" package which was not installed by default in WSL2. So I'm guessing that's the package the extension uses in the background. 
However, if that's the issue, a little warning that the package wasn't installed would have been helpful. Killing the error and hiding away from the user isn't exactly very informative.
The other 50% of the time it still gets stuck, but I have no idea why.

**Comment by cdennig** [comment]
Hi there! Any news on that topic? This is the bug that keeps us not using the extension in WSL2...basically for AppService and AzFunc extensions.

Thanks...

**Comment by nturinski** [comment]
I believe this should be resolved with [today's release!](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureappservice)  🤞
