### ISSUE TITLE
You do not have permission to view this directory or page.

### ISSUE THREAD

**Issue by tlkanth278** [microsoft/vscode-azureappservice#1572]
Hey Guys

I have successfully published code into Azure portal, and then get this error. Tried all the solutions mentioned here, still get this. Any solution for this is highly appreciated. 

<img width="504" alt="error" src="https://user-images.githubusercontent.com/42255161/83274738-067f1180-a183-11ea-8ac7-5704e0d0a361.PNG">

Thanks

**Comment by EricJizbaMSFT** [comment]
@tlkanth278 please add detailed repro steps including what type of project you deployed, how you created the web app, any deployment logs, etc.
