### ISSUE TITLE
Entry not found in cache.

### ISSUE THREAD

**Issue by EgorCloud** [microsoft/vscode-azureappservice#1573]
Does this occur consistently?  No
Repro steps:

1. clcik add button 
2. type any name

Action: appService.CreateWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.17.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.46.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49397
b.<anonymous> extension.js:229:174287
extension.js:229:168902extension.js:229:168902
extension.js:229:54224extension.js:229:54224
extension.js:229:52217extension.js:229:52217
extension.js:229:51839extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268extension.js:229:33268
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
