### ISSUE TITLE
hallo

### ISSUE THREAD

**Issue by vishnucey** [microsoft/vscode-azureappservice#1574]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: Error
Error Message: ETag does not represent the latest state of the file "hostingstart.html". Download the file from Azure to get the latest version.

Version: 0.17.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
FileEditor.<anonymous> extension.bundle.js:309:565460
rejected extension.bundle.js:309:564277
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@vishnucey the file you were trying to edit likely changed between when you downloaded it and when you tried to upload it. Re-download the file and try editing again. If that doesn't help, please add detailed repro steps
