### ISSUE TITLE
Delete files from previous deployment

### ISSUE THREAD

**Issue by jbeckton** [microsoft/vscode-azureappservice#1579]
It seems that once you do a deployment and then make changes to your app file structure the files from the previous deployment are still there causing the app to crash. How can we delete the old deployment files?

**Comment by EricJizbaMSFT** [comment]
@jbeckton there's several different factors affecting how a deploy works. Please give us more detailed information on your situation including, but not limited to: 
- Info on the web app, i.e. how you created it, the OS, the plan type
- Info on your local project, i.e. what language it is, do you have a `.deployment` file or any VS Code settings related to deploy
- Info on deployment itself - i.e. any deployment logs
