### ISSUE TITLE
503 while attempting Remote Debugging

### ISSUE THREAD

**Issue by baardl** [microsoft/vscode-azureappservice#1580]
Does this occur consistently? Yes
Repro steps:

1. In vscode right-click our appservice. 
2. Press Start Remote Debugging
3. No reason for the 503 are displayed.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Error getting tunnel status: 503

Version: 0.17.0
OS: linux
OS Release: 5.3.0-55-generic
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:154352
rejected extension.bundle.js:164:149924
```

</details>

**Comment by nturinski** [comment]
Hi @baardl

Have you confirmed that the app is currently running?  If the App failed to start, I don't think that Azure will be able to start the remote debugging.  Is there any information you could provide to help us repro this?

**Comment by baardl** [comment]
Hi.

The app might have run, I do not know as it was only responding 503 as
well.
To get back into production, I had to delete all and start all over again
in a new zone.
Sorry for not preserving any logs.

You may close this issue.

Best regards
Bård

fre. 5. jun. 2020, 20:11 skrev Nathan <notifications@github.com>:
