### ISSUE TITLE
can't deploy new project

### ISSUE THREAD

**Issue by xianxianwang2020** [microsoft/vscode-azureappservice#1586]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: BadRequest
Error Message: Exceeded the limit of 1 free tier linux server farm per subscription.

Version: 0.17.0
OS: linux
OS Release: 4.4.0-170-generic
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3676006
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584810
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:200:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@xianxianwang2020 the error indicates you have to delete your other app service plan if you want to create a new free plan. If that doesn't help, please add detailed repro steps
