### ISSUE TITLE
An error occurs when executing "Open in Portal" action for "Application Settings" node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1602]
**OS:** Win 10/Mac
**Build Version:** 20200616.2

**Repro Steps:**
1. Expand one web app.
2. Right click the "Application Settings" node and select "Open in Portal".

**Expect:**
Open in portal successfully without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/84880532-36a13c80-b0bf-11ea-85f0-454d753ed0cb.png)

**Comment by alexweininger** [comment]
Thanks!

**Note:** 

I created this bug when I made all of the site tree nodes generic. This broke most of the logic in `openInPortal.ts`.

Open in portal for the deployments tree item is also broken 😢
