### ISSUE TITLE
[Suggestion] Display the resource group name consistently with the changed web app name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1609]
**OS:** Mac
**Build Version:** 20200618.1
**.NET Core:** 2.1

**Repro Steps:**

1. F1 --> Type and select "Azure App Service: Create New Web App... (Advanced)".
2. Enter a valid name with "test1" --> Press "Enter" --> Select "+Create new resource group" --> The default name of resource group is "test1" --> Click "Back" button --> Click "Back" button --> Change the web app name with "test2" --> Press "Enter" --> Select "+Create new resource group".
3. Check the resource group name.

**Actual:**
Display the first name "test1" rather than changed name "test2".

**Suggestion:**
Display the changed name "test2".

**Comment by EricJizbaMSFT** [comment]
We might be able to only cache the value if they changed from the default
