### ISSUE TITLE
There is no output log and notification when updating the file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1610]
**OS:** Mac
**Build Version:** 20200618.1
**.NET Core:** 2.1

**Repro Steps:**

1. Expand one web app --> Files --> Open one file.
2. Make some change for this file and save it.
3. Check the output log.

**Expect:**
There is output log and notification.

**Actual:**
There is no output log and notification.

**Comment by EricJizbaMSFT** [comment]
Let's check the previous behavior in the last version and match that
