### ISSUE TITLE
Azure Extension doesn't support ñ in the name of the AppService

### ISSUE THREAD

**Issue by gjordana** [microsoft/vscode-azureappservice#1612]
I have an App Service with an ñ in it's name

When I try to configure the access in Azure extension I get this error:

"resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+[^.]$/

**Comment by EricJizbaMSFT** [comment]
@gjordana can you clarify - when do you get that error? Did you already create the web app (maybe in the portal?) or are you trying to create the web app from VS Code? Perhaps the error happened when you were deploying?

**Comment by gjordana** [comment]
Here you can find the error
[image: image.png]

**Comment by EricJizbaMSFT** [comment]
Hmm unfortunately I can't see that image. I would suggest you open GitHub in the browser, as it doesn't work very well when you reply directly in email

**Comment by gjordana** [comment]
![image](https://user-images.githubusercontent.com/11246369/86169457-0bbbdd00-baf0-11ea-97d0-db1d9be6b186.png)

Here you can find the image.

**Comment by EricJizbaMSFT** [comment]
Note to self: Check if this is fixed after we update to new azure sdk

**Comment by gjordana** [comment]
when will do you do that?

**Comment by EricJizbaMSFT** [comment]
Ideally in the next month or two. We were waiting on https://github.com/microsoft/vscode-azure-account/issues/140, and that's just about to ship.

**Comment by gjordana** [comment]
Ok. Thanks for your answer. I think I will need to continue using Visual
Studio Community until that.

Thanks,
Garcilaso
