### ISSUE TITLE
deployment always failed in VSCode

### ISSUE THREAD

**Issue by chanhong** [microsoft/vscode-azureappservice#1617]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.17.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399343extension.bundle.js:309:399343
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584810
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@chanhong please add detailed repro steps

**Comment by chanhong** [comment]
Doing this on VSCode 1.15.1
1. Right-click on the name of the app under "App Service" of Azure extension in VSCode
2. Click on "Deploy to Web App..." and the "Output" shows the following:
Creating zip package...
Starting deployment...
Error: An error has occurred.

**Comment by EricJizbaMSFT** [comment]
What kind of project are you deploying? And how did you create the web app?

**Comment by chanhong** [comment]
This was from the original WebMatrix web site project.  This is the content
of my coproject.sln file.  Thanks

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.29102.190
MinimumVisualStudioVersion = 10.0.40219.1
Project("{E24C65DC-7377-472B-9ABA-BC803B73C61A}") = "coproject",
"coproject\", "{FEB37E52-0E8B-45A1-A20E-546C54381A29}"
ProjectSection(WebsiteProperties) = preProject
TargetFrameworkMoniker = ".NETFramework,Version%3Dv4.7.2"
Debug.AspNetCompiler.VirtualPath = "/localhost_62448"
Debug.AspNetCompiler.PhysicalPath = "coproject\"
Debug.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_62448\"
Debug.AspNetCompiler.Updateable = "true"
Debug.AspNetCompiler.ForceOverwrite = "true"
Debug.AspNetCompiler.FixedNames = "false"
Debug.AspNetCompiler.Debug = "True"
Release.AspNetCompiler.VirtualPath = "/localhost_62448"
Release.AspNetCompiler.PhysicalPath = "coproject\"
Release.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_62448\"
Release.AspNetCompiler.Updateable = "true"
Release.AspNetCompiler.ForceOverwrite = "true"
Release.AspNetCompiler.FixedNames = "false"
Release.AspNetCompiler.Debug = "False"
VWDPort = "62448"
SlnRelativePath = "coproject\"
EndProjectSection
EndProject
Global
GlobalSection(SolutionConfigurationPlatforms) = preSolution
Debug|Any CPU = Debug|Any CPU
EndGlobalSection
GlobalSection(ProjectConfigurationPlatforms) = postSolution
{FEB37E52-0E8B-45A1-A20E-546C54381A29}.Debug|Any CPU.ActiveCfg = Debug|Any
CPU
{FEB37E52-0E8B-45A1-A20E-546C54381A29}.Debug|Any CPU.Build.0 = Debug|Any CPU
{FEB37E52-0E8B-45A1-A20E-546C54381A29}.Release|Any CPU.Build.0 =
Release|Any CPU
EndGlobalSection
GlobalSection(SolutionProperties) = preSolution
HideSolutionNode = FALSE
EndGlobalSection
GlobalSection(ExtensibilityGlobals) = postSolution
SolutionGuid = {0B2C4E97-3964-4BD2-8E6C-DD76DA524A90}
EndGlobalSection
EndGlobal

**Comment by EricJizbaMSFT** [comment]
VS Code ignores sln files, as far as I know. So it's a C# project? How'd you create it?

**Comment by chanhong** [comment]
Since it is a "site" project so the folder is the project and no project
file is needed.
Thanks

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of information. Please see our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines if you still need help.
