### ISSUE TITLE
VSC Azure git error

### ISSUE THREAD

**Issue by emimassa** [microsoft/vscode-azureappservice#1623]
18:02:59: WARNING: Ignoring deploySubPath "." for non-zip deploy.
18:03:04 entremp: Deploying Local Git repository to "xxxxxx"...
19:47:57: Error: remote: fatal: write error: No space left on device        
error: remote unpack failed: index-pack abnormal exit
error: failed to push some refs to 'https://$entremp:***@xxxxxx.scm.azurewebsites.net:443/xxxxxx.git'
Error type: Error
Error Message: remote: fatal: write error: No space left on device        
error: remote unpack failed: index-pack abnormal exit
error: failed to push some refs to 'https://$xxxxxx:***@xxxxxx.scm.azurewebsites.net:443/xxxxx.git'

Version: 0.17.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:529064
rejected extension.bundle.js:164:528536
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@emimassa please add repro steps. Also I would suggest contacting Azure support since that error seems related to the machine in Azure and here on the VS Code side of things we can't really help with that
