### ISSUE TITLE
[Suggestion] Remove the unsupported version Node10.12 from the Runtime list

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1634]
**OS:** Win10
**Build Version**: 20200629.30

**Repro Steps:**
1. Create a new Web App with Node10.12.
2. Deploy a project to this web app.
3. Check the result.

**Actual:**
Fail to deploy project and pop up an error.
![image](https://user-images.githubusercontent.com/57662131/86112494-a4575a80-bafa-11ea-881c-447584da550c.png)

**Suggestion:**
Remove the unsupported version Node10.12 from the Runtime list.

**Details in Output:**

	2:44:09 PM nicole-lin-adv-node10: Starting deployment…
	2:44:09 PM nicole-lin-adv-node10: Creating zip package...
	2:44:09 PM nicole-lin-adv-node10: Zip package size: 3.99 kB
	2:44:12 PM nicole-lin-adv-node10: Updating submodules.
	2:44:12 PM nicole-lin-adv-node10: Preparing deployment for commit id '713d448763'.
	2:44:12 PM nicole-lin-adv-node10: Repository path is /tmp/zipdeploy/extracted
	2:44:12 PM nicole-lin-adv-node10: Running oryx build...
	2:44:12 PM nicole-lin-adv-node10: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.12 -i /tmp/8d81cc1000a6222 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
	2:44:17 PM nicole-lin-adv-node10: Build orchestrated by Microsoft Oryx, https://github.com/Microsoft/Oryx
	2:44:17 PM nicole-lin-adv-node10: You can report issues at https://github.com/Microsoft/Oryx/issues
	2:44:17 PM nicole-lin-adv-node10: Oryx Version      : 0.2.20200312.1, Commit: 8fe90af07018bd4454a39b0edea6ecc5119642da, ReleaseTagName: 20200312.1
	2:44:17 PM nicole-lin-adv-node10: Build Operation ID: |FJFJXsgfle0=.ee70889d_
	2:44:17 PM nicole-lin-adv-node10: Repository Commit : 713d4487636647e6984a491a5c2846ed
	2:44:17 PM nicole-lin-adv-node10: Error: Platform 'nodejs' version '10.12' is unsupported. Supported versions: 4.4.7, 4.5.0, 4.8.0, 6.2.2, 6.6.0, 6.9.3, 6.10.3, 6.11.0, 6.17.1, 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.2, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.16.3, 10.19.0, 12.16.1
	2:44:21 PM nicole-lin-adv-node10: Error: Platform 'nodejs' version '10.12' is unsupported. Supported versions: 4.4.7, 4.5.0, 4.8.0, 6.2.2, 6.6.0, 6.9.3, 6.10.3, 6.11.0, 6.17.1, 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.2, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.16.3, 10.19.0, 12.16.1\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10.12 -i /tmp/8d81cc1000a6222 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
    2:44:29 PM nicole-lin-adv-node10: Deployment failed.

**Comment by EricJizbaMSFT** [comment]
We should check if there's some property like "isHidden" or "isDeprecated" that we're not using. Otherwise, not a huge fan of manually modifying what we get back from the availableStacks api

**Comment by alexweininger** [comment]
Unfortunately there isn't a "isHidden" or "isDeprecated" property according to the docs [here](https://docs.microsoft.com/en-us/rest/api/appservice/provider/getavailablestacks#applicationstackresource).

And I agree, manually filtering or modifying the data we get back wouldn't be great.

**Comment by EricJizbaMSFT** [comment]
Those docs aren't the most reliable/up-to-date 😬 For example, I already know those properties exist for Functions stacks

**Comment by alexweininger** [comment]
Those properties do exist, but it seems like they haven't been updated.

Here is a snippet of the JSON response from the API for the Node 10.12 stack.

```
{
    "displayVersion": "10.12",
    "runtimeVersion": "NODE|10.12",
    "isDefault": false,
    "minorVersions": [
        {
            "displayVersion": "10.12",
            "runtimeVersion": "NODE|10.12",
            "isDefault": true,
            "isRemoteDebuggingEnabled": true
        }
    ],
    "applicationInsights": true,
    "appSettingsDictionary": {},
    "siteConfigPropertiesDictionary": {},
    "isPreview": false,
    "isDeprecated": false,
    "isHidden": false
}
```

**Comment by EricJizbaMSFT** [comment]
![annoyed](https://media.tenor.com/images/d6c2f78be75331b83516a77bbcee916d/tenor.gif)

**Comment by alexweininger** [comment]
Status of this issue:

Blocked due to the Stacks API being outdated. (see above)

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/microsoft/vscode-azureappservice/pull/1835
