### ISSUE TITLE
No confirmation dialog pops up when removing Trial App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1641]
**OS:** Win10
**Build Version:** 20200701.1

**Repro Steps:**
1. Right click the Trial App.
2. Select "Remove" action.
3. Check the result.

**Expect:**
A confirmation dialog pops up, such as the dialog when deleting a web app.
![image](https://user-images.githubusercontent.com/45614674/86220993-e80f9a00-bbb6-11ea-8c03-98bf0139cc33.png)

**Actual:**
Remove the Trial App directly without confirmation dialog.

**Comment by nturinski** [comment]
Not sure if we need a modal for this, to be honest.  It's not a destructive action, and behaves a lot more like Database's Detach command.   In that case, we do not prompt the user if they would like to detach or not.

**Comment by EricJizbaMSFT** [comment]
I think I like having it. It might not be completely destructive, but it's still annoying to get the trial app re-imported, right? Especially for new users?
