### ISSUE TITLE
[Suggestion] Remove unsupported actions "Open in Portal"/"Configure Deployment Source..."/"Disconnect from Repo" for "Deployments" node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1644]
**OS:** Win10
**Build Version:** 20200701.1

**Repro Steps:**
Drill down one Trial App --> Right click the "Deployments" node --> Execute "Open in Portal"/"Configure Deployment Source..."/"Disconnect from Repo" actions.

**Actual:**
There is an error "This operation is not supported".
![image](https://user-images.githubusercontent.com/45614674/86223977-d7612300-bbba-11ea-8194-aa72ea2de925.png)

**Suggestion:**
Remove these unsupported actions for "Deployments" node.

**Comment by alexweininger** [comment]
Closing as we fixed the bad error output in #1647. And these unsupported actions were left in on purpose.
