### ISSUE TITLE
Fail to transfer Trial App to subscription which has a web app with "Free Linux App Service Plan" existing

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1655]
**OS:** Win10
**Build Version:** 20200701.1

**Repro Steps:**
1. Make sure there is a web app with "Free Linux App Service Plan" in your subscription.
2. Right click one Trial App and select “Transfer to Subscription…” --> Sign in and select the subscription --> Enter an unique web app name.

**Actual:**
Fail to transfer Trial App to subscription.
![image](https://user-images.githubusercontent.com/45614674/86424568-7f8aff00-bd15-11ea-8c11-7f908e32902a.png)

**Comment by EricJizbaMSFT** [comment]
@nturinski tested and this does seem to be a region-specific limit. Debatable how often users would run into this error, but we could just prompt for location as a workaround

**Comment by ejizba** [comment]
Closing because of https://github.com/microsoft/vscode-azureappservice/issues/1880
