### ISSUE TITLE
"Error Message: fatal: not a git repository (or any of the parent directories): .git" while deploying to azure

### ISSUE THREAD

**Issue by Yatenga** [microsoft/vscode-azureappservice#1658]
I am unable to deploy my Angular app to Azure . I have the error below

Action: appService.Deploy
Error type: Error
**Error Message: fatal: not a git repository (or any of the parent directories): .git**

**Comment by EricJizbaMSFT** [comment]
@Yatenga did you change your deployment source to "Local Git"? If so, you can either change it back to the default ("None"), or initialize a git repo for your project
