### ISSUE TITLE
Hide Cosmos DB Connections for Trial App

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1661]
**OS:** Mac/Win10
**Build Version:** 20200703.6

**Repro Steps:**
1. Select a Trial App and expand it.
2. Click "Connections" node --> Click "Cosmos DB" --> Click "Add Cosmos DB Connection…".
3. Select Subscription --> Create new Account --> Mongo DB API --> Enter a Cosmos DB name --> Create new resource group --> Select a location --> Create new database --> Enter default connection setting key.

**Expect:**
Success to add Cosmos DB Connection for Trial App.

**Actual:**
Fail to add Cosmos DB Connection for Trial App.
![image](https://user-images.githubusercontent.com/62053665/86583938-addb3980-bfb6-11ea-8812-861fe687dd7f.png)
And sometimes pop up another error.
![image](https://user-images.githubusercontent.com/57662131/86586066-e9c3ce00-bfb9-11ea-8f03-f13cb8a9c269.png)

**Comment by EricJizbaMSFT** [comment]
Discussed during bug bash: Should we even have the Connections node for trial apps? They would have to be signed in to Azure to list a cosmos db, which seems weird for the trial scenario
