### ISSUE TITLE
Fail to create a new basic Linux web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1662]
**OS:** All
**Build Version:** 20200703.6
Does this occur consistently? Yes

**Repro steps:**
Create a new basic Linux web app.

**Expect:**
Create the basic web apps successfully without any error.

**Actual:**
Create the basic web app failed and pop up an error.
![image](https://user-images.githubusercontent.com/62053665/86562902-0f3ee080-bf96-11ea-9e9d-e81530a9e4e4.png)

**More info:**
**Another issue:** We can create more than 4 basic Windows Web Apps in an App Service Plan, but the expected behavior is that it should create a new plan with a number appended to it when creating the forth web app.  e.g. asp_windows_centralus -> asp_windows-centralus2.

Version: 0.17.1-alpha
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code - Insiders
Product Version: 1.47.0-insider
Language: en

**Comment by EricJizbaMSFT** [comment]
Linux has a limit of one plan - windows has a higher limit (I think 10). This is a platform limitation that we can't do anything about on our side
