### ISSUE TITLE
[Suggestion] The same command is displayed consistently in different locations

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1663]
**OS:** Win10
**Build Version:** 20200703.6
Does this occur consistently? Yes

**Repro steps:**

1. F1 --> Azure App Service: Create New Web App...(Advanced).
2. Check the view.
![image](https://user-images.githubusercontent.com/62053665/86584762-0101bc00-bfb8-11ea-818c-b0a7a12deec7.png)
3. F1 --> Azure App Service: Deploy to Web App... --> Select the folder to Deploy --> Select a subscription --> Select a Web App.
4. Check the view.
![image](https://user-images.githubusercontent.com/62053665/86584826-15de4f80-bfb8-11ea-8766-abbb597f98ef.png)

**Actual:**
The same command is displayed inconsistently in different locations.

**Suggestion:**
The same command is displayed consistently in different locations.

**Comment by EricJizbaMSFT** [comment]
We prefer the look of the second screenshot. Unfortunately, we don't control the UI for the first screenshot (VS Code handles that)
