### ISSUE TITLE
Automatically open tutorial after cloning trial app repo

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azureappservice#1666]
I wonder if we can detect when a user just opened a window with the Trial App repo and automatically open the tutorial. Would have to figure out what should activate the extension

**Comment by EricJizbaMSFT** [comment]
Stretch goal for 0.18.0

**Comment by alexweininger** [comment]
Issue progress: I have yet to find a way to activate the extension after this reload.

**Comment by ejizba** [comment]
Closing because of https://github.com/microsoft/vscode-azureappservice/issues/1880
