### ISSUE TITLE
Error task not found on deploy

### ISSUE THREAD

**Issue by CLSCDC** [microsoft/vscode-azureappservice#1681]
Does this occur consistently? every time i try to deploy.
Repro steps:
1. Login in azure account
2. Select my website and press deploy 
3. Running preDeploytask "publish-release" message shows up
4. Error task not found shows up
5. Only Running preDeployTask still continue on screen

Action: appService.Deploy
Error type: Error
Error Message: Task not found

Version: 0.17.0
OS: linux
OS Release: 5.7.7-arch1-1
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:4182:990
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@CLSCDC what does your `.vscode/tasks.json` file look like at the root of your workspace?

**Comment by CLSCDC** [comment]
it's this one:
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/MakoaV1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/MakoaV1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/MakoaV1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}

**Comment by EricJizbaMSFT** [comment]
Looks like you're missing a few tasks. It should've been added automatically at some point, but in any case here is what that file should look like:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/MakoaV1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/MakoaV1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/MakoaV1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "clean",
            "command": "dotnet",
            "type": "process",
            "args": [
                "clean",
                "${workspaceFolder}",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish-release",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}",
                "--configuration",
                "Release",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile",
            "dependsOn": "clean"
        }
    ]
}
```

**Comment by CLSCDC** [comment]
thank you very much!, it works, i mean, is not crashing or something, the website still keep the default's home page after the deploy message with the success deploy, i'll keep searching about it.
