### ISSUE TITLE
Fail to remote debug for a Linux web app with Node runtime

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1684]
**OS:** All
**Build Version:** 20200708.1

**Repro Steps:**
1. Create a Linux web app with Node runtime.
2. Deploy a project to this web app.
3. Right click this web app --> Select "Start Remote Debugging".

**Expect:**
Succeed to enable and start the remote debugging for Node web app.

**Actual:**
Fail to start tunnel proxy during starting and enabling Node.js remote debugging.
![image](https://user-images.githubusercontent.com/57662131/86894403-970f2100-c135-11ea-9239-715cc1b3127f.png)

**Details in Output:**
```
	2:11:02 PM: Fetching site configuration...
	2:11:05 PM: Updating site configuration to set remote debugging...
	2:11:06 PM: Updating site configuration done.
	2:11:06 PM: Starting tunnel proxy...
	2:11:07 PM: [Tunnel] Pinging app default url...
	2:11:07 PM: [Tunnel] Ping responded with status code: 200
	2:11:08 PM: [Tunnel] Checking status, body: {"port":2222,"state":"STARTED","canReachPort":true,"msg":""}
	2:11:13 PM: [Tunnel] Pinging app default url...
	2:11:13 PM: [Tunnel] Ping responded with status code: 200
	2:11:14 PM: [Tunnel] Checking status, body: {"port":2222,"state":"STARTING","canReachPort":true,"msg":""}
	2:11:19 PM: [Tunnel] Pinging app default url...
	2:11:23 PM: [Tunnel] Ping responded with status code: 503
	2:15:23 PM: [Tunnel] Checking status, error: \r\n504 Gateway Time-out
	\r\n
	
	nginx\r\n
2:15:23 PM: Error: Unable to establish connection to application: Error getting tunnel status: 504
```

**Comment by hashtagintegration** [comment]
The Azure remote debugging concept spans Web App and JavaScript Debugger projects, this issue might be related to [issue 661](https://github.com/microsoft/vscode-js-debug/issues/661) I reported under the JavaScript Debugger project.

**Comment by nturinski** [comment]
@hashtagintegration Thanks for the extra information, we'll have to investigate this.  It's really strange that the remote debugging flag has to be off in order for it to work.
