### ISSUE TITLE
error deployed netcore node js

### ISSUE THREAD

**Issue by dolzah** [microsoft/vscode-azureappservice#1694]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.17.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:529064
rejected extension.bundle.js:164:528536
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps
