### ISSUE TITLE
Azure Deployment Issue From VS Code

### ISSUE THREAD

**Issue by Dsencha** [microsoft/vscode-azureappservice#1699]
Starting Deployment from VS Extention 

12:09:30 PM mybot: Creating zip package...
12:10:36 PM mybot: Starting deployment...
12:14:49 PM: Error: An error has occurred.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.17.0
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:399343
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:584748
Request.r._callback.r.callback.r.callback [as callback] extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.EventEmitter.emit domain.js:476:20
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
Request.EventEmitter.emit domain.js:476:20
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
IncomingMessage.EventEmitter.emit domain.js:476:20
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Could you please provide repro steps?

**Comment by Dsencha** [comment]
Thanks @nturinski, It was issue from microsoft app service, server was not responding at @free tier, we have moved to paid one and started working.
