### ISSUE TITLE
The status "Deploying" of the Web App is disappeared after refreshing

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1703]
**OS:** Mac
**Build Version:** 20200720.6

**Repro Steps:**
1. Deploy a project to a Web App.
2. Check the status of the Web App during deploying.
3. Refresh the App Service node.
4. Check the status of the Web App again during deploying.

**Expect:**
It still shows the status "Deploying" after refreshing, such as:
![Screen Shot 2020-07-22 at 4 27 24 PM](https://user-images.githubusercontent.com/62053665/88153973-bed3ae00-cc38-11ea-9903-211782e8c101.png)

**Actual:**
The status "Deploying" of the Web App is disappeared after refreshing.
![Screen Shot 2020-07-22 at 4 43 20 PM](https://user-images.githubusercontent.com/62053665/88155276-76b58b00-cc3a-11ea-8fc3-59f01185d1e8.png)

**Comment by EricJizbaMSFT** [comment]
Closing as "won't-fix". This reproduces for temporary descriptions like "deploying" that are only saved locally. It's not worth it for us to cache that temporary description across a refresh
