### ISSUE TITLE
[Suggestion] Install directly after clicking "Install" button

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1706]
**OS:** Windows
**Build:** 20200722.16

**Repro Steps:**
1. Expand the Trial App.
2. Click "Show tutorial".
3. Pop up a dialog --> Click "Install" button.
	
**Actual:**
Only open the Didact extension page.
![image](https://user-images.githubusercontent.com/57662131/88524622-2a988b00-d02c-11ea-8139-faceb0b1a32b.png)

**Suggestion:**
Open the Didact extension page and install the Didact extension directly after clicking "Install" button.
![image](https://user-images.githubusercontent.com/57662131/88524631-2ec4a880-d02c-11ea-8a15-eed52167a88e.png)

**Comment by EricJizbaMSFT** [comment]
Currently not possible because of VS Code.
