### ISSUE TITLE
Error: cannot open azureAppService:/package.json

### ISSUE THREAD

**Issue by pauloadilson** [microsoft/vscode-azureappservice#1707]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.openFile
Error type: Error
Error Message: cannot open azureAppService:/package.json?id%3D%2Fsubscriptions%2F7b79e647-b28e-43cf-810f-b86e3690cc43%2FresourceGroups%2FAppServicePAS-rg%2Fproviders%2FMicrosoft.Web%2Fsites%2Fpauloadilson%2FFiles%2Fpackage.json. Detail: Não é possível ler o arquivo 'azureAppService:/package.json?id=/subscriptions/7b79e647-b28e-43cf-810f-b86e3690cc43/resourceGroups/AppServicePAS-rg/providers/Microsoft.Web/sites/pauloadilson/Files/package.json' (Error)

Version: 0.18.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6082:388
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Could you provide repro steps please?
