### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by sanggil1107** [microsoft/vscode-azureappservice#1708]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "neoss" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.17.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.47.2
Language: ko

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3757825
extension.bundle.js:225:3755689extension.bundle.js:225:3755689
i extension.bundle.js:225:3755375
extension.bundle.js:225:3757548extension.bundle.js:225:3757548
t.ExtHostProgress._withProgress extensionHostProcess.js:578:963
t.ExtHostProgress.withProgress extensionHostProcess.js:578:717
Object.withProgress extensionHostProcess.js:918:395
Object.<anonymous> extension.bundle.js:225:3757480
fulfilled extension.bundle.js:225:3755443
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
@sanggil1107 It looks like your app is connected to a GitHub repo.  Please commit and push changes to that remote repo and your web app should automatically be deployed. Nifty! 😄
