### ISSUE TITLE
Error deploying web app to new Azure app in VSCode

### ISSUE THREAD

**Issue by awjdigital** [microsoft/vscode-azureappservice#1716]
Does this occur consistently? YES - repeated the install 5 times. Deleted and started again from scratch

Repro steps:

1. Create a website
2. Use the Deploy to web app option
3. Error

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.18.0
OS: darwin
OS Release: 20.0.0
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:388829
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593285
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
@awjdigital What kind of project are you trying to deploy?  Sometimes Azure just has outages, especially if you're using a Free tier.  Unfortunately, the extension doesn't have any way we can help you with that except to either try again later or try a higher tier.
