### ISSUE TITLE
Display state "Git" beside "Deployments" node after executing "Redeploy"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1718]
**OS:** Win10/Mac
**Build Version:** 20200730.4

**Repro Steps:**
1. Create a Trial Web App.
2. Expand "Deployments" node --> Right click the deployment --> Select "Redeploy".
3. Check the result.

**Expect:**
There is no "Git" state beside "Deployments" node.

**Actual:**
Display state "Git" beside "Deployments" node.
![image](https://user-images.githubusercontent.com/62053665/89263698-4c18f880-d664-11ea-9aa9-880552aac64a.png)

**More Info:**
This issue can be fixed after clicking "Refresh" button.

**Comment by nturinski** [comment]
Actually, we are trying to hide from the user that Trial Apps use Git deploy, so the bug might be that you can fix it by clicking "Refresh".

**Comment by ejizba** [comment]
Closing because of https://github.com/microsoft/vscode-azureappservice/issues/1880
