### ISSUE TITLE
Open files other than .txt in App Service Extension

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1719]
**OS:** Win10/Mac
**Build Version:** 20200730.4
Does this occur consistently? Yes

**Repro Steps:**

1. Create a Trial Web App.
2. Expand "Files" node --> Open the "node_modules.tar.gz" file.
3. Check the result.

**Expect:**
Open the "node_modules.tar.gz" file without any error.

**Actual:**
There is an error "Cannot open...".
![Screen Shot 2020-08-04 at 1 59 12 PM](https://user-images.githubusercontent.com/62053665/89262047-a795b700-d661-11ea-97fe-f06ba102667c.png)

**Comment by ejizba** [comment]
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1740
