### ISSUE TITLE
appService.CreateWebApp No resource Found Error

### ISSUE THREAD

**Issue by iandiaye** [microsoft/vscode-azureappservice#1720]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.18.0
OS: darwin
OS Release: 20.0.0
Product: Visual Studio Code
Product Version: 1.47.1
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItem.<anonymous> extension.bundle.js:1:589303
fulfilled extension.bundle.js:1:583122
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@iandiaye are you sign in to Azure? The message indicates we may not have found any subscriptions. Please add repro steps
