### ISSUE TITLE
appService.AddCosmosDBConnection

### ISSUE THREAD

**Issue by CODEr-SaNjU** [microsoft/vscode-azureappservice#1723]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.AddCosmosDBConnection
Error type: Error
Error Message: vCore value 0 is not valid. Please specify a valid vCore value.

Version: 0.18.0
OS: linux
OS Release: 5.4.0-42-generic
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:535:473792
rejected extension.bundle.js:535:473219
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Could you provide repro steps please?
