### ISSUE TITLE
Trying to Create ASP.NET Core 3.1 Web App

### ISSUE THREAD

**Issue by scotcurry** [microsoft/vscode-azureappservice#1728]
Does this occur consistently? 
Repro steps:

1.  Yes.  I created the original Solution / Project in Visual Studio for Mac (8.7.1)
2.  Closed VS for Mac and added the folder as a Workspace in Visual Studio Code
3.  Was prompted install the C# extensions (did), stopped and restarted VSC.
4.  Attempted to deploy the app.  Was presented with the error.
5.  Restarted VSC, opened the workspace, tried again, same error.

Action: appService.Deploy
Error type: Error
Error Message: Task not found

Version: 0.18.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
A.$getTaskExecution workbench.desktop.main.js:4241:501
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Can you copy the contents of the ".vscode/tasks.json" file at the root of your workspace? We should've prompted you to add tasks automatically...not sure why they're missing

**Comment by scotcurry** [comment]
Please let me know if you need anything else.

{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/ChuckBotAPI/ChuckBotAPI.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/ChuckBotAPI/ChuckBotAPI.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/ChuckBotAPI/ChuckBotAPI.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        }
    ]
}

**Comment by EricJizbaMSFT** [comment]
When I try to deploy a .NET Core project, I see a prompt like this:
<img width="436" alt="Screen Shot 2020-08-24 at 10 03 44 AM" src="https://user-images.githubusercontent.com/11282622/91074298-2d69aa00-e5f1-11ea-950f-63d065cf9eef.png">

After I click "Add Config", it will add a few more tasks, ending up with 5:
<details>
<summary>.vscode/tasks.json</summary>

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/dotnet1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/dotnet1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/dotnet1.csproj",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "clean",
            "command": "dotnet",
            "type": "process",
            "args": [
                "clean",
                "${workspaceFolder}",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile"
        },
        {
            "label": "publish-release",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}",
                "--configuration",
                "Release",
                "/property:GenerateFullPaths=true",
                "/consoleloggerparameters:NoSummary"
            ],
            "problemMatcher": "$msCompile",
            "dependsOn": "clean"
        }
    ]
}
```

</details>

Can you post a screenshot of your workspace? Perhaps the folder structure isn't what we expect. Here's mine:
<img width="337" alt="Screen Shot 2020-08-24 at 10 05 49 AM" src="https://user-images.githubusercontent.com/11282622/91074463-70c41880-e5f1-11ea-8023-b4a55118254e.png">
