### ISSUE TITLE
shit

### ISSUE THREAD

**Issue by Lance001Dy** [microsoft/vscode-azureappservice#1730]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Conflict
Error Message: Website with given name api-app already exists.

Version: 0.18.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:2905505extension.bundle.js:225:2905505
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593285
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
Seems like it should work if you try another website name. I thought we validated this up front (like when you enter the name), but maybe that doesn't work if you type too fast? Let us know if there's any improvement we can make related to that
