### ISSUE TITLE
There are extra application settings in the file which download settings from Trial App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1732]
**OS:** Windows 10
**Build Version:** 20200813.1

**Repro Steps:**
1. Drill down one Trial App --> Right click "Application Settings" node to download remote settings.
2. View the settings file.
3. Check the application settings in this file and "Application Settings" node.

**Expect:**
The application settings are the same in this file and "Application Settings" node.

**Actual:**
There are extra application settings in this file.
![image](https://user-images.githubusercontent.com/45614674/90229189-120cdb00-de4a-11ea-8baa-dc7fbf6bc681.png)
![image](https://user-images.githubusercontent.com/45614674/90229250-2cdf4f80-de4a-11ea-84de-9a3b3e1d22c3.png)

**More Info:**
This issue does not reproduce for web app.

**Comment by EricJizbaMSFT** [comment]
Yeah there's a bunch of app settings we want to hide in the tree for trial apps. It's probably best to also hide those when a user downloads the app settings, but not worth fixing at the moment since the trial app goes away within an hour anyways
