### ISSUE TITLE
Error: The service is unavailable.

### ISSUE THREAD

**Issue by brucevanhorn2** [microsoft/vscode-azureappservice#1735]
Does this occur consistently? 
Repro steps:

1.  Go to https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?pivots=platform-linux
2. Follow the instructions.  That's all I did.  It's a "hello world" app, it shouldn't be out of resources.  I generated the express app, installed the azure extension and attempted to deploy twice with the same result.

Action: postCreateWebApp
Error type: 503
Error Message: The service is unavailable.

Version: 0.18.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:388829
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593285
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by brucevanhorn2** [comment]
I deleted the app and recreated it manually in windows and it works

**Comment by EricJizbaMSFT** [comment]
Yeah service unavailable errors can happen from time to time and it usually works if you just try again. There's also these troubleshooting tips for future reference:
https://docs.microsoft.com/azure/app-service/troubleshoot-http-502-http-503
