### ISSUE TITLE
Deploying app service fails

### ISSUE THREAD

**Issue by KevinBurton** [microsoft/vscode-azureappservice#1736]
Does this occur consistently? Yes
Repro steps:
1. Load project into VS Code
2. Select Azure extension
3. Select the up arrow to deploy
4. Wait for about 5 minutes
5. Output window shows Error: An error has occurred.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.18.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:388829extension.bundle.js:309:388829
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593285
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.EventEmitter.emit domain.js:476:20
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
Request.EventEmitter.emit domain.js:476:20
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
IncomingMessage.EventEmitter.emit domain.js:476:20
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by EricJizbaMSFT** [comment]
@KevinBurton we can't repro with those steps alone. Please add more information for your specific situation, including what type of project you have, what type of web app, and any deploy logs

**Comment by KevinBurton** [comment]
This is a Gatsby React project like I indicated the deployment failed. I
don’t know where to find deployment logs. Here is a screen shot of the
error notification

**Comment by EricJizbaMSFT** [comment]
Unfortunately, GitHub doesn't work well when replying directly in email - I can't see any image you attach.

Here's where the output is:
<img width="989" alt="Screen Shot 2020-08-24 at 10 12 22 AM" src="https://user-images.githubusercontent.com/11282622/91075054-55a5d880-e5f2-11ea-80bf-638f8641a2e3.png">

It's VS Code's standard output pane - and just make sure to change the little dropdown to "Azure App Service"
