### ISSUE TITLE
Deploy to virtual directory

### ISSUE THREAD

**Issue by chewcw** [microsoft/vscode-azureappservice#1741]
Hi, thanks for the extension, currently whenever I deploy my app the destination defaults to `/site/wwwroot`, is there any configuration like _deployment profile_ in Visual Studio so that we can deploy to virtual folder?

**Comment by EricJizbaMSFT** [comment]
Can you share a sample deployment profile from VS? What exactly is the scenario here, aka what's the goal of deploying to a destination other than `/site/wwwroot`?

**Comment by chewcw** [comment]
Deployment profile as shown in this article: [https://medium.com/@the.green.man/azure-app-services-virtual-folders-f9e43914e3b2](https://medium.com/@the.green.man/azure-app-services-virtual-folders-f9e43914e3b2)

Use case for example my frontend lives in /wwwroot while my backend lives in /api

**Comment by EricJizbaMSFT** [comment]
For my own reference, here's some docs on the "virtual directory" pattern per the VS team:
https://docs.microsoft.com/iis/get-started/planning-your-iis-architecture/understanding-sites-applications-and-virtual-directories-on-iis#introduction

**Comment by EricJizbaMSFT** [comment]
Discussed in triage: Let's see how expensive this is. Might require supporting webdeploy instead of zipdeploy
