### ISSUE TITLE
The "WEBSITE_HTTPLOGGING_RETENTION_DAYS=7" setting does not support swap

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1742]
**OS:** Win10
**Build Version:** 20200824.1

**Repro Steps:**

1. Create new web app (advanced) with Linux OS.
3. Deploy a project to it.
4. Create a new deployment slot.
5. Swap the new deployment slot with production.
6. Check the Application Settings.

**Expect:**
Swap all settings.

**Actual:**
No swap for "WEBSITE_HTTPLOGGING_RETENTION_DAYS=7" setting.
![image](https://user-images.githubusercontent.com/62053665/91160008-7574f380-e6fb-11ea-9f67-32ea9eb920de.png)

**More Info:**
The "WEBSITE_HTTPLOGGING_RETENTION_DAYS=7" setting disappears after swapping a new deployment slot with another slot which deployed.
![image](https://user-images.githubusercontent.com/62053665/91160756-63478500-e6fc-11ea-9639-85bfa20e979e.png)

**Comment by EricJizbaMSFT** [comment]
That's by design - per [these docs](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots)

> Certain app settings that apply to unswapped settings are also not swapped. For example, since diagnostic settings are not swapped, related app settings like WEBSITE_HTTPLOGGING_RETENTION_DAYS and DIAGNOSTICS_AZUREBLOBRETENTIONDAYS are also not swapped, even if they don't show up as slot settings.
