### ISSUE TITLE
ENOTFOUND management.azure.com

### ISSUE THREAD

**Issue by jon20lee** [microsoft/vscode-azureappservice#1746]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.18.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@jon20lee please add repro steps
