### ISSUE TITLE
[Suggestion] Add the Trial App for Web App list when executing "Azure App Service: Browse Website" command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1747]
**OS:** Win10
**Build Version:** 20200826.10

**Repro Steps:**
F1 --> Azure App Service: Browse Website --> Check the Web App list.

**Actual:**
There is no Trial App.
![image](https://user-images.githubusercontent.com/62053665/91404644-4635c200-e874-11ea-818a-b8935c120889.png)

**Suggestion:**
Add the Trial App for Web App list, such as:
![image](https://user-images.githubusercontent.com/62053665/91407390-2783fb00-e875-11ea-89c3-c85d441581f9.png)

**More Info:**
This issue also reproduces for "Azure App Service: Start Streaming Logs/Stop Streaming Logs" commands.

**Comment by ejizba** [comment]
Closing because of https://github.com/microsoft/vscode-azureappservice/issues/1880
