### ISSUE TITLE
error entry not found in chache

### ISSUE THREAD

**Issue by shemulik1** [microsoft/vscode-azureappservice#1748]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.18.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.48.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:41330
extension.js:393:35925extension.js:393:35925
extension.js:243:74572extension.js:243:74572
extension.js:243:72553extension.js:243:72553
extension.js:243:72173extension.js:243:72173
i.find extension.js:243:106705
extension.js:243:53427extension.js:243:53427
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53

**Comment by shemulik1** [comment]
the problem solved after restart vocoder
thanks
