### ISSUE TITLE
Phantom WebApp is neither deleted nor accessible

### ISSUE THREAD

**Issue by marccashmore** [microsoft/vscode-azureappservice#1750]
I have been through a bit of a reorganisation of my WebApps which lead to some renaming and creation/deletion cycles. During this I created one WebApp which I subsequently deleted.

However, this WebApp still shows up in my list in VS Code and still shows up in the CLI when I run 'az webapp list'. However It does not show up in my list of resources on the Portal, and I cannot deleted it from either VS Code or the CLI. The error I get is:

{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/sites/xxxx' under resource group 'rgr_xxx' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
Any ideas how to delete this for good would be gratefully received!

**Comment by nturinski** [comment]
That's an interesting problem...

I'm not sure if this will work, but you might be able to install the [Azure Resource Group extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureresourcegroups) and delete the resource group this phantom app exists in.

**Comment by marccashmore** [comment]
Thanks for the suggestion. For some reason I couldn't get that extension working (in fact I already had it installed, it just doesn't seem to show my resource group). However, I did this in the Portal instead. Moved all my good resources to a new group and then deleted the old one which just contained my phantom resource. And.... partial success. Which I guess is really failure!

I can no longer find my resource through the CLI **but** it does still show up in VS Code! If I, for example, try to restart the phantom WebApp in VS Code I now get a message saying: "Resource group 'rgr_xxx' could not be found."

Any more ideas out there?

**Comment by marccashmore** [comment]
A little more information. When I right click in VS Code and click 'Delete...' and then confirm, I quickly get the message 'Successfully deleted web app "xxx".' and it disappears from the interface. However, if I just click refresh it comes straight back again.

To be clear, I still have this issue and I am still unable to delete the remains of this web app.

**Comment by EricJizbaMSFT** [comment]
@marccashmore I think you'd have better luck contacting Azure support (there should be a question mark button in the portal). Your app seems to be in a weird state where the normal "delete" API isn't working for us. The Azure support team will have access to more tools to get this fixed that my team just doesn't have access to

**Comment by marccashmore** [comment]
Hi Eric, unfortunately this is a personal project and I don't have access to an Azure support subscription, so I was hoping someone here could help.

**Comment by EricJizbaMSFT** [comment]
My team only has access to the same "Delete" methods that you do. We can only direct you to delete through the Portal or our extension, which you've already tried. Are you being billed for the web app? I'm not that familiar with all the different Azure support options, but I'm pretty sure all subscriptions have access to billing support

**Comment by marccashmore** [comment]
On my subscription I just get directed to Q&A for support. Anyway, it seems to have turned up again in the Portal and deleted as normal, so problem solved!
