### ISSUE TITLE
SSH connection to WebApp

### ISSUE THREAD

**Issue by Yevsyukov** [microsoft/vscode-azureappservice#1756]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.18.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:123037
fulfilled extension.bundle.js:164:118408
```

</details>

**Comment by nturinski** [comment]
Could you please provide repro steps?
