### ISSUE TITLE
The deployment is failing for what appears to be no reason

### ISSUE THREAD

**Issue by xtianus79** [microsoft/vscode-azureappservice#1759]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.18.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:515775
rejected extension.bundle.js:164:515202
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
