### ISSUE TITLE
pre deploy error 

### ISSUE THREAD

**Issue by shadymina1** [microsoft/vscode-azureappservice#1760]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: d:\TriOS Diploma Work\C#\InclassProject\MovieMate4\MovieMate\bin\Release\netcoreapp3.1\publish

Version: 0.18.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3763793
fulfilled extension.bundle.js:225:3763286
```

</details>

**Comment by nturinski** [comment]
Hi @shadymina1

Please report detailed repro steps.  It appears that your project isn't building the deploy path that we are expecting.  If you have a custom task for publishing your project, please point your `appService.deploySubpath` setting to where the published bits are.
