### ISSUE TITLE
Fail to deploy python project to a Linux web app with Python 3.8 runtime

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1761]
**OS:** Windows 10/Mac
**Build Version:** 20200909.3

**Repro Steps:**
1. Open the python-docs-hello-world project in VS Code
2. Deploy it to a Linux web app with Python 3.8 runtime

**Expect:**
Deploy successfully without any error.

**Actual:**
Fail to deploy the project to Python 3.8 web app.
![image](https://user-images.githubusercontent.com/45614674/92586144-76478100-f2c8-11ea-9001-d06ba74959b4.png)

**Output log:**
2:10:06 AM serene-py38: Starting deployment...
2:10:06 AM serene-py38: Creating zip package...
2:10:06 AM serene-py38: Zip package size: 2.57 kB
2:10:07 AM serene-py38: Fetching changes.
2:10:07 AM serene-py38: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/fecfceaf-beec-4fa8-a57a-00f4f39ee4f8.zip (0.00 MB) to /tmp/zipdeploy/extracted
2:10:10 AM serene-py38: Updating submodules.
2:10:10 AM serene-py38: Preparing deployment for commit id 'e927b6d9b5'.
2:10:11 AM serene-py38: Repository path is /tmp/zipdeploy/extracted
2:10:11 AM serene-py38: Running oryx build...
2:10:11 AM serene-py38: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -i /tmp/8d854a027900dbb -p compress_virtualenv=tar-gz -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
2:10:13 AM serene-py38: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2:10:13 AM serene-py38: You can report issues at https://github.com/Microsoft/Oryx/issues
2:10:13 AM serene-py38: Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
2:10:13 AM serene-py38: Build Operation ID: |TcwPNXyzdkU=.79d2b475_
2:10:14 AM serene-py38: Repository Commit : e927b6d9b5094869a1af57345c6a83bf
2:10:14 AM serene-py38: Detecting platforms...
2:10:14 AM serene-py38: Detected following platforms:
2:10:14 AM serene-py38:   python: 3.8.4
2:10:14 AM serene-py38: Using intermediate directory '/tmp/8d854a027900dbb'.
2:10:14 AM serene-py38: Copying files to the intermediate directory...
2:10:14 AM serene-py38: Done in 0 sec(s).
2:10:14 AM serene-py38: Source directory     : /tmp/8d854a027900dbb
2:10:14 AM serene-py38: Destination directory: /home/site/wwwroot
2:10:15 AM serene-py38: Python Version: /opt/python/3.8.4/bin/python3.8
2:10:15 AM serene-py38: Python Virtual Environment: antenv
2:10:15 AM serene-py38: Creating virtual environment...
2:10:29 AM serene-py38: Activating virtual environment...
2:10:29 AM serene-py38: Running pip install...
2:10:31 AM serene-py38: [09:10:31+0000] Collecting click==6.7
2:10:31 AM serene-py38: [09:10:31+0000]   Using cached click-6.7-py2.py3-none-any.whl (71 kB)
2:10:32 AM serene-py38: [09:10:32+0000] Collecting Flask==1.0.2
2:10:32 AM serene-py38: [09:10:32+0000]   Using cached Flask-1.0.2-py2.py3-none-any.whl (91 kB)
2:10:32 AM serene-py38: [09:10:32+0000] Collecting itsdangerous==0.24
2:10:32 AM serene-py38: [09:10:32+0000]   Using cached itsdangerous-0.24.tar.gz (46 kB)
2:10:34 AM serene-py38: [09:10:34+0000] Collecting Jinja2==2.10
2:10:34 AM serene-py38: [09:10:34+0000]   Using cached Jinja2-2.10-py2.py3-none-any.whl (126 kB)
2:10:34 AM serene-py38: [09:10:34+0000] Collecting MarkupSafe==1.0
2:10:34 AM serene-py38: [09:10:34+0000]   Using cached MarkupSafe-1.0.tar.gz (14 kB)
2:10:35 AM serene-py38:     ERROR: Command errored out with exit status 1:
2:10:35 AM serene-py38:      command: /tmp/8d854a027900dbb/antenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2uyx5adk/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2uyx5adk/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pqh3t3qo
2:10:35 AM serene-py38:          cwd: /tmp/pip-install-2uyx5adk/MarkupSafe/
2:10:35 AM serene-py38:     Complete output (5 lines):
2:10:35 AM serene-py38:     Traceback (most recent call last):
2:10:35 AM serene-py38:       File "<string>", line 1, in <module>
2:10:35 AM serene-py38:       File "/tmp/pip-install-2uyx5adk/MarkupSafe/setup.py", line 6, in <module>
2:10:35 AM serene-py38:         from setuptools import setup, Extension, Feature
2:10:35 AM serene-py38:     ImportError: cannot import name 'Feature' from 'setuptools' (/tmp/8d854a027900dbb/antenv/lib/python3.8/site-packages/setuptools/__init__.py)
2:10:35 AM serene-py38:     ----------------------------------------
2:10:35 AM serene-py38: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2:10:35 AM serene-py38: WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
2:10:35 AM serene-py38: You should consider upgrading via the '/tmp/8d854a027900dbb/antenv/bin/python -m pip install --upgrade pip' command.
2:10:39 AM serene-py38: ERROR: Command errored out with exit status 1:\n     command: /tmp/8d854a027900dbb/antenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2uyx5adk/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2uyx5adk/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pqh3t3qo\n         cwd: /tmp/pip-install-2uyx5adk/MarkupSafe/\n    Complete output (5 lines):\n    Traceback (most recent call last):\n      File "<string>", line 1, in <module>\n      File "/tmp/pip-install-2uyx5adk/MarkupSafe/setup.py", line 6, in <module>\n        from setuptools import setup, Extension, Feature\n    ImportError: cannot import name 'Feature' from 'setuptools' (/tmp/8d854a027900dbb/antenv/lib/python3.8/site-packages/setuptools/__init__.py)\n    ----------------------------------------\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\nWARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.\nYou should consider upgrading via the '/tmp/8d854a027900dbb/antenv/bin/python -m pip install --upgrade pip' command.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -i /tmp/8d854a027900dbb -p compress_virtualenv=tar-gz -p virtualenv_name=antenv --log-file /tmp/build-debug.log 
2:10:42 AM serene-py38: Deployment failed.

**More Info:**
1. This issue does not reproduce when deploying python project to Python 3.7 web app.
2. This issue does not reproduce on Linux.

**Comment by nturinski** [comment]
When you say it doesn't reproduce on Linux, you mean when you deploy with a Linux machine, the issue will not reproduce?  Have you tried deploying to the same web app from different OS's?

**Comment by v-ruizh** [comment]
@nturinski Verified this issue using the latest app service extension build 20200915.5, it also reproduces on all 3 platforms Windows/Mac/Linux.

**Comment by EricJizbaMSFT** [comment]
I can repro this with an old "python-docs-hello-world", but it works fine if I use the latest from here: https://github.com/Azure-Samples/python-docs-hello-world
