### ISSUE TITLE
[Suggestion] Keep the connected PostgreSQL database name and SQL database name consistently 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1765]
**OS:** Windows 10
**App Service extension build version:** 20200909.3
**Azure Databases extension build version:** 20200910.1

**Repro Steps:**
1. Expand one web app -> Databases node -> Add Database connection to web app -> Create a new PostgreSQL server database to attach -> Check the connected PostgreSQL database name.
2. Add Database connection to web app -> Select a SQL database -> Check the connected SQL database name.

**Actual:**
The connected PostgreSQL database name and SQL database name are inconsistent.
![image](https://user-images.githubusercontent.com/45614674/92706993-88d4bf80-f387-11ea-9601-3f2466e6127c.png)

**Suggestion:**
Keep the connected PostgreSQL database name and SQL database name consistently.

**Comment by neelip** [comment]
Not able to reproduce this.  Labels which include "...database.azure.come:[port]/..." are usually connections from Attached Accounts for Postgres and non-Postgres connections. 

Are both `"serene-portal.../afdsd"` and `"serene-portal.../server"` connections from Azure Subscription or is one of them from Attached Accounts?

**Comment by v-ruizh** [comment]
My one machine can reproduce this issue, known issue [1658 ](https://github.com/microsoft/vscode-cosmosdb/issues/1658)also reproduces on this machine. But others can't. I'm not sure if this is an environment issue or caused by known issue 1658.
