### ISSUE TITLE
1 Free Linux app service plan per region rule seems to be broken

### ISSUE THREAD

**Issue by nigarfin** [microsoft/vscode-azureappservice#1766]
Does this occur consistently? Yes
Repro steps:
1. Create Wep App in VS Code using the App Service Extension
2. Select a region that does not yet have a free linux ASP
3. Recieve an error

Action: appService.CreateWebAppAdvanced
Error type: Unauthorized
Error Message: This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.

Version: 0.18.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3676010extension.bundle.js:225:3676010
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593285
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
@nigarfin  Do you happen to know which region caused this?  Does it happen consistently for this subscription across all regions?

**Comment by nigarfin** [comment]
It was a Canadian region, I believe it was 'Canada Central' if I recall. I have not tried it for other regions.

**Comment by EricJizbaMSFT** [comment]
This error is coming directly from the platform, not us. I would follow up with them if you're still having this issue
