### ISSUE TITLE
entry not found in cache

### ISSUE THREAD

**Issue by diegocent07** [microsoft/vscode-azureappservice#1769]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.18.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:41330
extension.js:393:35925extension.js:393:35925
extension.js:243:74572extension.js:243:74572
extension.js:243:72553extension.js:243:72553
extension.js:243:72173extension.js:243:72173
i.find extension.js:243:106705
extension.js:243:53427extension.js:243:53427
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
