### ISSUE TITLE
not loaded

### ISSUE THREAD

**Issue by SeamTeam** [microsoft/vscode-azureappservice#1771]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.16.5
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:411388
rejected extension.bundle.js:164:410913
```

</details>

**Comment by EricJizbaMSFT** [comment]
@SeamTeam It seems like you may be trying to deploy to a Local Git web app, but the folder selected isn't a git repo. You can right click on the web app and change the deployment source back to "None" if you didn't mean to use "Local Git"

If that doesn't help, please add detailed repro steps
