### ISSUE TITLE
[Suggestion] Keep the input connection setting prefix is consistent with the error message

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1773]
**OS:** Windows 10/Mac
**App Service extension build version:** 20200911.1
**Azure Databases extension build version:** 20200914.4

**Repro Steps:**

1. Expand one web app -> Databases node -> Add Database connection to web app -> Select a PostgreSQL server -> Select a database -> Enter the default new connection setting prefix "POSTGRES".
2. Repeat the step 1 again and check the result.

**Actual:**
The input connection setting prefix is inconsistent with the error message.
![image](https://user-images.githubusercontent.com/62053665/93179091-c8c0eb80-f767-11ea-86e5-58095fad3fb1.png)

**Suggestion:**
Keep the input connection setting prefix is consistent with the error message.

**Comment by EricJizbaMSFT** [comment]
The difference between "setting" and "setting prefix" is a bit confusing, but the message is accurate here. The user is entering the _prefix_, but a setting with that prefix already exists. We think this messaging is good enough for now unless we get more user feedback
