### ISSUE TITLE
processTicksAndRejections task_queues.js:94:5

### ISSUE THREAD

**Issue by nagarjunCCP** [microsoft/vscode-azureappservice#1774]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.19.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:522736
rejected extension.bundle.js:164:522163
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @nagarjunCCP

Looks like you're trying to deploy to a web app that is configured for local git deploy.  You either need to deploy a project that has a git repository or you can configure your deployment source of your web app to `None` (which uses zip deploy).

![image](https://user-images.githubusercontent.com/5290572/93513608-f24e5400-f8da-11ea-91fb-6ad5cf0c2079.png)
