### ISSUE TITLE
The notification message is unclear when uploading an invalid file to application setting

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1778]
**OS:** Win10
**Build Version:** 20200917.5

**Repro Steps:**

1. Right click the "Application Settings" node -> Select "Upload Local Settings..." -> Select an invalid .json file.
2. Check the notification message.

**Expect:**
The notification message is clear.

**Actual:**
The notification message is unclear.
![image](https://user-images.githubusercontent.com/62053665/93746547-e2f73f80-fc27-11ea-9db1-a45a053f4cda.png)

**More Info:**
This issue also reproduces no matter what invalid file is selected.

**Comment by nturinski** [comment]
Could you explain what message you were expecting from this error?

Also, I should mention that in App Service, we are not expecting a .json file, but a .env file which looks like this:
![image](https://user-images.githubusercontent.com/5290572/93799159-9c87ed80-fbf3-11ea-9d0b-63ce74faf370.png)

**Comment by v-mengwe** [comment]
If we are not expecting a .json file, I think the error message "The operation only support .env file" should be better when choosing a .json file to upload.

**More Info:**
There is no error when uploading a txt/.json file which looks like this:
![image](https://user-images.githubusercontent.com/62053665/93956592-1e5b5080-fd85-11ea-9516-0cd269ccdbf9.png)

**Comment by EricJizbaMSFT** [comment]
In this case ".env" is referring to the file name, not the file extension. A "test.txt" file is also valid
