### ISSUE TITLE
[Unstable] There is an error when updating the file after selecting "Always Upload"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1779]
**OS:** Win10
**Build Version:** 20200917.5

**Repro Steps:**

1. Drill into the 'Files' node -> Click on a hostingstart.html file -> Edit the file and make changes -> Save.
2. Response when it prompts to update the remote file -> Select "Always Upload".
3. Repeat "Edit the file and make changes -> Save" step more than 3 times.
4. Check the result.

**Expect:**
There is no error when updating the file.

**Actual:**
There is an error when updating the file.
![image](https://user-images.githubusercontent.com/62053665/93850948-c7506f80-fce1-11ea-9970-8e6de63f2db1.png)

**More Info:**
Action: writeFile
Error type: Error
Error Message: ETag does not represent the latest state of the file "hostingstart.html". Download the file from Azure to get the latest version.

Version: 0.19.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.50.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
AppServiceFileSystem.<anonymous> extension.bundle.js:309:491914
rejected extension.bundle.js:309:490241
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
The etag is meant to prevent accidentally overriding something that has already been changed. You probably ran into a timing issue here because you saved so many times in a row. This would be a difficult thing to fix on our side and the workaround (re-download the file) is mentioned in the error
