### ISSUE TITLE
test

### ISSUE THREAD

**Issue by snsclanceo** [microsoft/vscode-azureappservice#1780]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+[^.]$/

Version: 0.19.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
WebApps._getConfiguration extension.bundle.js:225:1884985
extension.bundle.js:225:3167679extension.bundle.js:225:3167679
WebApps.getConfiguration extension.bundle.js:225:3167657
SiteClient.<anonymous> extension.bundle.js:164:145908
extension.bundle.js:164:142930extension.bundle.js:164:142930
i extension.bundle.js:164:142616
SiteClient.getSiteConfig extension.bundle.js:164:145730
extension.bundle.js:1:552564extension.bundle.js:1:552564
fulfilled extension.bundle.js:1:551148
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
What did you use as your app name?
