### ISSUE TITLE
Azureappsevice deployment Error

### ISSUE THREAD

**Issue by Ti-Jesu** [microsoft/vscode-azureappservice#1781]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: your current branch 'master' does not have any commits yet

Version: 0.19.0
OS: win32
OS Release: 6.3.9600
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:522736
rejected extension.bundle.js:164:522163
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Looks like you're trying to deploy via local git.  You should either commit a change to your branch or you can configure your deployment source to be "None" which leverages zip deploy.

**Comment by Ti-Jesu** [comment]
> Looks like you're trying to deploy via local git. You should either commit a change to your branch or you can configure your deployment source to be "None" which leverages zip deploy.
Thanks very much, im pretty new to this. What i want to deploy is the MEAN Stack and i am trying to figure out the way around it

**Comment by nturinski** [comment]
Well, in a terminal that is accessing your project, you should be able to do the following:

```
git add .
git commit -m 'First commit'
```

After doing this, you should be able to deploy to your web app.  Hope this helps!
