### ISSUE TITLE
Random Error after vscode update

### ISSUE THREAD

**Issue by saebs** [microsoft/vscode-azureappservice#1784]
Does this occur consistently? 
Repro steps:

1. Deploy from vscode using Azure plugin
2.

Action: appService.Deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN siyaso.scm.azurewebsites.net

Version: 0.19.0
OS: linux
OS Release: 4.19.104-microsoft-standard
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add more detailed repro steps
