### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by DANHAUT** [microsoft/vscode-azureappservice#1785]
Does this occur consistently? Yes
Repro steps:

1. Create new web app from Visual Studio code 1.49.2
2. Put name AzureAngular10
3. Select Nodes 12.x LTS
4. Waiting publication

Action: postCreateWebApp
Error type: 503
Error Message: The service is unavailable.

Version: 0.19.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:309:388829extension.bundle.js:309:388829
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593298
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:223:5
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:228:7
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:312:28
IncomingMessage.emit events.js:228:7
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Hi @DANHAUT

Could you try deploying this again?  I suspect that this error is happening because the web app is fresh and just needs some time to spin up.

**Comment by DANHAUT** [comment]
Hi nturinski
Thank a lot for your response.
I successfully deploy the web app but when I launch the url I got the following error :
You are not authorized or do not have any subscriptions associated with your account
![image](https://user-images.githubusercontent.com/69802606/94480501-af438900-01d6-11eb-8986-c4643682a736.png)
Best regards

**Comment by nturinski** [comment]
Hmm, the critical error reported makes me think that the deployment did not complete successfully.  If you click on view details, what did that output?
