### ISSUE TITLE
Support .ignore file for deploy

### ISSUE THREAD

**Issue by JeffMHunt** [microsoft/vscode-azureappservice#1786]
Developing a node.js app and using dotenv. I want to the deploy to ignore .env and other files. Cannot find anything similar to .funcignore in the Azure Functions extension?

**Comment by nturinski** [comment]
Hi @JeffMHunt

You should be able to change your `zipIgnorePattern` setting to include files that you don't want deployed.  You can read more about that setting here: https://github.com/microsoft/vscode-azureappservice/wiki/Configuring-Zip-Deployment#additional-zip-deploy-configuration-settings

**Comment by JeffMHunt** [comment]
Would it be possible to request feature parity with the Azure Functions extension?

**Comment by diberry** [comment]
Does this zipIgnorePattern get saved to a file that lives in source control with the project, or does it only live on the local box's VSCode configuration? The second one doesn't help and actually causes more problems because it becomes invisible to the maintenance of the deployment.

**Comment by EricJizbaMSFT** [comment]
You can modify zipIgnorePattern in either your User or Workspace settings. The Workspace settings will be in `.vscode/settings.json` and yes I would recommend including that in source control (we [do it](https://github.com/microsoft/vscode-azureappservice/tree/main/.vscode) for our own projects)
