### ISSUE TITLE
Failed deplyoing Angular App to Azure App Service

### ISSUE THREAD

**Issue by jacckjacck** [microsoft/vscode-azureappservice#1787]
Does this occur consistently? Yes
Repro steps:

- Build the angular code using ng build 

- From VSCode, using Azure App Service Extension, deploy the generated dist folder to web app server (stack: nodejs LTS - Linux)

Error Message:

`9:50:07 a. m. integra-front: Starting deployment...
9:50:08 a. m. integra-front: Creating zip package...
9:50:18 a. m. integra-front: Zip package size: 5.78 MB
9:50:24 a. m. integra-front: Updating submodules.
9:50:25 a. m. integra-front: Preparing deployment for commit id '51366a6610'.
9:50:26 a. m. integra-front: Repository path is /tmp/zipdeploy/extracted
9:50:26 a. m. integra-front: Running oryx build...
9:50:26 a. m. integra-front: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10 -i /tmp/8d863bdd546af58 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
9:50:30 a. m. integra-front: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
9:50:30 a. m. integra-front: You can report issues at https://github.com/Microsoft/Oryx/issues
9:50:30 a. m. integra-front: Oryx Version: 0.2.20200805.1, Commit: e7c39ede513143e9d80fd553f106f04268d770d4, ReleaseTagName: 20200805.1
9:50:30 a. m. integra-front: Build Operation ID: |lSBeMHC8Rpc=.40c00d59_
9:50:30 a. m. integra-front: Repository Commit : 51366a66107540029f7881b4940e75c9
9:50:30 a. m. integra-front: Detecting platforms...
9:50:30 a. m. integra-front: Could not detect any platform in the source directory.
9:50:30 a. m. integra-front: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
9:50:33 a. m. integra-front: Error: Couldn't detect a version for the platform 'nodejs' in the repo.\n/opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 10 -i /tmp/8d863bdd546af58 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
9:50:41 a. m. integra-front: Deployment failed.`

**Comment by nturinski** [comment]
Is there another folder within your dist folder?  Like dist/app_name?  If there is, I think you have to deploy that instead.

That being said, you may have more luck deploying your Angular App with the [Static Web Apps extension](https://github.com/microsoft/vscode-azurestaticwebapps).  This new Azure service was built to deploy static content, such as Angular or React apps.
