### ISSUE TITLE
cambio

### ISSUE THREAD

**Issue by jorgarciac** [microsoft/vscode-azureappservice#1790]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: your current branch 'master' does not have any commits yet

Version: 0.19.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:522736
rejected extension.bundle.js:164:522163
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Looks like you're trying to deploy via local git. You should either commit a change to your branch or you can configure your deployment source to be "None" which leverages zip deploy.
