### ISSUE TITLE
appService.StartRemoteDebug

### ISSUE THREAD

**Issue by shashisagar** [microsoft/vscode-azureappservice#1791]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Error getting tunnel status: 502

Version: 0.19.0
OS: linux
OS Release: 5.4.0-47-generic
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:122897
rejected extension.bundle.js:164:118469
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
