### ISSUE TITLE
issue in deploy

### ISSUE THREAD

**Issue by shashisagar** [microsoft/vscode-azureappservice#1792]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400 Bad Request
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

Version: 0.19.0
OS: linux
OS Release: 5.4.0-47-generic
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:522736
rejected extension.bundle.js:164:522163
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
