### ISSUE TITLE
Can't debug my app via vscode

### ISSUE THREAD

**Issue by thuzinho** [microsoft/vscode-azureappservice#1796]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Error getting tunnel status: 504

Version: 0.19.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code - Insiders
Product Version: 1.50.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:122897
rejected extension.bundle.js:164:118469
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
