### ISSUE TITLE
Replace the manual kudu client implementation with azure tools/ kudu

### ISSUE THREAD

**Issue by changsi-an** [microsoft/vscode-azureappservice#180]
The `logPointsClient.ts` is using a ad-hoc implementation of Kudu Client call. Get it replaced with the `azure tools/ kudu`

Get clarification/reminder on what to replace with.

**Comment by EricJizbaMSFT** [comment]
Logpoints was removed from this repo https://github.com/microsoft/vscode-azureappservice/pull/1101
