### ISSUE TITLE
[Suggestion] Add commands "Browse Website/Start Streaming Logs/Stop Streaming Logs/Start Remote Debugging/SSH into Web App" for slot in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#1800]
**OS:** Windows 10
**Build Version:** 20201011.1

**Repro Steps:**
Check the slot related commands from command palette.

**Actual:**
There is no commands "Browse Website/Start Streaming Logs/Stop Streaming Logs/Start Remote Debugging/SSH into Web App" for slot.

**Suggestion:**
Add commands "Browse Website/Start Streaming Logs/Stop Streaming Logs/Start Remote Debugging/SSH into Web App" for slot in command palette.

**Comment by EricJizbaMSFT** [comment]
Closing with same reasoning as https://github.com/microsoft/vscode-azurefunctions/issues/2477#issuecomment-712470952

We already do this for the "Deploy" command (we have a separate "Deploy to Slot" command), but that's only because "Deploy" is such a high priority scenario
