### ISSUE TITLE
Cannot connect to remote ssh 

### ISSUE THREAD

**Issue by ShyamKatti** [microsoft/vscode-azureappservice#1801]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: Error getting tunnel status: 504

Version: 0.19.0
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:122897
rejected extension.bundle.js:164:118469
```

</details>

**Comment by EricJizbaMSFT** [comment]
Will track with https://github.com/microsoft/vscode-azureappservice/issues/1802
