### ISSUE TITLE
Updating code on node.js server causes VSC to complain that this is not latest version - no changes made server-side or elswhere

### ISSUE THREAD

**Issue by strongteam23** [microsoft/vscode-azureappservice#1803]
Does this occur consistently? 
Repro steps:

1.
2.

Action: writeFile
Error type: Error
Error Message: ETag does not represent the latest state of the file "hostingstart.html". Download the file from Azure to get the latest version.

Version: 0.19.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
AppServiceFileSystem.<anonymous> extension.bundle.js:309:491914
rejected extension.bundle.js:309:490241
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Have you tried redownloading the file and trying to make your edits again?

**Comment by strongteam23** [comment]
Hello Nathan,

Thank you for your reply. My expectation was once I was connected to Azure
and able to read code from the default Azure App Server instance, I would
then be able to update the code and submit it back to the app server. I did
try redownloading, restarting VSC and even rebooting my workstation. Seeing
that none of this worked, I figured maybe the only way to update was to
establish a CI/CD pipeline. I'm not too sure how far I am on or off the
ranch.

I'm open to screen share to demonstrate if this helps you.

Thanks again,
Matthew

**Comment by nturinski** [comment]
This is definitely expected to work especially if you're just editing the default hostingstart.html file.  A successful attempt will look like this: 
![image](https://user-images.githubusercontent.com/5290572/96038090-7f71c380-0e1b-11eb-9af6-8bef6eb6f1dd.png)

Is there any possibility that you can use a different web app on a different subscription?  I'm wondering if that Microsoft Partner Network has some properties that are blocking the update.
