### ISSUE TITLE
Not sure how to fix this error. I am currently using the Azure for Students plan. I deleted my previous application service from Azure, but this error still comes up.

### ISSUE THREAD

**Issue by lungyoungyu** [microsoft/vscode-azureappservice#1808]
Does this occur consistently? 
Repro steps:

1. I am following these instructions: https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?pivots=platform-linux
2. Choose directory you currently have open in Visual Studio.
3. Choose Create new Web App.
4. Type a globally unique name for your Web App and press ENTER.
5. Choose Node.js version: Node 14 LTS.
6. Error pops up in bottom right notification bar after notification channel reaches to 3/5.

Action: appService.Deploy
Error type: Unauthorized
Error Message: This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.

Version: 0.19.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:225:3676010
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request._callback extension.bundle.js:1:593298
Request.r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:223:5
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:228:7
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:312:28
IncomingMessage.emit events.js:228:7
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Hi @lungyoungyu

Sorry you're running into issues here.  Could you try creating with Advanced Create and choose a different location?  You can find that action by right-clicking your subscription.

![image](https://user-images.githubusercontent.com/5290572/96188283-4c026800-0ef3-11eb-83c0-7ec7b0d45ba2.png)

**Comment by lungyoungyu** [comment]
Hi @nturinski 

Yes, I believe this fixed the issue I was facing. Thanks.
