### ISSUE TITLE
dRRRq;

### ISSUE THREAD

**Issue by t0dd2000** [microsoft/vscode-azureappservice#1811]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "Flask1WebApp" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.15.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.30.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:262:3460452
module.exports.n extension.bundle.js:262:3458872
module.exports.n extension.bundle.js:262:3458649
module.exports.t.deploy.i.window.withProgress extension.bundle.js:262:3460313
e._withProgress extensionHostProcess.js:467:3
e.withProgress extensionHostProcess.js:466:718
Object.withProgress extensionHostProcess.js:740:789
Object.<anonymous> extension.bundle.js:262:3460139
o extension.bundle.js:262:3458705
process._tickCallback next_tick.js:188:7
```

</details>

**Comment by nturinski** [comment]
As the error mentions, please push directly to your GitHub repo to deploy your web app.
