### ISSUE TITLE
The "loading..." sign does not disappear after adding azure databases connection with a SQL account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1814]
**OS:** All
**Build Version:** 20201013.1

**Repro Steps:**

1. Create a new Linux Web App  and select Node.js as the runtime.
2. Expand Deployments node -> Click "Connect to a GitHub Repository..." -> Choose organization -> Choose repository with "node-todo" -> Choose "master" branch.
3. Browse website.
4. Expand Databases node -> Click "Add Azure Databases Connection..." -> Select a SQL account -> Select a database.
5. Wait 10 minutes -> Browse website again.

**Expect:**
The "loading..." sign disappears.
![image](https://user-images.githubusercontent.com/62053665/96703514-840f1c80-13c5-11eb-957d-cc7cd098f4aa.png)

**Actual:**
The "loading..." sign does not disappear.
![image](https://user-images.githubusercontent.com/62053665/96703609-a4d77200-13c5-11eb-89bc-0648cffdbcff.png)

**More Info:**
This issue doesn't reproduce when adding azure databases connection with a MongoDB account

**Comment by nturinski** [comment]
Could you share the project that you're using for this?

**Comment by EricJizbaMSFT** [comment]
You probably just need to use the "cosmos" branch of the node-todo repo. The default "master" branch doesn't work with SQL

**Comment by v-mengwe** [comment]
@EricJizbaMSFT Thanks for your guidance, this issue doesn't reproduce when using the "cosmos" branch of the node-todo repo.
