### ISSUE TITLE
There is no "Import app into VS Code Insiders/VS Code" link in the page after creating a free trial app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1818]
**OS:** All
**Build Version:** 20201020.2

**Repro Steps:**

1. Sign out of Azure account -> Click the "Create a Free Trial App…" button -> Click "Continue" -> Select "Sign in with ReCAPTCHA".
2. Check the result.

**Expect:**
There is a "Import app into VS Code Insiders/VS Code" link in the page after creation.

**Actual:**

1. It will navigate to VS Code download page after signing in to create Trial App the first time.
 ![trial](https://user-images.githubusercontent.com/62053665/96948377-17f0fd80-1518-11eb-8578-94d36d9ac455.gif)
3. There is no "Import app into VS Code Insiders/VS Code" link in the page after signing in to create Trial App again. 
 ![trial1](https://user-images.githubusercontent.com/62053665/96948381-1de6de80-1518-11eb-82fe-a38548471540.gif)

**Comment by ejizba** [comment]
Closing because of https://github.com/microsoft/vscode-azureappservice/issues/1880
