### ISSUE TITLE
Issue from visual code

### ISSUE THREAD

**Issue by enunez5** [microsoft/vscode-azureappservice#1821]
Does this occur consistently? 
Repro steps:

1. I clicked over app of azure
2.

Action: api.revealTreeItem
Error type: Error
Error Message: TreeError [azureAppService] Data tree node not found: [object Object]

Version: 0.19.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
U.getDataNode workbench.desktop.main.js:1159:607
U.expand workbench.desktop.main.js:1157:795
async Q.expand workbench.desktop.main.js:5739:726
async p.reveal workbench.desktop.main.js:4578:470
```

</details>

**Comment by nturinski** [comment]
@enunez5 Could you provide more details to reproduce this?  It looks like you used the revealTreeItem command.  Is there anything of note about your app that could not be found? Did you create it through the portal or with any special conditions?
