### ISSUE TITLE
cannot deploy app from VSCODE to azure using azure app service

### ISSUE THREAD

**Issue by hello687** [microsoft/vscode-azureappservice#1822]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: {"body":"","headers":{"cache-control":"no-cache","pragma":"no-cache","expires":"-1","server":"Kestrel","set-cookie":["ARRAffinity=40b45f0624d0dbfccd23ea62135551a8ccc3170eb13646b7781105e7501c4119;Path=/;HttpOnly;Domain=qpehybrid.scm.azurewebsites.net"],"date":"Mon, 26 Oct 2020 12:15:19 GMT","connection":"close","content-length":"0"},"statusCode":400}

Version: 0.7.1
OS: win32

**Comment by nturinski** [comment]
Please provide detailed repro steps.
