### ISSUE TITLE
ssh into app service issue

### ISSUE THREAD

**Issue by merajmehrabi** [microsoft/vscode-azureappservice#1823]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartSsh
Error type: ERR_TLS_CERT_ALTNAME_INVALID
Error Message: Hostname/IP does not match certificate's altnames: Host: xxxx. is not in the cert's altnames: DNS:*.azurewebsites.net, DNS:*.scm.azurewebsites.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net, DNS:*.sso.azurewebsites.net

Version: 0.19.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RequestError extension.bundle.js:225:1107125
Request.callback extension.bundle.js:225:1105766
Request.RP$callback [as _callback] extension.bundle.js:225:1105212
r._callback.r.callback.r.callback extension.bundle.js:201:4468
Request.emit events.js:223:5
Request.EventEmitter.emit domain.js:475:20
Request.onRequestError extension.bundle.js:201:13754
ClientRequest.emit events.js:228:7
ClientRequest.EventEmitter.emit domain.js:475:20
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
TLSSocket.EventEmitter.emit domain.js:475:20
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Could you provide detailed repro steps please?  Are you able to SSH via the Portal?

**Comment by merajmehrabi** [comment]
Yeap, I can ssh using “az” command also through portal.

**Comment by nturinski** [comment]
Are you running through a proxy by chance?  VS Code may not be handling the proxy the same way as the az CLI or Portal.
