### ISSUE TITLE
Fail to upload the changes when uploading the remote file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1825]
**OS:** Win10
**Build Version:** 20201027.4

**Repro Steps:**

1. Create a Linux/Windows web app -> Deploy a project.
2. Drill into the Files node and click on a file -> Edit the file, make changes in the editor -> Save.
3. Response when it prompts to update the remote file -> Select "Upload".
4. Check the result.

**Expect:**
Succeed to upload the changes without any error.

**Actual:**
Fail to upload the changes with an error.
![image](https://user-images.githubusercontent.com/62053665/97275306-be1e6980-1870-11eb-83d9-d77626c2f5b3.png)

**More Info:**
Action: writeFile
Error type: Error
Error Message: file must be a string, Blob, ArrayBuffer, ArrayBufferView, or a function returning NodeJS.ReadableStream.

Version: 0.19.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code - Insiders
Product Version: 1.51.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
serializeBasicTypes extension.bundle.js:46:80291
Serializer.serialize extension.bundle.js:46:80417
getOperationArgumentValueFromParameterPath extension.bundle.js:52:976771
getOperationArgumentValueFromParameter extension.bundle.js:52:977021
serializeRequestBody extension.bundle.js:52:974858
KuduClient.ServiceClient.sendOperationRequest extension.bundle.js:52:975810
Vfs.putItem extension.bundle.js:539:356380
Object.<anonymous> extension.bundle.js:52:224425
fulfilled extension.bundle.js:52:222981
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
What type of file was this?  Where in the Files node was it?
