### ISSUE TITLE
[Suggestion] Keep the dialog consistently after clicking "Deploy" button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1828]
**OS:** Win10
**Build Version:** 20201027.11

**Repro Steps:**

1. Open a project in VS Code.
2. Create a Linux web app -> Pop up a notification -> Click "Deploy" button.
3. Check the result.

**Actual:**
1. Python Linux web app: There is no "Select the folder to deploy" dailog and don't pop up a dialog to ask whether always deploy workspace to the special web app or not.
  ![deploy](https://user-images.githubusercontent.com/62053665/97418587-f3e05280-1943-11eb-9f87-1818f0281d1e.gif)
2. Node Linux web app: There is a "Select the folder to deploy" dailog and pop up a dialog to ask 
whether always deploy workspace to the special web app or not.
  ![deploy1](https://user-images.githubusercontent.com/62053665/97418614-fc388d80-1943-11eb-9990-1f0ef8c87b92.gif)
3. NET Linux web app: There is no "Select the folder to deploy" dailog and pop up a dialog to ask 
  whether always deploy workspace to the special web app or not.
![deploycs](https://user-images.githubusercontent.com/62053665/97418651-065a8c00-1944-11eb-9345-e28ef052c9fc.gif)

**Suggestion:**
Keep the dialog consistently after clicking "Deploy" button.

**Comment by EricJizbaMSFT** [comment]
@v-mengwe in each case, can you let us know what settings you have in `.vscode/settings.json`? That could be affecting the behavior you're describing

**Comment by v-mengwe** [comment]
The setting "App Service: Default Web App To Deploy" is 
![image](https://user-images.githubusercontent.com/62053665/97516423-0b641d80-19ce-11eb-929f-21498e18c431.png)

The `.vscode/settings.json` file:
1. Python project:
```
{
    "appService.deploySubpath": ".",
}
```
2. Node project: 
```
{
    "git.ignoreLimitWarning": true,
    "appService.zipIgnorePattern": [
        "node_modules{,/**}",
        ".vscode{,/**}"
    ]
}
```
3. NET project: 
```
{
    "git.ignoreLimitWarning": true,
    "appService.preDeployTask": "publish-release",
    "appService.deploySubpath": "bin/Release/netcoreapp2.1/publish"
}
```

It's because of setting `appService.deploySubpath` in ".vscode/settings.json" file?

**Comment by EricJizbaMSFT** [comment]
Yes that behavior is controlled by `appService.deploySubpath`

**Comment by v-mengwe** [comment]
Thanks for your guidance.
