### ISSUE TITLE
Cannot establish remote debugging in VSCode to Azure Web App in Linux instance

### ISSUE THREAD

**Issue by fawinterfawinter** [microsoft/vscode-azureappservice#1832]
Does this occur consistently? Yes
Repro steps:
Just trying to connect remotely

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.19.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:123037
fulfilled extension.bundle.js:164:118408
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
