### ISSUE TITLE
專題

### ISSUE THREAD

**Issue by liuce1104** [microsoft/vscode-azureappservice#1836]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "lousi20201104" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.19.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.50.1
Language: zh-tw

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:225:3757968
extension.bundle.js:225:3755824extension.bundle.js:225:3755824
i extension.bundle.js:225:3755510
extension.bundle.js:225:3757682extension.bundle.js:225:3757682
t.ExtHostProgress._withProgress extensionHostProcess.js:640:3
t.ExtHostProgress.withProgress extensionHostProcess.js:639:734
Object.withProgress extensionHostProcess.js:995:551
Object.<anonymous> extension.bundle.js:225:3757614
fulfilled extension.bundle.js:225:3755578
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Thank you for using the extension! In order to deploy to Azure, you will need to push to your GitHub repository, not to the app service. Once you push a change to your repo, the changes will automatically be picked up by your web app.

If that doesn't resolve your issue, please let me know.
