### ISSUE TITLE
Can't ask OS when creating a basic web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1839]
**OS:** Win10/Mac
**Build Version:** 20201105.6

**Repro Step:**

1. Click the + button -> Enter a new name for the new web app -> Select a Node 12/.Net 2.1/.Net 3.1/ Python 3.6 runtime stack.
2. Check the result.

**Expect:**
Ask about OS.
![Screen Shot 2020-11-06 at 11 05 31 AM](https://user-images.githubusercontent.com/62053665/98335410-db58f200-203f-11eb-931c-213807c19938.png)

**Actual:**
Can't ask about OS.

**More Info:**
This issue also reproduces for "F1/right-click a subscription -> Select 'Create New Web App...'".

**Comment by EricJizbaMSFT** [comment]
This is by-design. The purpose of basic create is to reduce the number of prompts, and in the cases you mentioned we have a "recommended" OS that we pick for the user.
