### ISSUE TITLE
A warning notification pops up after deploying node.js project to Linux web app successfully

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1840]
**OS:** Mac/Win10
**Build Version:** 20201105.6

**Repro Steps:**

1. Open the nodejs-docs-hello-world-master project folder in VS Code.
2. Deploy it to a Linux Web App.
3. Wait a minute after deploying successfully.
4. Check the result.

**Expect:**
There is no warning.

**Actual:**
A warning notification "A critical error: tar (child): node_modules.tar.gz: Cannot open: No such file or directory" pops up.

**More Info:**
Details in output:
```
4:17:08 PM elsa-adv-node12-lin: Deployment successful.
4:17:19 PM: Deployment to "elsa-adv-node12-lin" completed.
4:17:24 PM: "elsa-adv-node10" reported a critical error: tar (child): node_modules.tar.gz: Cannot open: No such file or directory
4:17:47 PM: "elsa-adv-node12-lin" reported a critical error: tar (child): node_modules.tar.gz: Cannot open: No such file or directory

```
Details after clicking "View details":
![Screen Shot 2020-11-06 at 5 04 00 PM](https://user-images.githubusercontent.com/62053665/98347345-43b0cf00-2052-11eb-8042-240a078745e7.png)
![Screen Shot 2020-11-06 at 5 04 12 PM](https://user-images.githubusercontent.com/62053665/98347358-457a9280-2052-11eb-86d7-44bdda3a1df4.png)

**Comment by nturinski** [comment]
This is probably by-design.  Can you browse the webpage and verify if it is working or not?  If it's not, then this is by-design.  If it is, then it's reporting a false-positive and we need to investigate this.

**Comment by v-mengwe** [comment]
Browse the webpage:
![image](https://user-images.githubusercontent.com/62053665/98492277-4db11880-2272-11eb-95c7-dd1ef9fba0a0.png)
