### ISSUE TITLE
[Suggestion] Add the "recently used" state for "Linux" when creating a web app again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1841]
**OS:** Win10/Mac
**Build Version:** 20201105.6

**Repro Step:**

1. Create a web app with Linux OS.
2. Create a web app again.
3. Check the list ofask about OS.

**Actual:**
There is no "recently used" state.
![image](https://user-images.githubusercontent.com/62053665/98356997-7614f900-205f-11eb-83fe-5913059ea5f9.png)

**Suggestion:**
Add the "recently used" state for "Linux" when creating a web app again.

**More Info:**
This issue doesn't reproduce when creating web app with windows.
![image](https://user-images.githubusercontent.com/62053665/98357762-a741f900-2060-11eb-9bb7-3bfa9962d86b.png)

**Comment by EricJizbaMSFT** [comment]
This is by design. We only add `(recently used)` if it _changes_ the order of the picks. Since "Linux" is already first, we don't add it. This is because the `(recently used)` text is a bit ugly and we try to avoid adding it when possible
