### ISSUE TITLE
not deploying

### ISSUE THREAD

**Issue by wenotch** [microsoft/vscode-azureappservice#1844]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: unable to access 'https://testingqw.scm.azurewebsites.net:443/testingqw.git/': The requested URL returned error: 403

Version: 0.19.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:522736
rejected extension.bundle.js:164:522163
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
