### ISSUE TITLE
Display "Application Error" when deploying a .NET 2.1 project to a Linux web app created with .NET 3.1

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1845]
**OS:** Mac/Win10
**Build Version:** 20201105.6
**.NET Version:** 2.1

**Repro Steps:**

1. Create a C# project by "dotnet new web" -> Open this project in VS Code.
2. Deploy the project to a web app -> Browser website after deploying successfully.
3. Check the website.

**Expect:**
Display "Hello World!".
![image](https://user-images.githubusercontent.com/62053665/98517919-a0f28d80-22a9-11eb-8231-1f4c53fa8409.png)

**Actual:**

1. Display "Hello World!" when deploying the project to a Windows web app created with .NET 2.1/3.1 or Linux web app with .NET 2.1.
  ![image](https://user-images.githubusercontent.com/62053665/98518865-f0858900-22aa-11eb-8168-c99f27733f87.png)
3. Display "Application Error" when deploying the project to a Linux web app created with .NET 3.1.
  ![image](https://user-images.githubusercontent.com/62053665/98518982-1ca10a00-22ab-11eb-9455-37432eeeea44.png)

**More Info:**
**.NET Version:** 3.1
This issue also reproduces for .NET 3.1.
1. Display "Hello World!" when deploying the project to a Windows web app created with .NET 2.1/3.1 or Linux web app with .NET 3.1.
  ![image](https://user-images.githubusercontent.com/62053665/98518865-f0858900-22aa-11eb-8168-c99f27733f87.png)
3. Display "Application Error" when deploying the project to a Linux web app created with .NET 2.1.
  ![image](https://user-images.githubusercontent.com/62053665/98518982-1ca10a00-22ab-11eb-9455-37432eeeea44.png)

**Comment by EricJizbaMSFT** [comment]
This is expected behavior. Users must select the correct .NET version for their app to work in Azure. The fact that Windows works is more "luck" than "by design", and it's not guaranteed to work for future versions of .NET
