### ISSUE TITLE
Can't "Start Remote Debugging" again in 2 mins after cancelling remote debugging

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1846]
**OS:** All
**Build Version:** 20201105.6

**Repro Steps:**
1. Deploy a node.js project to a Linux web app.
2. Right click the web app -> Click "Start Remote Debugging".
3. Click "Cancel" when prompting a dialog.
![image](https://user-images.githubusercontent.com/57662131/98528053-bd48f700-22b6-11eb-8cb2-d8920b1e002c.png)
4. Start remote debugging again.

**Expect:**
Succeed to start the remote debugging again.

**Actual:**
Fail to start the remote debugging again.
![image](https://user-images.githubusercontent.com/57662131/98527734-59bec980-22b6-11eb-9119-cc0c3c358335.png)

**More Info:**
This issue will be fixed after waiting about 3 minutes.

**Comment by ejizba** [comment]
I see how that's annoying, but unfortunately this would be very complex for us to fix and may require changes on the platform side. For an advanced feature like this, we think the current experience is good enough.
