### ISSUE TITLE
spring boot deploy on Azure app service failed

### ISSUE THREAD

**Issue by sandeepeat2014** [microsoft/vscode-azureappservice#1848]
Does this occur consistently? 
Repro steps:

1.
2.

Action: postCreateWebApp
Error type: ECONNRESET
Error Message: request to https://spingbootapp.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: write ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
errorOrDestroy destroy.js:108:12
onwriteError _stream_writable.js:456:5
onwrite _stream_writable.js:477:5
destroy.js:50:7destroy.js:50:7
TLSSocket.Socket._destroy net.js:669:5
TLSSocket.destroy destroy.js:38:8
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:88:12
```

</details>

**Comment by nturinski** [comment]
Please add detailed repro steps.
