### ISSUE TITLE
Deploying NodeJS app fails

### ISSUE THREAD

**Issue by zuboje** [microsoft/vscode-azureappservice#1851]
Does this occur consistently? 
Repro steps:

1. Have Angular app
2. Deploy to Azure app service, any app

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://_MYURL_.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:166:16389
ClientRequest.emit events.js:228:7
ClientRequest.EventEmitter.emit domain.js:475:20
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
TLSSocket.EventEmitter.emit domain.js:475:20
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
This seems like an intermitted issue with Azure.  Could you please restart your app and try to deploy again later?  If this keeps occurring, please provide detailed repro steps.

You could also consider using [Azure Static Web Apps](https://github.com/microsoft/vscode-azurestaticwebapps).  It's built to handle SPA better than App Service.
