### ISSUE TITLE
Error type: ECONNRESET

### ISSUE THREAD

**Issue by kengkkun** [microsoft/vscode-azureappservice#1852]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://deploying-react.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:363:15219
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.

**Comment by initialresult** [comment]
@kengkkun This happend to me when I was deploying my nuxtjs web app, but I have fixed it by downgrading it to 0.19.0

**Comment by nturinski** [comment]
I don't think we changed anything regarding deployment code.  Could you try upgrading and deploying again to see if it works now?

**Comment by nturinski** [comment]
Actually, I forgot but we did a large refactor last release that's related to http calls.  If you could provide us any information to help us get to the bottom of this, it'd be much appreciated!

Could you give any information about the web app you were deploying to?
1. OS?
1. Do you have a GitHub repo for the project?
1. App service plan SKU?

**Comment by kengkkun** [comment]
Thank you for information. I try to change the command in script to build my project from `npm run build` to `run build` it work for me.
