### ISSUE TITLE
Error 403 - This web app is stopped.

### ISSUE THREAD

**Issue by chuongxl** [microsoft/vscode-azureappservice#1853]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 403
Error Message:  Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

If you are the web app administrator, please find the common 403 error scenarios and resolution here [https://go.microsoft.com/fwlink/?linkid=2095007]. For further troubleshooting tools and recommendations, please visit Azure Portal [https://portal.azure.com/].

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please start your app up.  If this doesn't resolve your issue, please give detailed repro steps.
