### ISSUE TITLE
file path include backslash(\) in Ubuntu

### ISSUE THREAD

**Issue by Yamaji-Toshiyuki** [microsoft/vscode-azureappservice#1854]
Does this occur consistently?  Yes
Repro steps:

I don't know how to reproduction this scene.
so, I wrote here my webapp setting
Python(use flask)
version 3.8.6

but, I think the app settings aren't effect to VSCode extension.
I think, It is bug of vscode-azureappservice.
It seems that error by last file path include backslash(\).
please fix.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /home/haruyuki/Documents/Sleep_Assist/server\azure

Version: 0.20.0
OS: linux
OS Release: 5.4.0-52-generic
Product: Visual Studio Code
Product Version: 1.51.0
Language: ja

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:696:24367
fulfilled extension.bundle.js:696:23861
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Yamaji-Toshiyuki can you copy the contents of the file `.vscode/settings.json` at the root of your workspace? Specifically, I'm interested in "appService.deploySubpath" and "appService.preDeployTask"
