### ISSUE TITLE
Entry not found in cache error showing when the azure sign in credentials changed

### ISSUE THREAD

**Issue by expsyama** [microsoft/vscode-azureappservice#1855]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:74739extension.js:243:74739
extension.js:243:73597extension.js:243:73597
B._callback extension.js:16:228415
B.t._callback.t.callback.t.callback [as callback] extension.js:202:5500
B.emit events.js:223:5
B.EventEmitter.emit domain.js:475:20
B.<anonymous> extension.js:202:18360
B.emit events.js:223:5
B.EventEmitter.emit domain.js:475:20
IncomingMessage.<anonymous> extension.js:202:17192
Object.onceWrapper events.js:312:28
IncomingMessage.emit events.js:228:7
IncomingMessage.EventEmitter.emit domain.js:475:20
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
