### ISSUE TITLE
app service times out for ssh

### ISSUE THREAD

**Issue by RileyMShea** [microsoft/vscode-azureappservice#1856]
Does this occur consistently?  No
Repro steps:

1. Click app in side bar
2. Select SSH into this app
3. wait

Action: appService.StartSsh
Error type: Error
Error Message: Unable to establish connection to application: Timed out

Version: 0.20.0
OS: linux
OS Release: 5.4.0-53-generic
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:419:121486
fulfilled extension.bundle.js:419:116847
```

</details>

**Comment by EricJizbaMSFT** [comment]
Please add repro steps
