### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by R-Lunna** [microsoft/vscode-azureappservice#1860]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
