### ISSUE TITLE
Error deploying to Azure App from Visual Studio Code mac OS

### ISSUE THREAD

**Issue by montenegrojd** [microsoft/vscode-azureappservice#1861]
Does this occur consistently? Yes
Repro steps:
1. Build a Web api using visual studio code for Mac
2. Install Azure Extension
3. Create App in Azure portal
4. Right click on Azure Subscription and select the app to deploy

Action: appService.Deploy
Error type: Error
Error Message: No workspace folder

Version: 0.20.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
A.$getTaskExecution workbench.desktop.main.js:4448:360
p._doInvokeHandler workbench.desktop.main.js:4475:707
p._invokeHandler workbench.desktop.main.js:4475:399
p._receiveRequest workbench.desktop.main.js:4474:59
p._receiveOneMessage workbench.desktop.main.js:4472:886
file:/workbench.desktop.main.js:4471:34
c.fire workbench.desktop.main.js:99:67
fire workbench.desktop.main.js:476:523
t.PersistentProtocol._receiveMessage workbench.desktop.main.js:481:629
file:/workbench.desktop.main.js:478:635
c.fire workbench.desktop.main.js:99:67
g.acceptChunk workbench.desktop.main.js:473:978
file:/workbench.desktop.main.js:473:330
Socket.t workbench.desktop.main.js:483:276
Socket.emit events.js:223:5
addChunk _stream_readable.js:309:12
readableAddChunk _stream_readable.js:290:11
Socket.Readable.push _stream_readable.js:224:10
Pipe.onStreamRead stream_base_commons.js:181:23
```

</details>

**Comment by nturinski** [comment]
Hi @montenegrojd 

Thanks for using Azure App Service.  Judging from the error, it seems like your project isn't opened in VS Code's workspace.  If you open the folder in VS Code prior to deploying, this should resolve your issue.   Please let me know if that doesn't work.

**Comment by montenegrojd** [comment]
It works. Thank you very much!

**Comment by nturinski** [comment]
Glad to help!
