### ISSUE TITLE
Update available SKUs

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#1862]
Update the list to limit the scope and make the selection simpler:

F1 Free - Recommended for development & testing
B1 Basic - Recommended for simple applications
P1v2 Premium V2 - Recommended for production applications

**Comment by ejizba** [comment]
Did it for basic create in https://github.com/microsoft/vscode-azureappservice/pull/1984. Do we want to do this for advanced create, too? I would vote to use those "recommended" skus at the top of the quick pick (in a group if we can do that), but still include all the rest below it for advanced create.

**Comment by fiveisprime** [comment]
Yeah and agreed. The "recommended for.." at the top, but include everything that we do today under those. 👍

**Comment by ejizba** [comment]
Darn - we can put them at the top, but can't do a "group" or "separator" until https://github.com/microsoft/vscode/issues/74967
