### ISSUE TITLE
Failed to deploy to azure

### ISSUE THREAD

**Issue by LiboniBinmak** [microsoft/vscode-azureappservice#1863]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:629:338022
rejected extension.bundle.js:629:337449
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
