### ISSUE TITLE
angular+azure appservice

### ISSUE THREAD

**Issue by TapanKumarBarik** [microsoft/vscode-azureappservice#1864]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:75486extension.js:243:75486
extension.js:243:73467extension.js:243:73467
extension.js:243:73087extension.js:243:73087
i.find extension.js:243:107619
extension.js:243:53535extension.js:243:53535
```

</details>

**Comment by ejizba** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
