### ISSUE TITLE
No workspace folder when deploying my asp.net core application to app service. Am i doing something wrong?

### ISSUE THREAD

**Issue by RichardJDay** [microsoft/vscode-azureappservice#1865]
Does this occur consistently?  yes. 
Repro steps:

1. Open a folder workspace in VS code that that was created in VS Pro as a project
2. Download the Azure App service extension.
3. Log in to Azure 
4. Deploy my folder/workspace to my App service 

Action: appService.Deploy
Error type: Error
Error Message: No workspace folder

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
A.$getTaskExecution workbench.desktop.main.js:4448:360
p._doInvokeHandler workbench.desktop.main.js:4475:707
p._invokeHandler workbench.desktop.main.js:4475:399
p._receiveRequest workbench.desktop.main.js:4474:59
p._receiveOneMessage workbench.desktop.main.js:4472:886
file:/workbench.desktop.main.js:4471:34
c.fire workbench.desktop.main.js:99:67
fire workbench.desktop.main.js:476:523
t.PersistentProtocol._receiveMessage workbench.desktop.main.js:481:629
file:/workbench.desktop.main.js:478:635
c.fire workbench.desktop.main.js:99:67
g.acceptChunk workbench.desktop.main.js:473:978
file:/workbench.desktop.main.js:473:330
Socket.t workbench.desktop.main.js:483:276
Socket.emit events.js:223:5
addChunk _stream_readable.js:309:12
readableAddChunk _stream_readable.js:290:11
Socket.Readable.push _stream_readable.js:224:10
Pipe.onStreamRead stream_base_commons.js:181:23
```

</details>

**Comment by nturinski** [comment]
Hi @RichardJDay Do you have your project opened in your current workspace before you deploy?  App Service relies on local settings in order to deploy so it requires that the project be opened in VS Code.
