### ISSUE TITLE
Unable to deploy to webapp through VScode in new subscription

### ISSUE THREAD

**Issue by Ansumole** [microsoft/vscode-azureappservice#1869]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/8f208c6c-af18-47fc-b10d-34de1e7c747a/resourceGroups/bth.lcl.rg/providers/Microsoft.Web/sites/bthlclwahelloapi/config/web?api-version=2019-08-01 failed, reason: connect ETIMEDOUT 40.78.196.33:443

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.

**Comment by Ansumole** [comment]
Hi,

Thanks for your email. I was able to dploy the app after few attempts.
This can be closed.

Regards,
Ansu

**Comment by nturinski** [comment]
Great! Thanks for the follow up!
