### ISSUE TITLE
The "Application Settings" node isn't alphabetically sorted after renaming one application setting

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1871]
**OS:** Win 10
**Build Version:** 20201127.1

**Repro Steps:**

1. Add a new application setting for a web App.
2. Rename this application setting and check if the "Application Settings" node is alphabetically sorted.

**Expect:**
The "Application Settings" node is alphabetically sorted after renaming one application setting.
![image](https://user-images.githubusercontent.com/62053665/100594833-23182400-3335-11eb-8c0e-7a357c8a214b.png)

**Actual:**
The "Application Settings" node isn't alphabetically sorted after renaming one application setting.
![image](https://user-images.githubusercontent.com/62053665/100594727-07ad1900-3335-11eb-88a3-43867075ff00.png)

**More Info:**
Refresh can fix this issue.

**Comment by ejizba** [comment]
https://github.com/microsoft/vscode-azurefunctions/issues/2525#issuecomment-740235836
