### ISSUE TITLE
Error view/edit invalid .json files 

### ISSUE THREAD

**Issue by pwm-sdc** [microsoft/vscode-azureappservice#1872]
Earlier we could edit and upload .json files even ones with invalid json content, now we have a error and can't view or correct the file.

The issue text

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.openFile
Error type: Error
Error Message: cannot open azureAppService:/F0000007-0001-0000-0000-000000000000.json?id%3D%2Fsubscriptions%2Fbcf41aba-5e2d-4ba2-94c9-7852e933b930%2FresourceGroups%2FRG-SDC000000-TEST-ASE-001%2Fproviders%2FMicrosoft.Web%2Fsites%2FSdc-Ape-systemtest-h0000t015ase001-001%2FFiles%2FResources%2FProducts%2FF0000007-0001-0000-0000-000000000000.json. Detail: Unable to read file 'azureAppService:/F0000007-0001-0000-0000-000000000000.json?id=/subscriptions/bcf41aba-5e2d-4ba2-94c9-7852e933b930/resourceGroups/RG-SDC000000-TEST-ASE-001/providers/Microsoft.Web/sites/Sdc-Ape-systemtest-h0000t015ase001-001/Files/Resources/Products/F0000007-0001-0000-0000-000000000000.json' (Error: Error "SyntaxError: Unexpected token ﻿ in JSON at position 0" occurred while parsing the response body - ﻿// format: productID-stepID-templateID-0000-000000000000
{
    "productID": "F0000007-0001-0000-0000-000000000000",
    "displayName": "LBS Credit (Consent)",
    "mediatorName": "FlowEngine",

    // BPMN process name
    "flowEngineProcessName": "DC.StaccStandaloneConsent",

    // BPMN process version (if specified, otherwise the latest version is used)
    // "flowEngineProcessVersion": 0,

    // add support for disabling the summary page
    "disableValidation": true,
    "templates": [
        {
            "templateID": "F0000007-0001-0001-0000-000000000000",
            "templateName": "AltinnConsent",
            "disableSummary": true,
            "eventReaders": [],
            "templateDefaults": [],
            "requestTransforms": []
        },
        {
            "templateID": "F0000007-0001-0002-0000-000000000000",
            "templateName": "ConsentCompleted",
            "disableSummary": true,
            "isCompleted": true,
            "eventReaders": [],
            "templateDefaults": [],
            "requestTransforms": []
        },
        {
            "templateID": "F0000007-0001-0003-0000-000000000000",
            "templateName": "ConsentRejected",
            "disableSummary": true,
            "isCompleted": true,
            "eventReaders": [],
            "templateDefaults": [],
            "requestTransforms": []
        }

    ]
}
.)

Version: 0.20.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6687:388
```

</details>
 was copied to the clipboard.  Please paste it into this window.

**Comment by ejizba** [comment]
Fixed in https://github.com/microsoft/vscode-azuretools/pull/918
