### ISSUE TITLE
[Suggestion] It would be better if add a "Open" button in the notification to open the folder in the current window

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1873]
**OS:** Win 10
**Build Version:** 20201127.1

**Repro Steps:**

1. Make sure no project open in VS Code.
2. Click "Deploy to Web App..." button -> Select a project folder to deploy -> Check the notification.

**Actual:**
There is only "Open in new window" button in the notification.
![image](https://user-images.githubusercontent.com/62053665/100693139-3378df00-33c7-11eb-80fa-9f3d3449faef.png)

**Suggestion:**
It would be better if add a "Open" button in the notification to open the folder in the current window.

**Comment by ejizba** [comment]
We like the simplicity of one button and think "open in new window" should satisfy most users.
