### ISSUE TITLE
Deployment to Azure app service fails

### ISSUE THREAD

**Issue by pshroti** [microsoft/vscode-azureappservice#1877]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: EPIPE
Error Message: request to https://gileaditdev.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: write EPIPE

Version: 0.20.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
errorOrDestroy destroy.js:108:12
onwriteError _stream_writable.js:456:5
onwrite _stream_writable.js:477:5
destroy.js:50:7destroy.js:50:7
TLSSocket.Socket._destroy net.js:669:5
TLSSocket.destroy destroy.js:38:8
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:88:12
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
