### ISSUE TITLE
I received following error in basic angular app deployment

### ISSUE THREAD

**Issue by msspdev** [microsoft/vscode-azureappservice#1878]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ETIMEDOUT
Error Message: request to https://pmsdemowebapp.scm.azurewebsites.net/deployments/1cd6bf5a3d6d4b2f85c2468c5ba0231b failed, reason: connect ETIMEDOUT 20.49.104.8:443

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:166:16389
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Does this happen consistently? Sometimes trying another deploy will fix these types of errors. If that doesn't resolve it, please leave detailed repro steps.
