### ISSUE TITLE
Deployment problems

### ISSUE THREAD

**Issue by EmmanuellaD** [microsoft/vscode-azureappservice#1879]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://restapi2020.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.20.0
OS: linux
OS Release: 4.4.0-18362-Microsoft
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
ClientRequest.EventEmitter.emit domain.js:475:20
TLSSocket.socketOnEnd _http_client.js:440:9
TLSSocket.emit events.js:228:7
TLSSocket.EventEmitter.emit domain.js:475:20
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Does this happen consistently?  Sometimes trying another deploy will fix these types of errors.  If that doesn't resolve it, please leave detailed repro steps.
