### ISSUE TITLE
Note: tryappservice is deprecated

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-azureappservice#1880]
I deprecated https://code.visualstudio.com/tryappservice/ because it is outdated.
It now redirects to https://code.visualstudio.com/docs/azure/deployment.

The link in the README that says "try Azure for free" might need updating

**Comment by nturinski** [comment]
Does this mean Try App Service is completely deprecated?  These two webpages didn't convey the same information.

**Comment by rzhao271** [comment]
Yep, completely deprecated.
I think @fiveisprime suggested just removing any links that point to that URL.

**Comment by ejizba** [comment]
We're still confused. Are you saying the _documentation_ is completely deprecated? Or the feature itself is completely deprecated? If it's just the documentation - can you explain what was outdated about it?

**Comment by rzhao271** [comment]
The feature itself is completely deprecated. There's no owner for it and there were many security vulnerabilities

**Comment by alexweininger** [comment]
😭

**Comment by nturinski** [comment]
😭🌹

**Comment by ejizba** [comment]
![salute](https://media3.giphy.com/media/fnKd6rCHaZoGdzLjjA/giphy.gif)
