### ISSUE TITLE
Azure Remote Debugging for .NET 5 on Linux

### ISSUE THREAD

**Issue by sanzor** [microsoft/vscode-azureappservice#1883]
I am trying to connect to a `.NET 5 web api` deployed as an `appservice` in Azure and i can not perform remote debugging.
When trying to attach from vscode i get this error:

`Azure Remote Debugging is currently only supported for Node.js apps on Linux.`

Is there any list of current state for Remote Debugging (which frameworks and on which platforms ) it is supported ?

**Comment by nturinski** [comment]
Hi @sanzor

Here's a little blurb in our wiki about what's supported https://github.com/microsoft/vscode-azureappservice/wiki/Remote-Debugging#supported-runtimes

But to save you some time, any Node.js above 8.11 and Python 3.6 are supported.  If you want to use Python remote debugging, you'll have to enable the feature flag `enablePythonRemoteDebugging` in your vscode settings for it
