### ISSUE TITLE
Web app failed

### ISSUE THREAD

**Issue by gmbhatti** [microsoft/vscode-azureappservice#1885]
Does this occur consistently? 
Repro steps:

1.
2.

Action: postCreateWebApp
Error type: ECONNRESET
Error Message: request to https://starmkg.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:166:16389
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Sometimes deploying immediately after a web app creation can cause issues.  If you try to deploy to it again after some time, it may start working.  If that doesn't resolve your issue, could you please leave detailed repro steps?
