### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by Swapna076** [microsoft/vscode-azureappservice#1890]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://wba-uiapp.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketOnEnd _http_client.js:440:9
TLSSocket.emit events.js:228:7
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
