### ISSUE TITLE
service is ass

### ISSUE THREAD

**Issue by ziplined** [microsoft/vscode-azureappservice#1895]
https://my-life.is-a.fail/L5SDoz

**Comment by jinglouMSFT** [comment]
I am sorry to hear that you had issues with Azure services.  However, this repro is for the AppService development tool. You can try to configure Azure Service Health to notify you about Azure service incidents and planned maintenance so you can take action to mitigate downtime. Configure customizable cloud alerts and use your personalized dashboard to analyze health issues, monitor the impact to your cloud resources, get guidance and support, and share details and updates.  https://azure.microsoft.com/en-us/features/service-health/#product-overview
Here is a link to all different options of Microsoft Azure Service support that might be helpful to you: https://azure.microsoft.com/en-us/support/faq/
