### ISSUE TITLE
Application Settings: WEBSITE_HOSTNAME is not allowed, why?

### ISSUE THREAD

**Issue by jhuang234** [microsoft/vscode-azureappservice#1897]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.appSettings.Add
Error type: BadRequest
Error Message: The data is not valid (Invalid or not allowed environment key name: WEBSITE_HOSTNAME).

Version: 0.20.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
App Service has a certain number of pre-defined environment variables that you can't overwrite, but that you can use in your app if you want. This probably isn't the most up-to-date doc, but it's the best I could find: https://github.com/projectkudu/kudu/wiki/Azure-runtime-environment
