### ISSUE TITLE
while deploying nodejs sequalize api to azure

### ISSUE THREAD

**Issue by SUNIL1004** [microsoft/vscode-azureappservice#1899]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/faa4cd95-0fa5-4606-ac79-f052d2505346/resourceGroups/onlinetest-01/providers/Microsoft.Web/sites/vernishafoundation-backend/config/web?api-version=2019-08-01 failed, reason: connect ETIMEDOUT 20.38.128.32:443

Version: 0.20.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.52.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
