### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by mikeschraven** [microsoft/vscode-azureappservice#1900]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Restart
Error type: ECONNRESET
Error Message: request to https://management.azure.com/subscriptions/2febd4a0-1ac6-4466-85df-16246006a5e7/providers/Microsoft.Web/sites?api-version=2019-08-01 failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.21277
Product: Visual Studio Code
Product Version: 1.52.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
