### ISSUE TITLE
Unable to deploy to Azure from VSC

### ISSUE THREAD

**Issue by mainhire** [microsoft/vscode-azureappservice#1903]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/c840b027-4a10-4c79-8473-ca47f200fdad/providers/Microsoft.Web/sites?api-version=2019-08-01 failed, reason: read ETIMEDOUT

Version: 0.20.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:166:16389
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
