### ISSUE TITLE
Server error when trying to depoly

### ISSUE THREAD

**Issue by mainhire** [microsoft/vscode-azureappservice#1904]
Does this occur consistently? 
Repro steps:

1.
2.

Action: postCreateWebApp
Error type: 502
Error Message: Server Error
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

Version: 0.20.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Could you please provide detailed repro steps?  Also are you working behind a corporate proxy of some sorts?
