### ISSUE TITLE
Angular 8 app hosting issue on azure

### ISSUE THREAD

**Issue by Moumit** [microsoft/vscode-azureappservice#1907]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 404
Error Message: Deployment '4b96d9de5c0d466492f772cef55800d5' not found.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
