### ISSUE TITLE
Change default sku to Basic for Linux

### ISSUE THREAD

**Issue by nigarfin** [microsoft/vscode-azureappservice#1908]
**Specific to Linux Apps Only**

We've seen issues related to the Linux Free SKU in Azure App Service wrt to deployment successes and general performance issues of their applications. To alleviate the impact of those issues on users, we believe it will be a better experience to default customers on Linux to the Basic (B1) SKU . Since the default is a paid SKU, I also suggest we output into the console that the SKU is paid, and link customers to the pricing page: https://azure.microsoft.com/en-us/pricing/details/app-service/linux/ and make them aware of the free sku.

One potential set of outputs: 
- The default SKU selected is Basic (B1). This is a paid App Service plan with a low monthly cost. For details on pricing and performance, please see the Azure pricing page: https://azure.microsoft.com/en-us/pricing/details/app-service/linux/. 
- You may also migrate the App Service plan to the free offering, or more performant offering in the Azure Portal.

_Note: The portal and CLI default to the Premium SKU._

**Comment by ejizba** [comment]
Closing in favor of https://github.com/microsoft/vscode-azureappservice/issues/1862
