### ISSUE TITLE
without a clue

### ISSUE THREAD

**Issue by dub-scratch** [microsoft/vscode-azureappservice#1910]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Start
Error type: Error
Error Message: Entry not found in cache.

Version: 0.16.5
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:176842
extension.js:229:171457
extension.js:229:43512
extension.js:229:41505
extension.js:229:41127
i.module.exports.i.find extension.js:229:75620
module.exports.find.init.then extension.js:229:22917
```

</details>

**Comment by nturinski** [comment]
As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
