### ISSUE TITLE
Cannot deploy from VS Code

### ISSUE THREAD

**Issue by jr3** [microsoft/vscode-azureappservice#1912]
Does this occur consistently? Yes
Repro steps:

select "Deploy to Web App..." from VS Code "Azure: App Service" plugin
1.
2.

Action: appService.Deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: request to https://cutoffanalyzertest3.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: unable to get local issuer certificate

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Could you please provide more detailed repro steps?  We won't be able repro this error with that step.  Could you answer the following questions?

- Are you working behind a proxy? 
- What language of project are you deploying?  
- What OS is your app service resource?  
- What app service plan are you using?

According to this https://docs.thousandeyes.com/product-documentation/tests/http-server-test-fails-with-ssl-error#scenario-1-web-server-failing-to-send-intermediate-certificates

> The most common cause of the "unable to get local issuer certificate" error is a misconfigured web server that fails to send all of the intermediate certificates with the server certificate, when the client and server perform the SSL/TLS negotiation.

They offer solutions in there that might be able to point you in the right direction, assuming that the error isn't coming directly from the extension.

**Comment by jr3** [comment]
Hi,

Thanks for your answer.

My problem was solved by not using VPN when deploying to Azure.

br,
Juha

________________________________

**Comment by nturinski** [comment]
Thanks for letting us know that you resolved it. I'll go ahead and close this issue.
