### ISSUE TITLE
Error apps 

### ISSUE THREAD

**Issue by joelkalonji** [microsoft/vscode-azureappservice#1914]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: Unauthorized
Error Message: This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
The error seems to indicate that you already have 1 free app service plan in that region.  You could create a new app service plan with `Create Web App (Advanced)`.  You will be able to select the location and SKU of your app service plan.

If you do not want to pay (as anything other than free will incur costs), you could try deleting your existing app service plan and creating a new one.
