### ISSUE TITLE
さ

### ISSUE THREAD

**Issue by saaaaak** [microsoft/vscode-azureappservice#1916]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "sampleapp2021" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: ja

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:696:18541
extension.bundle.js:696:16398extension.bundle.js:696:16398
o extension.bundle.js:696:16084
extension.bundle.js:696:18255extension.bundle.js:696:18255
t.ExtHostProgress._withProgress extensionHostProcess.js:644:622
t.ExtHostProgress.withProgress extensionHostProcess.js:644:376
Object.withProgress extensionHostProcess.js:1028:52
Object.<anonymous> extension.bundle.js:696:18187
fulfilled extension.bundle.js:696:16152
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Based off your error, it seems like you are deploying via GitHub.  In order to deploy, you need to create a new commit and push it to the GitHub repo remote that the web app is connected to.

Please let me know if this resolves your issue.
