### ISSUE TITLE
Unable to deploy Azure app service deployment slot from VSCode using extension

### ISSUE THREAD

**Issue by dp80** [microsoft/vscode-azureappservice#1918]
Does this occur consistently? No
Repro steps:
1.  select deploy to slot from vscode Azure app service extention
2. Select app service, deployment slot, then jar file

**ASE and ASP are on private network

Action: appService.DeploySlot
Error type: Error
Error Message: Cannot use simple-git on a directory that does not exist.

Version: 0.20.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:629:338022
rejected extension.bundle.js:629:337449
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Sorry for the long delay. Is your slot configured to use "Local Git"? If so, you may want to use "Configure Deployment Source" to convert it back to the default "None". The error seems to be related to git, and I'm not sure deploy a jar file works in that scenario.
