### ISSUE TITLE
not able to deploy angular app to app service azure

### ISSUE THREAD

**Issue by SUNIL1004** [microsoft/vscode-azureappservice#1919]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: REQUEST_SEND_ERROR
Error Message: request to https://vernishafoundation.scm.azurewebsites.net/deployments failed, reason: getaddrinfo ENOTFOUND vernishafoundation.scm.azurewebsites.net

Version: 0.20.0
OS: darwin
OS Release: 20.2.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
NodeFetchHttpClient.<anonymous> extension.bundle.js:860:823982
step extension.bundle.js:16:1925
Object.throw extension.bundle.js:16:2030
rejected extension.bundle.js:16:755
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by SUNIL1004** [comment]
found this whiledeploying

**Comment by nturinski** [comment]
Please provide detailed repro steps.
