### ISSUE TITLE
Investigate and see if it is possible to get column number when setting a logpoint

### ISSUE THREAD

**Issue by changsi-an** [microsoft/vscode-azureappservice#192]
Pertinent code:

https://github.com/Microsoft/vscode-azureappservice/blob/bc69cfbeade8a095413c212d8e1a372c1d99e9a2/src/diagnostics/LogPointsManager.ts#L144

See if possible to retrieve the column number from the user interaction point, and send it over to the agent when setting a logpoint

**Comment by EricJizbaMSFT** [comment]
Logpoints was removed from this repo https://github.com/microsoft/vscode-azureappservice/pull/1101
