### ISSUE TITLE
Error when deploying to Azure app-service

### ISSUE THREAD

**Issue by teodor-k96** [microsoft/vscode-azureappservice#1920]
Does this occur consistently? No
Repro steps:

1. Build the app
2. Start deploying

Action: appService.Deploy
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token S in JSON at position 0" occurred while parsing the response body - Service Unavailable.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
errorHandler extension.bundle.js:46:494892
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Sorry for the late response. If you're still having problems, try looking at these troubleshooting tips: https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503
