### ISSUE TITLE
Deploying an app service

### ISSUE THREAD

**Issue by hughle68** [microsoft/vscode-azureappservice#1924]
Does this occur consistently? 
Repro steps:

1.
2.

Action: postCreateWebApp
Error type: 503
Error Message: The service is unavailable.

Version: 0.20.0
OS: linux
OS Release: 4.4.0-189-generic
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
