### ISSUE TITLE
Opening "hostingstart.html

### ISSUE THREAD

**Issue by ItRefresh** [microsoft/vscode-azureappservice#1925]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.openFile
Error type: Error
Error Message: cannot open azureAppService:/hostingstart.html?id%3D%2Fsubscriptions%2Fea61b910-f5ac-4a97-954d-c96c562e1d10%2FresourceGroups%2Fappsvc_linux_centralus%2Fproviders%2FMicrosoft.Web%2Fsites%2FAplicativoboleto%2FFiles%2Fhostingstart.html. Detail: Unable to read file 'azureAppService:/hostingstart.html?id=/subscriptions/ea61b910-f5ac-4a97-954d-c96c562e1d10/resourceGroups/appsvc_linux_centralus/providers/Microsoft.Web/sites/Aplicativoboleto/Files/hostingstart.html' (Error: Entry not found in cache.)

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6800:388
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
