### ISSUE TITLE
Cannot specify typescript source map file location when remote debugging

### ISSUE THREAD

**Issue by jtesolin** [microsoft/vscode-azureappservice#1926]
I am trying to remote debug my app service with the Azure App Service extension, but it seems like it only looks in the workspace root for the typescript source map files.  I tried to add several types of configuration to the launch.json to no avail.  The scaffolding for my project places the source maps into a subfolder that is generated at build time.  The only workaround I have come up with at this point is to build my project, open a new VS Code instance with the subfolder as root, then debug from there.  This is not a great experience, as the actual typescript files are in an adjacent folder to the generated one, making browsing them to set breakpoints painful.  Also, the build process deletes the generated folder prior to regenerating it, so having an instance of VS Code set to the generated folder as root prevents it from being deleted and breaks the build until i close the instance.  

I am looking for some way to tell the extension where these files are without having them in the root folder.

**Comment by nturinski** [comment]
Hi @jtesolin

This documentation may be able to help you specify where your source map files are located: https://code.visualstudio.com/docs/typescript/typescript-debugging#_javascript-source-map-support

Basically, it seems like you can have a `tsconfig.json` file that will automatically set your `launch.json` for you.  But if you want to set it manually, it seems like you should be able to set the property `outFiles` to direct the debugger to your source map files.

**Comment by jtesolin** [comment]
I followed the instructions on that page and set the outFiles in launch.json to "outFiles": ["${workspaceFolder}/dist/**/*.js"].  I do have a tsconfig.json, and the outfiles property is set to the subfolder "compilerOptions": { "rootDir": "./src", "outDir": "./dist" }

I'm getting an error for each map file, like this:
Could not read source map for file:///home/site/wwwroot/index.js: ENOENT: no such file or directory, open 'd:\jtesolin\git\project-name\azure-web-apps\packages\auth-bot\index.js.map'

auth-bot is my workspace folder.  When I run tsc in the vs code terminal (in the workspace folder), the js and map files are created in the dist folder.

**Comment by nturinski** [comment]
Have you seen this documentation before? https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging

What's your `launch.json` look like? It seems like you might be able to set your local/remote roots here, so maybe you can change the remote root to be wherever the dist folder is being generated?
