### ISSUE TITLE
Clear the logpoints cache upon debug session close.

### ISSUE THREAD

**Issue by changsi-an** [microsoft/vscode-azureappservice#193]
Pertinent code

https://github.com/Microsoft/vscode-azureappservice/blob/bc69cfbeade8a095413c212d8e1a372c1d99e9a2/src/diagnostics/LogPointsManager.ts#L189

This is triggered when extension tears down. See whether we need to do anything (close existing connections etc)

**Comment by EricJizbaMSFT** [comment]
Logpoints was removed from this repo https://github.com/microsoft/vscode-azureappservice/pull/1101
