### ISSUE TITLE
visual studio code 

### ISSUE THREAD

**Issue by a-darwinhu** [microsoft/vscode-azureappservice#1930]
Does this occur consistently? 
Repro steps:

1.
2.

Action: writeFile
Error type: Error
Error Message: ETag does not represent the latest state of the file "ProfileSetting.php". Download the file from Azure to get the latest version.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
AppServiceFileSystem.<anonymous> extension.bundle.js:860:159904
rejected extension.bundle.js:860:158239
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
