### ISSUE TITLE
Deploy angular app

### ISSUE THREAD

**Issue by lcarrionr** [microsoft/vscode-azureappservice#1931]
Does this occur consistently? 
Repro steps:

1.When I tried to deploy a dist folder for angular app
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.20.0
OS: win32
OS Release: 10.0.21292
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Does this happen consistently?  A 500 error is typically intermittent so hopefully redeploying will fix this for you.
