### ISSUE TITLE
ECONNRESET during "Deploy to Web App"

### ISSUE THREAD

**Issue by spearsonwork** [microsoft/vscode-azureappservice#1932]
Does this occur consistently? Yes
Have redeployed several times in summer last year but now getting error message.

Repro steps:
1. Right click on App Service and choose "Deploy to Web App...."
2. Deployment fails with error message.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://xxxxxxxxxxxxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: socket hang up

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketOnEnd _http_client.js:440:9
TLSSocket.emit events.js:228:7
endReadableNT _stream_readable.js:1185:12
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by ejizba** [comment]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/2390
