### ISSUE TITLE
Angular deployment to azure failed visual studio code

### ISSUE THREAD

**Issue by ravindrapn** [microsoft/vscode-azureappservice#1933]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: CERT_HAS_EXPIRED
Error Message: request to https://xxxxxx.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: certificate has expired

Version: 0.20.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by ejizba** [comment]
Please add repro steps
