### ISSUE TITLE
Failed to load azure service in vs code

### ISSUE THREAD

**Issue by LiboniBinmak** [microsoft/vscode-azureappservice#1936]
Does this occur consistently? 
Repro steps:

1.No
2.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:75539extension.js:243:75539
extension.js:243:74397extension.js:243:74397
B._callback extension.js:16:228256
t._callback.t.callback.t.callback extension.js:202:5500
B.emit events.js:223:5
B.onRequestError extension.js:202:14581
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by ejizba** [comment]
As a workaround you could try reloading your window. This is being tracked upstream here: microsoft/vscode-azure-account#53
