### ISSUE TITLE
Re-enable error report when making Kudu calls

### ISSUE THREAD

**Issue by changsi-an** [microsoft/vscode-azureappservice#194]
Pertinent code

https://github.com/Microsoft/vscode-azureappservice/blob/bc69cfbeade8a095413c212d8e1a372c1d99e9a2/src/diagnostics/logPointsClient.ts#L50

And

https://github.com/Microsoft/vscode-azureappservice/blob/bc69cfbeade8a095413c212d8e1a372c1d99e9a2/src/diagnostics/structs/CommandRunResult.ts#L17

The error logging code was disabled. Because `util.getOutputChannel()` is not available from a debug adapter process. Some refactor need to be done to re-enable error reporting.

**Comment by EricJizbaMSFT** [comment]
Logpoints was removed from this repo https://github.com/microsoft/vscode-azureappservice/pull/1101
