### ISSUE TITLE
not able to deploy

### ISSUE THREAD

**Issue by SUNIL1004** [microsoft/vscode-azureappservice#1942]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.20.0
OS: darwin
OS Release: 20.2.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:629:338022
rejected extension.bundle.js:629:337449
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Did you configure your web app to use "Local Git" by chance? If so, you have to make sure you deploy a git repository. You can right click on the web app and do "Configure Deployment Source" to double check and/or change it back to "None". If that doesn't help, please add detailed repro steps
