### ISSUE TITLE
Azure App Service Extension: Error Message: Entry not found in cache.

### ISSUE THREAD

**Issue by RyanHill-MSFT** [microsoft/vscode-azureappservice#1943]
Does this occur consistently? No
Repro steps:

1. Create an app service inside the extension
2. Delete the app service from the portal
3. Refresh the extension

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:76673extension.js:243:76673
extension.js:243:74654extension.js:243:74654
extension.js:243:74274extension.js:243:74274
i.find extension.js:243:108806
extension.js:243:53535extension.js:243:53535
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
This is usually caused by another bug being tracked upstream here: microsoft/vscode-azure-account#53

As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.
