### ISSUE TITLE
The webpage is not auto-refresh after swapping slots for a Linux Python web app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#1944]
**OS:** Win 10
**Build Version:** 20210127.1

**Repro Steps:**
1. Create an advanced Linux Python web app.
2. Create a Deployment Slot "slot1" for the above web app and select "Don't clone...".
3. Deploy the project to the above slot -> Browse website -> "Hello World" shows in the webpage.
4. Create a Deployment Slot "slot2" for the above web app again.
5. Swap "slot1" with "slot2" -> Browse website.
6. Check whether the webpage shows well or not.

**Expect:**
The webpage shows well.

**Actual:**
The webpage is not auto-refresh after swapping slots.
![image](https://user-images.githubusercontent.com/57662131/106098695-6eec1b80-6174-11eb-9af3-369a8ee966a5.png)

**More Info:**
1. This issue also reproduces when swapping the slot with the production.
2. This issue also reproduces for the Linux .NET core web app.
3. This issue doesn't reproduce for Windows Python web app.
4. This issue doesn't reproduce for node web app.
5. This issue is fixed after restarting VS Code or refreshing the webpage.
6. This issue is not fixed after refreshing the web app.

**Comment by ejizba** [comment]
> This issue is fixed after restarting VS Code or refreshing the webpage.

If that is the case, then I will close as "wont-fix". We don't have any way to refresh the browser automatically for them. In addition, "swapping a slot" sometimes just takes a little bit of time (which I agree is not great, but the Azure team controls that, not us) so waiting to a little bit for the refresh to work is also fine
