### ISSUE TITLE
New issue found

### ISSUE THREAD

**Issue by forozco** [microsoft/vscode-azureappservice#1946]
Does this occur consistently? 
Repro steps:

1.
2.

Action: writeFile
Error type: Error
Error Message: ETag does not represent the latest state of the file "App.vue". Download the file from Azure to get the latest version.

Version: 0.20.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
AppServiceFileSystem.<anonymous> extension.bundle.js:860:159904
rejected extension.bundle.js:860:158239
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
