### ISSUE TITLE
"resourceGroupName" with value "первая" should satisfy the constraint "Pattern": /^[-\w\._\(\)]+[^\.]$/.

### ISSUE THREAD

**Issue by sergeychugun** [microsoft/vscode-azureappservice#1948]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "resourceGroupName" with value "первая" should satisfy the constraint "Pattern": /^[-\w\._\(\)]+[^\.]$/.

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: ru

<details>
<summary>Call Stack</summary>

```
failValidation extension.bundle.js:46:77998
Serializer.validateConstraints extension.bundle.js:46:78855
Serializer.serialize extension.bundle.js:46:79390
getOperationArgumentValueFromParameterPath extension.bundle.js:52:977128
getOperationArgumentValueFromParameter extension.bundle.js:52:977378
WebSiteManagementClient.ServiceClient.sendOperationRequest extension.bundle.js:52:973140
WebApps.getConfiguration extension.bundle.js:52:688663
SiteClient.<anonymous> extension.bundle.js:419:146525
fulfilled extension.bundle.js:419:143272
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
I don't think our API can handle these special characters.  Are you able to make this resource group in the portal?
