### ISSUE TITLE
Can't create a web service in Visual studio code

### ISSUE THREAD

**Issue by hanhsia** [microsoft/vscode-azureappservice#1953]
Does this occur consistently? Yes
Repro steps:

1. Signin my azure account in VS Code App service extension
2. Create a new web service
3. Input Application name 
4. Input runtime: Node 12 LTS
5. following error message prompt 

Action: appService.CreateWebApp
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: location

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:46:90222
Object.nonNullProp extension.bundle.js:46:90371
Object.<anonymous> extension.bundle.js:860:120693
fulfilled extension.bundle.js:860:119836
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Hi @hanhsia 

When we do a basic create, we automatically choose Central US for the location.  If you do an advanced create, that should be able to resolve your problem.

The error itself is a bit puzzling though.  Do you happen to have the AZ Cli installed on your system as well?
