### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by rmftechnologiesllc** [microsoft/vscode-azureappservice#1967]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.ViewProperties
Error type: REQUEST_SEND_ERROR
Error Message: request to https://management.azure.com/subscriptions/b9f05098-ee2a-48ae-a3d0-f8d34fc299b3/resourceGroups/flepru/providers/Microsoft.Web/sites/flepru/config/web?api-version=2019-08-01 failed, reason: getaddrinfo ENOTFOUND management.azure.com

Version: 0.20.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.53.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
NodeFetchHttpClient.<anonymous> extension.bundle.js:860:823982
step extension.bundle.js:16:1925
Object.throw extension.bundle.js:16:2030
rejected extension.bundle.js:16:755
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
