### ISSUE TITLE
updating trigger in index.js

### ISSUE THREAD

**Issue by ihnrodrigueze** [microsoft/vscode-azureappservice#1972]
Does this occur consistently?  Yes
Repro steps:

1.  updating trigger for healthbot
2.  

Action: writeFile
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: etag

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.nonNullValue extension.bundle.js:46:90222
AppServiceFileSystem.<anonymous> extension.bundle.js:860:159517
extension.bundle.js:860:158424extension.bundle.js:860:158424
o extension.bundle.js:860:158110
AppServiceFileSystem.writeFileImpl extension.bundle.js:860:159031
AppServiceFileSystem.<anonymous> extension.bundle.js:629:29830
fulfilled extension.bundle.js:629:28258
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by ejizba** [comment]
I'm unable to reproduce with just those steps. Can you add more detail, please?
