### ISSUE TITLE
VS Code React App Deploy

### ISSUE THREAD

**Issue by sametgunduz** [microsoft/vscode-azureappservice#1973]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.20.0
OS: darwin
OS Release: 20.3.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Dupe of https://github.com/microsoft/vscode-azureappservice/issues/1589
