### ISSUE TITLE
k

### ISSUE THREAD

**Issue by antonvyshemirskii** [microsoft/vscode-azureappservice#1975]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.CreateWebApp
Error type: Unauthorized
Error Message: This subscription has reached the limit of 1 Free Linux app service plan(s) it can create in this region. Please choose a different sku or region.

Version: 0.20.0
OS: linux
OS Release: 5.4.0-54-generic
Product: Visual Studio Code
Product Version: 1.52.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:46:66146
extension.bundle.js:46:496611
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by ejizba** [comment]
Please try using your existing free plan or deleting that one to create a new one. Otherwise, please add detailed repro steps here
