### ISSUE TITLE
Azzure publicação

### ISSUE THREAD

**Issue by alexandreoibh** [microsoft/vscode-azureappservice#1977]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Refresh
Error type: Error
Error Message: Entry not found in cache.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.53.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:76721extension.js:243:76721
extension.js:243:74702extension.js:243:74702
extension.js:243:74322extension.js:243:74322
i.find extension.js:243:108854
extension.js:243:53535extension.js:243:53535
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by alexandreoibh** [comment]
Azzure publicação

**Comment by alexandreoibh** [comment]
Azzure publicação

**Comment by ejizba** [comment]
As a workaround you could try reloading your window. This is being tracked upstream here: microsoft/vscode-azure-account#53
