### ISSUE TITLE
Failed to deploy to Azure

### ISSUE THREAD

**Issue by slishnevsky** [microsoft/vscode-azureappservice#1980]
Does this occur consistently? Yes
Repro steps:

1. Install .NET Core 5.0
2. Create an app, like: dotnet new angular -o Homepage
3. Try to deploy to Azure using Azure App Services VSCode extension

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\Slava\Projects\Homepage\bin\Release\netcoreapp5.0\publish

Version: 0.20.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:696:24367
fulfilled extension.bundle.js:696:23861
```

</details>

When app is created, dotnet core CLI sets:

`<TargetFramework>net5.0</TargetFramework>`

**This generates the above error.**

If I change it manually to: `<TargetFramework>netcoreapp5.0</TargetFramework>`, then delete bin and obj folders, then the deployment works.

But it should work with the original `<TargetFramework>net5.0</TargetFramework>`

Looks like the extension is still using "netcoreapp5.0" format

**Comment by ejizba** [comment]
@slishnevsky I would recommended doing a search in the `.vscode` folder at the root of your workspace for `netcoreapp5.0` and replace all occurrences with `net5.0`. There's some settings and tasks that control the path we deploy

**Comment by slishnevsky** [comment]
> @slishnevsky I would recommended doing a search in the `.vscode` folder at the root of your workspace for `netcoreapp5.0` and replace all occurrences with `net5.0`. There's some settings and tasks that control the path we deploy

Yes, you are right :) In the vscode/settings.json: `"appService.deploySubpath": "bin/Release/netcoreapp5.0/publish"`

should be changed to: `"appService.deploySubpath": "bin/Release/net5.0/publish"`

That solves the problem (looks like it was left from the preview version).

**Comment by slishnevsky** [comment]
Resolved, thank you.
