### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by eyerene14** [microsoft/vscode-azureappservice#1981]
- Issue Type: `Bug`
- Extension Name: `vscode-azureappservice`
- Extension Version: `0.20.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by nturinski** [comment]
I believe that there was some data we needed to be pasted.  Unfortunately I can't help you with this issue because the issue is not described and there are no repro steps.  Please provide those so I can assist you!
