### ISSUE TITLE
unable to deploy via VSCode

### ISSUE THREAD

**Issue by ybprincipal** [microsoft/vscode-azureappservice#1988]
Does this occur consistently?  YES
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to https://summer01uat.scm.azurewebsites.net/api/zipdeploy?isAsync=true&author=VS%20Code failed, reason: read ECONNRESET

Version: 0.20.0
OS: win32
OS Release: 10.0.16299
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps

**Comment by vasukushwah** [comment]
Facing similar issue.
![image](https://user-images.githubusercontent.com/42324889/109759545-2ca27800-7c13-11eb-8500-fc8424fa418a.png)

**Comment by nturinski** [comment]
Are you using WSL or Codespaces by chance?

**Comment by vasukushwah** [comment]
No

**Comment by nturinski** [comment]
Could you please post your deployment logs?  They should be in the output channel after a deployment.

**Comment by vasukushwah** [comment]
![image](https://user-images.githubusercontent.com/42324889/110196040-d5e1ac00-7e67-11eb-8c17-d246bf534c3c.png)

**Comment by nturinski** [comment]
Okay, thank you.  We should releasing a new App Service this week that may hopefully resolve your issue.  It may be an issue involving the archiver that we were using previously.

**Comment by vasukushwah** [comment]
Thank you, Its working now
