### ISSUE TITLE
Azure File won't update: ETag does not represent the latest state of the file "app.py". 

### ISSUE THREAD

**Issue by Wozziwozziwozzi** [microsoft/vscode-azureappservice#1989]
Does this occur consistently? 
Repro steps:

1. I edit a file in Visual Studio Code
2. I save it
3. I click on upload
4. The error in the title appears:

ETag does not represent the latest state of the file "app.py". Download the file from Azure to get the latest version.
Source: Azure App Service (Extension)

5. Code File in Azure won't update

Action: writeFile
Error type: Error
Error Message: ETag does not represent the latest state of the file "app.py". Download the file from Azure to get the latest version.

Version: 0.20.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
AppServiceFileSystem.<anonymous> extension.bundle.js:860:159904
rejected extension.bundle.js:860:158239
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by ejizba** [comment]
Sorry for the late reply. Can you confirm if you had the latest version of the file, as the error says? Does it work if you get the file again and retry?
