### ISSUE TITLE
There is an error in the Terminal after executing "SSH into Web App" for a Python Linux web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1993]
**OS:** All
**Build Version:** 20210302.12

**Repro Steps:**

1. Create a Python Linux web app -> Deploy a Python project.
2. Right click the Linux web app -> Select "SSH into Web App".
3. Check the Terminal.

Expect:
There is no error in the Terminal.

**Actual:**
There is an error in the Terminal.
![image](https://user-images.githubusercontent.com/62053665/109789236-1ca68a80-7c4b-11eb-8063-54bd2db34151.png)

**More Info:**
This issue doesn't reproduce for Node.js/C# Linux web app.

**Comment by ejizba** [comment]
I can repro this on v0.20.0, so it's _not_ a regression related to our upcoming release. Also, the error doesn't seem to affect much. Ssh still started and was working for me

**Comment by ejizba** [comment]
I would guess this is the Python extension trying to activate some random venv and it's not working. We could see if it repros without the Python extension installed
