### ISSUE TITLE
The uploaded setting value is inconsistent with the setting value in the file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#1999]
**OS:** All
**Build Version:** 20210305.9

**Repro Steps:**

1. Expand a web app -> Right click the "Application Settings" node -> Select "Upload Local Settings..." -> Select a file such as: 
    ![image](https://user-images.githubusercontent.com/62053665/110444161-a5b03c80-80f7-11eb-92a6-6cf779b9ca66.png)
2. Expand the "Application Settings" node -> Check whether the uploaded setting value is correct.

**Expect:**
The uploaded setting value is correct.

**Actual:**
The uploaded setting value is incorrect.
![image](https://user-images.githubusercontent.com/62053665/110444321-d5f7db00-80f7-11eb-903e-233f491552a0.png)

**More Info:**
Right click a setting and edit it with `"123",` -> The setting value is changed to `"123",`.
![image](https://user-images.githubusercontent.com/62053665/110444498-0f304b00-80f8-11eb-9687-8a931d25d526.png)

**Comment by nturinski** [comment]
The behavior is the same in the portal.  We aren't parsing the `.env` file so I suspect that this is by-design.  `"` and `,` seem to be valid characters available for application settings.

**Comment by v-mengwe** [comment]
I got it. The setting value is changed to **"123",**  when creating/editing a setting value with **"123",**  in Portal or VS Code, but the setting value is changed to **123",**(the left double quote disappears)  when uploading a setting value with **"123",**  in VS Code.
![image](https://user-images.githubusercontent.com/62053665/110729703-22f3c280-825a-11eb-918f-ef18a496bd1e.png)

**Comment by neelip** [comment]
This is only happening with values ending in a comma. If the value is just `"123"`, then only the value `123` is added to the setting. 
I have created an issue on the `dotenv` repo. If there isn't a fix through that package we might need to handle this in our code.

**Comment by neelip** [comment]
Didn't get any response yet on the `dotenv` repo. The usual format for env doesn't include commas. 
Should we find an immediate fix for this specific issue in our code or wait until there is a fix in `dotenv`?
