### ISSUE TITLE
Add capability to modify debug config for remote debugging

### ISSUE THREAD

**Issue by avicenna-developer** [microsoft/vscode-azureappservice#2006]
The extension sometimes shows the following message:

"Long time to take breakpoints, set outFiles in launch.json"

How can I modify outFiles if launch.json does not exist for this extension?

**Comment by ejizba** [comment]
Can you show a screenshot of the error? Are you sure it's coming from this extension? I'm pretty sure we don't do anything related to debugging or launch.json

**Comment by avicenna-developer** [comment]
It happens when I click on Start Remote Debugging (see screenshot below)

[image: image.png]

But it is a random bug, sometimes it works OK, and sometimes it fails,
therefore I have not a screenshot of the bug right now.

I'll let you know if the error persists.

________________________________
Alejandro Reinoza
Software Developer
Avicenna Medical Systems, Inc.
http://www.avicenna-medical.com/
(914) 704-5981
***@***.***

**Comment by ejizba** [comment]
Ah this is for remote debugging, that makes more sense. I assume this is a Node.js project?

Unfortunately GitHub does not handle email replies very well, so I can't see the image you attached.

**Comment by avicenna-developer** [comment]
Correct. It's a nodejs project.
