### ISSUE TITLE
No subscription found

### ISSUE THREAD

**Issue by GeluKu** [microsoft/vscode-azureappservice#2010]
Issue Type: <b>Bug</b>

No subscriptions were found. Set up your account at https://azure.microsoft.com/en-us/free/.

Extension version: 0.21.2
VS Code version: Code 1.55.0 (Universal) (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|16.00GB (3.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by ejizba** [comment]
@GeluKu please add more information, including repro steps. Have you visited that url and fully set up your account?

**Comment by GeluKu** [comment]
Hi,

found the problem searching the internet for the issues (VS Code Azure Account Extension Cannot Find Subscription (kurkuree.com) <https://kurkuree.com/blog/VSCode-Azure-Account-Cannot-Find-Subscription>).

Please close my ticket.

Thank you,

Gelu Liuta
