### ISSUE TITLE
App Settings context menu inconsistent with Functions

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#2021]
Figured while we're working on app settings stuff, might as well make the two consistent.

Functions:
![image](https://user-images.githubusercontent.com/5290572/115289272-40dcfe80-a107-11eb-8220-aa1b9eb1aea6.png)

App Service:
![image](https://user-images.githubusercontent.com/5290572/115289308-49353980-a107-11eb-9fa7-93b228547a0a.png)

**Comment by neelip** [comment]
Should remove "Open in Portal" from the App Service context menu?
