### ISSUE TITLE
Build command (Npm install) question during deployment - where is this setting? 

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azureappservice#2022]
I should have set my deployment to run build commands. How do I manually set this so the next deployment includes the npm install command? 

![image](https://user-images.githubusercontent.com/41597107/115299146-4b04fa00-a113-11eb-8477-b2c2864cc791.png)

**Comment by diberry** [comment]
Is it .deployment with 

```
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=true
```

**Comment by nturinski** [comment]
Hi @diberry 

That's correct.  When a user clicks "Yes" at this prompt, we generate the `.deployment` file for them that enables the app setting `SCM_DO_BUILD_DURING_DEPLOYMENT` to true, which enables the `npm install` command to run on the target server.

If you want the prompt to come back, you can change this setting in VS Code.
![image](https://user-images.githubusercontent.com/5290572/115312684-a12f6880-a126-11eb-93c6-07b4ea829cff.png)

In the issue that I linked, we have discussed configuring the app setting by default without prompting the user as this is a very crucial step to ensuring that the app deploys successfully.

**Comment by nturinski** [comment]
Will be fixed by https://github.com/microsoft/vscode-azureappservice/pull/2024

**Comment by neelip** [comment]
#2024 fixes this issue for **newly created web apps**. SCM_DO_BUILD_DURING_DEPLOY is set to 'true' by default. 

For existing ones, you can now add an App Setting "SCM_DO_BUILD_DURING_DEPLOY" and set this value to 'true'.
