### ISSUE TITLE
There is no icon for the "Files" and "Logs" nodes after creating a new web app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2023]
**OS:** All
**Build Version:** 20210419.1

**Repro Steps:**

1. Create a new web app and expand it.
2. Check the nodes of the web app.

**Expect:**
The icons of the all nodes show well. 

**Actual:**
There is no icon for the "Files" and "Logs" nodes.
![image](https://user-images.githubusercontent.com/57662131/115344096-6d644980-a1df-11eb-870e-1934c8468a07.png)

**Comment by ejizba** [comment]
Related to https://github.com/microsoft/vscode-azureappservice/pull/2014, these icons are now pulled from your theme. You can change it through the command palette:
<img width="271" alt="Screen Shot 2021-04-26 at 10 50 17 AM" src="https://user-images.githubusercontent.com/11282622/116128059-65902380-a67d-11eb-87af-77527e18ed1e.png">

Depending on the theme, it may or may not have icons for folders. Here is one with icons:
<img width="82" alt="Screen Shot 2021-04-26 at 10 55 21 AM" src="https://user-images.githubusercontent.com/11282622/116128549-eb13d380-a67d-11eb-909c-c935ca1bd190.png">
