### ISSUE TITLE
There are two extra pircing tiers in the list when creating an advanced web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2032]
**OS:** All
**Build Version:** 20210507.5

**Repro Steps:**

1. Create an advanced web app.
2. Check the pircing tier list when ask to select one.

**Expect:**
There is no extra pircing tier.

**Actual:**
There are two extra pircing tiers.
![image](https://user-images.githubusercontent.com/62053665/117416048-90b32680-af4b-11eb-8d0e-64582d44d446.png)

**Comment by ejizba** [comment]
This is by design

https://github.com/microsoft/vscode-azuretools/pull/880

**Comment by v-mengwe** [comment]
@ejizba Thanks for your sharing.
I have a confusion to confirm with you, could you help to give us some guidance?
Create a web app with "Preminum" pirving tier -> Check it in portal:
![image](https://user-images.githubusercontent.com/62053665/117524480-feb12980-afef-11eb-8248-d4c166323d03.png)
Create a web app with "P1v2" pirving tier -> Check it in portal:
![image](https://user-images.githubusercontent.com/62053665/117524423-c27dc900-afef-11eb-82d0-b41da9d1617c.png)
What is the difference between the two "P1v2"?

**Comment by ejizba** [comment]
This was redone in https://github.com/microsoft/vscode-azuretools/pull/920 and https://github.com/microsoft/vscode-azureappservice/pull/2062

Hopefully there's no more confusion.
