### ISSUE TITLE
Can't redeploy after successful deploy

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azureappservice#2035]
1. Took an OS update, VSCode updated, and changed my build script. 
2. Fresh/new instance of VSCode on Win10
3. Deploy successfully, can see new files on App Service via VSCode extension and output window says deployment is complete 

    ```
    9:37:01 AM diberry-msal-expressjs: Deployment successful.
    9:37:10 AM: Deployment to "diberry-msal-expressjs" completed.
    ```
4. Make a change and redeploy

    ```
    9:37:01 AM diberry-msal-expressjs: Deployment successful.
    9:37:10 AM: Deployment to "diberry-msal-expressjs" completed.
    9:52:46 AM diberry-msal-expressjs: Starting deployment...
    9:52:46 AM diberry-msal-expressjs: Creating zip package...
    9:52:49 AM: Error: There is a deployment currently in progress. Please try again when it completes.
    ```

5. I have to completely shut down VSCode to redeploy again.

**Comment by ejizba** [comment]
This error is actually coming from Azure, not our VS Code extension. We've got an open tracking issue if/when the platform team ever supports an API to cancel deployments, but unfortunately we don't have any recent updates on that https://github.com/microsoft/vscode-azureappservice/issues/1589
