### ISSUE TITLE
Create & Deploy .NET app to Linux fails

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azureappservice#2049]
Repro steps:
1. Deploy a .NET web app to a new linux app in Azure

Error: "Deployment to "emjnetlin" failed."

Logs:
```log
5:14:01 PM : Starting deployment...
5:14:03 PM : Creating zip package...
5:14:05 PM : Fetching changes.
5:14:06 PM : Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/8bcfbb0b-1412-4140-b1f1-853a073205bf.zip (0.95 MB) to /tmp/zipdeploy/extracted
5:14:09 PM : Updating submodules.
5:14:11 PM : Preparing deployment for commit id '16ba6ec3-f'.
5:14:11 PM : Repository path is /tmp/zipdeploy/extracted
5:14:11 PM : Running oryx build...
5:14:11 PM : Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version 3.1 -i /tmp/8d917365d555e9e --log-file /tmp/build-debug.log 
5:14:16 PM : Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
5:14:16 PM : You can report issues at https://github.com/Microsoft/Oryx/issues
5:14:16 PM : Oryx Version: 0.2.20210225.2, Commit: f7b557f29a83aa078cc94c0056e7337c07f14271, ReleaseTagName: 20210225.2
5:14:16 PM : Build Operation ID: |YculNHp/AXM=.e875fca6_
5:14:16 PM : Repository Commit : 16ba6ec3-fa96-4f1b-899d-f20c5b969f6f
5:14:16 PM : Detecting platforms...
5:14:16 PM : Could not detect any platform in the source directory.
5:14:16 PM : Error: Couldn't detect a version for the platform 'dotnet' in the repo.
5:14:18 PM : /opt/Kudu/Scripts/starter.sh oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform dotnet --platform-version 3.1 -i /tmp/8d917365d555e9e --log-file /tmp/build-debug.log 
5:14:24 PM : Deployment failed.
```

Nightly tests started failing and I can repro this myself. It think it's because we set "SCM_DO_BUILD" by default on new apps now, related to https://github.com/microsoft/vscode-azureappservice/issues/1357

Version: 0.21.3-alpha
OS: darwin
OS Release: 20.4.0
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

**Comment by ejizba** [comment]
I think we need to reconsider setting "SCM_DO_BUILD" by default. It doesn't make sense for .NET IMO, because we set up the tasks and whatnot to do a build locally for them before deploying.

Also in [this comment](https://github.com/microsoft/vscode-azureappservice/issues/1357#issuecomment-594976809), @fiveisprime seemed to imply he only wanted this on Windows apps, but @neelip did it for both Linux and Windows.

> I added a note that the SCM_DO_BUILD... app setting should also be set for Windows apps. This comes from feedback from the docs team where the Windows workflow (via local git) run npm install by default.

@fiveisprime can you clarify if this should be Windows-only? And should it be for all runtimes?

**Comment by neelip** [comment]
Setting the SCM_DO_BUILD... to false is resolving the issue. 
I agree, we might want to skip linux platform entirely.

**Comment by fiveisprime** [comment]
It's not just Windows only, that must be an old comment. I specifically want to see it on Linux for node and python - I'd be happy scoping to only those two runtimes.

**Comment by ejizba** [comment]
I think I'm okay with doing it for node and python (assuming we can reliably determine it's node/python). Since those runtimes are just installing dependencies, it should be less risky than doing a full build for something like .NET. Plus, `npm install` would essentially be a no-op if the "node_modules" folder _was_ included in the zip.

@neelip can you look into doing that change ASAP so that CTI has it for testing?
