### ISSUE TITLE
[Suggestion] Only show the existing AI resources with the selected location when creating a new advanced web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2052]
**OS:** All
**Build Version:** 20210518.3

**Repro Steps:**
1. F1 -> Azure App Service: Create New Web App...(Advanced) -> Enter a web app name -> + Create new resource group -> Enter a resource group name -> Select a runtime -> Select an OS -> Select a location(such as "South Africa North") -> + Create new App Service Plan -> Enter a app service plan name -> Select a pricing tier.
2. Check whether it only contains the "South Africa North" AI resources or not.

**Actual:**
It contains all existing AI resources with different locations.
![image](https://user-images.githubusercontent.com/45614674/118617690-743da680-b7f5-11eb-96ad-5df30adda6c2.png)

**Suggestion:**
Only show the existing AI resources with the selected location, like the one for App Service plan.
![image](https://user-images.githubusercontent.com/45614674/118617511-4bb5ac80-b7f5-11eb-8450-5669ccb27f9b.png)

**Comment by ejizba** [comment]
This is by design and matches what the portal does. App Insights doesn't work in as many regions, so it's much more common for people to use a different region
