### ISSUE TITLE
[Suggestion] It would be better if the locations below "Recommended" and "Other" are sorted respectively with the first letter

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2053]
**OS:** All
**Build Version:** 20210518.3

**Repro Steps:**

1. Create an advanced web app -> Select a location for new resources.
2. Check the location list.

**Actual:**
Locations are not sorted.
![image](https://user-images.githubusercontent.com/62053665/118613099-00010400-b7f1-11eb-9afe-ad354d148547.png)

**Suggestion:**
It would be better if the locations below "Recommended" and "Other" are sorted respectively with the first letter.

**Comment by ejizba** [comment]
We're using the sorting provided to us in the ARM api call, which matches what the portal does when creating a resource group. I'm pretty sure they have some sort of smart sorting based on which regions they want people to use. If we sort alphabetically a ton of people will end up creating stuff in Australia East, which doesn't really make sense to me.
