### ISSUE TITLE
The log "Disconnected from log-streaming service" doesn't display in a new line after executing "Stop Streaming Logs"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2054]
**OS:** Windows
**Build Version:** 20210518.3

**Repro Steps:**
1. Create a new Windows Web App.
2. Right click this Web App and execute "Start Streaming Logs" action.
3. Execute "Stop Streaming Logs" action.
4. Check if the log "Disconnected from log-streaming service" displays in a new line.

**Expect:**
The log "Disconnected from log-streaming service" displays in a new line.
![image](https://user-images.githubusercontent.com/57662131/118597890-edca9a00-b7df-11eb-85a4-b2865dc317bf.png)

**Actual:**
The log "Disconnected from log-streaming service" doesn't display in a new line.
![image](https://user-images.githubusercontent.com/57662131/118585437-768b0b00-b7cb-11eb-86a8-3498c58e39fa.png)
 
**More Info:**
This issue doesn't reproduce for Linux Web App.

**Comment by ejizba** [comment]
We do not insert new lines from any of the logs coming from the streaming service and that log is coming from the streaming service. Closing as upstream
