### ISSUE TITLE
Prompting "Select Subscription" with Deploy button in "Web App created" notification

### ISSUE THREAD

**Issue by neelip** [microsoft/vscode-azureappservice#2057]
**OS**: All
**Build Version**: 20210518.3

**Repro Steps**:
1. Create a web app
2. Click "Deploy" from the "Web App created" notification
Check the behavior after selecting an app to deploy.

**Expect**:
Directly start creating a web app

**Actual**:
Ask to select a subscription.

![image](https://user-images.githubusercontent.com/17537419/118737237-42c6da00-b7f9-11eb-913c-4134924c8b7c.png)

**Comment by ejizba** [comment]
This did not repro for me and Neelima got it fixed offline for her machine
