### ISSUE TITLE
Deploy to App Service Environement failed with error 503.

### ISSUE THREAD

**Issue by yutaro113** [microsoft/vscode-azureappservice#2063]
Hi Team, 

I faced deploy to App Service Environment (ILB ASE) from VSCode via App Service extension failed with error 503.
Below is the log we got from VS code.

*-
12:23:46 <App Name>: Starting deployment...
12:23:46 <App Name>: Creating zip package...
12:25:46:Error: Failed with code "503". View troubleshooting tips [here](https://aka.ms/AA772mm).
*-

I saw previous issues similar to this and document below, and first suspect this is temporary issue on App Service, or App Service was actually unavailable, but issue always occurs even if App Service was running without issues.(*) So there seems no issue on WebApps itself.
https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-http-502-http-503

(*) To assure this, more than checking app service status is running, tried deploy from other tools from same client machine like STS (Spring Tool Suite + Azure Toolkit for Eclipse).

**ASK:**
Then question is what can be the reason this error is returned?
I also suspect Azure side issue like network configuration, but based on the result that deploy from STS succeeded so wondering deploy traffic can be different between VSCode and other tools.

Thank you very much in advance!

**Comment by yutaro113** [comment]
@ejizba appologies for the mention from my side but could you please confirm this question...? 

I also wonder whether deploy to ASE is spported or not but as per below discussion, it seems supported...
https://github.com/microsoft/vscode-azureappservice/issues/449

**Comment by ejizba** [comment]
Yes, deploying to an ASE should be supported. Can you describe more about your specific situation?

For example you mention Spring and Eclipse, so I assume this is a Java project? What runtime stack are you using when you create your web app? We have a few known issues around Java, but not sure if those apply to your situation.

Is your project open source so that we can give it a try? Another option is for you to find a sample project and see if you can reproduce the same error with that sample project.

**Comment by yutaro113** [comment]
Yes, content is Java project.
Runtime Stack:
- Java 11
- TOMCAT 9.0
Can we know about known issue? (issue ID would also be fine)
Deploy of sample project also failed with same error. In WebApps, no deployment log is shown in portal so it seems request itself didn't reach to webapps.

As deploy from STS on same client succeeded so network configuration of ASE seems no issue so I'm wondering what can cause this result... 1 suspicisous point is that we have on-premise proxy.  So we have already configured proxy on VSCode like below and as Azure resources can be fetched successfully, proxy configuration also seems fine.

*-
{
    "http.proxy": "http://proxy.example.com:8000",
    "http.proxyStrictSSL": false
}
*-

**Comment by ejizba** [comment]
Sorry for the delay here. The main issue I had in mind (https://github.com/microsoft/vscode-azureappservice/issues/783) is only for Java SE runtime. I suppose this one might apply: https://github.com/microsoft/vscode-azureappservice/issues/2020. Basically, we deploy the whole folder if you use the default path in the prompt, but it should work if you use the "Browse..." option to pick the correct artifact you want to deploy. You can use the "azureFunctions.deploySubpath" setting to set a default here. Also we have another setting "azureFunctions.preDeployTask" that you should probably hook up to a task that builds your artifact, to ensure you get the latest artifact every time you deploy
