### ISSUE TITLE
Refresh is needed to for Deploy to Web App to show new app service

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-azureappservice#207]
1. Connect the extension to an azure subscription, open the subscription you are going to use
2. Create a new App Service in the subscription
3. Select a node project and try to deploy to the newly created App Service using the "Deploy to Web App" context menu.
4. Select the subscription in the listbox that appears

Expected:
The newly created App Service appears in the listbox

Actual:
The newly created App Service is not on the listbox. After clicking on the refresh button of the  Azure App Service widget the newly created App service does appear.

**Comment by EricJizbaMSFT** [comment]
This has been fixed on master and will be released within the next week
