### ISSUE TITLE
Fail to connect a repository for a new web app which created with a custom location

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2071]
**OS:** Windows 10
**Build Version:** 20210525.11

**Repro Steps:**
1. Create a new Linux Web App with a custom location selected.
2. Expand this web app -> Deployments -> Click "Connect to a GitHub Repository..." -> Select a repository to connect.
3. Check whether succeed to connect or not.

**Expect:**
Succeed to connect the repository.

**Actual:**
Fail to connect the repository with an error.
![image](https://user-images.githubusercontent.com/45614674/119760692-05d7a300-bedd-11eb-9462-88c42563659a.png)

**More Info:**
1. This issue does not reproduce for a web app with non-custom location selected.
2. The error "Method not supported for Kubernetes Environments" also pops up when executing "Start Streaming Logs" action for the web app (custom location).

**Comment by ejizba** [comment]
This is by-design. The custom locations are still in preview and don't support all of the same features. We think the error shown is good enough in the meantime
