### ISSUE TITLE
Unable to publish App Service to Azure

### ISSUE THREAD

**Issue by DevaKamble** [microsoft/vscode-azureappservice#2072]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com

Version: 0.18.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:67:26
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps and provide the following details:

- Does this happen consistently?
-  Are you on normal Azure or a sovereign account like Azure Government, Azure China, Azure Germany, etc.?
- Was this a brand new app or an existing app?
