### ISSUE TITLE
An error "Internal error: Expected value to be neither null nor undefined: site" occurs after deleting one web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2079]
**OS:** Windows
**Build Version:** 20210607.9

**Repro Steps:**
1. Create a new web app.
2. Delete it.
3. Check whether an error occurs in the notification and output logs or not.

**Expect:**
Succeed to delete the web app without any error.

**Actual:**
An error "Internal error: Expected value to be neither null nor undefined: site" occurs after deleting the web app.
![image](https://user-images.githubusercontent.com/45614674/121158628-17c22a00-c87d-11eb-85d0-ea1ddfee0ffa.png)

**More Info:**
Succeed to delete the web app with this error.

**Comment by ejizba** [comment]
Same as https://github.com/microsoft/vscode-azurefunctions/issues/2841
