### ISSUE TITLE
The runtime stack is inconsistent between the Germany/China account and Azure account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2081]
**OS:** Windows 10
**Build Version:** 20210609.5

**Repro Steps:**
1. Sign in with Azure Germany/China account.
2. F1 -> Create New Web App(Basic) -> Enter a name -> Check runtime stack list.
3. Sign in with Azure account and check runtime stack list.
4. Check Whether the runtime stack is consistent between the Germany/China account and Azure account.

**Expect:**
The runtime stack is consistent between the Germany/China account and Azure account.

**Actual:**
The runtime stack is inconsistent between the Germany/China account and Azure account.
![image](https://user-images.githubusercontent.com/57662131/121667234-a4b6ee80-cadc-11eb-9494-3214038fb4c6.png)

**More Info:**
The runtime stack is consistent between the portal of the Germany/China account and Azure account.
![image](https://user-images.githubusercontent.com/57662131/121668608-0c216e00-cade-11eb-8879-8ab7544d0507.png)

**Comment by ejizba** [comment]
Yeah this will happen from time to time until Azure Germany/China supports the ARM Stacks api. I can update the backup stacks
