### ISSUE TITLE
Subscriptions not showing in vscode

### ISSUE THREAD

**Issue by tarunhere** [microsoft/vscode-azureappservice#2088]
When I log into web portal, I have pay-as-you-go plan but in visual-studio it is asking to choose plan.
I have just installed web-app plugin in azure.

**Comment by nturinski** [comment]
Sorry, I'm not totally sure what you are trying to communicate.  Could you please provide repro steps of the problem that you are encountering?

These are the subscriptions which should appear under the App Service view: 
![image](https://user-images.githubusercontent.com/5290572/123689010-97517200-d807-11eb-863d-75ae0f33104e.png)

You can filter subscriptions by clicking on that funnel icon.

Choosing a plan is usually a step involved in creating an App Service:
![image](https://user-images.githubusercontent.com/5290572/123688946-856fcf00-d807-11eb-8a33-b49fb48d84eb.png)

To get to here, access to a subscription is required.
