### ISSUE TITLE
Error Azure App Service -- Unable to Post Update To WebApp

### ISSUE THREAD

**Issue by rsbepvb** [microsoft/vscode-azureappservice#2089]
Issue Type: <b>Bug</b>

I'm using Azure App Service and click deploy to Web App to post an update to a pre-existing and functioning Azure PHP Web App.   

Output Window Displays:

Warning:  Ignoring deploySubPath for nonzip deploy
Staring Deployment
Deploying local Git repository to ...WebApp
Error:  Failed to Get Status of Web Deployment

I have tried this 5 or 6 times, but I get the same failed deployment each time.

Extension version: 0.22.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.09GB free)|
|Process Argv|--crash-reporter-id ae78a6b9-d253-45d8-84d8-0f9c550790d8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30322306
binariesv615:30325510
vsccppwtct:30329789
aatestflightcf:30331712

```

</details>

**Comment by nturinski** [comment]
Hi @rsbepvb  Sorry to hear you're having issues with the deployment.   Could you check your VS Code workspace settings and see what the `appService.deploySubpath` is?  

Is the deployment type intended to be local git?  Typically that setting is only set for zip-deployments.
