### ISSUE TITLE
Allow choosing a folder to zip deploy

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-azureappservice#209]
It would be amazing if we could prompt the user to select the folder to zip deploy. Often in web apps we deploy a `dist` or `public` folder. Let's allow the user to select the folder to deploy so we don't deploy everything, including source code.

cc @timheuer as FYI

**Comment by Globalrun** [comment]
I was looking for the same thing.

**Comment by timheuer** [comment]
Instead of starting on the Azure App Service instance, if you start from the folder in the Workspace, there is a "zip this folder and deploy" 

![untitled](https://user-images.githubusercontent.com/4821/33629556-5416d48a-d9b9-11e7-8e21-a155fb4ce727.png)

**Comment by johnpapa** [comment]
nice find!

would love to see a way to prompt the user from the extension too.

**Comment by timheuer** [comment]
Yes @johnpapa -- don't close this please...if anything this is now an issue to IMPROVE the discoverability and capability of the existing functionality.

**Comment by Globalrun** [comment]
Unfortunately it's not working for me. I can select the subscription, but not the Web App. I only get the option to add a new Web App. All my Web Apps are listet in the Azure App Service Panel.

**Comment by whiskeyjay** [comment]
@Globalrun Are all of your Web Apps Windows based?

**Comment by Globalrun** [comment]
Yes they are. The only thing, I can think of, that could be different to a default installation is the fact, that I have two Azure subcriptions. But it works all fine in the Azure panel.

**Comment by ggirard07** [comment]
Is this possible to pass options too at the same time? (main concern here is cleaning additional files at destination)

**Comment by whiskeyjay** [comment]
@Globalrun This should have been fixed in 0.5.0. It will be published to the marketplace in a few days.

**Comment by whiskeyjay** [comment]
@johnpapa @timheuer currently the deploy command will ask you to pick a workspace folder when there is multiple workspace folders. Now the question is, do you want the prompt to go as deep as the folder structure goes? Or just first level of folders under the workspace folder root?

I'm also thinking about adding a workspace setting to remember the choice so you don't have to choose the same folder each time you deploy.

Thoughts? (especially about the folder depth)

**Comment by timheuer** [comment]
@whiskeyjay I think you need to go deeper.  The example we were working with was that the workspace represented the full source, but you can do a build within that which will produce a static site output and then put things in the 'dist' folder which is the one you actually want to zip up.  Make sense?
