### ISSUE TITLE
Failed to az cli login\

### ISSUE THREAD

**Issue by satrex** [microsoft/vscode-azureappservice#2095]
Does this occur consistently?  No
Repro steps:

1.
2.

Action: AzureTreeDataProvider.getChildren
Error type: InvalidAuthenticationTokenTenant
Error Message: The access token is from the wrong issuer 'https://sts.windows.net/f220aaaa-a5d6-4a54-9beb-2db0dcee4f5b/'. It must match the tenant 'https://sts.windows.net/b6cc8f32-0d28-41cd-beb7-3a18c4775049/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/b6cc8f32-0d28-41cd-beb7-3a18c4775049' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.

Version: 0.22.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.58.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1212945
extension.bundle.js:2:1200779
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by ejizba** [comment]
Please add repro steps
