### ISSUE TITLE
Verify .NET 6 support

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2096]
**OS:** Windows 10
**Build Version:** 20210719.1
**.NET Version:** **6.0.100-preview.6.21355.2**

**Repro Steps:**
1. Create a **.NET 6 web project** using this command "dotnet new web".
2. Deploy this project to a **.NET 6 web app**.
3. Execute "Browse Website" for the web app to open the web page.
4. Check whether the web page shows well or not.

**Expect:**
The web page shows well.
![image](https://user-images.githubusercontent.com/45614674/126287191-de6d576e-9c7e-47d6-ad44-0049af971841.png)

**Actual:**
Error shows in the web page.

Deploy to a **Windows .NET 6 web app**:
![image](https://user-images.githubusercontent.com/45614674/126287543-4150e547-a15a-4693-a1de-75994bfe528d.png)

Deploy to a **Linux .NET 6 web app**:
![image](https://user-images.githubusercontent.com/45614674/126287507-c1edffee-eecb-41da-b39f-c42e422bbdb2.png)

**More Info:**
Succeed to deploy a .NET 6 project to a .NET 6 web app(Windows/Linux).

**Comment by v-mengwe** [comment]
Verified on the latest build 20210928.1, update the .NET Version from 6.0.100-preview.6.21355.2 to 6.0.100-rc.1.21458.32, this issue doesn't reproduce for now, so close it.
