### ISSUE TITLE
How do I get this to work from in a dev container?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoft/vscode-azureappservice#2099]
I have an ASP.Net Core application opened in a VsCode dev container. I install the VsCode Azure Tools extension, which installs this and a load of other stuff, most of which is installed in the dev container itself. But then any attempt to log into Azure just results in the dev container attempting to load a localhost url like `localhost:40301/signin` on a random port.

What do I need to do to get this working please?

**Comment by ejizba** [comment]
As a workaround, try using "Sign in with device code" from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)

Related to https://github.com/microsoft/vscode-azure-account/issues/179

If you're still having issues signing in, please follow up on the azure account repo
