### ISSUE TITLE
Succeed to deploy the node.js project to the windows Python 3.6 web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2106]
**OS:** All
**Build Version:** 20210730.3

**Repro Steps:**

1. Open a node.js project in VS Code -> Deploy the project to a windows Python 3.6 web app.
2. Check whether fail to deploy the project to the windows Python 3.6 web app.

**Expect:**
Fail to deploy the node.js project to the windows Python 3.6 web app and pop up an error, like below:
![Screen Shot 2021-08-02 at 6 09 19 PM](https://user-images.githubusercontent.com/62053665/127854331-b74cfe14-d0a0-4e5e-9662-db4988466fbf.png)

**Actual:**
Succeed to deploy the node.js project to the windows Python 3.6 web app.

**More Info:**

1. The webpage shows well after execute "Browse Website" for the windows Python 3.6 web app.
2. Succeed to deploy node.js/Python project to the windows .NET Core 3.1 web app.

**Comment by ejizba** [comment]
This is controlled by the platform and although the behavior is weird, it's kind of nice that it "just works" regardless of if you have python or node.js
