### ISSUE TITLE
Subscriptions list under Azure App Service take 13 seconds to load

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-azureappservice#211]
The Subscriptions list under the Azure App Service widget take 13 seconds to get populated.
I'm not sure if this is an issue with the VS Code extension, or with the underling Azure APIs you are calling, but it'd be great if someone figured out how to make all this faster (ideally less than 100 ms).

**Comment by whiskeyjay** [comment]
Hi @digeff, thanks for the feedback! Do you mind letting us know how many subscriptions you have?

**Comment by digeff** [comment]
About 10 I think

**Comment by chrmarti** [comment]
@digeff Do you know how many tenants/directories your account has? That might have a larger impact than the number of subscriptions. (The tenants/directories are, e.g., listed on https://portal.azure.com when you click on the account in the top right corner.)

**Comment by EricJizbaMSFT** [comment]
This was fixed in v0.3.0 of the account extension
