### ISSUE TITLE
Deployment starts without any confirmation dialog if deploying the project by clicking "Deploy" button from the notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2118]
**OS:** Windows 10
**Build Version:** 20210816.4
**Regression:** Not a regression

**Repro Steps:**
1. Open "nodejs-docs-hello-world" project in VS Code.
2. Create a Node web app.
3. Click "Deploy" button from below notification -> Select the project to deploy.
![image](https://user-images.githubusercontent.com/45614674/129685048-8b2e701d-a7d3-4321-8606-bca66a4ff605.png)
4. Check whether the confirmation dialog pops up or not.

**Expect:**
The confirmation dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/129685014-c0248d53-0277-4500-9e9d-4679e740f5e3.png)

**Actual:**
Deployment starts without any confirmation dialog.

**More Info:**
1. This issue does not reproduce when deploying by context menu/deploy icon/command palette.
2. This issue also reproduces on the previous released app service extension 0.23.0.

**Comment by ejizba** [comment]
This is by design - since it's a brand new web app, we know there are no previous deployments so there's no risk of overwriting anything.
