### ISSUE TITLE
The name in the link is inconsistent with the web app name when web app name contains uppercase letters

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2119]
**OS:** Windows 10/ Mac
**Build Version:** 20210816.4
**Regression:** Not a regression

**Repro Steps:**
1. Create a web app whose name contains uppercase letters, like "a-NET3-test".
2. Check the log message in **OUTPUT** window.

**Expect:**
The name in the link is consistent with the web app name.

**Actual:**
The name in the link is inconsistent with the web app name.
![image](https://user-images.githubusercontent.com/57662131/129698361-8dde5e26-7527-4c52-8947-f3019d1c4b9e.png)

**Comment by ejizba** [comment]
Urls are not case sensitive and we're just passing along the url we get from Azure (so we couldn't fix if we wanted to)
