### ISSUE TITLE
Fail to execute "start remote debugging“ for the Python Linux web app with an error "connect ECONNREFUSED 127.0.0.1:8000"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2120]
**OS:** Windows 10/ Mac
**Build Version:** 20210816.4
**Regression:** Previous release

**Repro Steps:**
1. Open **python-docs-hello-world** project in VS Code.
2. Create a Linux web app with python runtime.
3. Deploy the python project to the web app.
4. Right click the web app -> Click "Start Remote Debugging" (Make sure the setting "App Service: Enable Python Remote Debugging" is checked)
5. Check whether succeed to execute "start remote debugging“ for the Python Linux web app.

**Expect:**
Succeed to execute "start remote debugging“ for the Python Linux web app.

**Actual:**
Fail to execute "start remote debugging“ for the Python Linux web app.
![image](https://user-images.githubusercontent.com/57662131/129831523-bce1365f-a4d7-4915-a9e8-c05cde02fc2d.png)

**More Info:**
This issue does not reproduce on the previous released App Service extension 0.23.0.

**Comment by ejizba** [comment]
Will be fixed by https://github.com/microsoft/vscode-azuretools/pull/990
