### ISSUE TITLE
Creating app service and app service plan in App Service Environment (ASE) .

### ISSUE THREAD

**Issue by samlin-msft-zz** [microsoft/vscode-azureappservice#2123]
Hi,

I'm trying to create an app service into an App Service Environment(ASE) with "Adv." command. Comparing with Azure portal UI and vs code extension, I come out an app creation flow. It seems be a gap to create app service in ASE.

1. I can only create an app service into an existing ASP resides in an existing ASE with the flow ( 1  -> 2 -> 3 -> **4b** -> 5 -> 6 -> 7a -> 8a -> **9b** -> 13 ).  
2. If there is no ASP in an existing ASE, cannot create an app service and ASP in the existing ASE.
3. I'm not able to create a new app into a new ASE. The purple blocks and ASE configure sub-process( **6, 7b, 11b, 11b, 11c/12b** ) are not available in vs code extension. Is it possible to add the feature to backlog? Thanks!

![image](https://user-images.githubusercontent.com/3676608/130870237-bbbaac0f-a0b3-4242-b87e-0451d8067d29.png)

**Comment by ejizba** [comment]
We try to keep things relatively simple in VS Code and unfortunately creating an ASE would add several more steps to an already complicated flow. We recommend people use the Portal, az cli, or an ARM/Bicep template for more complicated scenarios. That being said, we can leave this open for now to see if we get more feedback asking for this feature

**Comment by samlin-msft** [comment]
@ejizba, thanks for considering this. Is it possible to implement display Isolated sku only in step "10b" first? I think this leave less complexity that addresses the new ASP creation issue in ASE. Thanks!

==> If there is no ASP in an existing ASE, cannot create an app service and ASP in the existing ASE.

**Comment by samlin-msft** [comment]
Hi @ejizba,
Thanks for considering this. Is it possible to display ASE list in step 6? It will enable another flow (... 5 -> 6 -> **7b** -> 8b -> 9b -> 13) to provide better user experience align with Azure Portal. 
I've got information from Portal owner that getting ASE list from the API with filter like below, FYR.

`https://management.azure.com/resources?api-version=2018-11-01&$filter=(subscriptionId eq 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx') and (resourceType eq 'Microsoft.Web/hostingEnvironments')`

**Comment by ccompy** [comment]
ASE is where most enterprise customers are with App Service. More importantly ASEv3 is where they are going to be.  It has the best story for an injected service.  This isn't expensive like ASEv2 either.  Without supporting this, you are regulating use of this extension to smaller business use.

**Comment by ejizba** [comment]
@ccompy that is correct. Our understanding is that enterprise customers and other more advanced users do _not_ deploy from VS Code and instead use more automated solutions like CI/CD. In VS Code we try to make things quick and easy which is great for new users and people testing stuff out, but its often _too_ easy for people who do not want to risk mistakes affecting their production apps. Our goal is to complement other tooling like the Portal, CI/CD, etc. - not replicate it.

If you have enterprise customers in mind, you're welcome to point them to this issue to upvote or comment if our understanding is incorrect.
