### ISSUE TITLE
Error when deploying from WSL

### ISSUE THREAD

**Issue by rolftimmerman** [microsoft/vscode-azureappservice#2124]
I have a .NET 3.1 project (using WSL2 Ubuntu 20.04) which I want to deploy. When using the "Deploy to Web App..." button in VS Code, the build process runs fine but during deployment I get the following error:
```
1:58:41 PM readit-inventory-demo: Starting deployment...
1:58:46 PM readit-inventory-demo: Creating zip package...
1:58:50 PM readit-inventory-demo: Zip package size: 4.82 MB
1:58:49 PM readit-inventory-demo: Fetching changes.
1:58:49 PM readit-inventory-demo: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\dxllsu3a.zip (4.61 MB) to C:\local\Temp\zipdeploy\extracted
1:58:49 PM readit-inventory-demo: The given path's format is not supported.
1:58:54 PM readit-inventory-demo: Deployment failed.
```

When I do the same on my Windows 10 machine everything works fine. 

Azure App Service Extension v0.23.0

**Comment by ejizba** [comment]
Does this reproduce for other projects or just your specific project? Maybe try with a simple `dotnet new webapp`. If the error _is_ specific to your project - is it by chance on GitHub where I can try it out?

**Comment by rolftimmerman** [comment]
Thank you for your quick reply. I've tried your solution and it deploys succesfully. However, I think I've already found the issue. When copying the project files from Windows to a folder on WSL extra ":Zone.Identifier" files are added (https://github.com/microsoft/WSL/issues/4609) which results in the `The given path's format is not supported.` error.
