### ISSUE TITLE
The opened webpage is incorrect after clicking "Learn more" button in the dialog which prompted to enable the remote debug

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2129]
**OS:** Win10/Mac
**Build Version:** 20210901.3
**Regression:** Not a regiression

**Repro Steps:**

1. Right click a Node.js Linux web app -> Select "Start Remote Debugging" -> Select "Learn more" when prompting to enable the remote debug.
   ![image](https://user-images.githubusercontent.com/62053665/131630140-880f0563-396c-41f3-b774-2db0169d868e.png)
2. Check whether the opened webpage is correct.

**Expect:**
The opened webpage is correct.

**Actual:**
The opened webpage is incorrect.
![webpage](https://user-images.githubusercontent.com/62053665/131631366-63b6ff99-6211-4764-9628-c7f048c888ae.gif)

**Comment by ejizba** [comment]
Recreated the link - it's possible we didn't own it and it got deleted for some reason. I pointed it here:
https://github.com/microsoft/vscode-azureappservice/wiki/Remote-Debugging

@fiveisprime let me know if you have any better docs
