### ISSUE TITLE
Provide some better progress indication during deploy

### ISSUE THREAD

**Issue by timheuer** [Microsoft/vscode-azureappservice#213]
When recently using the Deploy to Web App capability I didn't know if the steps were stuck or what.  Some type of progress indication other than the console output static text would be helpful (animated cursor would even be fine).  It's an improved UX to let me know something is happening (user perception) rather than just a log output that appears to the user that it happenED.  Subtle but important.

Also, while a deployment is happening, should the command to Deploy to Web App be disabled?  Seems it would collide if I did that and cause an unknown state to occur in my deployment.

**Comment by whiskeyjay** [comment]
@timheuer thanks for the feedback! Actually there was a discussion about having a spinner in the VS Code status bar when a deployment is going on - similar to when a build is in progress. Is that something you are looking for?

**Comment by timheuer** [comment]
@whiskeyjay *maybe* -- but I had to think about it because I didn't even know that's where deployment status was :-) -- status bars have become like ads in editors for me, too much info so I stop paying attention.  From a UX standpoint, my attention is drawn to the console output because that is where the command starting giving me feedback.  I'm not sure if the model in the output allows for you to "update" the output but I could see:

`Starting deployment....10%`

And the % keeps updating.

**Comment by whiskeyjay** [comment]
@timheuer with the latest release the output is now printing timestamped messages on deployment status. Does that solve the problem for you?

**Comment by EricJizbaMSFT** [comment]
Closing since there have been several improvements to this since the issue was originally filed. There's a spinner in the App Service tree. There's a notification at the bottom right, and the logs in the output channel are more detailed
