### ISSUE TITLE
A11y_Azure App Service extension for VS Code_Files_Popup_FocusOrder: The Keyboard focus moves out of the Pop up on pressing Tab.

### ISSUE THREAD

**Issue by v-gitsay** [microsoft/vscode-azureappservice#2137]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureAppServiceextensionforVSCode_Win32_Sep2021;#Azure Tools for VS Code;#DesktopApp;#WCAG2.4.3;#AINotInScope;#FTP;#FocusOrder;#Keyboard;#Linked:Bug135636;#External:VSCode;

### Environment Details:
Application Name: Azure App Service extension for VS Code
Screen Reader: NVDA/JAWS
Operating system: Windows 10

### Repro Steps:

1. Launch VS Code application.
2. Tab till "Azure" and press enter.
3. Tab till "app service " dropdown and press enter.
4. Tab till "Files" dropdown and press enter.
5. Tab to any file and press enter.
6. Edit by adding "make changes" and save(ctrl + S) the "SRC" file..
7. Tab till the Pop up Saving "hostingstart.html".
8. Check if the keyboard focus moves out of the Pop up on pressing Tab.

### Actual:
The Keyboard focus moves out of the Pop up on pressing Tab.

**Note:** This issue is observed with all the Notification Pop up that appear for "Initializing SSH" Pop up scenario.

### Expected:
The Keyboard focus should remain in the Pop up on pressing Tab. 

### User Impact:
Keyboard users will be confused if the keyboard focus moves out of the Pop up on pressing Tab key.

**Please find the below attachment for reference:**
![2137](https://user-images.githubusercontent.com/86710911/134297964-74742e25-70df-4dde-9a8b-3e1e5ffe73c3.gif)

**Comment by nturinski** [comment]
Using [this](https://code.visualstudio.com/api/get-started/your-first-extension) to create a basic extension , I am able to reproduce this issue.

The extensions can't control where the focus is after a pop-up notification appears.  Please file an issue on VS Code here: https://github.com/microsoft/vscode/issues

**Comment by v-gitsay** [comment]
As per the external bug comment and as discussed with SME this is not a modal pop up control hence closing this issue
