### ISSUE TITLE
[Suggestion] Remove the .env file option during uploading settings if there is no .env file in the opened project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2138]
**OS:** All
**Build Version:** 20210920.5
**Regression:** Not a Regression

**Repro Steps:**
1. Download and open the project [nodejs-docs-hello-world](https://github.com/Azure-Samples/nodejs-docs-hello-world/archive/master.zip) in VS Code.
2. Deploy this project to one web app(Node.js).
3. Click the "Upload Settings" button in the notification after deployment.
4. Check whether there is a local .env file option to select.
![image](https://user-images.githubusercontent.com/45614674/134314620-2ba67dd5-1e3b-4ecb-8317-c461185eeb1a.png)

**Actual:**
There is a local .env file option to select, but an error occurs if selecting it.
![image](https://user-images.githubusercontent.com/45614674/134313988-4f4c1e48-df71-4680-a03d-f21e5d7dbe98.png)
**Note:** There is no .env file in the project.

**Suggestion:**
Remove the local .env file option during uploading settings if there is no .env file in the opened project.

**Comment by nturinski** [comment]
I think that we will keep this design as it is.  I think that the .env file is standard convention and if the user does not have one, then this can give them guidance on what file that they should if they want to use this command.
