### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MouadBenjrinija** [microsoft/vscode-azureappservice#2144]
- Issue Type: `Performance`
- Extension Name: `vscode-azureappservice`
- Extension Version: `0.23.0`
- OS Version: `Darwin x64 20.5.0`
- VS Code version: `1.61.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/pk/jnb34l2963z3pyr0184m3gym0000gn/T/ms-azuretools.vscode-azureappservice-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by neelip** [comment]
Could you please attach the given file to your home-directory as mentioned in the error and let us know if you are still facing problems?
