### ISSUE TITLE
Error when deploying Nodejs app 

### ISSUE THREAD

**Issue by alexyak** [microsoft/vscode-azureappservice#2148]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: remote: Deploy Async        
send-pack: unexpected disconnect while reading sideband packet
error: error in sideband demultiplexer
To https://twobitbears.scm.azurewebsites.net:443/twobitbears.git
 * [new branch]      HEAD -> master

Version: 0.19.0
OS: darwin
OS Release: 20.5.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:164:522736
rejected extension.bundle.js:164:522163
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
