### ISSUE TITLE
Error debugging 

### ISSUE THREAD

**Issue by alexyak** [microsoft/vscode-azureappservice#2149]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: Error getting tunnel status: 504

Version: 0.19.0
OS: darwin
OS Release: 20.5.0
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> extension.bundle.js:164:122897
rejected extension.bundle.js:164:118469
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
