### ISSUE TITLE
How deploy a React frontend.

### ISSUE THREAD

**Issue by JoeWarwick** [microsoft/vscode-azureappservice#2150]
On deploy of locally working react app to Linux Node 14 lts.

I get errors:

- Can't import  React outside of a module.

I have type=module in package.json same issue.

- Can't find node_modules.tar.gz

Not going to spend time on this.

**Comment by nturinski** [comment]
What folder are you deploying?  I think with React, you can't deploy the root folder, but you'll have to deploy the `build`.  Though if you are trying to deploy a React Frontend, I recommend using the [Azure Static Web Apps extension](https://github.com/microsoft/vscode-azurestaticwebapps).
