### ISSUE TITLE
No puedo Implementar mi app web, sin embargo en local todo va bien 

### ISSUE THREAD

**Issue by cabarronc** [microsoft/vscode-azureappservice#2165]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.23.0
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1213193
extension.bundle.js:2:1201027extension.bundle.js:2:1201027
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
