### ISSUE TITLE
App Service deploy running really slow

### ISSUE THREAD

**Issue by RyanHill-MSFT** [microsoft/vscode-azureappservice#2170]
I've noticed that when deploying an app, the deployment takes quite a while; tens of minutes (notice timestamps below). Observing the Output log, it seems to get hindered on the `Creating a zip package ...` step. The extension version is 0.23.0 on Windows 11 (Build 22538). The app in question is a simple ReactJS app that I created following this tutorial.

```
6:18:01 PM app-ryhill-msalreact: Starting deployment...
6:18:02 PM app-ryhill-msalreact: Creating zip package...
6:34:24 PM app-ryhill-msalreact: Zip package size: 79.1 MB
6:34:28 PM app-ryhill-msalreact: Fetching changes.
6:34:30 PM app-ryhill-msalreact: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/cebb9097-723a-4311-9a8c-94987383e257.zip (75.42 MB) to /tmp/zipdeploy/extracted
6:35:19 PM app-ryhill-msalreact: Updating submodules.
6:35:20 PM app-ryhill-msalreact: Preparing deployment for commit id '970326dc0b'.
6:35:20 PM app-ryhill-msalreact: Repository path is /tmp/zipdeploy/extracted
6:35:20 PM app-ryhill-msalreact: Running oryx build...
6:35:20 PM app-ryhill-msalreact: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 14 -i /tmp/8d9dd36b0398260 -p compress_node_modules=tar-gz --log-file /tmp/build-debug.log 
```

<img width="380" alt="image" src="https://user-images.githubusercontent.com/47189704/150613678-2b5a4de2-ceca-495b-8f96-f433d2c38893.png">

**Comment by nturinski** [comment]
The App Service extension has to zip your project before deploying, and it looks like your zip file is around 80 MB, so I think that it's taking a while to zip it.  Are you excluding the node_modules when deploying?  For a simple ReactJS app, that's a pretty large file.

I'm not sure if there is much we can do on our end to increase the speed of zipping the projects, but we can investigate our zipstream library.

If you click Yes on this prompt:
![image](https://user-images.githubusercontent.com/5290572/151460732-af46bb5f-6548-4dc4-a0a3-d2fd6ac338df.png)

It should increase performance of your deployment.  It'll add a setting to ignore your node_modules when deploying.

**Comment by TKlerx** [comment]
I have a similar issue with a python flask app and some wheels that I need to upload.
Even though I have 100 Mbps upload, the upload speed is 1 Mbps from the zipstream. My deployment fails with a request timeout after approx. 30 minutes.
I cannot imagine that my computer can only zip with 1 megabit (=128kb) per second.
Actually zipping the whole directory (without ignoring .vscode or any other directory) via 7-zip took approx 5 seconds!

**Comment by bferg317-perrigo** [comment]
Having the same issue with a completely blank template. I'm new to all this so I'm just testing out the workflow. PowerShell Event Grid Trigger template, publish to Function App. I'm in minute 18 zipping. Total folder size is less than 4 KB.

**Comment by nturinski** [comment]
We've made several improvements to deployment since this issue. Hopefully we can close this issue as resolved, but please re-open if the deploy is still taking forever to zip up your project.
