### ISSUE TITLE
Custom Locations not listed when creating new Web App on App Service on Kubernetes With Azure Arc

### ISSUE THREAD

**Issue by apwestgarth** [microsoft/vscode-azureappservice#2172]
I have found in VSCode 1.64.0 with ms-azuretools.vscode-azureappservice I am no longer able to list custom locations during Advanced Web App Create.  All I see listed are Azure regions.

**Comment by nturinski** [comment]
Do you know if you downgrade VSCode or the Azure App Services extension, if this resolves the problem?  I suspect that something changed with the Azure API, but it would be nice to be able to eliminate those variables!

**Comment by bwateratmsft** [comment]
Maybe related to https://github.com/microsoft/vscode-azuretools/pull/1006. The API changed and I had to update our listing query.

**Comment by nturinski** [comment]
Hi @apwestgarth

Could you confirm that this is still an issue?

With the current released version, I am seeing my custom location:
![image](https://user-images.githubusercontent.com/5290572/201199810-7017ec98-cec7-480d-b66f-310c92f56073.png)

Maybe it was an error in the API that was resolved?
