### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HoussemMereghni** [microsoft/vscode-azureappservice#2174]
Does this occur consistently? yes
Repro steps:

1.sign in to sub
2.try to access any web app

Action: api.revealTreeItem
Error type: BadGateway
Error Message: Response from service 'Microsoft.Web' does not contain sufficient information to enforce access control policy.

Version: 0.23.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.64.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1213193
extension.bundle.js:2:1201027extension.bundle.js:2:1201027
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by HoussemMereghni** [comment]
@nturinski

Am able to access the resources through the portal and am not running through a proxy nor a VPN.

**Comment by nturinski** [comment]
Could you tell me what version of the Azure Account Extension you have installed?  Also, maybe your subscription doesn't have proper access roles assigned? https://docs.microsoft.com/en-us/azure/role-based-access-control/troubleshooting

**Comment by HoussemMereghni** [comment]
I have Azure tools 0.2.1 / Azure App Service 0.23.1 which should be the latest versions. As for the access role, my user is assigned Contributor role on the whole resource group inherited by every resource in the group and that should be sufficient i think. Yet for some reason i cant access any web app.

**Comment by nturinski** [comment]
Sorry for the delayed response.

The only thing I could think of is maybe you are logged in as a different role on VS Code than you are in the Azure Portal.  I know that it's probably not helpful now, but if you are still running into this problem, could you please try signing out and in again?  Maybe that would refresh the token.

To sign out, hit F1 -> Azure: Sign Out, F1 -> Azure: Sign In
