### ISSUE TITLE
Can't deploy to multiple app service environments with right click deploy

### ISSUE THREAD

**Issue by jthompson22** [microsoft/vscode-azureappservice#2183]
I have one app service deploying to a staging environment called {appname-staging}. I'm tyring to deploy that same app to another app service that is my production environment called {appname}. I cannot deploy to two environments using right click deploy - the search suggestion defaults to {appname-staging} and will not allow me to just type in {appname} (it defaults to staging). Hence I cannot deploy to two different workspaces. 

Version: 0.23.1
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

**Comment by nturinski** [comment]
Could you check your VS Code settings and see if this setting has a value?

![image](https://user-images.githubusercontent.com/5290572/156670903-ed395c72-4015-4e66-ae5e-b516fe06eab9.png)

You'll have to delete this or set it to "None" to prevent deploying to the same app every deployment.
