### ISSUE TITLE
Fail to execute the command "SSH into Web App" for a Linux web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2186]
**OS:** Win10
**Build Version:** 20220225.1
**Regression:** Preview release

**Repro Steps:**

1. Right click a Linux web app -> SSH into Web App.
2. Check whether succeeds to execute the command "SSH into Web App".

**Expect:**
Succeed to execute the command "SSH into Web App"

**Actual:**
Fail to execute the command "SSH into Web App".
**Details of output:**
![image](https://user-images.githubusercontent.com/62053665/157828987-4787e000-ac6e-4eec-b61a-61b4584d2c38.png)

**Comment by nturinski** [comment]
@v-mengwe Could you confirm that this is still happening?  There was a release with VS Code that disabled the use of the proposed API, but we should have been cleared to use it.

@isidorn Could you confirm that our team migrated everything correctly in this PR? https://github.com/microsoft/vscode-azureappservice/commit/aee2408bdf7aa804c0c8f07c60058a5a92aed28e

**Comment by v-mengwe** [comment]
Verified on the latest build 20220321.4, this issue still reproduces for now.
VS Code Version:
> Version: 1.65.2 (user setup)
> Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
> Date: 2022-03-10T14:33:55.248Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Windows_NT x64 10.0.19044

**Comment by isidorn** [comment]
@nturinski you did everything right on your side, but if you use proposedAPI you also need to let us know so we allow it from our side. In this case we were not aware that the `azure-appservice` relies on the `terminalDataWriteEvent` proposed API. I will add it now, so it should be fixed in insiders soon and in the next stable
