### ISSUE TITLE
Zip deployment broken in latest VS Code release

### ISSUE THREAD

**Issue by mtinnes** [microsoft/vscode-azureappservice#2202]
Issue Type: <b>Bug</b>

Publishing to Azure app service using Zip deployment is broken in the latest VC Code release. Publish fails with ECONNRESET after a period of time. Rolling back to 1.65 fixes the issue.

Extension version: 0.23.1
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz (12 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (39.74GB free)|
|Process Argv|--crash-reporter-id 2ba4c841-4ca1-4fd9-90b1-491927626d60|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by alexweininger** [comment]
@mtinnes sorry you ran into this bug, the good news is we are working on a fix for this right now, and we have a development build available if you'd like to try and verify the fix works for us.

---

Steps to install extension development build:
1. If needed, update VS Code to `1.66.0` or greater.
1. Download the extension .VSIX from our Azure DevOps Pipeline - [Direct download link](https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/45132/artifacts?artifactName=vsix&api-version=7.0&%24format=zip) | [View artifacts](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=45132&view=artifacts&pathAsName=false&type=publishedArtifacts)
1. Extract the .vsix file from the .zip folder
1. From the command palette (`F1` or `Command/Ctrl + Shift + P`), run the "Extensions: Install from VSIX..." command.
1. Select the downloaded .VSIX file, then reload VS Code as prompted.

Once installed, attempt to deploy your app as normal. Report back and let us know if deployment succeeded/failed. 

---

Follow along with #2191 (closed as the fix has been merged, but not released yet) for more updates and discussion.

**Comment by alexweininger** [comment]
Fix has been released in version https://github.com/microsoft/vscode-azureappservice/releases/tag/v0.23.2 of the extension.
