### ISSUE TITLE
Cannot publish web app to Azure from VS Code

### ISSUE THREAD

**Issue by datalakeshore** [microsoft/vscode-azureappservice#2209]
Does this occur consistently? Yes
Repro steps:

1. I have a fully functional angular app running locally
2. I want to deploy to Azure
3. It fails every time.

Action: appService.Deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription 'redacted:id' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.23.2
OS: win32
OS Release: 10.0.22598
Product: Visual Studio Code - Insiders
Product Version: 1.67.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1226441
extension.bundle.js:2:1214275extension.bundle.js:2:1214275
```

</details>

**Comment by nturinski** [comment]
Hi @datalakeshore

It seems like your subscription might have expired.  Does following the steps in this [document](https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/subscription-disabled) help?

**Comment by datalakeshore** [comment]
I fixed it – all good now.

Thanks,
Damon Carr, CEO
Data Lake Shore, LLC
Book Meeting: http://calendly.com/datalakeshore
https://www.linkedin.com/company/data-lake-shore-initiative
Damon ***@***.***) • Instagram photos and videos<https://www.instagram.com/datalakeshore/>
https://www.facebook.com/contactdatalakeshore/
Data Lake Shore, LLC ***@***.***) / Twitter<https://twitter.com/CarrrDamon>

***@***.***<https://www.datalakeshore.com/>

**Comment by nturinski** [comment]
Thanks for following up!
