### ISSUE TITLE
Cannot publish web app to Azure slot from VS Code

### ISSUE THREAD

**Issue by atapiagithub** [microsoft/vscode-azureappservice#2210]
Does this occur consistently? Yes
Repro steps:

I have a fully functional angular app running locally
I want to deploy to Azure, into an app service SLOT
I open the Azure tab, go to APP SERVICE, and search for my app service. Select "Deployment Slots", right clic into my destination slot, and select the option "Deploy to slot"
VS Code open "Command Palette" and ask me to chose one of my App Services in the current suscription. I Can't see the destination slot in this terminal, only the app service parent.
In previous versions, VS Code just asking me to confirm that the deployment destination slot is right, and install the app in that slot.

Version: 0.23.2
OS: Windows 10 Pro (64 bits)
OS Release: 19042.1645
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

**Comment by nturinski** [comment]
Thanks for reporting this issue @atapiagithub.  Unfortunately this is a regression from our last release.  If you weren't experiencing any issues deploying with the v0.23.1, please try downgrading to that version to deploy to slots.

We're very sorry for the inconvenience!

**Comment by nturinski** [comment]
Note for our team:  This is happening due to 2 different versions of the azureextensionui package being installed by appservice and the App Service extension.  Somehow the `package-lock.json` got ahead of the `package.json`

**Comment by fabianotavallini** [comment]
When will this fix be released? Thanks.

**Comment by atapiagithub** [comment]
Downgrade VS Code to version 1.65.2 and the Azure App Services extension to version v0.23.1 resolves the problem, for those who need a temporary fix for this

**Comment by nturinski** [comment]
> When will this fix be released? Thanks.

Fix was just released today!  Please install v0.23.3.  This should include the fix for VS Code version 1.66 > as well.
