### ISSUE TITLE
[Suggestion] It would be better to update the version of App Service extension latest "unified" build

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2217]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Regression:** Not a regression

**Repro Steps:**
1. Install the App Service extension latest "unified" build.
2. Click "Extensions" icon -> There is an update of App Service extension.
![image](https://user-images.githubusercontent.com/45614674/164955776-aeb5024f-f7b8-4ccb-a44b-90bf5dff3caf.png)
3. Restart VS Code or reload window.
4. Check whether the App Service extension updates to released version automatically.

**Actual:**
The App Service extension updates to released version automatically.

**Suggestion:**
It would be better to update the version of App Service extension latest "unified" build.

**Comment by alexweininger** [comment]
Fixed by #2238
