### ISSUE TITLE
An error occurs when executing "Generate Azure CLI Script" action for a web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2218]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Regression:** Not a regression

**Repro Steps:**
1. Create a web app.
2. Right click this web app and execute "Generate Azure CLI Script" action.
3. Check whether succeeds to execute "Generate Azure CLI Script" action or not

**Expect:**
Succeed to execute "Generate Azure CLI Script" action.

**Actual:**
An error occurs when executing "Generate Azure CLI Script" action.
![image](https://user-images.githubusercontent.com/45614674/164955877-f22d4bfa-64e1-4c09-9a7c-4d2b65f8f569.png)

**Comment by alexweininger** [comment]
Fixed by #2234
