### ISSUE TITLE
An error occurs when creating a deployment slot

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2219]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Regression:** Not a regression

**Repro Steps:**
1. Create a web app.
2. Right click "Deployment Slot" node and execute "Create New Deployment Slot..." action.
3. Check whether succeeds to create a deployment slot or not

**Expect:**
Succeed to create a deployment slot.

**Actual:**
An error occurs when creating a deployment slot.
![image](https://user-images.githubusercontent.com/45614674/164955922-fd2d0d45-8ba7-4841-84b5-1e419ea520ce.png)

**More Info:**
1. The output logs show as below.
![image](https://user-images.githubusercontent.com/45614674/164956027-8b8cfdf1-569e-42da-9a1e-2c583799bf2e.png)
2. Expand "Deployment Slot" node, the same error shows.
![image](https://user-images.githubusercontent.com/45614674/164956032-f81dfdaf-8593-4339-b3ad-6a0ec6243a07.png)

**Comment by alexweininger** [comment]
Fixed by #2235
