### ISSUE TITLE
There is no "Add New Setting..." action in "Application Settings" context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2220]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Regression:** Not a regression

**Repro Steps:**
1. Create a web app.
2. Right click "Application Settings" node to open its context menu.
3. Check whether there is a "Add New Setting..." action or not.

**Expect:**
There is a "Add New Setting..." action in "Application Settings" context menu.
![image](https://user-images.githubusercontent.com/45614674/164956154-4d543bb9-fef8-463e-ae81-d93e81053689.png)

**Actual:**
There is no "Add New Setting..." action in "Application Settings" context menu.
![image](https://user-images.githubusercontent.com/45614674/164956146-04c99111-82e9-4da7-8b70-a37a349ed430.png)

**Comment by alexweininger** [comment]
Closed by #2233
