### ISSUE TITLE
There are 2 "Refresh" actions in "Deployments" context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2221]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Azure Functions Extension Build Version:** 20220421.8 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Install Azure Resource and App Service extension unified build in VS Code.
2. Create a web app.
3. Right click "Deployments" node to open its context menu, there is only one "Refresh" action.
4. Install the Azure Functions Extension unified build.
5. Refresh the Azure Resources view.
6. Right click "Deployments" node to open its context menu again.
7. Check whether there is only one "Refresh" action or not.

**Expect:**
There is only one "Refresh" action in "Deployments" context menu.

**Actual:**
There are 2 "Refresh" actions in "Deployments" context menu.
![image](https://user-images.githubusercontent.com/45614674/164956471-cc553b4c-b367-4728-a2ef-c937ad278943.png)

**More Info:**
1. There are 2 "Disconnect from Repo..." actions after connecting to a GitHub repository.
![image](https://user-images.githubusercontent.com/45614674/164956578-d8ec367a-9976-4205-9e91-7dd30a30fdbb.png)
2. Right click the connected repository, the context menu shows as below.
![image](https://user-images.githubusercontent.com/45614674/164972444-bc03e7d5-3cfa-4079-bb11-2cd72934dc6f.png)
3. This issue also reproduces for Files/Logs node.
4. This issue does not reproduce if don't install the Azure Function unified extension build.

**Comment by alexweininger** [comment]
Closed by #2232
