### ISSUE TITLE
An error "Resource not found" shows in the opened page after executing "Open in Portal" action for "Deployments" node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2222]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32
**App Service Extension Build Version:** 20220421.6
**Regression:** Not a regression

**Repro Steps:**
1. Create a web app.
2. Right click "Deployments" node and execute "Open in Portal" action.
3. Check whether the "Deployment Center" page is opened well or not.

**Expect:**
The "Deployment Center" page is opened well.

**Actual:**
An error "Resource not found" shows in the opened page.
![image](https://user-images.githubusercontent.com/45614674/164956781-ee60da03-3200-4036-85ac-8cd1d4a96706.png)

**Comment by v-xinda** [comment]
This issue also reproduces after executing "Open in Portal" action for "Deployment Slots" node.

**Comment by alexweininger** [comment]
Closed by #2232
