### ISSUE TITLE
The deleted web app doesn't disappear automatically after deleting it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2225]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension build Version:** 20220421.6 (unified)
**Regression:** Not a Regression

**Repro Steps:**
1. Right click a web app -> Click "Delete...".
2. Check whether the deleted web app disappears automatically after deleting it or not.

**Expect:**
The deleted web app disappears automatically after deleting it.

**Actual:**
The deleted web app doesn't disappear automatically after deleting it.
![image](https://user-images.githubusercontent.com/57662131/164968791-5c0faabe-f37f-40b8-8770-dc964a5dcb58.png)

**More Info:**
This issue can be fixed by refreshing.

**Comment by v-xinda** [comment]
The new created web app doesn't display under the "App Services" node automatically after creating it

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/222
