### ISSUE TITLE
Fail to execute action "Reveal in Application Settings" with an error for a connected database

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azureappservice#2226]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Service Extension Build Version:** 20220421.6 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Expand a Linux Node web app -> Databases node -> Add a connection and select a Mongo Account.
2. Right click the connected database -> Reveal in Application Settings.
3. Check whether succeeds to execute action "Reveal in Application Settings" or not.

**Expect:**
Succeed to execute action "Reveal in Application Settings" without any error.

**Actual:**
Fail to execute action "Reveal in Application Settings" with an error.
<img width="444" alt="Screen Shot 2022-04-24 at 17 57 30" src="https://user-images.githubusercontent.com/62053665/164971008-3f8e5262-b671-452d-adb0-dbbfb6f98ead.png">

**Comment by nturinski** [comment]
Fixed by #2004
