### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by intouch-opec** [microsoft/vscode-azureappservice#2231]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.16.5
OS: darwin
OS Release: 21.4.0
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline extension.bundle.js:309:399870
retryCallback extension.bundle.js:225:116429
retryCallback extension.bundle.js:157:31051
extension.bundle.js:157:32664
handleRedirect extension.bundle.js:171:7747
extension.bundle.js:157:29836
Request.module.exports.r.requestLibrarySink.r.headersOnly.r.streamedResponse.r.body.function.r.body.pipe.o.pipe.l [as _callback] extension.bundle.js:1:582082
Request.module.exports.Request.init.r._callback.r.callback.r.callback [as callback] extension.bundle.js:201:4468
Request.emit events.js:182:13
Request.<anonymous> extension.bundle.js:201:17577
Request.emit events.js:187:15
IncomingMessage.<anonymous> extension.bundle.js:201:16367
Object.onceWrapper events.js:273:13
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by nturinski** [comment]
Please retry the deployment.  Based on the error message, there is currently a deployment in progress: `There is a deployment currently in progress. Please try again when it completes.`.

If this issue isn't resolved by redeploying, please reopen with steps to reproduce this error.
