### ISSUE TITLE
Improve performance of deploy

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#224]
I'll have to think through the experience for making this work, but I want to make sure the need is captured. This will ensure Windows users are able to deploy compiled modules.

Things to consider:

* An app could be one of many runtimes (and may be custom)
* How can we know to alert a user that they need to enable npm install on deploy?
* At what point in the process should this be configured?

See also [vscode-azuretools#7](https://github.com/Microsoft/vscode-azuretools/issues/7) and the [Kudu docs](https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions)

**Comment by fiveisprime** [comment]
I did some comparisons over the weekend of deploying `node_modules` with the app vs running the build in Kudu. For a pretty standard node app (~10 dependencies), deployment times didn't vary by much more than a few seconds (a typical deploy took around 2min in both cases). It's unclear if the install is run with `--production` which may speed things up even more.

That said, I suggest enabling the Kudu build by default to prevent compatibility issues (VS Code is still 60%+ Windows) when deploying. That "answers" the second and third question above, but we still need to make sure we handle different runtimes.

The setting isn't specific to node, it will run the build for .NET as well so the open question is *how does the build affect the various runtimes and do we need to treat each runtime differently?*

**Comment by johnpapa** [comment]
The `readme` file says this ...

> And in order to have the web app run proper deployment command to restore the npm packages, you need to have the following Application Setting on your site: 

`SCM_DO_BUILD_DURING_DEPLOYMENT=true`

which lead me to believe it would run `npm install`. I tried this with a simple app that has 2 files, and it did not restore the `node_modules`. I had `index.js` (below) and a `package.json` with a single dependency of `express`.

```
// index.js
const express = require("express");
const app = express();

app.get("/", (req, res) => res.send("Hello World!"));

const port = process.env.PORT;

app.listen(port, () => console.log("Example app listening on port " + port));
```

**Comment by whiskeyjay** [comment]
@johnpapa did you restart the web app after setting _SCM_DO_BUILD_DURING_DEPLOYMENT_ to true? I just tried something similar and it seems a restart is required. I'll try to confirm this.

**Comment by EricJizbaMSFT** [comment]
Renaming this issue to generally improving the performance of deploy. An app service could be different runtimes and 'SCM_DO_BUILD_DURING_DEPLOYMENT' is not specific to node apps. The only thing that's runtime specific is the files we exclude from the zip (npm packages vs nuget packages, etc.)

We need to have a discussion about whether or not the "fast" behavior should be the default behavior. Ideally yes - but that also introduces risk because people can customize their directory structure/build steps. We know generic zip deploy will work for everything (even if its slow). One option is to prompt the user "Do you want to improve the performance of your deployment?" and then we guide them through 1. Setting SCM_DO_BUILD_DURING_DEPLOYMENT and 2. excluding files as appropriate

**Comment by nturinski** [comment]
@EricJizbaMSFT Does this apply to azurefunctions as well?  Since they both use the same Kudu zipdeploy api, I figured that the application setting would apply for both.  If this is the case, then I should implement this in azuretools rather than appservice.  Thoughts?

**Comment by EricJizbaMSFT** [comment]
Yeah it probably applies in some sense, but I think it's lower priority and different enough that you should just focus on AppService for now. We're still not sure how best to handle node modules in the functions extension (See this bug: https://github.com/Microsoft/vscode-azurefunctions/issues/218)
