### ISSUE TITLE
Error in deploying a sample flask app from vscode to appservice

### ISSUE THREAD

**Issue by hriazi** [microsoft/vscode-azureappservice#2241]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: {"body":"","headers":{"cache-control":"no-cache","pragma":"no-cache","expires":"-1","server":"Kestrel","set-cookie":["ARRAffinity=f7e8112d174b035dedc0e95aa90dd578d821ba1ae7596ea4277e4837d982995e;Path=/;HttpOnly;Secure;Domain=pweb1.scm.azurewebsites.net","ARRAffinitySameSite=f7e8112d174b035dedc0e95aa90dd578d821ba1ae7596ea4277e4837d982995e;Path=/;HttpOnly;SameSite=None;Secure;Domain=pweb1.scm.azurewebsites.net"],"date":"Sat, 30 Apr 2022 11:51:57 GMT","connection":"close","content-length":"0"},"statusCode":400}

Version: 0.7.1
OS: win32

**Comment by alexweininger** [comment]
Is this a persistent issue? Could you try deploying again to see if this is still happening? 

If so, could you provide more details like:
* a link to the demo repository/project if possible
* Python version info for your project
* Python version info for you Function App
