### ISSUE TITLE
[Suggestion] It would be better to change log to "Delete slot 'xxx' Succeeded" in the ACTIVITYLOG window after deleting a slot

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2249]
**OS:** Windows 10
**Build Version:** 20220513.10

**Repro Steps:**
1. Expand a web app.
2. Right click a slot -> Click "Delete Slot...".
3. Check the log message in the **ACTIVITYLOG** window.

**Actual:**
There is a "Delete web app 'xxx' Succeeded" log in the **ACTIVITYLOG** window.
![image](https://user-images.githubusercontent.com/57662131/168583702-af2ec0bd-561e-4bbb-9b55-42bc303861b7.png)

**Suggestion:**
It would be better to change log to "Delete slot 'xxx' Succeeded" in the **ACTIVITYLOG** window after deleting a slot.

**Comment by alexweininger** [comment]
Issue also exists in Functions https://github.com/microsoft/vscode-azurefunctions/issues/3148
