### ISSUE TITLE
An error "Failed with code 307" occurs in Files node and Logs node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2254]
**OS:** All
**Azure Resource Extension Build Version:** 20220518.13
**App Service Extension build Version:** 20220517.4

**Repro Steps:**
1. Create a web app.
2. Expand this web app -> Files node and Logs node.
3. Check whether there is no error in Files node and Logs node.

**Expect:**
There is no error in Files node and Logs node.

**Actual:**
An error "Failed with code 307" occurs in Files node and Logs node.
![image](https://user-images.githubusercontent.com/45614674/169028827-12313f0a-606d-4741-b389-00d3df2e4f53.png)

**Comment by alexweininger** [comment]
This isn't actually fixed yet, need to release and upgrade the appservice package.

**Comment by v-ruizh** [comment]
Verified this issue on App Service extension 20220523.6, it is no longer reproduced.
