### ISSUE TITLE
There is an extra option "Select undefined" when creating a slot from command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2255]
**OS:** All
**Azure Resource Extension Build Version:** 20220518.13
**App Service Extension build Version:** 20220517.4

**Repro Steps:**
1. F1 -> Azure App Service: Create New Deployment Slot... -> Select a web app.
2. Check whether the next option is "Enter the slot name" or not.

**Expect:**
The next option is "Enter the slot name".
![image](https://user-images.githubusercontent.com/45614674/169033030-7b0c19b4-18ce-4f3d-8b1a-93bc7092045a.png)

**Actual:**
The next option is "Select undefined".
![image](https://user-images.githubusercontent.com/45614674/169033203-dfb9e3a3-68e1-40e0-a5e0-c0114d700a51.png)

**Comment by v-ruizh** [comment]
This issue also reproduces when executing "Swap deployment slot..." command from command palette.

**Comment by alexweininger** [comment]
Note: this doesn't reproduce for Functions
