### ISSUE TITLE
Deploy to deployment slot only available from the extension tab, not from the explorer

### ISSUE THREAD

**Issue by rolfback** [microsoft/vscode-azureappservice#2269]
Been waiting for the right-click on folder in Explorer and publish to a slot, to come back in VS Code. An upgrade of the extension removed that feature a month ago or so. 

The only way to publish to a deployment slot now is to go to the Azure extension tab and click down the tree to find my slot. I don't then know which folder I'm actually publishing.

**Comment by nturinski** [comment]
Hi @rolfback 

Which version of the extension are you using that you see a "Deploy to Deployment Slot?" from the Explorer? I went back to v0.22.0 and I'm only able to deploy a folder to a web app.  

![image](https://user-images.githubusercontent.com/5290572/181618084-c0add7d5-6177-45c9-8b60-e933a5511c4d.png)

Would you mind showing me a screenshot of what you're referring to?
