### ISSUE TITLE
Fail to deploy a .NET 7.0 web project to a basic .NET 7 Web App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2271]
**OS:** Win 10
**Build Version:** 20220612.1
**.NET Version:** 7.0.100-preview.4.22252.9

**Repro Steps:**
1. Enable setting "appService.showHiddenStacks".
2. Create a .NET 7.0 web project using command "dotnet new web".
3. Create a basic .NET 7 Web App.
4. Deploy the .NET 7.0 web project to the basic .NET 7 Web App.
5. Check whether succeeds to deploy a .NET 7.0 web project to a basic .NET 7 Web App.

**Expect:**
Succeed to deploy a .NET 7.0 web project to a basic .NET 7 Web App.

**Actual:**
Fail to deploy a .NET 7.0 web project to a basic .NET 7 Web App.
```
1:22:17 AM serene-bas-net7: Starting deployment...
1:24:17 AM serene-bas-net7: Creating zip package...
1:24:17 AM serene-bas-net7: Zip package size: 81.4 kB
1:26:27 AM: Error: Server Error
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.
```
**More Info:**
Succeed to deploy a .NET 7.0 web project to an advanced .NET 7 Web App.

**Comment by nturinski** [comment]
I tried this again and it seems to be working now.

![image](https://user-images.githubusercontent.com/5290572/180329247-acd706e3-f9d9-44ed-ac92-6f6bdd5aad6b.png)

Could you confirm that this still occurring?

**Comment by v-ruizh** [comment]
@nturinski Verified this issue on the latest main branch build 20220721.4, the .NET 7 web project can be deployed to basic .NET 7 web app successfully. But there is an error in the opened web page (browse website for the deployed web app).

Deploy to **Windows** .NET 7 web app:
![image](https://user-images.githubusercontent.com/45614674/180373541-0c1c86d6-ce41-4023-9aa8-3c091f746a57.png)
Deploy to **Linux** .NET 7 web app:
![image](https://user-images.githubusercontent.com/45614674/180373561-3a1310c9-f227-4a23-b3da-eaf906b645e2.png)

**Comment by nturinski** [comment]
What version of dotnet are you running? 

![image](https://user-images.githubusercontent.com/5290572/181647126-cdf83feb-a50c-4ac5-8973-52c31213faba.png)

Mine seems to be working fine with this version.

**Comment by nturinski** [comment]
@v-ruizh Whenever you get a chance, could you verify your dotnet version?

**Comment by v-ruizh** [comment]
@nturinski My dotnet version is .NET7 RC1 which is the latest released version. This issue still reproduces on the App Service RC build.
![image](https://user-images.githubusercontent.com/45614674/190573501-8e12d861-34d3-45f6-a68b-155a065550bf.png)

**More Info:**
I verified this issue on .NET 7 Preview 7 (22377.5 the last released version of .NET 7) with the App Service RC build, this issue does not reproduce.

**Comment by nturinski** [comment]
Okay, I will close this issue then as it seems to be related to .NET 7 rather than our extension/service.  Hopefully the next RC will resolve this.
