### ISSUE TITLE
The 'Deploy to Static Website' menu option is missing

### ISSUE THREAD

**Issue by InteXX** [microsoft/vscode-azureappservice#2287]
I'm following [this tutorial](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-host), but I've run into a problem. In my installation, I'm not getting the `Deploy to Static Website` menu item:

![image](https://user-images.githubusercontent.com/10966749/178617780-702d7137-478c-4b14-ba79-53d086f11db4.png)

Is there a configuration item somewhere that I must set?

**Comment by nturinski** [comment]
The tutorial is for [Azure Storage](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage), actually.  Please download that extension to follow the tutorial.

**Comment by InteXX** [comment]
Aha!

Thank you for the link (and for your quick reply as well).
