### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'portalUrl')

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-azureappservice#2288]
Upon deploying an app service, I see the following error:

Cannot read properties of undefined (reading 'portalUrl')

Screenshot:
<img width="546" alt="Screen Shot 2022-07-13 at 4 44 03 PM" src="https://user-images.githubusercontent.com/297042/178855474-3caf2cd7-f021-4836-850f-bae536d8d374.png">

Interestingly, the deploy appears still to be successful, with the deployment center showing a successful deploy.

I used the deployment steps here (but for my own app):
https://docs.microsoft.com/en-us/azure/app-service/tutorial-python-postgresql-app?tabs=flask%2Cwindows%2Cazure-portal%2Cterminal-bash%2Cazure-portal-access%2Cvscode-aztools-deploy%2Cdeploy-instructions-azportal%2Cdeploy-instructions--zip-azcli%2Cdeploy-instructions-curl-bash#6---deploy-your-application-code-to-azure

**Comment by pamelafox** [comment]
This issue is also reported in another repo, but I believe this is the most pertinent repo: https://github.com/microsoft/azure-pipelines-tasks/issues/16432

**Comment by nturinski** [comment]
Hi @pamelafox, did this error come up _after_ you clicked a notification with the following text?

![image](https://user-images.githubusercontent.com/5290572/179116504-1a48ff41-a710-4171-b4d4-4e0a405f0c02.png)

Or did the error `Cannot read properties of undefined (reading 'portalUrl')` appear without you clicking anything?

**Comment by tushaar9027** [comment]
I am also facing the same issue while deploying the spacy to azure app service. Is anyone able to fix this.

**Comment by nturinski** [comment]
A fix for this is merged, but not released yet. If you need it urgently, you can download a custom vsix from here: https://dev.azure.com/ms-azuretools/534e1e1c-b364-44d0-b5ee-dce879a5106e/_apis/build/builds/50748/artifacts?artifactName=vsix&api-version=7.0&%24format=zip
