### ISSUE TITLE
Add documentation for log points feature

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#229]
We should add a "Preview Features" section to the main README with instructions on how to enable the feature. It should also link to documentation for the feature itself (since the log points feature seems kind of complex). For example, you could put a README in [this folder](https://github.com/Microsoft/vscode-azureappservice/tree/master/src/diagnostics) and link to that

**Comment by EricJizbaMSFT** [comment]
@changsi-an do you think you could do this for 0.5.0? It doesn't have to be super in-depth at this point

**Comment by auchenberg** [comment]
@EricJizbaMSFT We don't have plans to go public with Logpoints in the next comings months, so we should wait for this doc change

**Comment by EricJizbaMSFT** [comment]
Per offline discussion, Logpoints requires Azure bits that have not been released publicly. Closing this issue as fixed in #231. Docs will still need to be done eventually, but that can be tracked separately closer to the public release.
