### ISSUE TITLE
Error: `Cannot read properties of undefined (reading 'createClient')`

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#2291]
If you try to deploy from the command palette and have a `appService.defaultWebAppToDeploy` setting, you're hit with this error.

**Comment by nturinski** [comment]
Note: this only applies if you have never opened the tree view before

**Comment by stevemurch** [comment]
Am running into this as well (v1.8.1 of the VS Code Extension.) Expanding the Azure tree does not fix it. Node project. Just started happening -- very frustrating.

**Comment by nturinski** [comment]
Do you have `azureFunctions.defaultFunctionAppToDeploy` set? If you do, clearing that setting may help with this issue.

**Comment by stevemurch** [comment]
Thanks @nturinski -- I've cleared that and restarted, but unfortunately the problem still persists. I've also tried deleting the .vscode folder and restarting Visual Studio Code and I still get the same problem. Frustrating.

**Comment by nturinski** [comment]
Are you deploying by clicking the cloud button?  There was an update in VS Code that is causing this to throw that error that we are currently fixing.  For now, could you try deploying from the resources view by right-clicking the App Service app that you are trying to deploy to?

![image](https://user-images.githubusercontent.com/5290572/195900115-ddf651af-2899-4f4f-bfb4-bca407507546.png)

**Comment by alexweininger** [comment]
This issue has been fixed by the [0.7.0 release of the Azure Resources extension](https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.7.0).
