### ISSUE TITLE
Cannot choose account on Azure plug in before pushing website.

### ISSUE THREAD

**Issue by Javaman2** [microsoft/vscode-azureappservice#2294]
Does this occur consistently? 
Repro steps:
Open Visual Studio Code and connect to Azure.  

1. Yesterday I wanted to publish a new web app to Azure.  I must have accidentally created a new account.  I pushed the site and it came up ok, but I want the site to go to my other account.
2. The problem is now that in Visual Studio Code, any time I connect now it automatically goes to the account I don't want, signs in and doesn't seem to allow me to switch accounts.

Version: 0.24.3
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by nturinski** [comment]
Hi @Javaman2

If you hit F1, and type "Sign Out", you should see the following command:

![image](https://user-images.githubusercontent.com/5290572/181604840-701a9c6f-cd02-4e63-b9ca-1b004d4b0736.png)

After that, you can sign in via the `Sign into Azure` node or by F1 => `Azure: Sign In`.

Hope that helps!
