### ISSUE TITLE
Cannot read properties of undefined (reading 'createClient')

### ISSUE THREAD

**Issue by coutinhomarco** [microsoft/vscode-azureappservice#2304]
Does this occur consistently? YES
Repro steps:

1.Right click on app folder
2.Click Deploy to Web App...
3.Select the app

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.3
OS: darwin
OS Release: 20.6.0
Product: Visual Studio Code
Product Version: 1.70.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3487411
fulfilled extension.bundle.js:2:3486239
```

</details>

**Comment by nturinski** [comment]
Hi @coutinhomarco

Thanks for filing this. I think that this bug is related: https://github.com/microsoft/vscode-azureappservice/issues/2291. To work around this, please activate the extension first by opening the Azure Resources view or running an App Service command.

**Comment by elsurudo** [comment]
I worked around it be deploying from the Azure resources view instead of the workspace view. Thanks for the tip.

**Comment by nturinski** [comment]
Hi all, just wanted to let you know v0.24.5 has been released and should resolve this issue.
