### ISSUE TITLE
Getting Exception <ModuleNotFoundError: No module named 'spacy' > while deploying python app in azure 

### ISSUE THREAD

**Issue by tushaar9027** [microsoft/vscode-azureappservice#2307]
Hi Everyone,

Getting Exception <ModuleNotFoundError: No module named 'spacy' > while deploying python app in azure .
It's working fine locally. Virtual enviroment is there.

spacy version : 3.4.1

![image](https://user-images.githubusercontent.com/10369409/185265777-1ffde67d-0d5a-474f-9ada-2bb43419beed.png)

I can see the package installed in my virtual environment as well...Code is working fine locally

I have added both these configurations in azure & virtual environment was activated in vscode terminal before running the deploy web app command from azure app service extn.

WEBSITE_RUN_FROM_PACKAGE=1
SCM_DO_BUILD_DURING_DEPLOYMENT=true

Please help in fixing this.

**Comment by tushaar9027** [comment]
Hi ,

Can anyone help me with this issue. As far my understanding is after adding WEBSITE_RUN_FROM_PACKAGE=1 , it should pick everything from my package and i can see space installed on azure as well , still getting no module found on import.

**Comment by MicroFish91** [comment]
Can you try running it again without the SCM_DO_BUILD... flag set to true and tell us if that fixes the issue?
