### ISSUE TITLE
Created web app missing from tree

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azureappservice#2314]
Slightly reworded from customer email:

> Created an App Service successfully from VSCode, the Azure activity log and azure portal both show it but the Azure explorer doesn’t. Is this typical behavior? If it isn’t, how should I refresh VSCode to get the app service?
>  
> I’ve been using command palette -> reload window because the refresh in the Azure explorer (either app service or subscription) doesn’t actually reload the azure explorer with the new app.

**Comment by nturinski** [comment]
Answered offline, but this is currently a known bug 🪲

**Comment by nturinski** [comment]
Fixed in new v2 API. Will be resolved whenever that is released.
