### ISSUE TITLE
"(0 , P.randomUUID) is not a function" error when doing almost anything

### ISSUE THREAD

**Issue by christianshay** [microsoft/vscode-azureappservice#2320]
I'm receiving "(0 , P.randomUUID) is not a function" when I do almost anything with this extension.

Some googling suggests it is related to nodejs crypto and old node versions so I tried updating node, I tried deinstalling and reinstalling the Azure Tools pack, but nothing is working.

Have you seen this before?

**Comment by alexweininger** [comment]
What version of VS Code are you using? This may be fixed by updating VS Code.

**Comment by christianshay** [comment]
You're right! I had stopped VS Code from auto updating. Once I did it is fixed. Thanks!
