### ISSUE TITLE
An error occurs after restarting remote debugging for the Python Linux web app

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2358]
**OS:** Win10
**Build Version:** 20230130.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a Python Linux web app -> Deploy a project to it.
2. Right click the Python Linux web app -> Select "Start Remote Debugging".
3. Click "Restart"
   ![image](https://user-images.githubusercontent.com/107091828/215728342-71485c19-e71d-4efa-a62c-5306ebee78e6.png)
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/215729726-5803587f-8d80-4e55-b67c-a1d6bb6a0185.png)

**Comment by alexweininger** [comment]
Does remote debugging work as expected if you don't restart it?

**Comment by v-chenzha** [comment]
@alexweininger Yes, succeed to start remote debugging to Python web app as expected if we don't restart it.

**Comment by nturinski** [comment]
When you say "restart", do you mean that you are restarting the web app or are you restarting the debugging session? As in, clicking the green refresh arrow.

If you mean restarting the debug session, this is by-design.

Please re-open if you did mean "restarting the web app."
