### ISSUE TITLE
Report a critical error when deploy to java webapp in some cases

### ISSUE THREAD

**Issue by Flanker32** [microsoft/vscode-azureappservice#2359]
### Steps to reproduce:
Create a new webapp with java11+linux+Java SE > Deploy jar package to the app > Get the result as below
Also repro with java17+linux+tomcat10+war package

### Actual Behavior:
Shows a critical error

![image](https://user-images.githubusercontent.com/12445236/215965726-d4df6873-a727-42a5-a401-deac17c54eb8.png)

![image](https://user-images.githubusercontent.com/12445236/215965770-a429d36f-1823-43e5-a59a-f62536536efa.png)

But the website is deployed succeed which could be access with browse website

**Comment by alexweininger** [comment]
According to @nturinski this is an issue with the linux detectors. @Flanker32 does this still reproduce?
