### ISSUE TITLE
An error occurs after executing "Open in Portal" action for "Deployments" node

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2361]
**OS:** All
**Build Version:** 20230130.1
**Regression:** Preview Release

**Repro Steps:**

1. Create a web app.
2. Right click "Deployments" node and execute "Open in Portal" action.
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/215985443-a04d0895-d8c6-4219-aba3-5539b6dbcd80.png)

**Comment by alexweininger** [comment]
Caused by [the use of `instanceof` in `openInPortal`](https://github.com/microsoft/vscode-azuretools/blob/d38498f0085deb912675e4d2cb376f973c12f31e/azure/src/openInPortal.ts#L10).

**Comment by v-chenzha** [comment]
@alexweininger  Verified this issue on the latest build 20230203.1, it does not reproduce.
