### ISSUE TITLE
Cannot browse files in appservice anymore (error 404)

### ISSUE THREAD

**Issue by jeroenjeremy** [microsoft/vscode-azureappservice#2370]
Until today's update of VSC I could browse and edit files directly inside an appservice. As of now I can't anymore. I restarted VSC and the laptop several times but no success.
Does this occur consistently? Yes
Repro steps:

1. Select Azure extension (works)
2. Select correct resource (works)
3. Select an app service (works)
4. Select 'Files' -> Error: Unexpected status code: 404

Version: 0.24.6
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.75.0
Language: en

**Comment by motm32** [comment]
Thanks for filing this issue! You should be able to revert to the previously released version of the App Service extension (v0.24.5) to get the files working again.

**Comment by alexweininger** [comment]
Works again if I revert 37abfbee4004894153e7f71886c7cec50e7507d1 😄

**Comment by jeroenjeremy** [comment]
Confirmed, thanks for that!

**Comment by alexweininger** [comment]
Fix has been released in the latest extension version [v0.24.7](https://github.com/microsoft/vscode-azureappservice/releases/tag/v0.24.7).
