### ISSUE TITLE
Trying to deploy a .NET 7.0 webapp doesn't work with extensions

### ISSUE THREAD

**Issue by MattReda11** [microsoft/vscode-azureappservice#2374]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 0.24.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
SubscriptionTreeItem.<anonymous> extension.bundle.js:2:2101403
fulfilled extension.bundle.js:2:2099773
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps. This error indicates that you used the command palette and didn't have any function apps to deploy to.
