### ISSUE TITLE
An error occurs when executing "Deploy to Web App..." command from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2375]
**OS:** All
**Azure Resources extension:** 20230215.1
**App Service Extension Version:** 0.24.7

**Repro Steps:**
1. Open the [nodejs-docs-hello-world](https://github.com/Azure-Samples/nodejs-docs-hello-world/archive/master.zip) project in VS Code.
2. F1 -> Azure App Service: Deploy to Web App.... -> Select the above project -> Select a web app to deploy.
3. Check whether succeeds to deploy the project to web app.

**Expect:**
Succeed to deploy the project to web app.

**Actual:**
An error occurs when executing "Deploy to Web App..." command from Command Palette.
![image](https://user-images.githubusercontent.com/45614674/219021268-5af86f17-3002-4e6b-9c1d-0d50b5cd6e10.png)

**More Info:**
This issue does not reproduce when deploying the project from context menu.

**Comment by alexweininger** [comment]
I'm unable to reproduce this, but this seems like a critical issue that needs fixing. 

Can you try reproducing this again? Are there any other details you can provide to help me reproduce this?

**Comment by v-ruizh** [comment]
@alexweininger This issue reproduces on the yesterday's latest main branch Resource Groups extension build 20230215.1.

Verified this issue on the latest main branch Resource Groups extension build 20230215.10, it is no longer reproduce. Close it.

**Comment by alexweininger** [comment]
> @alexweininger This issue reproduces on the yesterday's latest main branch Resource Groups extension build 20230215.1.
> 
> Verified this issue on the latest main branch Resource Groups extension build 20230215.10, it is no longer reproduce. Close it.

Thank you!
