### ISSUE TITLE
An error occurs when executing "Connect to GitHub Repository...." command from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2376]
**OS:** All
**Azure Resources extension:** 20230215.1
**App Service Extension Version:** 0.24.7

**Repro Steps:**
1. F1 -> Azure App Service: Connect to GitHub Repository.... -> Select a web app.
2. Check whether the next step is "Choose organization" or not.

**Expect:**
The next step is "Choose organization".

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/219022626-e449d773-e95a-4c61-99d9-f692b6dc6c9f.png)

**More Info:**
This issue does not reproduce when executing "Connect to GitHub Repository...." from Azure view.

**Comment by alexweininger** [comment]
I'm unable to reproduce this.

**Comment by v-ruizh** [comment]
Verified this issue on the latest main branch Resource Groups extension build 20230215.10, it is no longer reproduce. Close it.
