### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kittipongkp** [microsoft/vscode-azureappservice#2377]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.24.7
OS: darwin
OS Release: 22.2.0
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
