### ISSUE TITLE
automatically browse to site after it is created

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#238]
Once a site is created and the URL is in the output pane, why not also open the site in the browser?

**Comment by whiskeyjay** [comment]
The extension will now ask whether to deploy after a site is created; will auto browsing the site make things too busy? Besides, what's to see on a new site?

**Comment by chrisdias** [comment]
auto-browsing to the site indicates that the site was created successfully.  I don't think it is too busy.
