### ISSUE TITLE
Preparing zip package' operation conflicts with the pending 'Performing continuous deployment' operation started 

### ISSUE THREAD

**Issue by himadrish** [microsoft/vscode-azureappservice#2380]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: The 'Preparing zip package' operation conflicts with the pending 'Performing continuous deployment' operation started at redacted:id15T17redacted:id8756190Z.  Please retry operation later.

Version: 0.24.7
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
