### ISSUE TITLE
No error occurs when executing "Remove Connection" command for a disconnected web app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2383]
**OS:** All
**Azure Resources extension:** 20230215.10
**App Service Extension Version:** 0.24.7

**Repro Steps:**
1. Make sure there is no database connection for one web app.
2. F1 -> Azure App Service: Remove Connection... -> Select the above web app.
3. Check whether there is an error "No matching resources found".

**Expect:**
There is an error "No matching resources found", such as the below screen.
![image](https://user-images.githubusercontent.com/45614674/219303620-e93b9fac-1d4c-4aff-8be5-a1f837da699f.png)

**Actual:**
There is no error and it keeps in empty list of "Select Connection" option.
![image](https://user-images.githubusercontent.com/45614674/219303598-d3bd3216-c36d-4b2d-b018-ffb1a5d8f834.png)

**More Info:**
This issue also reproduces when executing commands "Disconnect from Repo/View Commit in GitHub/Reveal in Azure Databases Extension/Reveal in Application Settings...".

**Comment by alexweininger** [comment]
No longer showing an error is now expected behavior here. Though, I do think we should be showing the "No matching resources found" message on the quick pick. I don't think that's a critical issue though.
