### ISSUE TITLE
Fail to execute "Browse Website" command from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2386]
**OS:** All
**Azure Resources extension:** 20230216.6
**App Service Extension:** 0.24.7
**Regression:** Previous Release

**Repro Steps:**
1. F1 -> Azure App Service: Browse Website -> Select one web app.
2. Check whether succeeds to execute "Browse Website" command.

**Expect:**
Succeed to execute "Browse Website" command.

**Actual:**
Fail to execute "Browse Website" command from Command Palette.
![image](https://user-images.githubusercontent.com/45614674/219563657-a88cb22f-9c38-4628-950b-33521dccdfd7.png)

**More Info:**
1. This issue does not reproduce when executing "Browse Website" action from context menu.
2. This issue does not reproduce on the current released "App Service + Azure Resources" extensions.

**Comment by nturinski** [comment]
Related to https://github.com/orgs/microsoft/projects/782/views/3?pane=issue&itemId=24413878

**Comment by nturinski** [comment]
Could you check if this reproduces? Similar to https://github.com/microsoft/vscode-azureappservice/issues/2429, this may be fixed by a lot of work that has been already merged.

**Comment by v-chenzha** [comment]
Verified this issue on the latest build 20230705.1, it doesn't reproduce for now. So, close it.
