### ISSUE TITLE
Fail to execute "Start Remote Debugging" command from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2387]
**OS:** All
**Azure Resources Extension:** 20230216.6
**App Service Extension:** 0.24.7
**Regression:** Previous Release

**Repro Steps:**
1. F1 -> Azure App Service: Start Remote Debugging -> Select one web app.
2. Check whether succeeds to execute "Start Remote Debugging" command.

**Expect:**
Succeed to execute "Start Remote Debugging" command.

**Actual:**
Fail to execute "Start Remote Debugging" command from Command Palette.
![image](https://user-images.githubusercontent.com/45614674/219569381-e1fc2ace-00a9-432a-877e-dc71bff9bf37.png)

**More Info:**
1. This issue does not reproduce when executing "Start Remote Debugging" action from context menu.
2. This issue does not reproduce on the current released "App Service + Azure Resources" extensions.

**Comment by nturinski** [comment]
Related to https://github.com/orgs/microsoft/projects/782/views/3?pane=issue&itemId=24413878

**Comment by nturinski** [comment]
We can't reproduce this as of the current build. Could you please verify?

**Comment by v-ruizh** [comment]
This issue has been fixed on the latest build 20230719.13, close it.
