### ISSUE TITLE
Fail to execute "Start Streaming Logs" command from Command Palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azureappservice#2388]
**OS:** All
**Azure Resources Extension:** 20230216.6
**App Service Extension:** 0.24.7
**Regression:** Previous Release

**Repro Steps:**
1. F1 -> Azure App Service: Start Streaming Logs -> Select one web app.
2. Check whether succeeds to execute "Start Streaming Logs" command.

**Expect:**
Succeed to execute "Start Streaming Logs" command.

**Actual:**
Fail to execute "Start Streaming Logs" command from Command Palette.
![image](https://user-images.githubusercontent.com/45614674/219570544-cd278766-6e21-467e-beef-c71f8747e6c8.png)

**More Info:**
1. This issue also reproduces when executing "Stop Streaming Logs" command from Command Palette.
2. This issue does not reproduce when executing "Start Streaming Logs" action from context menu.
3. This issue does not reproduce on the current released "App Service + Azure Resources" extensions.

**Comment by nturinski** [comment]
Related to https://github.com/orgs/microsoft/projects/782/views/3?pane=issue&itemId=24413878

**Comment by nturinski** [comment]
Could you check if this reproduces? Similar to https://github.com/microsoft/vscode-azureappservice/issues/2429, this may be fixed by a lot of work that has been already merged.

**Comment by v-chenzha** [comment]
Verified this issue on the latest build 20230705.1, it doesn't reproduce for now. So, close it.
