### ISSUE TITLE
Deployment option without removing dependencies ?

### ISSUE THREAD

**Issue by erikpa1** [microsoft/vscode-azureappservice#2394]
Hi, 

when I deploy python app (for example because of 1 file), I have to always wait until dependencies are reinstalled. Could be nice to disable this (not sure if its even possible on plugin site, or it has to be developed for azure itself)

**Comment by MicroFish91** [comment]
If you just want to make a quick change, you could navigate to the `Files` node and directly edit the file itself.

A better way might be to connect your deployments to a remote GitHub repository and make the changes that way.

**Comment by alexweininger** [comment]
To clarify, are you talking about skipping reinstalling dependencies locally before deploying, or reinstalling on the server once the app is deployed?
