### ISSUE TITLE
Unable to Deploy to App Service from VS Code

### ISSUE THREAD

**Issue by siva-thiagarajan** [microsoft/vscode-azureappservice#2395]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/redacted:username/CLOUD/Azure/inventory/bin\Release\net6.0\publish

Version: 0.24.7
OS: darwin
OS Release: 20.3.0
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410573
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by MicroFish91** [comment]
Was the net6.0 deploy path intentional here? If not, that might be the issue.

Can you check your appService.deploy subpath by pressing F1 > Preferences: Open User Settings and make sure the path matches the one you are trying to deploy from.

**Comment by alexweininger** [comment]
What type of app are you trying to deploy? Python, .NET, etc.?
