### ISSUE TITLE
Error while deploying

### ISSUE THREAD

**Issue by jagannath-cd** [microsoft/vscode-azureappservice#2397]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.7
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
