### ISSUE TITLE
he access redacted:key UTC time '2/25/redacted:id redacted:id PM

### ISSUE THREAD

**Issue by justamal** [microsoft/vscode-azureappservice#2399]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ExpiredAuthenticationToken
Error Message: The access redacted:key UTC time '2/25/redacted:id redacted:id PM' is earlier than current UTC time '2/25/redacted:id redacted:id PM'.

Version: 0.24.7
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:1607519
deserializeResponseBody extension.bundle.js:2:1608250
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
