### ISSUE TITLE
Cannot read properties of undefined (reading 'refresh')    or    Unexpected status code: 403

### ISSUE THREAD

**Issue by rhiwn** [microsoft/vscode-azureappservice#2400]
Does this occur consistently? 
Repro steps:

Since 2 days ago I'm getting 1 of 2 issues when deploying
1. Cannot read properties of undefined (reading 'refresh')
2. Unexpected status code: 403

Action: appService.Deploy
Error type: object
Error Message: Unexpected status code: 403

Version: 0.24.7
OS: win32
OS Release: 10.0.22623
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1709073
extension.bundle.js:2:2539228
extension.bundle.js:2:2534985
```

</details>

**Comment by alexweininger** [comment]
Which version of the Azure Resources extension do you have installed?

Could you provide the exact steps you are taking when encountering these errors?
