### ISSUE TITLE
Error deploy on vivasoft app service

### ISSUE THREAD

**Issue by Patrita63** [microsoft/vscode-azureappservice#2402]
Does this occur consistently? 
Repro steps:

1.deploy on vivasoft app service
2.Message from visual code

Action: appService.Deploy
Error type: 409
Error Message: The 'Preparing zip package' operation conflicts with the pending 'Preparing zip package' operation started at redacted:id01T09redacted:id0551188Z.  Please retry operation later.

Version: 0.24.7
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by MicroFish91** [comment]
Based on the error, it seems like there is a zip operation conflict.  Does the error reproduce consistently?  If it fails again, could you try deploying from a new App Service instance and let us know if it works.  Thank you
