### ISSUE TITLE
Error ao deploy a next.js app  Azure app

### ISSUE THREAD

**Issue by DanielRBG** [microsoft/vscode-azureappservice#2404]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: socket hang up

Version: 0.24.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.0
Language: pt-br

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191279
```

</details>

**Comment by MicroFish91** [comment]
Could you please provide detailed repro steps?  Thank you
