### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by rahullabeasy** [microsoft/vscode-azureappservice#2405]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.7
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by MicroFish91** [comment]
Could you please provide additional repro steps?  Thank you
