### ISSUE TITLE
Failure to deploy Django App to Web App (using zip file with Postman not showing on Web App either)

### ISSUE THREAD

**Issue by torcuata22** [microsoft/vscode-azureappservice#2406]
Does this occur consistently? 
Repro steps:

1.Can't deploy Django app from VSCode. I keep getting the error: The deployment failed with error: Failed to deploy path that does not exist: /Users/marilynmarquez/Desktop/webster/python/filemanager/bin/Release/net6.0/publish. 
2.I've tried deploying using Postman, too, and it received the .zip file (got a 200 from postman), but the app is not showing when I go to the link

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/redacted:username/Desktop/webster/python/filemanager/bin/Release/net6.0/publish

Version: 0.24.7
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410573
fulfilled extension.bundle.js:2:2407953
```

</details>
This is the error from VSCode and the response from Postman (these are the two ways I've tried)
<img width="1440" alt="Screen Shot 2023-03-03 at 9 45 47 AM" src="https://user-images.githubusercontent.com/97114668/222764116-c3d62e14-b4f7-48c1-a79e-14c68ae64217.png">
![Screen Shot 2023-03-03 at 9 45 47 AM (2)](https://user-images.githubusercontent.com/97114668/222764122-1957d191-d441-4923-8f13-bc8b670e7cd9.png)

**Comment by MicroFish91** [comment]
Is the deploy path originating from a net6.0 path intentional here?  If not, that might be the issue.

Can you check your `appService.deploy` subpath by pressing F1 > Preferences: Open User Settings and make sure the path matches the one you are trying to deploy from.

If this is intentional, then you might need to set up a custom build script to get your deploy working

**Comment by torcuata22** [comment]
Hello, and thanks for your response. I checked appService.deploy and the path matches the one I'm trying to deploy from.

**Comment by alexweininger** [comment]
Try clearing the `appService.deploySubpath` setting and redeploy. I believe the setting value is misconfigured for a django app.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/12476526/225771951-33b9513a-4368-46e0-8c2c-54d3d451148f.png">
