### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jnxiong11** [microsoft/vscode-azureappservice#2408]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.24.7
OS: darwin
OS Release: 22.3.0
Product: Visual Studio Code
Product Version: 1.75.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by MicroFish91** [comment]
To fix this issue, you can either:

1) Initialize your local project to be a git repository using `git init`
2) Configure deployment source as `None` (zip deploy)

![image](https://user-images.githubusercontent.com/40250218/223875392-4a1fb602-1cb7-4958-b7c5-1a87d6beb5c9.png)

![image](https://user-images.githubusercontent.com/40250218/223875318-f93f6bd0-1b0b-4fb4-b53e-ae6c665aac4d.png)

**Comment by jnxiong11** [comment]
Thanks, what you said is correct.
