### ISSUE TITLE
Sort AppService tree nodes alphabetically

### ISSUE THREAD

**Issue by dhanvikapila** [Microsoft/vscode-azureappservice#241]
Its unclear how the appService applications under the subscriptions are sorted and its confusing as it stands currently.  I expected the applications to be sorted alphabetically but that doesnt seem to be case, they are also not sorted based on the latest updated/create time. So how are they sorted? 

It would be great if we could sort them alphabetically as it would be the most straightforward way.

**Comment by EricJizbaMSFT** [comment]
This has been fixed on master and will be included in a release soon (within the next week)
