### ISSUE TITLE
Failing to deploy

### ISSUE THREAD

**Issue by Belmiro-webdeveloper** [microsoft/vscode-azureappservice#2410]
Does this occur consistently? Yes 
Repro steps:

1. When I use Azure App services on vs code 
2. The deploy to the web app 
3. It gives  me error 
![image](https://user-images.githubusercontent.com/71973458/223931213-71511457-f6f7-42f5-9135-802c05f8bad9.png)

Action: appService.Deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN redacted:url

Version: 0.24.7
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.69.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:1631436
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind?

**Comment by Belmiro-webdeveloper** [comment]
No, I resolved the issue thanks

**Comment by alexweininger** [comment]
Great! Thanks for following up.
