### ISSUE TITLE
azure

### ISSUE THREAD

**Issue by OzgeVuralKoca** [microsoft/vscode-azureappservice#2414]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "ShoppingListBackandWithNodejsMongoDb-Azure" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.24.7
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.76.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410350
extension.bundle.js:2:2408199extension.bundle.js:2:2408199
S extension.bundle.js:2:2407885
extension.bundle.js:2:2410000extension.bundle.js:2:2410000
y.d extensionHostProcess.js:96:43826
y.withProgress extensionHostProcess.js:96:43669
Object.withProgress extensionHostProcess.js:117:41056
Object.<anonymous> extension.bundle.js:2:2409931
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by nturinski** [comment]
As the error indicates, you'll have to make a commit and push that up to your GitHub repo in order to deploy changes to your web app. If you want to use zip deploy, right-click your web app and change the Deployment Source to "None".
