### ISSUE TITLE
Not able to deploy an app on azure using App service

### ISSUE THREAD

**Issue by ati-jain** [microsoft/vscode-azureappservice#2415]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.7
OS: linux
OS Release: 5.19.0-35-generic
Product: Visual Studio Code
Product Version: 1.76.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by alexweininger** [comment]
Are you able to successfully deploy if you try the deployment again?

**Comment by ati-jain** [comment]
That's what I was looking for. Thanks for your help. It helped me a lot.

**Comment by MicroFish91** [comment]
Sorry that you are experiencing this issue, could you please add additional repro steps, thank you
