### ISSUE TITLE
Help fix this bag

### ISSUE THREAD

**Issue by Davud1Ramazanov** [microsoft/vscode-azureappservice#2419]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: socket hang up

Version: 0.24.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191279
```

</details>

**Comment by alexweininger** [comment]
Can you please add detailed steps to reproduce this issue? Are there any logs in the output channel you can provide?
