### ISSUE TITLE
Selecting 'No' still deploys something to my web app

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#242]
Related to https://github.com/Microsoft/vscode-azureappservice/pull/210

When I create a new web app, it asks "Deploy to Web App?", but it deploys even if I select "No"

Additionally, I have no idea what it deployed. The user is not guaranteed to have the correct repo open when they created the web app, so we need to ask them for a folder at least

**Comment by nturinski** [comment]
It uses the workspace selector, so it'll default to opened folder if there is only one.  That being said, I agree that it should include "Browse" like the Functions extension.

**Comment by EricJizbaMSFT** [comment]
@nturinski do you think you could add 'browse'? @whiskeyjay was working on another issue and this would help him out as well.

If not - I might be able to fix first thing tomorrow morning.

**Comment by EricJizbaMSFT** [comment]
@whiskeyjay I think 'Browse...' is much more important in this situation (a user setting wouldn't help). Since the functions extension already has this behavior, it shouldn't be hard to implement. I can look into it tomorrow morning if nathan doesn't get to it first.

**Comment by nturinski** [comment]
@EricJizbaMSFT  Just talked to @whiskeyjay  and he said he'd take care of it, so don't worry about it.
