### ISSUE TITLE
error deploying my angular app after ng build correctly

### ISSUE THREAD

**Issue by kintela** [microsoft/vscode-azureappservice#2422]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/redacted:username/Repos/Intranet-Angular/Intranet-app/dist\intranet-app

Version: 0.24.7
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410573
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by alexweininger** [comment]
Can you provide detailed steps to reproduce this issue?

**Comment by kintela** [comment]
What I do is ng build and then with the Azure extension I go to the app service where I want to publish the application and I execute the Deploy to web contextual menu and it doesn't ask me where the dist folder is but it gives me this error directly when try

**Comment by alexweininger** [comment]
Thank you for that explanation. Do you have a settings.json file in your workspace with the `appService.deploySubpath` setting?

<img width="471" alt="image" src="https://user-images.githubusercontent.com/12476526/229171649-6b3b30a0-a8ce-47a5-af27-87adf214b7a9.png">

**Comment by alexweininger** [comment]
It looks like the deploy subpath is invalid as it contains both forward and backward slashes. 

`/Users/redacted:username/Repos/Intranet-Angular/Intranet-app/dist\intranet-app` try fixing that and try deploying again?

It should look like: `/Users/redacted:username/Repos/Intranet-Angular/Intranet-app/dist/intranet-app`
