### ISSUE TITLE
Issue when tryingt to deploy dotnet net webapp sample project to App Service webapp using VS Code

### ISSUE THREAD

**Issue by hugobarona** [microsoft/vscode-azureappservice#2425]
Issue when tryingt to deploy dotnet net webapp sample project to App Service webapp using VS Code

Does this occur consistently? No, first time.
Repro steps:

1. Azure Sign-in in VS Code
2. App Service: Deploy web app using command pallete
3. Got the error.

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3774915extension.bundle.js:2:3774915
fulfilled extension.bundle.js:2:3773586
```

</details>

**Comment by nturinski** [comment]
As a workaround, could you try deploying by pressing the deploy button on the `Workspace` ribbon 
![image](https://user-images.githubusercontent.com/5290572/226697991-31c33c9e-f02e-4aec-bdaf-4f5dcca39339.png)

Or by right-clicking the web app that you are trying to deploy to.

**Comment by hugobarona** [comment]
Hi @nturinski. Thanks for the workaround. I end-up just using azure cli to deploy the app, but anyway just opened this bug to report the issue I was facing. It was the first time that I faced this issue, and even today I tested again, and it is all good. So not sure what the conditions were for this to happen, tbh.

**Comment by alexweininger** [comment]
The fix for this bug has been merged and is waiting to be released in the Azure Resources extension. https://github.com/microsoft/vscode-azureresourcegroups/pull/642

**Comment by hugobarona** [comment]
Thank you @alexweininger  and @nturinski.
