### ISSUE TITLE
Failed to deploy path that does not exist:

### ISSUE THREAD

**Issue by mahdikhiat** [microsoft/vscode-azureappservice#2426]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /Users/redacted:username/Desktop/ReadIT/inventory/bin\Release\net6.0\publish

Version: 0.24.7
OS: darwin
OS Release: 22.2.0
Product: Visual Studio Code
Product Version: 1.76.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410573
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by nturinski** [comment]
Please add detailed repro steps.

**Comment by alexweininger** [comment]
What type of web app are you trying to deploy? Is it .NET, Python, Node, etc.?
