### ISSUE TITLE
Fail to execute "Azure App Service: Configure Deployment Source..." command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2429]
**OS:** All
**Build Version:** 20230320.1
**Regression:** Previous Release

**Repro Steps:**

1. F1 -> Azure App Service: Configure Deployment Source... -> Select a subscription -> Select a resource -> Select a new source.
2. Check whether succeeds to execute "Azure App Service: Configure Deployment Source..." command.

**Expect:**
Succeed to execute "Azure App Service: Configure Deployment Source..." command.

**Actual:**
Fail to execute "Azure App Service: Configure Deployment Source..." command from command palette.
![image](https://user-images.githubusercontent.com/107091828/226565459-96fb33af-da86-46fd-8fe2-066764b1773e.png)

**More Info:**
This issue does not reproduce when executing "Configure Deployment Source..." action from context menu.

**Comment by nturinski** [comment]
Could you please try to reproduce this again? We have released many things that may have fixed this and related issues.

**Comment by v-chenzha** [comment]
@nturinski  Verified this issue on the latest build 20230531.1, it doesn't reproduce for now. So close it.
