### ISSUE TITLE
Fail to execute "Azure App Service: Stop/Start/Restart" command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2430]
**OS:** All
**Build Version:** 20230320.1
**Regression:** Previous Release

**Repro Steps:**

1. F1 -> Azure App Service: Stop -> Select a subscription -> Select a resource.
2. Check whether succeeds to execute "Azure App Service: Stop" command.

**Expect:**
Succeed to execute "Azure App Service: Stop" command.

**Actual:**
Fail to execute "Azure App Service: Stop" command from command palette.
![image](https://user-images.githubusercontent.com/107091828/226567950-6cc685e1-b484-4ad5-a359-4089ba6ca22d.png)

**More Info:**
1. This issue does not reproduce when executing "Stop/Start/Restart" action from context menu.
2. This issue also reproduces when executing "Azure App Service: Restart" command from command palette.
![image](https://user-images.githubusercontent.com/107091828/226568750-56f40d79-e2d5-4fe1-b058-8046592cc306.png)
3. This issue also reproduces when executing "Azure App Service: Start" command from command palette.
![image](https://user-images.githubusercontent.com/107091828/226570784-dab6e12b-d268-4754-b9a6-e3698830e13e.png)

**Comment by v-chenzha** [comment]
@alexweininger There is a video about this issue. This issue is irregular. It only reproduces during a certain time of day. Other time periods are normal.
![3](https://user-images.githubusercontent.com/107091828/226787738-ce3d920b-b69b-4372-bcff-5fb361d9130c.gif)

**Comment by alexweininger** [comment]
The fix for the create client bug has been merged and is waiting to be released in the Azure Resources extension. https://github.com/microsoft/vscode-azureresourcegroups/pull/642
