### ISSUE TITLE
VS Code Azure app deployment

### ISSUE THREAD

**Issue by theElephants** [microsoft/vscode-azureappservice#2432]
Does this occur consistently? 
Repro steps:

1. Using Azure App Services (VS code extension)
2. Locate App Services and right click on the App
3. Select Deploy to Web App
4. Choose project root directory
5. Select Yes to "Would you like to update your workspace configuration to run build commands on the target server?"
6. Select Deploy to "Are you sure you want to deploy to Service? This will overwrite any previous deployment and cannot be undone."
7. Wait for deploy to fail

Action: appService.Deploy
Error type: object
Error Message: <div style="display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;"><h1 style="color: redacted:id">:( Application Error</h1><p style="color:#666">If you are the application administrator, you can access the <a style="color: grey"href="redacted:url resources</a>.</div>

Version: 0.24.7
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1709073
extension.bundle.js:2:2539228
extension.bundle.js:2:2534985
```

</details>

**Comment by nturinski** [comment]
Could you please add repro steps?

**Comment by theElephants** [comment]
> Could you please add repro steps?

I updated the repo steps.

**Comment by alexweininger** [comment]
It looks like your app is failing to start once it's deployed. Are there any details in the deploy logs that could help out?

Can you verify that your app runs locally first before deploying?

**Comment by theElephants** [comment]
It runs locally and also runs on the server when uploaded manually. The
issue occurs during the extensions build process. It happens everytime but
not always at the same point of the build. I can also build manually and
that works just fine. The extension wants to build it on the server and
doesnt want my build folder. The only reason I want to use the extension is
because then I can just deploy without having to share files back and
fourth.

**Comment by alexweininger** [comment]
Can you check what app settings you have, specifically any related to the build/deploy process.

If you have the `SCM_DO_BUILD_DURING_DEPLOYMENT` enabled, try disabling that setting.

<img width="871" alt="image" src="https://user-images.githubusercontent.com/12476526/230508355-b883c4aa-75be-42b5-be69-61c110205958.png">

https://learn.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#deployment-customization
