### ISSUE TITLE
ERROR Hosting app

### ISSUE THREAD

**Issue by Neutrolabs** [microsoft/vscode-azureappservice#2437]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND redacted:url

Version: 0.24.7
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:1631436
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
