### ISSUE TITLE
Error: Failed to get status of deployment (azure git local and deployment proyect next js .next size 2.7 gb)

### ISSUE THREAD

**Issue by RomanshkVolkov** [microsoft/vscode-azureappservice#2438]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.8
OS: linux
OS Release: 5.15.90.1-microsoft-standard-WSL2
Product: Visual Studio Code
Product Version: 1.76.2
Language: es

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
