### ISSUE TITLE
Azure app service extenstion

### ISSUE THREAD

**Issue by Kavaljeetarya** [microsoft/vscode-azureappservice#2439]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: not a git repository (or any of the parent directories): .git

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.77.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
