### ISSUE TITLE
time zone

### ISSUE THREAD

**Issue by Kavaljeetarya** [microsoft/vscode-azureappservice#2442]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ExpiredAuthenticationToken
Error Message: The access redacted:key UTC time '3/27/redacted:id redacted:id PM' is earlier than current UTC time '3/28/redacted:id redacted:id AM'.

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.77.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:1607519
deserializeResponseBody extension.bundle.js:2:1608250
```

</details>

**Comment by Kavaljeetarya** [comment]
1

**Comment by alexweininger** [comment]
Please add detailed repro steps.
