### ISSUE TITLE
Error 400 BadRequest when deploying

### ISSUE THREAD

**Issue by ShineCsLabs** [microsoft/vscode-azureappservice#2445]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 400
Error Message: redacted:id BadRequest

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed repro steps.
