### ISSUE TITLE
Deploy doesnt work

### ISSUE THREAD

**Issue by Adame33** [microsoft/vscode-azureappservice#2449]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected redacted:key in JSON at position 0" occurred while parsing the response body - <div style="display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;"><h1 style="color: redacted:id">:( Application Error</h1><p style="color:#666">If you are the application administrator, you can access the <a style="color: grey"href="redacted:url resources</a>.</div>
.

Version: 0.24.8
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.77.0
Language: es

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
errorHandler extension.bundle.js:2:1694826
```

</details>

**Comment by MicroFish91** [comment]
What type of project are you deploying?  Have you been able to deploy successfully in the past?
