### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrvaibhavsharma** [microsoft/vscode-azureappservice#2453]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "vaibhavdello" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.24.8
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.77.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410350
extension.bundle.js:2:2408199extension.bundle.js:2:2408199
S extension.bundle.js:2:2407885
extension.bundle.js:2:2410000extension.bundle.js:2:2410000
D.d extensionHostProcess.js:98:46171
D.withProgress extensionHostProcess.js:98:46014
Object.withProgress extensionHostProcess.js:114:34084
Object.<anonymous> extension.bundle.js:2:2409931
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by nturinski** [comment]
Your web app is connected to a GitHub repository. All you need to do is commit and push to that repository.
