### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kfarrukh** [microsoft/vscode-azureappservice#2454]
Does this occur consistently? yes
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 404
Error Message: 404 Web Site not found.

You may be seeing this error due to one of the reasons listed below :

 * Custom domain has not been configured inside Azure. See how to map an existing domain [redacted:url to resolve this.
 * Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.

Checkout App Service Domain FAQ [redacted:url for more questions.

Version: 0.24.8
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
