### ISSUE TITLE
Error Deploying to Azure App Service NodeJS

### ISSUE THREAD

**Issue by cbreakspear** [microsoft/vscode-azureappservice#2455]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: UNKNOWN
Error Message: UNKNOWN: unknown error, scandir 'c:\Users\redacted:username\OneDrive - Prolifics Corporation redacted:email

Version: 0.24.8
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.77.1
Language: en

**Comment by nturinski** [comment]
Please app repro steps.
