### ISSUE TITLE
Cannot update existing app service

### ISSUE THREAD

**Issue by Ellosaur** [microsoft/vscode-azureappservice#2456]
Does this occur consistently? Yes
Repro steps:

1. Select an existing API folder in VS code
2. Right click and select "Deploy to Web app"
3.  Select the existing web app deployment from the list
4. Error occurs `Cannot read properties of undefined (reading 'createClient')`

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.70.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3774915extension.bundle.js:2:3774915
fulfilled extension.bundle.js:2:3773586
```

</details>

**Comment by alexweininger** [comment]
Which version of the Azure Resources extension are you using?

A workaround for this issue is right-clicking on the web app itself and selecting Deploy instead of right clicking the folder.
