### ISSUE TITLE
11:24:15 AM: Error: The access token expiry UTC time '4/15/2023 7:40:04 AM' is earlier than current UTC time '4/15/2023 8:24:15 AM'.

### ISSUE THREAD

**Issue by castrombithisamm** [microsoft/vscode-azureappservice#2457]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ExpiredAuthenticationToken
Error Message: The access redacted:key UTC time '4/15/redacted:id redacted:id AM' is earlier than current UTC time '4/15/redacted:id redacted:id AM'.

Version: 0.24.8
OS: linux
OS Release: 5.19.0-38-generic
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:1607519
deserializeResponseBody extension.bundle.js:2:1608250
```

</details>

**Comment by nturinski** [comment]
Could you please provide detailed repro steps? Did you leave your VS Code window opened for a long time? Or is this through VS Code for the Web?
