### ISSUE TITLE
Azure Deployment fail

### ISSUE THREAD

**Issue by daedalusdigital-za** [microsoft/vscode-azureappservice#2458]
Does this occur consistently? 
Repro steps:

1. I tried to deploy it to my web app on Azure and In the output i get a message 
2. Error: An error has occurred.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.8
OS: darwin
OS Release: 17.7.0
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by nturinski** [comment]
Sometimes the service is down and re-trying will just work.

If it still isn't working, what kind of project are you deploying? And to what type of app service?
