### ISSUE TITLE
Unable to Deploy the Office-Addin Web App

### ISSUE THREAD

**Issue by Test-evc** [microsoft/vscode-azureappservice#2460]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
