### ISSUE TITLE
deployment issues while uploading from VS code

### ISSUE THREAD

**Issue by Taqveemammag** [microsoft/vscode-azureappservice#2461]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:1690253
step extension.bundle.js:2:1756133
Object.throw extension.bundle.js:2:1756238
rejected extension.bundle.js:2:1754963
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
