### ISSUE TITLE
Render issue in resources view

### ISSUE THREAD

**Issue by fsigalov** [microsoft/vscode-azureappservice#2463]
Somehow the resource view is trying to write multiple strings to the same line. You can see the result in the picture. running v.0.24.8 on win 11.
![image](https://user-images.githubusercontent.com/17628060/234064791-20a368ab-522e-4ea4-86c0-2475700c0378.png)

**Comment by nturinski** [comment]
Uhhhh.... is this reproducing consistently? 

Does reloading or refreshing do anything to fix this?

If not, my only hunch is that looks like a bunch of application settings in the background. Maybe there's an overflow of tree items or something?

**Comment by fsigalov** [comment]
when I restarted vs code this went away and I haven't seen it since. I wanted to open the issue though because it looked super weird.

**Comment by nturinski** [comment]
This was definitely a VS Code issue that has now been resolved.
