### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rudy-stephane** [microsoft/vscode-azureappservice#2465]
- Issue Type: `Performance`
- Extension Name: `vscode-azureappservice`
- Extension Version: `0.24.8`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.77.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/stekam/AppData/Local/Temp/1/ms-azuretools.vscode-azureappservice-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nturinski** [comment]
Please make sure to **attach** this file from your *home*-directory:
`file:///c%3A/Users/stekam/AppData/Local/Temp/1/ms-azuretools.vscode-azureappservice-unresponsive.cpuprofile.txt`
