### ISSUE TITLE
Unable to deploy app service from VS code

### ISSUE THREAD

**Issue by PNFPS** [microsoft/vscode-azureappservice#2466]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3774915extension.bundle.js:2:3774915
fulfilled extension.bundle.js:2:3773586
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
