### ISSUE TITLE
deployment issue

### ISSUE THREAD

**Issue by tharunS123** [microsoft/vscode-azureappservice#2467]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: <div style="display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;"><h1 style="color: redacted:id">:( Application Error</h1><p style="color:#666">If you are the application administrator, you can access the <a style="color: grey"href="redacted:url resources</a>.</div>

Version: 0.24.8
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1709073
extension.bundle.js:2:2539228
extension.bundle.js:2:2534985
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
