### ISSUE TITLE
error deploy vs code azure

### ISSUE THREAD

**Issue by jamitengola** [microsoft/vscode-azureappservice#2469]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to find pre-deploy task "publish-release". Modify your tasks or the setting "appService.preDeployTask".

Version: 0.24.8
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2427803
fulfilled extension.bundle.js:2:2424934
```

</details>

**Comment by nturinski** [comment]
Could you please add repro steps?
