### ISSUE TITLE
Deployment already running

### ISSUE THREAD

**Issue by varndellwagglebee** [microsoft/vscode-azureappservice#2470]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.DeploySlot
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.74.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
