### ISSUE TITLE
Erro ao efetuar deploy de uma aplicação Angular

### ISSUE THREAD

**Issue by RaulBBrito** [microsoft/vscode-azureappservice#2471]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.8
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
