### ISSUE TITLE
React App Deployment Issue

### ISSUE THREAD

**Issue by dev-dev-7** [microsoft/vscode-azureappservice#2472]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.8
OS: darwin
OS Release: 22.1.0
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
