### ISSUE TITLE
ISSUE FOR DEPLOYIOING django app

### ISSUE THREAD

**Issue by hghalebi** [microsoft/vscode-azureappservice#2473]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "tp1DjangoApp" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.24.8
OS: linux
OS Release: 6.2.6-76060206-generic
Product: Visual Studio Code
Product Version: 1.77.3
Language: fr

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410350
extension.bundle.js:2:2408199
S extension.bundle.js:2:2407885
extension.bundle.js:2:2410000
D.d extensionHostProcess.js:98:46171
D.withProgress extensionHostProcess.js:98:46014
Object.withProgress extensionHostProcess.js:114:34084
Object.<anonymous> extension.bundle.js:2:2409931
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
