### ISSUE TITLE
Error trying to deploy nextjs app

### ISSUE THREAD

**Issue by LALauw** [microsoft/vscode-azureappservice#2477]
Does this occur consistently? Yes
Repro steps:

1. create next app
2. try to deploy using the azure app service extension from vs coded

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: read ECONNRESET

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.0
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191476
```

</details>

**Comment by alexweininger** [comment]
Could you retry the deployment and provide logs from the output channel?
