### ISSUE TITLE
extension issue

### ISSUE THREAD

**Issue by RohitGadhave** [microsoft/vscode-azureappservice#2479]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND redacted:url

Version: 0.24.8
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:1631436
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
