### ISSUE TITLE
Socket HangUp

### ISSUE THREAD

**Issue by Ashishkumarpanda** [microsoft/vscode-azureappservice#2480]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: socket hang up

Version: 0.24.8
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.78.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191476
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
