### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by dev-dev-7** [microsoft/vscode-azureappservice#2482]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.24.8
OS: darwin
OS Release: 22.1.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
