### ISSUE TITLE
deploying using visual studio show this error

### ISSUE THREAD

**Issue by Aamir9** [microsoft/vscode-azureappservice#2485]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.24.8
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1709073
extension.bundle.js:2:1690253
extension.bundle.js:2:1756133
extension.bundle.js:2:1756238
extension.bundle.js:2:1754963
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind?

Please add detailed steps to reproduce the issue.
