### ISSUE TITLE
Issue with deployment from vscode

### ISSUE THREAD

**Issue by AbdelkhalekBakkari** [microsoft/vscode-azureappservice#2486]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Redeploy
Error type: Error
Error Message: Redeploy is not supported for non-git deployments.

Version: 0.24.8
OS: linux
OS Release: 5.15.0-71-generic
Product: Visual Studio Code
Product Version: 1.77.1
Language: en

<details>
<summary>Call Stack</summary>

```
DeploymentTreeItem.<anonymous> extension.bundle.js:2:2474947
extension.bundle.js:2:2473445
S extension.bundle.js:2:2473131
DeploymentTreeItem.redeployDeployment extension.bundle.js:2:2474874
extension.bundle.js:2:3796910
extension.bundle.js:2:3796495
S extension.bundle.js:2:3796181
redeployDeployment extension.bundle.js:2:3796683
extension.bundle.js:2:2667327
fulfilled extension.bundle.js:2:2666601
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.

**Comment by AbdelkhalekBakkari** [comment]
My yml file is : 
`# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - az-authen

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: | 
         sudo apt-get update
         sudo apt-get install -y build-essential cmake libopenblas-dev libjpeg-dev libpng-dev libtiff-dev
         pip install --upgrade pip
         pip install dlib
         pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'az-authen'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_767DD8298AD54E87964EE765A6F89BB2 }}`
          
          The error which I am getting is : 
          `[14:59:36+0000]   Building wheel for dlib (setup.py): started
[14:59:37+0000]   Building wheel for dlib (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
      running build_ext
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
[14:59:37+0000]   Running setup.py clean for dlib
[14:59:37+0000] Successfully built django-extensions
`

**Comment by AbdelkhalekBakkari** [comment]
Could you please provide me with your feedback?

**Comment by alexweininger** [comment]
The original error you're facing indicates that your app is not connected to a git repository for deployments. Anything zip deployed is readonly and cannot be redeployed.

**Comment by AbdelkhalekBakkari** [comment]
Thank you!
