### ISSUE TITLE
Deploy Node Project

### ISSUE THREAD

**Issue by iGen-Sam** [microsoft/vscode-azureappservice#2489]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 403
Error Message: Error 403 - Forbidden

The web app you have attempted to reach has blocked your access.

Version: 0.24.9
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: de

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
