### ISSUE TITLE
Dotnet App service deployment issue

### ISSUE THREAD

**Issue by maosierra** [microsoft/vscode-azureappservice#2491]
Does this occur consistently? 
Repro steps:

1. Select generated dotnet publish folder
2. Deploy app service

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Does this issue reproduce if you retry the deployment?

**Comment by maosierra** [comment]
> Does this issue reproduce if you retry the deployment?

Correct it is not possible to publish the API (dotnet core 7) to the app service using VS Code. I am using FTP deployments for the moment.

**Comment by alexweininger** [comment]
@maosierra, does this issue still produce on version 0.25.0 of the App Service extension?
