### ISSUE TITLE
Error type: 400

### ISSUE THREAD

**Issue by ShineCsLabs** [microsoft/vscode-azureappservice#2493]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy

Error Message: redacted:id BadRequest

Version: 0.24.9
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
