### ISSUE TITLE
 Cannot read properties of undefined (reading 'createClient')

### ISSUE THREAD

**Issue by yashavanth-acharya** [microsoft/vscode-azureappservice#2494]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.9
OS: linux
OS Release: 5.4.0-144-generic
Product: Visual Studio Code
Product Version: 1.75.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3774912
fulfilled extension.bundle.js:2:3773583
```

</details>

**Comment by alexweininger** [comment]
What version of the Azure Resource Groups extension do you have installed? Make sure you're on the latest version.

Also, please provide detailed repro steps so we can investigate the issue.
