### ISSUE TITLE
Failed to get status of deployment.

### ISSUE THREAD

**Issue by ShineCsLabs** [microsoft/vscode-azureappservice#2495]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.9
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2436391extension.bundle.js:2:2436391
rejected extension.bundle.js:2:2434001
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
