### ISSUE TITLE
Error while deploying quarkus code to web-app

### ISSUE THREAD

**Issue by a487518** [microsoft/vscode-azureappservice#2496]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.9
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
