### ISSUE TITLE
Deploying NEXT js app to azure apps service with windows from vs code .

### ISSUE THREAD

**Issue by usamastr** [microsoft/vscode-azureappservice#2497]
Also previously tried with linux but still couldnt get the app runing .

Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.70.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.

**Comment by usamastr** [comment]
alex thanks for the reply .
Simply just created a next js app added some content images .
build is working fine on dev runing on port 3000 .
tried to deploy it on azure app service with push from vs code it did deploy it sucessfully but content was not available .azure default page was shown .
then i tried to deploy it from git hub repo still it also deployed sucessfuly but showed APPLICATION Error if you are administrator use diagnostic tool .
tried adding server.js file but couldnt get the app working on any host .
Also tried to host it on cpanel hosting that didnt even detect package.json so i moved to azure for that.
