### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pealmeid** [microsoft/vscode-azureappservice#2504]
- Issue Type: `Performance`
- Extension Name: `vscode-azureappservice`
- Extension Version: `0.24.9`
- OS Version: `Darwin arm64 22.4.0`
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/hj/bh6b5yf5347_zr_88kcj7x_40000gn/T/ms-azuretools.vscode-azureappservice-unresponsive.cpuprofile.txt`

Find more details here: [ms-azuretools.vscode-azureappservice-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-azureappservice/files/11636741/ms-azuretools.vscode-azureappservice-unresponsive.cpuprofile.txt)

**Comment by alexweininger** [comment]
Could you share more details about what you were doing in the extension when this warning appeared?
