### ISSUE TITLE
issue with deployment in Azure Web app

### ISSUE THREAD

**Issue by parthcompengg** [microsoft/vscode-azureappservice#2505]
Does this occur consistently? 
Repro steps:

1.  deployed an application via Azure deployment extension in visual studio code.
![image](https://github.com/microsoft/vscode-azureappservice/assets/115192971/5142860f-fa5b-4104-85bc-0b9ba9f0d612)

2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Does this issue reproduce consistently? Are there any logs in the output channel that provide more info?
