### ISSUE TITLE
An error occurs after executing the command "SSH into Web App" for a Linux web app

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2506]
**OS:** Win10
**Azure App Service Extension Build Version:** 20230604.1
**Azure Resources Extension Version:** v0.7.5

**Repro Steps:**

1. Right click a Linux web app -> Click "SSH into Web App".
2. Check whether succeeds to execute the command "SSH into Web App".

**Expect:**
Succeed to execute the command "SSH into Web App".

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-azureappservice/assets/107091828/bcac8ba6-dc50-4c87-9a18-628204f1d686)

**More Info:**
This issue also reproduces when executing the command "Start Remote debugging".

**Comment by alexweininger** [comment]
I was able to repro this. Works as expected on the portal.

**Comment by v-xinda** [comment]
Verified this issue on the main branch build 20230719.1, another error pops up after executing "SSH into Web App" and "Start Remote debugging" actions.
![image](https://github.com/microsoft/vscode-azureappservice/assets/57662131/29fb667f-ca8b-4c3f-baab-123ae4f79da2)

**Comment by alexweininger** [comment]
I'm getting the same 401 error when I try to use `az webapp ssh` from the Azure CLI v2.47.0, but on v2.50.0 it works. Something with the service must have changed.

**Comment by alexweininger** [comment]
Looks like we need to apply the same fix that the Azure CLI did here https://github.com/Azure/azure-cli/pull/26229

**Comment by v-ruizh** [comment]
This issue has been fixed on the latest build 20230719.13.
