### ISSUE TITLE
request to redacted:url failed, reason: socket hang up

### ISSUE THREAD

**Issue by MatosLarissa** [microsoft/vscode-azureappservice#2508]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: socket hang up

Version: 0.24.9
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: pt-br

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191473
```

</details>

**Comment by alexweininger** [comment]
Please add detailed steps to reproduce the issue.
