### ISSUE TITLE
File editing need better error handling

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azureappservice#251]
1. Create a web app.
2. Deploy to production.
3. Create a new slot.
4. Expand the Files node from production.
5. Swap slot with production.
6. Because of #250, the Files node doesn't auto-refresh, now from the Files node, try to edit a file that doesn't exists in the production (previously the new slot).

You'll get this error:
![image](https://user-images.githubusercontent.com/15821566/34062180-18343a40-e1a0-11e7-98d3-66186c367476.png)

And this error message in the editor (which is not the content of the file because the file doesn't exist):
![image](https://user-images.githubusercontent.com/15821566/34062218-40e6f50e-e1a0-11e7-8f71-b74da570e26f.png)

When you save, the file will be uploaded as a new file.

The correct behavior should be a message saying what the server error response say, in this case "'/home/site/wwwroot/cseries.azcli' not found."

**Comment by nturinski** [comment]
This was fixed by https://github.com/Microsoft/vscode-azuretools/pull/59.   I'll go ahead and close this.
