### ISSUE TITLE
Issue deploying website to Azure Web Apps

### ISSUE THREAD

**Issue by malcolmdomecq** [microsoft/vscode-azureappservice#2510]
Does this occur consistently? 
Repro steps:
I initiated the deploy from Visual Studio Code for Mac

1.
2.

Action: appService.Deploy
Error type: 400
Error Message: redacted:id BadRequest

Version: 0.24.9
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please fill out the information requested in the issue description.
