### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by tpkphani1** [microsoft/vscode-azureappservice#2513]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

Version: 0.24.9
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:4191473
```

</details>

**Comment by alexweininger** [comment]
Update to the latest version of VS Code to fix this issue.
