### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by Mosuhli-Coder** [microsoft/vscode-azureappservice#2514]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: request to redacted:url failed, reason: read ECONNRESET

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:4191473
```

</details>

**Comment by alexweininger** [comment]
Please fill out the information requested in the issue description.
