### ISSUE TITLE
deployment issue 

### ISSUE THREAD

**Issue by Dxuian** [microsoft/vscode-azureappservice#2515]
Does this occur consistently? 
yes 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Please fill out the information requested in the issue description. Are there any relevant logs from the deployment? What sort of app are you trying to deploy?
