### ISSUE TITLE
unable to deploy

### ISSUE THREAD

**Issue by Dxuian** [microsoft/vscode-azureappservice#2516]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by alexweininger** [comment]
Please fill out the information requested in the issue description.
