### ISSUE TITLE
unable to deploy nodejs to azure 

### ISSUE THREAD

**Issue by sultan2099** [microsoft/vscode-azureappservice#2521]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: socket hang up

Version: 0.24.9
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191473
```

</details>

**Comment by alexweininger** [comment]
Please fill out the information requested in the issue description.
