### ISSUE TITLE
deploying your webapp on azure free tier 95% chance of failing

### ISSUE THREAD

**Issue by juanc07** [microsoft/vscode-azureappservice#2522]
Does this occur consistently? 
Repro steps:

1. yes
2. 95% chance
3. just deploy your webapp using visual studio code azure plugin

Action: appService.Deploy
Error type: object
Error Message: <div style="display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;"><h1 style="color: redacted:id">:( Application Error</h1><p style="color:#666">If you are the application administrator, you can access the <a style="color: grey"href="redacted:url resources</a>.</div>

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1709073
extension.bundle.js:2:2539228
extension.bundle.js:2:2534985
```

</details>

**Comment by alexweininger** [comment]
Please provide details about the project you're trying to deploy to help us investigate the issue.

**Comment by juanc07** [comment]
Already have a workaround make sure to delete everything before deploying

**Comment by MicroFish91** [comment]
Glad you were able to find a workaround!
