### ISSUE TITLE
Message: request to redacted:url failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by eincioch** [microsoft/vscode-azureappservice#2523]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: request to redacted:url failed, reason: read ECONNRESET

Version: 0.24.9
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.79.2
Language: es

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:4191473
```

</details>

**Comment by alexweininger** [comment]
Please fill out the requested information in the issue description.
