### ISSUE TITLE
Failed to deploy path that does not exist

### ISSUE THREAD

**Issue by CleitonE** [microsoft/vscode-azureappservice#2524]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: c:\Users\redacted:username\Desktop\projeto-final-master\apparteyment\bin\Release\net6.0\publish

Version: 0.24.9
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410573
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by alexweininger** [comment]
Please provide detailed information about the project you're deploying.

Are you deploying a .NET project?
