### ISSUE TITLE
error occurs when i am deploying the node js project using puppeteer downloader

### ISSUE THREAD

**Issue by shivareddy1287** [microsoft/vscode-azureappservice#2527]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Can you please provide more details about the project you're deploying and the error you encountered. Please add any logs you have and any steps you took before running into the error.
