### ISSUE TITLE
committed branch showing error

### ISSUE THREAD

**Issue by amitlals** [microsoft/vscode-azureappservice#2529]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: your current branch 'main' does not have any commits yet

Version: 0.24.9
OS: win32
OS Release: 10.0.22623
Product: Visual Studio Code
Product Version: 1.79.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2208177extension.bundle.js:2:2208177
rejected extension.bundle.js:2:2206767
```

</details>

**Comment by nturinski** [comment]
Looks like you haven't committed any changes to your repository yet. In a terminal, you should be able to run

```
git add .
git commit -m 'Initial commit'
```

That should resolve your issue. Please reopen if it doesn't help.
