### ISSUE TITLE
500 Deployment Error

### ISSUE THREAD

**Issue by JamesMHerrington** [microsoft/vscode-azureappservice#2534]
Does this occur consistently? Yes
Repro steps:

1.  Using the extension, I select deploy
2. I expect it to deploy, but I receive that an error has occurred.  

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by nturinski** [comment]
What tier is your app service plan? Unfortunately, the free tier can have outages, and usually that's what a 500 error is indicating. Unfortunately, if it is a service issue, there isn't a lot that we can do to help. 

Could you please try deploying again and see if this is still occurring?
