### ISSUE TITLE
APP Deploy Failed

### ISSUE THREAD

**Issue by yk3lee** [microsoft/vscode-azureappservice#2537]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: site

Version: 0.24.9
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:2:3867078
Proxy.<anonymous> extension.bundle.js:2:3848180
fulfilled extension.bundle.js:2:3846380
```

</details>

**Comment by nturinski** [comment]
Could you please provide some detailed repro steps and answer the following questions?
- What type of Azure account are you using? Student or anything that is not standard Azure?
- Do you remember how you created this web app?
- Do you know the SKU of your app service plan?
