### ISSUE TITLE
deploy failure occuring 

### ISSUE THREAD

**Issue by Dxuian** [microsoft/vscode-azureappservice#2538]
Does this occur consistently? 
Repro steps:

1.change deployment source via vscode az app extension to github 
2.deploy web app 

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.80.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

```[tasklist]
### Tasks
```

**Comment by nturinski** [comment]
Were you able to successfully hook up your web app to a GitHub repository? 

If yes, then all you should have to do to deploy is push a change to the repository it is hooked up with.

If no, what error are you seeing at the time you are trying to change the deployment source? This appears to be a deployment error.
