### ISSUE TITLE
failed, reason: socket hang up

### ISSUE THREAD

**Issue by intelecision** [microsoft/vscode-azureappservice#2539]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: socket hang up

Version: 0.24.9
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.80.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191473
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
