### ISSUE TITLE
no permite deploy

### ISSUE THREAD

**Issue by YuderHernandez** [microsoft/vscode-azureappservice#2543]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "proyectocontrolBanda" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.80.1
Language: es

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:2:2410350
extension.bundle.js:2:2408199extension.bundle.js:2:2408199
S extension.bundle.js:2:2407885
extension.bundle.js:2:2410000extension.bundle.js:2:2410000
k.d extensionHostProcess.js:97:43474
k.withProgress extensionHostProcess.js:97:43337
Object.withProgress extensionHostProcess.js:117:31108
Object.<anonymous> extension.bundle.js:2:2409931
fulfilled extension.bundle.js:2:2407953
```

</details>

**Comment by nturinski** [comment]
"proyectocontrolBanda" is connected to a GitHub repository. Push to GitHub repository to deploy.
