### ISSUE TITLE
The deployed project doesn't show under the "Files" node after deploying a project to web app

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azureappservice#2544]
**OS:** Win10
**Build Version:** 20230717.1
**Regression:** Preview Release

**Repro Steps:**

1. Create a web app -> Deploy a project to it.
2. Expand the "Files" node.
3. Check whether the deployed project shows under the "Files" node.

**Expect:**
The deployed project shows under the "Files" node.

**Actual:**
The deployed project doesn't show under the "Files" node.

**Comment by alexweininger** [comment]
Yeah the Files feature is broken. I'm guessing from https://github.com/microsoft/vscode-azuretools/pull/1450/files#diff-e5441c0191cfea1b2d365b04d1bafdafa0adeead2ead9b8b8154a7b5cbd92238.

I looked at it and the request doesn't have any auth header.
