### ISSUE TITLE
Deploy to custom image web apps can fail silently

### ISSUE THREAD

**Issue by whiskeyjay** [microsoft/vscode-azureappservice#256]
1. Deploy a web app using a custom Linux image from the Docker extension.
2. From the App Service extension, try to deploy a project to the web app created in step 1.

Expected:
Either the deployment should succeed or there should be an error message saying why it failed.

Actual:
The output window says deployment succeeded, but nothing changed in the web app.

The extension should detect custom image and give warning when users trying to deploy from the extension because it's anti-pattern.

**Comment by whiskeyjay** [comment]
And we also need to figure out how this should work with other SCM configurations.

**Comment by whiskeyjay** [comment]
@fiveisprime @chrisdias 

How about when a custom Linux image is detected upon "Deploy" command, the extension show an error message and direct user to proper steps (or maybe the Docker extension readme?) for such deployment scenario?

**Comment by chrisdias** [comment]
Don't you already say that the site will be overwritten? If so, I would expect that the site is completely overwritten, which means clearing out the image app settings.
