### ISSUE TITLE
cannot deploy angular web app to azure app service

### ISSUE THREAD

**Issue by lztli** [microsoft/vscode-azureappservice#2568]
Does this occur consistently? yes
Repro steps:

1. in vs code, create an angular app

    Angular CLI: 16.0.5
    Node: 18.12.1
    Package Manager: npm 8.19.2
    OS: win32 x64

    Angular: 16.0.4
    ... animations, common, compiler, compiler-cli, core, forms
    ... platform-browser, platform-browser-dynamic, router

    Package                         Version
    ---------------------------------------------------------
    @angular-devkit/architect       0.1600.5
    @angular-devkit/build-angular   16.0.5
    @angular-devkit/core            16.0.5
    @angular-devkit/schematics      16.0.5
    @angular/cdk                    16.1.1
    @angular/cli                    16.0.5
    @angular/material               16.1.1
    @schematics/angular             16.0.5
    rxjs                            7.8.1
    typescript                      5.0.4

3. in azure portal create a new app service
4. in vs code, deploy to azure 
5. got "Error: An error has occurred." 

Action: appService.Deploy
Error type: 500
Error Message: An error has occurred.

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by alexweininger** [comment]
Can you share the logs from the output channel?
