### ISSUE TITLE
No way to see the entire info after zooming in more than 6 times using 'Ctrl+='

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#257]
Repro Step:
1. Launch VS Code then zoom in more than 6 times using 'Ctrl+='.
2. Check whether we can see the entire info or not.

Expect:
The scrollbar in the right side displays well, in this case we can pull it to see the entire info.

Actual:
The scrollbar in the right side disappears from view. Please see the attachment.
![scrolbar](https://user-images.githubusercontent.com/34729092/34250268-4b0b8e60-e677-11e7-8b93-768544b2f886.png)

**Comment by StephenWeatherford** [comment]
We should only be testing zoom up to 200% (pressing the button 4x). Thanks.

**Comment by v-dantch** [comment]
Hi Stephen, 

Thanks  a lot for your update.
