### ISSUE TITLE
what is the reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by kanagao1** [microsoft/vscode-azureappservice#2573]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: request to redacted:url failed, reason: unable to get local issuer certificate

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.82.2
Language: ja

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191473
```

</details>

**Comment by alexweininger** [comment]
Do you have a proxy configured? If so, please configure the proxy properly in VS Code. There are docs for how to do this here: https://code.visualstudio.com/docs/setup/network.
