### ISSUE TITLE
Display group glyph when there is no sub-node after expanding 'Deployment Slots/WebJobs'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#258]
Repro Step:
1. Create a web app in VS Code.
2. Click the 'Deployment Slots/WebJobs' node to expand it.

Expect:
There is no group glyph when there is no sub-node. 

Actual:
Display group glyph when there is no sub-node. Please see the attachment.

Attachment:
![group glyph](https://user-images.githubusercontent.com/34729092/34250325-7e552fec-e677-11e7-8a3f-1efb55308588.png)

**Comment by whiskeyjay** [comment]
Thanks for reporting this.

It is the expected behavior which aligns with other TreeView controls in VSC (for example, the File Explorer).
