### ISSUE TITLE
The operation was aborted while deploy python to app services

### ISSUE THREAD

**Issue by MrLinkGe** [microsoft/vscode-azureappservice#2587]
![image](https://github.com/microsoft/vscode-azureappservice/assets/149657935/a2aac9ed-e43a-4c19-ab86-c366c1dce8e6)

**Comment by MicroFish91** [comment]
Could you please provide repro steps to give additional context to the error? Also please let me know if you are able to provide a breakdown of your folder structure as that could help us determine what the issue is as well.

Thank you.
