### ISSUE TITLE
The listed nodes aren't collapsed after clicking 'Refresh' in the subscription context menu/toolbar

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#259]
Repro Step:
1. Select one subscription and expand some nodes under it.
2. Refresh this subscription.
3. Check whether all sub-nodes are collapsed or not.

Expect:
All sub-nodes are collapsed.

Actual:
The listed nodes aren't collapsed. Please see the below screenshot.
![gtreh](https://user-images.githubusercontent.com/34729092/34250460-df351c14-e677-11e7-9fd3-7fed118292bb.PNG)

**Comment by EricJizbaMSFT** [comment]
This by design. Refreshing the node should keep the collapsed state the same. Also, we added a "collapse all" button to the title bar since this issue was filed, which should satisfy any users that wanted this behavior.
