### ISSUE TITLE
Cannot connect to Azure Subscription 

### ISSUE THREAD

**Issue by rameshrajappan-next** [microsoft/vscode-azureappservice#2592]
Showing Fetch Failed  
Acquiring token with refresh token failed
Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'

**Comment by nturinski** [comment]
Could you try the actions in this thread to see if that will resolve your issue?

https://github.com/microsoft/vscode-azurefunctions/issues/3907#issuecomment-1823204532

**Comment by nturinski** [comment]
Closing due to lack of response. Please re-open if you're still having this issue!
