### ISSUE TITLE
Azure Error - This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

### ISSUE THREAD

**Issue by HaydenBussard** [microsoft/vscode-azureappservice#2600]
Does this occur consistently?  Yes
Repro steps:

1. Click Azure icon on the left side of Visual Studio Code
2. Hover "Resources" and select "Create Resource..."
3. Select "Create App Service Web App..."
4. Enter name (I've tried 10 names, the name isn't the problem)
5. Select "Python 3.9"
6. Select "Free (F1) Try out Azure at no cost"
7. Then I get the error "This region has a quota of 0 instances for your subscription. Try selecting different region or SKU."
8. Note: this is following the Microsoft learning "Deploy a Django application to Azure by using PostgreSQL" exactly as Microsoft has instructed. Please refer to your steps given in that tutorial for expected results.

Action: appService.CreateWebApp
Error type: Unauthorized
Error Message: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

Version: 0.25.1
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.85.1
Language: en

<details>
<summary>Call Stack</summary>

```
handleErrorResponse extension.bundle.js:2:1726156
deserializeResponseBody extension.bundle.js:2:1726883
```

</details>

**Comment by alexweininger** [comment]
This could be a temporary problem with the Azure region being deployed to. So apart from trying again another time you could try deploying to a different region.

To create an app in a different region, use the "Create App Service Web App (Advanced)..." command. 
<img width="459" alt="image" src="https://github.com/microsoft/vscode-azureappservice/assets/12476526/cbea148e-a6ee-4d25-8099-aa6479c14342">
