### ISSUE TITLE
[Bug] Azure Web App Deploy Failed Path Not Found (on Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by benyaminl** [microsoft/vscode-azureappservice#2602]
Hello, I got errors when want to deploy sample project https://microsoftlearning.github.io/APL-2002-develop-aspnet-core-consumes-api/Instructions/Labs/01-interact-with-an-api.html, I don't think it's because wrong path, but because the path that got from the function is hardcoded in Windows way of handling path rather than Linux 

![image](https://github.com/microsoft/vscode-azureappservice/assets/2817332/280e5a5a-8a21-40f3-a63e-0f9d99ea1e0a)
![image](https://github.com/microsoft/vscode-azureappservice/assets/2817332/90c9a682-bbee-46cf-b261-70f5268f92e2)

I tried on Windows 10 and it's working as it should be, is there any config that I can change in order to make it work on Linux? 

Thank you

**Comment by alexweininger** [comment]
Do you have the `azureFunctions.deploySubpath` set? It might be set to the Windows path and then causing issues on Linux.

**Comment by benyaminl** [comment]
> Do you have the `azureFunctions.deploySubpath` set? It might be set to the Windows path and then causing issues on Linux.

Yes, but it's not azureFunction, but 

```json
{
 ///.......
    "appService.deploySubpath": "bin\\Release\\net7.0\\publish",
///........
}
```

I tried to change it to 

```json
{
 ///.......
    "appService.deploySubpath": "bin/Release/net7.0/publish",
///........
}
```
It start working, but then failed in ziping (it give born to a new error :/)

```
12:01:20 PM net-fruit-api: Starting deployment...
12:01:21 PM net-fruit-api: Creating zip package...
12:01:21 PM net-fruit-api: Zip package size: 22 B
12:01:22 PM net-fruit-api: Fetching changes.
12:01:23 PM net-fruit-api: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/c9ec78d0-b835-42b5-9f6f-625c2aa7bd64.zip (0.00 MB) to /tmp/zipdeploy/extracted
```

Regarding the path, 
The biggest question is why it's defaulting to windows path? Is there anyway to make this path not auto to Windows, as I'm in Linux? 

Thank you

**Comment by alexweininger** [comment]
> 12:01:21 PM net-fruit-api: Zip package size: 22 B

This line tells me that for some reason nothing was zipped up. Did build execute successfully before the zipping step? Also, it could be that the `appService.deploySubpath` is wrong. Try removing the setting completely, and then trying deploy again.

**Comment by benyaminl** [comment]
> > 12:01:21 PM net-fruit-api: Zip package size: 22 B
> 
> This line tells me that for some reason nothing was zipped up. Did build execute successfully before the zipping step? Also, it could be that the `appService.deploySubpath` is wrong. Try removing the setting completely, and then trying deploy again.

I already check it and clean up, there are no other config other than this on the settings.json 

```
{
    "dotnet.defaultSolution": "FruitAPI.sln",
}
```

The extension recreate the config like this 

```
{
    "appService.preDeployTask": "publish-release",
    "appService.deploySubpath": "bin/Release/net7.0/publish"
}
```

I also have same question, why the zip is very small when if I deploy it manually using zip command and az cli, I doesn't got that small problem and I can deploy. :/ 

Does the zip rely on system cli zip or dotnet cli or others? I'm confused at this point

**Comment by MicroFish91** [comment]
The zip on the extension does not rely on those, but on the `yazl` npm package.

We do have a release coming out soon that should allow you to deploy directly from a zip through VS Code that may help to resolve this issue as well.

**Comment by benyaminl** [comment]
But it still doesn't answer the problem itself, as we need to zip it manually right? Is there anyway for me, as end user, to debug it more thoroughly? 

Thank you

**Comment by nturinski** [comment]
Well, to unblock you, we do have the new version released to deploy via zipfile directly.

Right now, the only way to really debug this as an end user is to clone down the repository, build the extension, and run it in the VS Code debugger. You could put breakpoints where the zip stream code is.

Do you have a `.gitignore` in your project? We skip adding those files to the zipfile, so maybe that's affecting your deployment?
