### ISSUE TITLE
App service deploy to web app always deploys code to root directory(site/wwwroot)

### ISSUE THREAD

**Issue by pramodmd** [microsoft/vscode-azureappservice#2603]
Is there a way to specify target folder inside wwwroot, where my code needs to be deployed.

I have multiple sites published inside same app service.

site/wwwroot ==> contains my Host application
site/wwwroot/products ==> contains my sub application

how can I deploy my products application to site/wwwroot/products folder ?
/products is virtual application created in path mappings.

**Comment by alexweininger** [comment]
According to the documentation on zip deploy [here](https://learn.microsoft.com/en-us/azure/app-service/deploy-zip?tabs=cli#deploy-a-zip-package) it says:

> When you deploy a ZIP package, App Service unpacks its contents in the default path for your app (D:\home\site\wwwroot for Windows, /home/site/wwwroot for Linux).

It doesn't mention anything about being able to customize this location.

**Comment by nturinski** [comment]
You should be able to specify a custom deployment location by following these steps: https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-folder-for-a-node-php-or-aspnet-site

You can do this with either a `.deployment` file or an app setting.
