### ISSUE TITLE
Deployment failure for Angular Web App

### ISSUE THREAD

**Issue by thabisomol** [microsoft/vscode-azureappservice#2606]
Does this occur consistently? 
Repro steps:

1. Go to VS Code, right click on the web app, deploy from dist/prod folder the app artifacts.
2.  Get the the below error

Action: appService.Deploy
Error type: ECONNRESET
Error Message: request to redacted:url failed, reason: read ECONNRESET

Version: 0.24.9
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.bundle.js:2:4191473
```

</details>

**Comment by nturinski** [comment]
Hi @thabisomol

This may be an intermittent error with the service. Could you please try again and see if this error is consistent?
