### ISSUE TITLE
Extension Not Fetching Blob Storage Name from Azure: Created Ticket with Microsoft Team, Have All Access on All Storage, but Still Not Fetching Details.

### ISSUE THREAD

**Issue by Harshal09Dev** [microsoft/vscode-azureappservice#2607]
We have Blob Storage on Azure, and we deploy the code using the Azure App Service extension. Earlier, we were able to fetch the Blob Storage name and deploy the code. However, for the past week, when we click on the resource group name, we can't see the storage name. We have tried reinstalling the extension, checked Blob Storage access, and raised a ticket with the Microsoft team, but unfortunately, we have had no luck. We have also cleared the cache of Visual Studio and tried various solutions, but the issue persists. Please help us resolve this as our deployment has been adversely affected

No Error 
No logs 
<img width="444" alt="image" src="https://github.com/microsoft/vscode-azureappservice/assets/61572211/b23f758b-b011-4d50-a59f-06bca42609b1">
  
Non working img 

<img width="448" alt="image" src="https://github.com/microsoft/vscode-azureappservice/assets/61572211/8857d837-5b36-4035-bab2-c9570a3c2235">
working one

**Comment by nturinski** [comment]
Hi @Harshal09Dev

Could you share what command that you are attempting to deploy with? I don't think App Service has ever allowed users to deploy to Blob Storage.

However, the Storage extension has this command:
![image](https://github.com/microsoft/vscode-azureappservice/assets/5290572/5c615606-a2d0-4ae2-a413-32a4f2719412)

Is it possible that you were previously using this command?
