### ISSUE TITLE
AppService.openfile/ 1952

### ISSUE THREAD

**Issue by shahidcres** [microsoft/vscode-azureappservice#2612]
Everytime when i worked on VS code its working fine but after few mins its giving this error message, tried to open case with Microsoft but they suggested to check with Github as they are not supporting VS code features.

<img width="960" alt="image" src="https://github.com/microsoft/vscode-azureappservice/assets/158062927/36311d30-1228-4092-8ba6-e3fc58574193">

**Comment by MicroFish91** [comment]
Could you please provide additional repro steps?  Does this only occur when trying to open app service files, or does something similar happen with other commands as well?  Also, what actions are you taking that temporarily fixes the issues?
