### ISSUE TITLE
Unable to change region when initial deployment fails using B1 tier.

### ISSUE THREAD

**Issue by spboyer** [microsoft/vscode-azureappservice#2613]
I was going through this basic app service quickstart using the vs code path
 
[Quickstart: Deploy a Python (Django or Flask) web app to Azure - Azure App Service | Microsoft Learn](https://learn.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=flask%2Cmac-linux%2Cvscode-aztools%2Cvscode-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli)
 
I keep getting quota error when I try to add the resource using the B1 pricing tier.

There is no way to change my region in the simple "Create App Service Web App"

![image](https://github.com/microsoft/vscode-azureappservice/assets/7681382/6ff0c2e3-99b5-484a-bc6b-ae75b4a40207)

**Comment by spboyer** [comment]
@nturinski

**Comment by MicroFish91** [comment]
Closing in favor of https://github.com/microsoft/vscode-azureappservice/issues/2447
