### ISSUE TITLE
i can not deploiy

### ISSUE THREAD

**Issue by rfletez72** [microsoft/vscode-azureappservice#2614]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.24.9
OS: win32
OS Release: 10.0.22635
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:1709073
extension.bundle.js:2:1696547extension.bundle.js:2:1696547
```

</details>

**Comment by MicroFish91** [comment]
Could you please provide additional repro steps, thank you
