### ISSUE TITLE
Only shows staging slots in deployment slots

### ISSUE THREAD

**Issue by zdavidfarris** [microsoft/vscode-azureappservice#2618]
Type: <b>Bug</b>

When opening ASE apps and looking at the deployement slots only the staging slot is visible.

Extension version: 0.25.1
VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (12.44GB free)|
|Process Argv|--crash-reporter-id 6b945450-a0cc-4699-8470-1e609f3f9ca5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30951795
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
8082a590:30958339
3ef8e399:30949928
e3gdj431:30958358

```

</details>

**Comment by nturinski** [comment]
Hi @zdavidfarris

What other slots are you expecting and do they show up on the portal? 

Are you able to create any more deployment slots via the extension?

**Comment by zdavidfarris** [comment]
Some have a prod and a staging slot, we use them for a sort of blue/green deployment. But onbly the stagins seem to show.


[HUB International]<https://www.hubinternational.com/?utm_medium=email&utm_source=readyfortomorrow_email-sig&utm_campaign=readyfortomorrow&utm_busunit=&utm_cmpyr=2020&utm_content=brand2020&utm_tstvar=&utm_spec=email-signature&partner>

[cid:ffaf7797-8757-4e17-8455-921356cd0c93]

Risk & Insurance | Employee Benefits | Retirement & Private Wealth

Ready for tomorrow.



David Farris

Digital Platform Engineer



HUB International Midwest Limited

203 ​North ​LaSalle ​Street

Chicago,​IL ​60601



Office: 312-​980-7864

Mobile: 331-​806-6264

Email: ***@***.******@***.***>



hubinternational.com<https://www.hubinternational.com/?utm_medium=email&utm_source=readyfortomorrow_email-sig&utm_campaign=readyfortomorrow&utm_busunit=&utm_cmpyr=2020&utm_content=brand2020&utm_tstvar=&utm_spec=email-signature&partner>



[LinkedIn]<https://www.linkedin.com/company/hub-international>[Instagram]<https://www.instagram.com/hub_intl/>[Facebook]<https://www.facebook.com/HUBInternationalLimited>[Twitter]<https://twitter.com/HUBInsurance>





________________________________
From: Nathan ***@***.***>
Sent: Wednesday, February 21, 2024 1:06 PM
To: microsoft/vscode-azureappservice ***@***.***>
Cc: Farris, David ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-azureappservice] Only shows staging slots in deployment slots (Issue #2618)


Hi @zdavidfarris<https://github.com/zdavidfarris>

What other slots are you expecting and do they show up on the portal?

Are you able to create any more deployment slots via the extension?

**Comment by nturinski** [comment]
Ahh, I see the issue now.

So in the portal, you're probably seeing something similar to this:

![image](https://github.com/microsoft/vscode-azureappservice/assets/5290572/d0cc69f3-c43a-4305-b037-80d1e9fd540f)

But in our extension, it looks like this:
![image](https://github.com/microsoft/vscode-azureappservice/assets/5290572/f5616dbe-6d4c-4290-a99a-cf8e1c76948b)

This is because the production app is _technically_ the web app itself, so we chose not to display it as a slot.  If you need to deploy to your production app, right-click the web app itself:
![image](https://github.com/microsoft/vscode-azureappservice/assets/5290572/4ece8d87-517b-44bc-b56e-e780897a6d38)

**Comment by zdavidfarris** [comment]
Right you got it. But in our case it uses network priority, one is set to 100% and the other is 0, unfortunately only the 0 or the staging is visible.



[HUB International]<https://www.hubinternational.com/?utm_medium=email&utm_source=readyfortomorrow_email-sig&utm_campaign=readyfortomorrow&utm_busunit=&utm_cmpyr=2020&utm_content=brand2020&utm_tstvar=&utm_spec=email-signature&partner>

[cid:73ded238-31a8-482d-86c9-5c593247bbd3]

Risk & Insurance | Employee Benefits | Retirement & Private Wealth

Ready for tomorrow.



David Farris

Digital Platform Engineer



HUB International Midwest Limited

203 ​North ​LaSalle ​Street

Chicago,​IL ​60601



Office: 312-​980-7864

Mobile: 331-​806-6264

Email: ***@***.******@***.***>



hubinternational.com<https://www.hubinternational.com/?utm_medium=email&utm_source=readyfortomorrow_email-sig&utm_campaign=readyfortomorrow&utm_busunit=&utm_cmpyr=2020&utm_content=brand2020&utm_tstvar=&utm_spec=email-signature&partner>



[LinkedIn]<https://www.linkedin.com/company/hub-international>[Instagram]<https://www.instagram.com/hub_intl/>[Facebook]<https://www.facebook.com/HUBInternationalLimited>[Twitter]<https://twitter.com/HUBInsurance>





________________________________
From: Nathan ***@***.***>
Sent: Wednesday, February 21, 2024 1:58 PM
To: microsoft/vscode-azureappservice ***@***.***>
Cc: Farris, David ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-azureappservice] Only shows staging slots in deployment slots (Issue #2618)


Ahh, I see the issue now.

So in the portal, you're probably seeing something similar to this:

image.png (view on web)<https://github.com/microsoft/vscode-azureappservice/assets/5290572/d0cc69f3-c43a-4305-b037-80d1e9fd540f>

But in our extension, it looks like this:
image.png (view on web)<https://github.com/microsoft/vscode-azureappservice/assets/5290572/f5616dbe-6d4c-4290-a99a-cf8e1c76948b>

This is because the production app is technically the web app itself, so we chose not to display it as a slot. If you need to deploy to your production app, right-click the web app itself:
image.png (view on web)<https://github.com/microsoft/vscode-azureappservice/assets/5290572/4ece8d87-517b-44bc-b56e-e780897a6d38>

**Comment by nturinski** [comment]
Would you be able to share what your deployment slots look like in the portal? Similar to what I shared in the screenshot above?

**Comment by zdavidfarris** [comment]
Hm I should be able to, i am in a few meetings will do it later



[HUB International]<https://www.hubinternational.com/?utm_medium=email&utm_source=readyfortomorrow_email-sig&utm_campaign=readyfortomorrow&utm_busunit=&utm_cmpyr=2020&utm_content=brand2020&utm_tstvar=&utm_spec=email-signature&partner>

[cid:3d4ea43b-cd2f-4518-a15b-73f94f7dcc33]

Risk & Insurance | Employee Benefits | Retirement & Private Wealth

Ready for tomorrow.



David Farris

Digital Platform Engineer



HUB International Midwest Limited

203 ​North ​LaSalle ​Street

Chicago,​IL ​60601



Office: 312-​980-7864

Mobile: 331-​806-6264

Email: ***@***.******@***.***>



hubinternational.com<https://www.hubinternational.com/?utm_medium=email&utm_source=readyfortomorrow_email-sig&utm_campaign=readyfortomorrow&utm_busunit=&utm_cmpyr=2020&utm_content=brand2020&utm_tstvar=&utm_spec=email-signature&partner>



[LinkedIn]<https://www.linkedin.com/company/hub-international>[Instagram]<https://www.instagram.com/hub_intl/>[Facebook]<https://www.facebook.com/HUBInternationalLimited>[Twitter]<https://twitter.com/HUBInsurance>





________________________________
From: Nathan ***@***.***>
Sent: Wednesday, February 21, 2024 2:02 PM
To: microsoft/vscode-azureappservice ***@***.***>
Cc: Farris, David ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-azureappservice] Only shows staging slots in deployment slots (Issue #2618)


Would you be able to share what your deployment slots look like in the portal? Similar to what I shared in the screenshot above?

**Comment by nturinski** [comment]
Just wanted to check back in with you.

**Comment by nturinski** [comment]
Closing due to a lack of response. I think that this issue can be considered completed. 

I think there is a misunderstanding with our tree's UI. Maybe we should revisit how we display the production slot/main web app?
