### ISSUE TITLE
Where are instructions for how to connect to subscription

### ISSUE THREAD

**Issue by bdelaney** [Microsoft/vscode-azureappservice#262]
tried to do appsettings.add but all I get for the set of commands is 'command not found'
am I missing a dependency?

**Comment by whiskeyjay** [comment]
Hi @bdelaney ,
You can either do this:
![image](https://user-images.githubusercontent.com/15821566/34689246-af8aeb74-f469-11e7-980a-531e628c48a4.png)

Or use the "Azure: Sign In" command.

This extension has a dependency on the [Azure Account extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azure-account), which should be automatically installed when you install this extension from the marketplace.

**Comment by whiskeyjay** [comment]
#274 added a link to a tutorial which includes how to sign in.
