### ISSUE TITLE
Error experienced 

### ISSUE THREAD

**Issue by MugaruraEdwin** [microsoft/vscode-azureappservice#2625]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.24.9
OS: darwin
OS Release: 23.2.0
Product: Visual Studio Code
Product Version: 1.77.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:2436391
rejected extension.bundle.js:2:2434001
```

</details>

**Comment by MicroFish91** [comment]
Please provide repro steps, thank you
