### ISSUE TITLE
Local Workspace Does not display.  

### ISSUE THREAD

**Issue by cechrisha** [microsoft/vscode-azureappservice#2626]
Hello all, 

Currently I'm unable to see My local Workspace. 

![image](https://github.com/microsoft/vscode-azureappservice/assets/119649072/77f62eb4-de59-497c-b306-fcc687787754)

I have tried to see if it's hidden, That is not the case. 

![image](https://github.com/microsoft/vscode-azureappservice/assets/119649072/a73a9bc1-81ab-4b14-8f00-e3cef83c7bc4)

I have also tried to follow this issue.  

https://github.com/microsoft/vscode-azurefunctions/issues/3522

.... 

After trying to reinstall core tools, resources -- >   The error still remains.

**Comment by nturinski** [comment]
Could you try running this command?

![image](https://github.com/microsoft/vscode-azureappservice/assets/5290572/e49999de-c494-4c21-9ada-3fd61ca31515)

Also what version of the `Azure Resources` extension do you have installed?

![image](https://github.com/microsoft/vscode-azureappservice/assets/5290572/ea376a34-4138-4a5a-9aa9-118fc8c5bbc3)
