### ISSUE TITLE
Azure Remote Debugging is currently only supported for Node.js apps on Linux.

### ISSUE THREAD

**Issue by takeshi4github** [microsoft/vscode-azureappservice#2627]
I would like to attach and debug a python web application (streamlit) deployed on Azure App Service using vscode.
I selected the app I want to debug, right-clicked it and selected "Start Remote Debugging", but it says "Azure Remote Debugging is currently only supported for Node.js apps on Linux." and I can't debug it.
Is it not possible to attach and debug a python web application deployed on Azure App Service using vscode?
Thank you for your cooperation.
Visual Studio Code
version: 1.87.1

**Comment by motm32** [comment]
Hi! Could you try pressing F1 and searching `Preferences: Open User Settings` and then turn this setting on: 
![image](https://github.com/microsoft/vscode-azureappservice/assets/59709511/66ece64a-f500-497c-b5d7-25879176fff5) Please let us know if that doesn't work!

**Comment by takeshi4github** [comment]
Thank you for confirmation. I turned on "Enable Python Remote Debugging" in VSCode settings. Thanks to you, the first error has been resolved.
However, when I right-clicked on the App Service to be debugged and pressed "Start Remote Debugging", another error occurred. The error message is "Unable to establish connection to application: Timed out". Please let me know the possible causes and solutions.
Thank you for your cooperation.
![image](https://github.com/microsoft/vscode-azureappservice/assets/59782239/ba8f0d8e-5989-456f-b777-c2791cccbc8c)

**Comment by takeshi4github** [comment]
By the way, if I disabled "Remote Debug" and pressed "SSH into Web App", I was able to connect via SSH from vscode.

**Comment by nturinski** [comment]
@takeshi4github

When you try to start remote debugging, do you get a prompt to ask you to enable remote debugging? I know that it uses a different port to tunnel than SSH, which we have to change the app configuration in order to enable.

**Comment by takeshi4github** [comment]
@nturinski 
Thank you for your confirmation and reply.
> When you try to start remote debugging, do you get a prompt to ask you to enable remote debugging? 

No.

> we have to change the app configuration in order to enable.

Remote Debugging is already turned on in the configuration.
![image](https://github.com/microsoft/vscode-azureappservice/assets/59782239/630fd779-eaf1-43f0-9d5b-427e9674cc36)

**Comment by nturinski** [comment]
@takeshi4github Do you know if the app is running successfully? Are you able to ping or browse to it? I'm not sure why it would time out when you try to remote debug otherwise.

**Comment by takeshi4github** [comment]
@nturinski 
>Do you know if the app is running successfully? Are you able to ping or browse to it?

Yes, I do. My web application is running successfully. I can access my web application through MS Edge.

**Comment by nturinski** [comment]
@takeshi4github

Hi, I just wanted to follow up with you on this issue.

Is it still unable to connect? I don't know if there's anything that the extension can do specifically. I'm hoping it was just a temporary service side issue 🤞
