### ISSUE TITLE
I tried to deploy an app that was already deployed using my azure extension and is no longer working

### ISSUE THREAD

**Issue by noeleiva** [microsoft/vscode-azureappservice#2629]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.9
OS: darwin
OS Release: 23.4.0
Product: Visual Studio Code
Product Version: 1.71.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3774912
fulfilled extension.bundle.js:2:3773583
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repo steps.
