### ISSUE TITLE
GenAI Portal deployment from VS Code

### ISSUE THREAD

**Issue by Yogeshpatil5** [microsoft/vscode-azureappservice#2637]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: site

Version: 0.24.9
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:2:3867078
Proxy.<anonymous> extension.bundle.js:2:3848180
fulfilled extension.bundle.js:2:3846380
```

</details>

**Comment by alexweininger** [comment]
Please provide repro steps.
