### ISSUE TITLE
The "Files" node of the slot is different from the web app after choosing the web app as the configuration source

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2640]
**OS:** Win10
**Build Version:** 20240510.1
**Regression:** Not a Regression

**Repro Steps:**
1. Create a Python Linux web app and deploy a python-docs-hello-world project to it.
2. Create a slot for this web app and choose the above web app as the configuration source.
3. Expand the "Files" node for the web app and its slot.
4. Check whether the "Files" node of the slot is same with the web app.

**Expect:**
The "Files" node of the slot is same with the web app.

**Actual:**
The "Files" node of the slot is different from the web app.
![image](https://github.com/microsoft/vscode-azureappservice/assets/57662131/b7cc824f-bfbe-48bd-8c89-e05df32d8288)

**More Info:**
This issue doesn't reproduce for the "Application Settings" node.
![image](https://github.com/microsoft/vscode-azureappservice/assets/57662131/fc82474a-6c4b-4685-af93-ef1344967162)

**Comment by nturinski** [comment]
Closing as by-designed.

According to the docs:
> The new deployment slot has no content, even if you clone the settings from a different slot. 

The documentation can be seen in this hyperlink: https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots?tabs=portal
