### ISSUE TITLE
I just install aes-everywhere via my terminal in vscode locally I keep getting this error

### ISSUE THREAD

**Issue by EjilolaHammedEjitomiwa** [microsoft/vscode-azureappservice#2641]
I just install aes-everywhere via my terminal in vscode locally I keep getting this error but when I uninstall the aes-everywhere package it will deploy successfully 

03:11:28 geotopuptest: Zip package size: 30.4 MB
03:11:29 geotopuptest: Fetching changes.
03:11:29 geotopuptest: Cleaning up temp folders from previous zip deployments and extracting pushed zip file C:\local\Temp\zipdeploy\lodnadyh.zip (29.04 MB) to C:\local\Temp\zipdeploy\extracted
03:11:30 geotopuptest: The given path's format is not supported.
03:11:35 geotopuptest: Deployment failed.

**Comment by nturinski** [comment]
`aes-everywhere` must be messing with our zipping logic on deployment. As another workaround, you can zip the project yourself and deploy the zipfile directly.
