### ISSUE TITLE
vs code app service deployment issue

### ISSUE THREAD

**Issue by tesfayealex** [microsoft/vscode-azureappservice#2649]
Does this occur consistently? 
Repro steps:

1.
2.

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'createClient')

Version: 0.24.9
OS: linux
OS Release: 5.13.0-52-generic
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:3774912
fulfilled extension.bundle.js:2:3773583
```

</details>

**Comment by nturinski** [comment]
Could you provide repro steps please?
