### ISSUE TITLE
Fail to create a web app with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azureappservice#2652]
**OS:** Win10
**Build Version:** 20240704.1
**Regression:** Not a regression

**Repro Steps:**
1. Create a new web app.
2. Check whether succeeds to create a web app.

**Expect:**
Succeed to create a web app.

**Actual:**
Fail to create a web app.
![image](https://github.com/microsoft/vscode-azureappservice/assets/57662131/0661dfd9-668a-4e5a-9d1d-0bc5c7085243)

**More Info:**
This issue also reproduces for **Azure Functions extension**.

**Comment by MicroFish91** [comment]
Does this reproduce consistently?  We are having issues reproducing this behavior.  If so, can you also let us know which inputs you are selecting, maybe that has some impact on reproducing this issue

**Comment by v-xinda** [comment]
@MicroFish91  Yes, it reproduces consistently. 
The steps of creating web app as below:
Create "App Services" node -> Create New Web App...(Advanced) -> Enter a name -> Select "+Create new resource group" -> Type default name -> Select "Node 20 LTS" runtime stack -> Select Linux/Windows OS -> Select "East US" location -> Select "+Create new App Service plan" -> Type default name -> Select "S1" pricing tier -> Select "+Create new Application Insights resource" -> Type default name.

**Comment by v-xinda** [comment]
Verified this issue on the latest build, it doesn't reproduce for mow. So I close it.
