### ISSUE TITLE
RxPredictor

### ISSUE THREAD

**Issue by presiZHai** [microsoft/vscode-azureappservice#2656]
Does this occur consistently? 
Repro steps:

1.
2.

Version: 0.25.2
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.91.1
Language: en

**Comment by presiZHai** [comment]
Web App for Prescription Predictor

**Comment by nturinski** [comment]
Could you provide issue details and the repro steps?
