### ISSUE TITLE
Pushing to Github

### ISSUE THREAD

**Issue by theheemmanuel** [microsoft/vscode-azureappservice#2659]
> git push -u origin master
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

I keep getting this error. while trying to push to a new repo i just created

**Comment by MicroFish91** [comment]
Could you please provide repro steps for this issue?
