### ISSUE TITLE
Internal error: Expected value to be neither null or undefined: id

### ISSUE THREAD

**Issue by aa-bharath** [microsoft/vscode-azureappservice#2671]
I am recently facing error "Internal error: Expected value to be neither null or undefined: id" while using VS Code. I have already tried reinstalling to latest versions and various other options.

**Comment by MicroFish91** [comment]
Could you please provide repro steps for this issue?  

Also, a couple other questions:
1. So was this previously working in VS Code before and recently broke?
2. Have you run into any issues when viewing your apps through the portal?
