### ISSUE TITLE
Account updation

### ISSUE THREAD

**Issue by Rupak1017** [microsoft/vscode-azureappservice#2678]
Type: <b>Bug</b>

I have logged in new azure account and want to create new app service and deploy web app through vsc but the extension still catches old account services and that is why I am not able to deploy my app.

Extension version: 0.25.3
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.61GB free)|
|Process Argv|. --crash-reporter-id 53f51bad-5f0b-46c8-a279-f7c8a209e729|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by nturinski** [comment]
Are you using the old Azure Accounts extension?

Could you please sign out through the command palette:
![{70E34DF5-BBF8-4298-A469-10DB1DC1C2AF}](https://github.com/user-attachments/assets/ad6f6128-4214-4f66-9ecf-8a1c146c599c)

And also make sure that you sign out of your old account through VS Code Microsoft's Authentication provider?
![{B9A18197-A2A8-4491-BBEA-C71DDE1F1E2B}](https://github.com/user-attachments/assets/01922b9c-aa6b-4e13-8692-846c0d8128d6)
