### ISSUE TITLE
.NET 9 is not listed in the runtime stack when creating a new web app in Azure China account

### ISSUE THREAD

**Issue by Amar-QA** [microsoft/vscode-azureappservice#2683]
**OS:** All
**Build Version:** v0.25.3

**Repro Steps:**

1. Sign in with Azure China account.
2. F1 -> Create New Web App (Basic) -> Enter a name -> Check runtime stack list.
3. Check whether the ".NET9" is displayed in the runtime stack list.

**Expected:**
.NET9 should display in the runtime stack list.

**Actual:**
.NET9 is not displayed in the runtime stack list.
![image](https://github.com/user-attachments/assets/5aa2e071-f050-4ec1-828e-88e22757af5a)

**More Info:**

1. This issue also reproduces in Azure China portal.
2. This issue does not reproduce in Azure Account.

![image](https://github.com/user-attachments/assets/a168b8fd-c903-4db3-b3f2-b3d6d6d84ceb)

**Comment by nturinski** [comment]
Sometimes Azure China does not update their runtimes as quickly as public Azure. I don't think that this would be considered a bug.
