### ISSUE TITLE
There is no runtime stack "Node 22 LTS" when creating a Node.js web app

### ISSUE THREAD

**Issue by v-meilei** [microsoft/vscode-azureappservice#2698]
**OS:** Win 11
**Build Version:** 20241125.1

**Repro Steps:**

1. F1 -> Select "Azure App Service: Create New Web App..." -> Select a subscription -> Enter a name -> Select a runtime stack.
2. Check whether there is the runtime stack "Node 22 LTS".

**Expect:**
There is the runtime stack "Node 22 LTS".

**Actual:**
There is no runtime stack "Node 22 LTS".
![Image](https://github.com/user-attachments/assets/c712ba1a-7107-4bf1-a334-97069ded7580)

**Comment by MicroFish91** [comment]
Is the expectation that Node 22 LTS should be ready to show up? Do you know if any other clients are showing Node 22 LTS yet?  I believe we are not seeing it show up to display through our APIs yet

**Comment by v-meilei** [comment]
@MicroFish91 Hi, also tried in portal, there is no runtime stack "Node 22 LTS" when creating a Node.js web app. (but for Azure Functions extension, there is “Node.js 22 (preview)” runtime stack when creating a function app.)

![Image](https://github.com/user-attachments/assets/bdc3037d-ca2b-46ee-9f11-15ae9bba22ed)

**Comment by nturinski** [comment]
> [@MicroFish91](https://github.com/MicroFish91) Hi, also tried in portal, there is no runtime stack "Node 22 LTS" when creating a Node.js web app. (but for Azure Functions extension, there is the “Node.js 22 (preview)” runtime stack when creating a function app.)
> 

Just to clarify, the runtime stack for App Service and Functions are not expected to be the same. I'm going to keep this issue closed as this is just a difference in services.
