### ISSUE TITLE
Choosing not to deploy on creation deploys anyway

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#278]
Create a new web app from "+" button in sash and follow the steps; when prompted to deploy, choose "no"; app deploys anyway.

**Comment by EricJizbaMSFT** [comment]
What version are you testing on? This should've been fixed in december: https://github.com/Microsoft/vscode-azureappservice/issues/242

I can't repro on the latest

**Comment by fiveisprime** [comment]
I'm on the published version. D:

It's fixed in the pre-release so I'll switch to that and close this.
