### ISSUE TITLE
Pop up an error after creating a web app with 63-characters name

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#282]
Repro Step:

1. Right click one subscription and select 'Create New Web App'.
2. Create a web app with 63-characters name like 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz12345678901'.
3. Verify that whether this web app can be created successfully or not.

Expect: 
The web app can be created successfully.

Actual:
Pop up an error.

Attachment:
![1](https://user-images.githubusercontent.com/34729092/35435280-05bfd16e-0282-11e8-8239-3f4dde1d5d13.PNG)

**Comment by EricJizbaMSFT** [comment]
Looks like this was fixed at some point. The validation prevents you from creating a web app with 63 characters:

![Screen Shot 2020-04-13 at 3 43 29 PM](https://user-images.githubusercontent.com/11282622/79167971-987eb680-7d9d-11ea-8cf6-f42ee634ac96.png)
