### ISSUE TITLE
File editor doesn't handle binary files properly

### ISSUE THREAD

**Issue by whiskeyjay** [microsoft/vscode-azureappservice#293]
1. Publish a web app with images.
2. Navigate to the Files node under the web app.
3. Click an image file.

Expected:
![image](https://user-images.githubusercontent.com/15821566/35834845-5d2465ac-0a8c-11e8-8e51-f8ee638a034f.png)
or
![image](https://user-images.githubusercontent.com/15821566/35834858-6dfbde82-0a8c-11e8-8caf-278f1b956d45.png)
![image](https://user-images.githubusercontent.com/15821566/35834890-931d6672-0a8c-11e8-8366-24659e0d3223.png)

Actual:
![image](https://user-images.githubusercontent.com/15821566/35834923-afd107ce-0a8c-11e8-88df-6b5f5fd01688.png)

**Comment by EricJizbaMSFT** [comment]
Closing in favor of https://github.com/microsoft/vscode-azureappservice/issues/1740
