### ISSUE TITLE
Empty error message when creating a deployment slot that exceeds limit

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azureappservice#294]
1. Create a new Web App with S1 plan.
2. Create four deployment slots under the new Web App.
3. Try to create a fifth deployment slot which should exceed the plan limitation.

Expected:
A reasonable error message.

Actual:
![image](https://user-images.githubusercontent.com/15821566/35880178-115bae2c-0b32-11e8-9215-924e0e52e227.png)

**Comment by nturinski** [comment]
This was resolved with https://github.com/Microsoft/vscode-azuretools/commit/afd15f5e1c75eedf37fbe7ced5f16b6c70a1214a.  You may have to update vscode-azureextensionui
