### ISSUE TITLE
Support runtimes other than node

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#299]
This biggest piece of this is to show runtime when creating an app service. However, we also need to keep runtimes in mind for the deploy feature here: https://github.com/Microsoft/vscode-azureappservice/issues/224

Example runtimes we might support:
1. .NET Core
1. PHP

**Comment by nturinski** [comment]
Closed by https://github.com/Microsoft/vscode-azuretools/commit/82f22249164f8ce72c1256cc747d386f5f8a0eff
