### ISSUE TITLE
Remove web apps and slots opening a browser upon creation

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azureappservice#302]
It is very distracting to have a browser be opened every time I create a web app or slot.  Granted, I doubt a user will be creating as many slots/apps as I am, but it's generally pretty annoying to have something open up on its own a la an ad.

This also distracts users from the Deploy to App pop-up that happens upon creation which is currently the most streamlined entry point to deploying as there is only one prompt to select a project.

I understand that we want to make the user aware that the app is created, but there is an output message that is shown and a "Creating..." node in the explorer.

**Comment by fiveisprime** [comment]
I agree that it is distracting and hides the deploy prompt, but I see the convenience.. just not on the create event. Could we change the trigger to open the site when a deployment completes?

**Comment by nturinski** [comment]
I think that makes a lot more sense.

**Comment by EricJizbaMSFT** [comment]
Closing since its fixed
