### ISSUE TITLE
[Suggestion]'Start' item should be disabled for one web app after it is started successfully

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#306]
Repro Steps:
1. Create one web app.
2. Right click the web app and select 'Start'.
3. Make sure the web app is started successfully  in Output window.
4. Right click the same web app again then check the context menu.

Expect:
The 'Start' item is disabled after it is started successfully.

Actual:
The 'Start' item is enabled and it works well.
![start](https://user-images.githubusercontent.com/34729022/36087649-5fee8544-0fcb-11e8-9392-a445f6b50364.png)

More info:
'Stop' item should be disabled for one web app after it is stoped successfully.

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix. Starting a running app has no consequences for the user and I don't believe VS Code exposes functionality to gray out context menus from an extension
