### ISSUE TITLE
Zip deployment fails with Node app, NPM install from WSL - Symlinks

### ISSUE THREAD

**Issue by benc-uk** [Microsoft/vscode-azureappservice#312]
When deploying a Node.js app it will fail if the `npm install` has been run from within WSL bash.
The zip task fails with files in the `node_modules\.bin` sub-folder, it varies what file triggers the error from project to project but it's always in `node_modules\.bin`

![image](https://user-images.githubusercontent.com/14982936/36786891-f39b3ac4-1c7f-11e8-9d32-5c1d725e8867.png)

If you delete node_modules directory and they run `npm install` in Windows (e.g. from PowerShell) then the zip task works and deployment succeeds

EDIT: Update - further investigation shows the failing file is a symlink which is what is probably tripping up the zipping task. Manually removing the symlink fixes the issue
![image](https://user-images.githubusercontent.com/14982936/36787052-a3a92e26-1c80-11e8-839d-0388a82e3310.png)

**Comment by fiveisprime** [comment]
Related to #176 so we may need to review our solution. This will no longer be an issue in most cases once #224 is finished though.

@benc-uk you can choose to ignore symlinks by adding `"appService.zipIgnorePattern"` either to your global or local config and set it to `"node_modules/.bin/*"` or `"node_modules/.bin/semver"` if you need other bins from your modules.

**Comment by benc-uk** [comment]
Thanks Matt, 
The `appService.zipIgnorePattern` config setting is great solution, I have no need for anything in the `.bin` folder deployed to the app service. 

The option to not include **node_modules** at all and let Kudu restore them would be a nice option to have and it looks like you are exploring that too.

I've just tested deploying a project via this extension without node_modules but included a `.deployment` file with the contents
```
[config]
SCM_DO_BUILD_DURING_DEPLOYMENT=true
```
and Kudu ran npm install for me on the App Service

Anyhow please close
