### ISSUE TITLE
zipIgnorePattern should allow both string and array

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#313]
Right now, it only allows a string and seems like if I set this to an array, the pattern is ignored completely.

The underlying modules that's being used allows for both (see the [unit tests](https://github.com/isaacs/node-glob/blob/98327d8def195b1ba200217952df8ea829426038/test/ignore.js) since all OSS has crap documentation).

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azureappservice/pull/318
