### ISSUE TITLE
We should attempt to validate that a webapp deployment was successful

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azureappservice#316]
I.e., beyond just the kudu response - can we access the web app?  Etc.

**Comment by EricJizbaMSFT** [comment]
@StephenWeatherford do you still plan to do something with this? It's been bumped the past two releases which makes me think it should be in 'future' rather than '0.8.0'

**Comment by StephenWeatherford** [comment]
I was actually hoping to do something with it. Thanks for the reminder.

**Comment by EricJizbaMSFT** [comment]
Using detectors for this https://github.com/microsoft/vscode-azureappservice/issues/1249
