### ISSUE TITLE
Multiple subscriptions supported?

### ISSUE THREAD

**Issue by mmusket** [Microsoft/vscode-azureappservice#319]
On the extension features its says that we can browse all of your azure subscriptions
"Browse sites across all of your Azure subscriptions"

Does this mean the plugin supports multiple subs? Cause when I sign in to a second subscription it removes my first one. 
Is that the correct behaviour? 
and if yes, can the extension be made to support multiple subs cause its annoying to switch every time.

**Comment by StephenWeatherford** [comment]
@mmusket Marco, I assume when you say "sign in to a second subscription" you mean you want to sign in to multiple *accounts* at the same time, is that correct? (All subscriptions of the current signed-in account are already available.)

We depend on the "Azure Account" extension for our sign-in capability, and it currently only supports being signed in to a single account at a time. I've added an issue there: Microsoft/vscode-azureappservice#319

**Comment by mmusket** [comment]
@StephenWeatherford yes that is correct. Thanks for creating https://github.com/Microsoft/vscode-azure-account/issues/42
