### ISSUE TITLE
No prompting pops up after saving the setting file

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#331]
Repro Steps:
1. Clicking 'File'>'Preferences'>'Settings.
2. Modify the 'appService.showRemoteFiles' to be true.
3. Save it.

Expect:
Pop up a prompting to upload it.

Actual:
No prompting pops up.

**Comment by nturinski** [comment]
If I'm understanding you correctly, this is the intended behavior.

The prompt to upload a file should only appear when you are saving files from the Files node that is in a Web App node.  Local files such as the settings in your workspace should not be uploaded to an Azure web app.

**Comment by v-xuanzh** [comment]
Thanks for your update.
