### ISSUE TITLE
Log site url after deploy completes

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#333]
We discussed this offline, but I didn't see an issue filed. We should really print the site url after a deploy completes. This is the current output:
```
09:22:37 example: Deployment successful.
09:22:38 example: App container will begin restart within 10 seconds.
>>>>>> Deployment to "example" completed. <<<<<<
```

This is the output after creating a web app, which we could model it after:
```
Created App Service plan "example (S1)".
Creating new Web App "example"...
>>>>>> Created new Web App "example": https://example.azurewebsites.net <<<<<<
```

**Comment by StephenWeatherford** [comment]
This is more important than bringing up the page in the browser.
