### ISSUE TITLE
.NET Core does not deploy succesfully through zipdeploy

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azureappservice#338]
Today App Service does not support deploy through zipdeploy.  A .NET Core app's deployment source must be set to Local Git to deploy.

**Comment by EricJizbaMSFT** [comment]
This is only an issue on Linux. The new create workflow will automatically default users to Windows (https://github.com/Microsoft/vscode-azuretools/pull/202).

We'll say that's good enough for now - most of the fixes need to be on the app service side anyways.
