### ISSUE TITLE
infinite loop while trying to authenticate

### ISSUE THREAD

**Issue by wassim-azirar** [Microsoft/vscode-azureappservice#349]
I have installed this extension today after watching this [video](https://www.youtube.com/watch?v=iY1L0UC2bdE), and I got very excited about this.

After I installed the extension and restared VSCode, I tried this steps many times, but I didn't work for me. The console debugger says there is an error in the passphrase which is not true, because the web page recognizes it, and says it's coming from VSCode.

I'm using VSCode 1.22.0-insider and macOS 10.13.3. 

**UPDATE 1**
I tried with the stable version of VSCode 1.21.0 and I have the same issue.

<img width="1012" alt="1" src="https://user-images.githubusercontent.com/670586/37373200-fecdeb8a-2715-11e8-9c06-32369aea9178.png">

<img width="572" alt="2" src="https://user-images.githubusercontent.com/670586/37373210-05464264-2716-11e8-81cc-4fa0ac129058.png">

<img width="579" alt="3" src="https://user-images.githubusercontent.com/670586/37373226-11376b16-2716-11e8-8deb-107d1b7793b6.png">

<img width="865" alt="4" src="https://user-images.githubusercontent.com/670586/37373236-16c1a7ea-2716-11e8-8714-0f51b6145735.png">

<img width="813" alt="5" src="https://user-images.githubusercontent.com/670586/37373255-20abce52-2716-11e8-87b5-9768ae25f59e.png">

**Comment by EricJizbaMSFT** [comment]
@chrmarti any ideas on this issue?

**Comment by chrmarti** [comment]
@wassim-azirar Could you try with an "private" (or "incognito") browser window? That will help us understand if there is some state in the browser affecting this.

**Comment by wassim-azirar** [comment]
@chrmarti I get excatly the same error event in incognito mode ( Chrome & Firefox )
<img width="711" alt="firefox" src="https://user-images.githubusercontent.com/670586/37497991-f063268a-28bb-11e8-914b-b8c69994f1a9.png">

**Comment by EricJizbaMSFT** [comment]
@chrmarti @wassim-azirar any updates on this? I'm guessing it's more of an "Azure Sign-In" issue rather than anything to do with VS Code. For example, does it also happen if you try to sign in to the azure cli? If possible, I'd like to find a better home to track this issue as I don't think the app service extension can fix this.

**Comment by wassim-azirar** [comment]
@EricJizbaMSFT using the azure CLI works very fine. It's what I have used as a workaround to deploy my API on azure.

**Comment by EricJizbaMSFT** [comment]
Closing this issue since there's nothing we can do in the App service extension. All of the account stuff in VS Code is handled by this extension: https://github.com/Microsoft/vscode-azure-account

Please file an issue there if this is still blocking you
