### ISSUE TITLE
Dissallow creating a new app on a Windows plan

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#359]
I see quite a few reports from users attempting to create and deploy from the extension and seeing the error:

> You do not have permission to view this directory or page.

This typically turns out to be that they are attempting to create a new app within an existing plan that is on Windows infrastructure. We should be able to detect and prevent this from happening by providing an error.

**Comment by nturinski** [comment]
@fiveisprime Do you have any more detail on this?  Currently, we do not display Windows app service plans in Create Web App for the Azure App Service extension so I'm not sure how users are creating any apps on a Windows plan.

**Comment by fiveisprime** [comment]
I have a single, windows-based app in my personal account and I am able to choose it as a deployment target. 

![image](https://user-images.githubusercontent.com/1186948/38009666-5237bd56-320a-11e8-9cb8-200ccbb8a7e3.png)

Confirmed on windows worker (IIS exe is the only running process)

![image](https://user-images.githubusercontent.com/1186948/38009698-77db9d02-320a-11e8-979d-2e25ae420ee0.png)

**Comment by EricJizbaMSFT** [comment]
Haha so I think I changed this code while refactoring the wizard stuff (which is why you guys might be seeing different behavior on the released version vs. master branch). Since Nathan's working on the 'install func cli' feature - I'll take a look at this
