### ISSUE TITLE
Turn on strictNullChecks

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#364]
Originally when we did tslint for this repo we decided to turn off strictNullChecks (I don't remember the full discussion). After the recent bug in the Cosmos repo that potentially could've been caught by this, I say we turn it on. Even if we end up using the non-null assertion operator in a lot of cases, I think its worth it.

**Comment by StephenWeatherford** [comment]
Fully agree. There might be some ways to reduce the number of assertions necessary, got an idea to try.
