### ISSUE TITLE
Direct users to better deployment method when zip is too large

### ISSUE THREAD

**Issue by bowdenk7** [microsoft/vscode-azureappservice#369]
Output from my attempted zip deploy. I'm assuming this means the zip is too large to upload?

Do yall know what the size limit is? I'm guessing there is nothing we can do about this, but could we add an error message that suggests using a different deployment method?

11:36:56 staticsite-tutorial: Creating zip package...
11:37:53 staticsite-tutorial: Starting deployment...
Error: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by EricJizbaMSFT** [comment]
It was back in October, but I've [successfully deployed](https://github.com/Microsoft/vscode-azuretools/pull/6) a 1.4GB folder on a B1 (Basic: 1 Small) app service plan, which resulted in a 250 MB zip file. But no - I don't know the exact upper limit

I assume you're using the standard deployment and not local git deployment? Did you see this message when you deployed?
<img width="470" alt="screen shot 2018-03-27 at 5 08 45 pm" src="https://user-images.githubusercontent.com/11282622/38037830-89d14eae-325e-11e8-9bb7-ab4929655311.png">

It only applies for node projects at the moment, but it will exclude the node_modules folder when deploying, which would result in a smaller zip file. You can see more info here: https://github.com/Microsoft/vscode-azureappservice/blob/master/README.md#configuring-zip-deploy

**Comment by bowdenk7** [comment]
Mine is 1.1GB. I'll remove the `node_modules` folder and try again, but I'm pretty sure it's a bunch of images and static content that make this site so big.

**Comment by EricJizbaMSFT** [comment]
Ah interesting - well the Kudu repo would be the right place to file an issue about the root problem (I couldn't find an existing issue about large deployments): https://github.com/projectkudu/kudu 

I'll leave this issue open to discuss possible warnings or other things we can do from the extension

**Comment by bowdenk7** [comment]
What is the root problem? That kudu can't handle files of that size? I admittedly don't know how this works under the covers. What is actually doing the file transfer?

**Comment by EricJizbaMSFT** [comment]
I'm pretty sure Kudu is just an ASP.NET app. It's using the basic System.Net.Http.CopyToAsync method and would inherit whatever limitations that has: https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Deployment/PushDeploymentController.cs#L140
