### ISSUE TITLE
Connect to App Log Stream

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azureappservice#37]
Also requested by @lostintangent

**Comment by whiskeyjay** [comment]
@fiveisprime please help to find out if this is supported on Linux web apps.

**Comment by lostintangent** [comment]
Yes this works for Linux Web Apps as well. As part of their GA release, they enabled the same Kudu log stream endpoint that the Az CLI uses to view web app logs.

**Comment by whiskeyjay** [comment]
I'll send out PR soon.

![image](https://user-images.githubusercontent.com/15821566/30898990-d81d4e40-a312-11e7-8416-007b3c06ee2d.png)

![image](https://user-images.githubusercontent.com/15821566/30898998-e0fec7aa-a312-11e7-80cb-4dc5f4f1a111.png)
