### ISSUE TITLE
Web Apps Aren't Listed When serverFarmId Is Undefined

### ISSUE THREAD

**Issue by sunmorgus** [Microsoft/vscode-azureappservice#371]
Per conversation in #370, the serverFarmId in the SiteClient constructor can return as undefined, causing the Web App List in the explorer pane to return an error and not display the available web apps.

Going to review the code and submit a PR when a better solution is found (other than the solution submitted in #370).

**Comment by EricJizbaMSFT** [comment]
@sunmorgus FYI - we just released an update to the extension that includes this fix.

Thanks again for the contribution!
