### ISSUE TITLE
Pop up an error when opening a file under deployment slot after swapping with production

### ISSUE THREAD

**Issue by v-flyuan** [microsoft/vscode-azureappservice#375]
## Steps to reproduce
1. Make some changes to file 'florajson20180328' under deployment slot1.
2. Swap the deployment slot1 with production successfully.
3. Open the file 'florajson20180328' under production and it contains the updated content.
4. Open the file 'florajson20180328' under deployment slot1 and verify whether it opens successfully.

## Expected  behavior
The file 'florajson20180328' under deployment slot1 opens successfully.

## Actual behavior
Pop up an error.
![image](https://user-images.githubusercontent.com/12556995/38078657-99da91b8-336f-11e8-9f31-fbfd6ad3a5c6.png)

**Comment by StephenWeatherford** [comment]
Please go ahead and start using the new "Report an issue" button for these so that gets tested, too.  Thanks!
