### ISSUE TITLE
The function apps don't list in the tree view 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#381]
Repro Steps:
1. Select the same subscription as App Service Extension in Cloud Explorer and navigate to 'App Services' node.
2. Check the apps type, then check whether all nodes are listed or not for App Service Extension.

Expect:
All nodes under 'App Services' node list in the tree view for App Service Extension.

Actual:
The function apps don't list in the tree view for App Service Extension.
![compare](https://user-images.githubusercontent.com/34729092/38242685-ef904586-3724-11e8-9310-5dd283d881d0.png)

More Info:
The icons are same among web apps, mobile apps and API apps.

**Comment by EricJizbaMSFT** [comment]
Closing this as by-design. We intentionally chose to create a separate VS Code extension for Function Apps https://github.com/Microsoft/vscode-azurefunctions
