### ISSUE TITLE
Remote debug node-based app services

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#384]

**Comment by EricJizbaMSFT** [comment]
@auchenberg  you're working on this correct?

**Comment by auchenberg** [comment]
Yes @EricJizbaMSFT there's a branch for this with a working prototype: https://github.com/Microsoft/vscode-azureappservice/tree/node-remote-debug

This will be owned by an engineering team going forward.

**Comment by fiveisprime** [comment]
This will be in preview and behind a feature flag for Build with only Node.js support.

**Comment by EricJizbaMSFT** [comment]
Closed in #407. Remaining work #416 #417
