### ISSUE TITLE
App deploy error

### ISSUE THREAD

**Issue by sovaxster** [Microsoft/vscode-azureappservice#390]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Not Found</pre>
</body>
</html>

Version: 0.7.0
OS: win32

**Comment by nturinski** [comment]
@sovaxster We released a new version of the extension today that will hopefully fix this error.  Please let us know if this resolves your issue with deploying.

**Comment by EricJizbaMSFT** [comment]
Closing this since we haven't heard in a while. Please re-open if you're still having issues
