### ISSUE TITLE
JSON parse error when expanding files node

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#396]
I have a **Windows** app that is serving static content **with a custom domain**, expanding the files node results in a JSON parse error:

![image](https://user-images.githubusercontent.com/1186948/38630704-885728d2-3d6c-11e8-8476-da5d6b49a928.png)

**Comment by EricJizbaMSFT** [comment]
Can you try this on the latest version? It should be fixed
