### ISSUE TITLE
No tooltip displays for 'OK' button when selecting subscriptions

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#401]
Repro Steps:
1. Press 'Ctrl+ Shift+ P' to open 'Command Palette...'.
2. Type 'Select Subscriptions'.
3. Check whether there is a tooltip for 'OK' button or not.

Expect:
There is a tooltip for 'OK' button.

Actual:
No tooltip displays for 'OK' button.
![tooltip](https://user-images.githubusercontent.com/34729092/38726341-6ba7d1ee-3ef9-11e8-9a1b-43f7a0c94a4f.png)

**Comment by StephenWeatherford** [comment]
I wouldn't expect a tooltip for a button. It's normally used when there's information that won't fit on the control.
