### ISSUE TITLE
No 'WebJobs' node displays for deployment slots

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#402]
Repro Steps:
1. Right click one 'Deployment Slots' node and select 'Create New Deployment Slot'.
2. Expand the new created deployment slot and check the sub-nodes.

Expect:
Display 'WebJobs' node.

Actual:
No 'WebJobs' node displays.
![webjobs](https://user-images.githubusercontent.com/34729092/38726552-0042a84c-3efa-11e8-90f1-fbc08a1ab599.png)

More Info:
There is no context menu for new created WebJob.
![context](https://user-images.githubusercontent.com/34729092/38726608-24b8b0a4-3efa-11e8-8c9d-7014d76cc772.png)

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azureappservice/pull/720

![screen shot 2019-02-20 at 3 04 22 pm](https://user-images.githubusercontent.com/11282622/53131159-dc22bb00-3520-11e9-90f6-f5728e2d143d.png)
