### ISSUE TITLE
Remember what folder I've used to deploy

### ISSUE THREAD

**Issue by rolledback** [Microsoft/vscode-azureappservice#403]
Steps to repro:
1. Right click on a web app in the Azure App Service tree
2. Choose "Deploy to Web App"
3. Command palette appears, choose "Browse..."
4. Find and select folder
5. Deploy finishes, do some more stuff
6. Repeat steps 1 and 2

Expected:
The folder I chose in step 4 is now one of the options when the command palette appears in step 3.

Actual:
It's not there.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-azureappservice/pull/491
