### ISSUE TITLE
App service plan names are inconsistent

### ISSUE THREAD

**Issue by rolledback** [Microsoft/vscode-azureappservice#404]
Not a blocking issue, just an inconsistency between this tool and another Microsoft App Service tool.

Steps to repro:
1. Deploy an app service for the first time in VS (a service plan is made during this process)
2. Deploy another app service for the first time using this extension (a service plan is made during this process)

Expected
The names of the plans are created with the same format.

Actual
The VS app service tool uses the format "(app service name)Plan". This extension uses the format "(app service name)".

**Comment by EricJizbaMSFT** [comment]
This is by-design. We don't go by VS when determining consistency, we usually go by the portal. To us, "Plan" feels redundant and you don't get "rg" or "resourcegroup" appended when you get the default name for a resource group

**Comment by rolledback** [comment]
While I understand what you're saying, as a user, the inconsistency is weird. All I'm asking if for you guys to talk to the people who own the VS app service tool and get on the page as them/get them on the same page as you. Thanks!

**Comment by EricJizbaMSFT** [comment]
If you disagree with our reasoning for the default name then by all means let us know. However if you don't care about the default name and only care about consistency, please file feedback against VS to remove "Plan" :)

On a more general note, there's always going to be minor inconsistencies between VS and VS Code. It sounds like a long-term solution may be to help you choose a single development environment. If you prefer VS I can't really help with that - but if you prefer VS Code we'd love if you reported any blocking issues preventing you from moving completely over to VS Code.
