### ISSUE TITLE
jpApp

### ISSUE THREAD

**Issue by ejarekp** [Microsoft/vscode-azureappservice#406]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: fatal: Not a git repository (or any of the parent directories): .git

Version: 0.7.1
OS: win32

**Comment by nturinski** [comment]
@ejarekp Are you trying to deploy your application via Local Git?  You can check this by right-clicking your app service node in the explorer and clicking "Configure Deployment Source."

If the application is deploying via Local Git, the deployed project must have a git repository.  You can do this in your Powershell terminal by doing a `git init` in the project directory and then `git add .` and `git commit -m 'First commit'`.

**Comment by ejarekp** [comment]
Hi,
I am learning how Azure, Angular and API with ASP.NET Core works together.
I had som problems with configurations and free Hosted agent minutes (
visualstudio.com) so I had to switch into GitHub and I was forced to find
different solution in order to build succesly my basic project with Azure
(Web App). Now, I hope, I will build my foront and back demo app without
obstacles.


2018-04-23 20:24 GMT+02:00 Nathan <notifications@github.com>:

**Comment by EricJizbaMSFT** [comment]
Closing this since it's sounds like you have it fixed. Feel free to re-open if you're still having problems
