### ISSUE TITLE
Error when deploy to web app

### ISSUE THREAD

**Issue by owsis** [Microsoft/vscode-azureappservice#409]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND apptobi.scm.azurewebsites.net apptobi.scm.azurewebsites.net:443

Version: 0.7.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Thanks for reporting! Closing this a dupe of #398
