### ISSUE TITLE
Display a confused message when enabling logging for web apps at the first time

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#414]
Repro Steps:
1. Right click one web app and select 'Start Streaming Logs'.
2. Click 'Yes' in the prompting dialog, then check the activity log.

Expect:
Display '**Starting** 'xxx'(web app name)...'.

Actual:
Display '**Restarting** 'xxx'(app name)...'.
![restart](https://user-images.githubusercontent.com/34729092/39117507-964b786c-46d6-11e8-98a5-ac700ead9caf.PNG)

**Comment by EricJizbaMSFT** [comment]
Closing this as won't-fix. @fiveisprime and I think the wording here makes sense. It's restarting the app, not restarting the 'log stream'.

We have another issue open to go over this experience more broadly anyways: https://github.com/Microsoft/vscode-azureappservice/issues/391
