### ISSUE TITLE
Error during deploy nodejs app to Azure

### ISSUE THREAD

**Issue by acoderlive** [Microsoft/vscode-azureappservice#415]
Repro steps:
1. Expand Azure App Service 
2. Right click and Create new Web App
3. After entering all the relevant info, web app on Azure is created
4. Deploy web app
5. error
17:22:25 carboapi: Creating zip package...
17:24:57 carboapi: Starting deployment...
17:38:13 carboapi: Fetching changes.
17:38:13 carboapi: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/3e9kpaa2.zip (0.00 MB) to /tmp/zipdeploy/extracted
17:38:13 carboapi: Central Directory corrupt.
Error: Deployment to "carboapi" failed.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "carboapi" failed. See output channel for more details.

Version: 0.7.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Glad you got it fixed for yourself. I'll leave this open - it's possible we can provide better validation that we zipped the folder successfully

**Comment by acoderlive** [comment]
Hi, actually the error is on the azure server. Not sure why the zip file was not uploading to completion. Had to delete the app server and recreate it. Can you check that? Tq

Sent from my iPhone

On 3 May 2018, at 1:48 AM, Eric Jizba <notifications@github.com<mailto:notifications@github.com>> wrote:


Glad you got it fixed for yourself. I'll leave this open - it's possible we can provide better validation that we zipped the folder successfully

**Comment by EricJizbaMSFT** [comment]
Closing as this seemed to have been fixed when using a new web app. Please file a new issue with updated repro steps if it's still a problem
