### ISSUE TITLE
Cannot find Subscription with name xxxxxxxx-xxxx-xxxxxxxxxxxx

### ISSUE THREAD

**Issue by FlowCAD** [Microsoft/vscode-azureappservice#419]
Repro steps:
- Clicked on "Deploy to webApp"
- Selected the folder of my webApp
- Selected my Free Plan (just created so empty)
- And then seeing the error occured and crying

Usefull information : I've got an error in my Azure App Extension ! Under "Free Trial" there is "Error : Cannot find Subscription with name xxxxxxxx-xxxx-xxxxxxxxxxxx." but I saw on the internet that it was because ain't got anything in my account and it wasn't important...

Action: appService.Deploy
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{"statusCode":404,"request":{"rawResponse":false,"queryString":{},"url":"https://management.azure.com/subscriptions/ xxxxxxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Web/sites?api-version=2016-08-01","method":"GET","headers":{"x-ms-client-request-id":"xxxxxxxx-xxxx-xxxxxxxxxxxx","accept-language":"en-US","Content-Type":"application/json; charset=utf-8","user-agent":"Node/v7.9.0 (x64-Linux-4.4.0-121-generic) ms-rest/2.3.3 ms-rest-azure/2.5.5 azure-arm-website/1.0.0-preview Azure-SDK-For-Node"},"body":null},"response":{"body":"{\"Code\":\"NotFound\",\"Message\":\"Cannot find Subscription with name  xxxxxxxx-xxxx-xxxxxxxxxxxx.\",\"Target\":null,\"Details\":[{\"Message\":\"Cannot find Subscription with name xxxxxxxx-xxxx-xxxxxxxxxxxx.\"},{\"Code\":\"NotFound\"},{\"ErrorEntity\":{\"ExtendedCode\":\"51004\",\"MessageTemplate\":\"Cannot find {0} with name {1}.\",\"Parameters\":[\"Subscription\",\" xxxxxxxx-xxxx-xxxxxxxxxxxx\"],\"Code\":\"NotFound\",\"Message\":\"Cannot find Subscription with name  xxxxxxxx-xxxx-xxxxxxxxxxxx.\"}}],\"Innererror\":null}","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"519","content-type":"application/json; charset=utf-8","expires":"-1","strict-transport-security":"max-age=31536000; includeSubDomains","x-ms-ratelimit-remaining-subscription-reads":"14997","server":"Microsoft-IIS/10.0","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","x-ms-request-id":"ad980a2a-733d-4e1e-a745-014d5da30cab","x-ms-correlation-request-id":"ad980a2a-733d-4e1e-a745-014d5da30cab","x-ms-routing-request-id":"FRANCECENTRAL:20180424T160207Z:ad980a2a-733d-4e1e-a745-014d5da30cab","x-content-type-options":"nosniff","date":"Tue, 24 Apr 2018 16:02:06 GMT","connection":"close"},"statusCode":404},"body":{}},"_listeners":null,"_isException":false,"_errorId":7}}

Version: 0.7.1
OS: Ubuntu 16.04

**Comment by fiveisprime** [comment]
Are you behind a proxy? If so, you may need to set `HTTP_PROXY` and `HTTPS_PROXY` environment variables to get things working correctly.

Something like 

```sh
export HTTPS_PROXY=http://username:password@proxy:8080
export HTTP_PROXY=http://username:password@proxy:8080
```

**Comment by FlowCAD** [comment]
No but I finally find out a solution in creating my first webapp from the azure website and then using vs code extension for other webapp ! Maybe something badly initialized somewhere ... but now it's working fine for me ! =)

**Comment by EricJizbaMSFT** [comment]
Not sure how/if we can fix the main issue, but we can at least show a better error message than all that json

**Comment by EricJizbaMSFT** [comment]
Re-opening this as it consistently reproduces for new subscriptions. Turns out we have to make sure the 'Microsoft.Web' provider is registered
