### ISSUE TITLE
[From Email] Failed deployment: "Unexpected token '<'"

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#421]
Got a user report of a deployment error that appears to be related to changes in the extension:

---

I've successfully updated node.js app into Azure Web App with your extension... until today.
The app after deployment reports `"Unexpected token '<'"`.

Unfortunately I'm not experiences node.js developer (it is just some unknown native code for me). I will work on it by myself.

But just for your information that probably something changed in deployment procedure? It displays different lines than previously (Luckily I've copied old and new output).

**Comment by EricJizbaMSFT** [comment]
Need a little more information to investigate this. Putting in future for now

**Comment by EricJizbaMSFT** [comment]
Closing this issue due to lack of information. Feel free to re-open with more info
