### ISSUE TITLE
Entry not found in cache

### ISSUE THREAD

**Issue by xcodemaker** [microsoft/vscode-azureappservice#430]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.CreateWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.7.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
I'm not sure if we can fix this on the VS Code side or if this error is coming directly from Azure. Worth at least investigating where the error is coming from

**Comment by jdneo** [comment]
This might be related with this issue: https://github.com/Microsoft/vscode-azure-account/issues/53

**Comment by gezza-b** [comment]
I am still receiving this error:

Repro steps: deploy jar file
Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.
Version: 0.9.1
OS: win32

**Comment by mmulhearn** [comment]
I'm still seeing this today

**Comment by nturinski** [comment]
Yeah, we are still tracking the external issue here:
https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/199

Please add some 👍's to give the team feedback that this is an issue worth resolving!
