### ISSUE TITLE
Error in Deploying Nodejs App

### ISSUE THREAD

**Issue by gaurav-bothra** [Microsoft/vscode-azureappservice#437]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN management.azure.com:443

Version: 0.8.0
OS: linux

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
