### ISSUE TITLE
It is unfriendly to display the entire long string for application setting name

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#442]
Repro Steps:
1. Right click 'Application Settings' node and select 'Add New Setting...'.
2. Enter a large value for setting key, then press 'Enter'.
3. Check the large value for setting key.

Expect:
A part of the setting key is omitted with ellipsis.

Actual:
Display the entire long string.

More Info:
This issue also reproduce when deleting an application setting with long string key/value.

**Comment by EricJizbaMSFT** [comment]
Won't fix. This is debatably by-design and handled by VS Code anyways, not us.

**Comment by v-dantch** [comment]
Got it. Thanks a lot for your update.
