### ISSUE TITLE
Issue with Angular 5 

### ISSUE THREAD

**Issue by ecingala** [Microsoft/vscode-azureappservice#452]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "chatapp-web-dev" failed. See output channel for more details.

Version: 0.8.1
OS: win32

**Comment by nturinski** [comment]
Hi @ecingala 

Thank you for reporting this issue.

Could you provide any more information about the web app that you are deploying to? Is your web app running on Windows or Linux?

If you look at the logs, there might be some more information as to why the deployment failed.

Sorry that you're dealing with this issue, but hopefully we can resolve this.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response.  Please feel free to reopen if you are still having issues.
