### ISSUE TITLE
Improved getting started experience

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#453]
When deploying an app, try to determine the type of app being deployed; based on the type of app, use the following defaults. These defaults follow the `$ az webapp up` experience.

### All stacks
There are some places where the extension can be a little smarter and remove some prompts.

- Only prompt for workspace if more than one is present (need to discuss the implications here...)
- Only prompt for subscription when more than one sub is available (factor filtering into this)

### Node.js
There will only be two prompts when creating then deploying a new node app: name and location. Everything will be created based on the name and location. 

- Linux
- Resource group name to `appsvc_rg_Linux_<location>`
- Set plan to B1 with name of `appsvc_asp_Linux_<location>`
- Set `SCM_DO_BUILD_DURING_DEPLOYMENT` to 1
- Add VS Code setting to ignore node_modules directory
- Use latest LTS version of node (whatever the recommended version is at the time)

### .NET Core
Since .NET Core doesn't support zip deploy on Linux, we should default to the Windows experience. 

- Windows
- Resource group name to `appsvc_rg_Windows_<location>`
- Set plan to B1 with name of `appsvc_asp_Windows_<location>`

**Comment by nturinski** [comment]
No workspace/Not recognized project- 

Prompt for Name, Location, Language, or OS/Framework
