### ISSUE TITLE
Keep output window hidden, use long running notifications

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#455]
Keep the output window hidden when deploying or deleting (those are the commands I can think of that open the output window). Still write info to output and just keep it out of the way, instead use the long running notification.

On failed deployment, prompt to check the output window and open to the correct channel if selected.

**Comment by nturinski** [comment]
@fiveisprime I think the answer is yes, but do we want to show the output window when users Start Streaming?

**Comment by fiveisprime** [comment]
Super late considering you just merged this, but... yeah. haha
