### ISSUE TITLE
[Suggestion]Add keyboard shortcuts for 'Azure' tab

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#457]
Repro Steps:
Hover the mouse on the Azure, then check whether there is a keyboard shortcuts for it.

Suggestion:
Add keyboard shortcuts for 'Azure' tab.
![keyboard](https://user-images.githubusercontent.com/34729092/40967723-50cac57e-68a3-11e8-805a-b0841198691b.png)

**Comment by fiveisprime** [comment]
I like this idea. Is this something the API allows for @chrisdias?

**Comment by chrisdias** [comment]
I don't think so, @sandy081 ?  if not, @fiveisprime can you submit an issue to the vs code repo?

**Comment by sandy081** [comment]
This should be supported out of the box. Please file an issue in VS Code.

**Comment by v-dantch** [comment]
Thanks a lot for your update.

**Comment by nturinski** [comment]
Hi @sandy081,

I was wondering if I could get a quick answer from you about setting keybindings.
1. Is the only place to set custom keybindings is in the `keybindings.json`?
![image](https://user-images.githubusercontent.com/5290572/42537859-f66100f8-844a-11e8-8b2e-372e7df6652a.png)
1.  Would the command to open the view be `workbench.view."id"` where "id" is the id property of the viewContainer?
![image](https://user-images.githubusercontent.com/5290572/42537900-12508996-844b-11e8-961e-cadba1d67507.png)

Thanks,
Nathan

**Comment by sandy081** [comment]
Yes, but the command is `workbench.view.extension.${id}`.
