### ISSUE TITLE
App Service readme issue

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#459]
bad link to image in app service readme:

![image](https://user-images.githubusercontent.com/1487073/41109758-9b223424-6a2c-11e8-8cfb-1344d9be5f08.png)

**Comment by fiveisprime** [comment]
Fixed in #450

**Comment by EricJizbaMSFT** [comment]
This was actually _caused_ by 450, not fixed by it. 

@chrisdias I created an issue on VS Code for this: https://github.com/Microsoft/vscode/issues/52219. We didn't realize the marketplace was pulling images directly from our master branch on Github.
