### ISSUE TITLE
Unable to disable Azure extension(s) due to circular dependency.

### ISSUE THREAD

**Issue by jleach** [Microsoft/vscode-azureappservice#463]
Looks like there is a circular dependency: Azure App Services cannot be disabled because Azure Functions depends on it; Azure Functions can not be disable because App Services depends on it.

- VSCode 1.24.0
- Latest extensions.

When asked "Would you like to disable the dependencies of the extensions also?" I answer **Yes**

<img width="572" alt="screenshot 2018-06-08 12 17 33" src="https://user-images.githubusercontent.com/390891/41176722-59b4e852-6b16-11e8-94ff-076a6f99a568.png">

**Comment by jleach** [comment]
Closing because nobody seems too interested in this bug.

**Comment by EricJizbaMSFT** [comment]
@jleach Sorry for the delay. The extensions aren't actually dependencies of each other. However, they both depend on the 'Azure Account' extension. You must select 'No' for that question if you want to disable an individual Azure extension.

I've filed an issue on the VS Code repo to make the error message clearer: https://github.com/Microsoft/vscode/issues/52220
