### ISSUE TITLE
Random Web Deploy Error

### ISSUE THREAD

**Issue by sarif-zparr** [Microsoft/vscode-azureappservice#464]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: The page cannot be displayed because an internal server error has occurred.

Version: 0.8.1
OS: win32

**Comment by nturinski** [comment]
Hi @sarif-zparr,

Sorry that you're having problems deploying, but thank you for reporting this issue.

Could you provide any more information about the project that you are deploying and the web app that you are deploying to?

1. What language is your project?  If nodejs, are you using a Angular/React?
1. Is your web app running on Windows or Linux?

Thanks,
Nathan

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
