### ISSUE TITLE
Unable to get remote debugging to work with node

### ISSUE THREAD

**Issue by jackharich** [Microsoft/vscode-azureappservice#469]
Repro steps:
Trying to get remote debugging to work. This is a node app. In package.json I added this line:
"start_azure_debug": "node --inspect=0.0.0.0:$APPSVC_TUNNEL_PORT ./work/TrsServer.js",

The documentation on remote debugging in non-existent. The best is a non-azure article at:
https://medium.com/@auchenberg/introducing-remote-debugging-of-node-js-apps-on-azure-app-service-from-vs-code-in-public-preview-9b8d83a6e1f0
But note how this is obsolete. Application Settings no longer has a startup file.

And then there's this article: https://blog.maartenballiauw.be/post/2018/05/29/remote-debugging-node-js-azure-app-service-webstorm.html
But again, this is not official doc and it to has Startup File. The fact that people are publishing articles like this indicates that they found no doc, so they wrote an article to help others. But they did get remote debugging working. I have not. 

Can you point me toward some current documentation how to get remote debugging working with node and Azure App Service in Visual Code Studio? Thanks.

Action: diagnostics.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application after 30000 milliseconds

Version: 0.8.1
OS: win32

**Comment by auchenberg** [comment]
Hi @jackharich 👋

Remote debugging for Node apps on App Service Linux are currently in a early preview, hence for reason for my why announcement blog post is the only documentation.

It looks like you have created a new npm script `start_azure_debug`, which looks great. The next step would be for you to update your startup file for your Node app. You are saying that the option isn't no longer in your Azure Portal? It should be under `Application settings` for your App Service instance.

**Comment by mrcrane** [comment]
Documentation can currently be found here: https://github.com/Microsoft/vscode-azureappservice/wiki/Remote-Debugging

The experience has improved and is simpler than when this issue was created.
