### ISSUE TITLE
Azure Cloud Shell - mkdir command fails

### ISSUE THREAD

**Issue by jackharich** [Microsoft/vscode-azureappservice#470]
Please examine this astonishing behavior. All I'm trying to do is what's described in this doc:
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs
in the Download the Sample section.

PS Azure:\> mkdir quickstart
Azure:\
PS Azure:\> cd quickstart
cd : Cannot find path 'Azure:\quickstart' because it does not exist.
At line:1 char:1
+ cd quickstart
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Azure:\quickstart:String) [Set-Location], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

Azure:\
PS Azure:\> ls
    Directory: Azure:
Mode SubscriptionName SubscriptionId                       TenantId                             State
---- ---------------- --------------                       --------                             -----
+    Free Trial       eef5ad79-6834-40a5-ac89-1c2d172f4f00 ad1885cb-fc85-4048-8657-f1537640a127 Enabled

**Comment by fiveisprime** [comment]
Moved this to the account extension: https://github.com/Microsoft/vscode-azure-account/issues/69
