### ISSUE TITLE
Diagnose and solve problems - Health checkup hangs for over an hour

### ISSUE THREAD

**Issue by jackharich** [Microsoft/vscode-azureappservice#471]
This on a node site that I'm having extreme difficultly getting to work. Please see the image.

![azurehealthcheckuphangs](https://user-images.githubusercontent.com/34491685/41503261-7e565556-719c-11e8-97a0-125a50459ab0.png)

**Comment by fiveisprime** [comment]
Hi, please use the Help and Support (question mark button up in the top, right) to contact the platform support team for this.
