### ISSUE TITLE
deployment issue?

### ISSUE THREAD

**Issue by ryanjparke** [Microsoft/vscode-azureappservice#474]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: No matching resources found.

Version: 0.8.1
OS: darwin

**Comment by ryanjparke** [comment]
What does the error mean? Error: no matching resources found. 

Note: the resource in my discription displays as “nsg-site-tst (invalid).  Could that be part of the issue?

**Comment by nturinski** [comment]
Hi @ryanjparke,

Thanks for reporting this issue.  

Could you please answer these questions to help shed some light on the problem?

- Is this a new subscription that you created?  
- Was it a F1 (Free) tier?  
- Is the resource new?  Did you create it in the extension or the portal?
- Did the resource always display (invalid) or did that happen recently?

Sorry for the issues.  Hopefully, we can get to the bottom of this.

**Comment by davidramirezv17** [comment]
Hi
I have the same problem.
- The subscription has been created by other, but is an App Service in a Basic App Service Plan. 
- The App Service has been created in the Portal.
- The resource has been always (invalid) since I installed and logging in the extension.

If you know a possible solution, I'll thank you so much.

Regards

**Comment by nturinski** [comment]
Hi @davidramirezv17 

Thanks for answering my questions.  I created an app with similar settings, but it's not showing up as invalid for me.  Do you know exactly how your app is configured?

- Is the App Service Plan Linux or Windows?
- The runtime of your App Service if it's on a Linux ASP?
- Any other unique configurations that you might have?

Sorry for the trouble-- I'll keep trying on my end to see what's going on here.

Thanks!

**Comment by davidramirezv17** [comment]
Hi @nturinski 

It's a Windows App Service.
Only one aditional configuration:
{
    "name": "WEBSITE_NODE_DEFAULT_VERSION",
    "slotSetting": false,
    "value": "8.9.4"
}
I already deployed through Azure CLI and It works. 
Even after the deployment, the App Service is still (invalid).

Regards

**Comment by nturinski** [comment]
@davidramirezv17 I've tried to create an app with those settings without any luck.  But I'll keep investigating and trying to repro your issue.  

I'm really sorry about the inconvenience and lack of resolution.  Please let me know if you can think of anything else that may have caused your app to appear as invalid.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of info and since the extension has changed since last July. If you're still running into this issue please file a new issue with detailed repro steps
