### ISSUE TITLE
Error: There is a deployment currently in progress. Please try again when it completes when deploy to Windows Azure App Service

### ISSUE THREAD

**Issue by jficarapi** [Microsoft/vscode-azureappservice#476]
Repro steps:
Create a new app service in azure using vs code azure workbench.view.extension.azure
Wait for app service to be created

Right click on app service you just created and choose deploy
After Starting deployment message and waiting for long running command to finish the following error is presented:

Error: There is a deployment currently in progress. Please try again when it completes.

Action: appService.Deploy
Error type: Error
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.8.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Does this happen consistently for you?

Just to confirm - you only deployed once and you still saw this error?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more information
