### ISSUE TITLE
Display an error after expanding 'kudu' node under 'Log Files'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#481]
Repro Steps:
1. Click '+' to create a new web app.
2. Make sure the new web app is created successfully, then drill down from new web app > 'Log Files' > 'kudu'.
3. Check whether there is an error after expanding 'kudu' node.

Expect:
There is no error.

Actual:
Display an error 'Error: 'D:\home\ome\LogFiles\kudu' not found'.
![compare](https://user-images.githubusercontent.com/34729092/41705807-ad3cfba0-7529-11e8-98d9-ce4d01d4834b.png)

**Comment by nturinski** [comment]
Nice catch!

It seems to be an error with the path parsing.  Windows apps use the prefix 'home\' whereas Linux uses 'home/'.

Opening a PR to solve this bug.
