### ISSUE TITLE
Unable to establish connection to application after 30000 milliseco

### ISSUE THREAD

**Issue by Spandana-Gajangi** [Microsoft/vscode-azureappservice#483]
Repro steps:
<Enter steps to reproduce issue>

Action: diagnostics.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application after 30000 milliseconds

Version: 0.8.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Closing as dupe of https://github.com/Microsoft/vscode-azureappservice/issues/448
