### ISSUE TITLE
Support remote debugging of Python Apps

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-azureappservice#484]
We'd love to see support in the [Python](https://github.com/Microsoft/vscode-python) extension as well. Please do let us know if this can be done today for Python as well.

Looking at the implementation, we (Python app) would at a minimum need the `APPSVC_TUNNEL_PORT` environment variable.
Also, the VSC client side extension would need to launch the Python debugger locally. Do let us know how we can assist in this space to get it working for Python.

**Comment by EricJizbaMSFT** [comment]
@auchenberg @mrcrane thoughts on this

**Comment by DonJayamanne** [comment]
@EricJizbaMSFT 
We (Python Extension Team) had a chat with @auchenberg and a few others about this.
To my knowledge this is what will happen next (a very high level overview):
* App Services team creates the Python Docker container for Python Web Apps with conditional debugging (based on `APPSVC_TUNNEL_PORT` env variable or similar)
* Next, this Extension will need to be modified to detect whether its a python container and accordingly launch the `Python Debugger`. I can submit a PR once we have the Python Container ready.

**Comment by fiveisprime** [comment]
There're are changes proposed against the images to add Python debugging support and I'll work with the diagnostics team to get this planned.

https://github.com/microsoft/Oryx/pull/303

**Comment by nturinski** [comment]
I believe everything is merged on our end.  @Anapo14 could you confirm that Python Remote Debugging is working as expected?

**Comment by EricJizbaMSFT** [comment]
Nathan says it works
