### ISSUE TITLE
The previous name should be selected when renaming one Application Setting

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azureappservice#488]
Repro Steps:
1. Go to Subscription -> Select one web app.
2. Create a new Application Setting named 'test1'-> Rename the created Setting -> Check whether the previous name is selected or not.

Expected:
The previous name is selected.
![selected](https://user-images.githubusercontent.com/34729022/41898623-0df56e5c-791a-11e8-806f-b5cfacc0e3ba.png)

Actual:
The previous name isn't selected.

**Comment by EricJizbaMSFT** [comment]
I tested this and it no longer repros for me - the value is selected by default. It was likely fixed in VS Code at some point
