### ISSUE TITLE
Suggestion: Add ability to ssh into app service console

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#493]
It would be cool to be able to open up a console for the App Service, directly from within VS Code, much like you can open a Cloud Console (see https://www.michaelcrump.net/azure-tips-and-tricks49/).  Not sure if it is possible, but it would be helpful to see logs, run npm install, builds, etc.

**Comment by fiveisprime** [comment]
I thought for sure I had already created an issue for this. SSH access will be added via the new SSH API that was added around Build time.

https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ssh-support
