### ISSUE TITLE
Support deploying to a slot and making it live immediately

### ISSUE THREAD

**Issue by cfjedimaster** [microsoft/vscode-azureappservice#496]
Please note I am *not* a real user of this service. I was having a conversation on Twitter (https://twitter.com/John_Papa/status/10142358554463313920) with John Papa where he mentioned the 'slot' feature and how cool it was to deploy - test - and set as release w/o harming his current active production deployment.

I followed up with a question about being able to automate this - ie deploy this new slot and when it is done, make it automatically the new production slot. Wouter de Kort mentioned this wasn't available but it would be a good request. Which I've done here. :) 

Again - I'm not really a user so forgive me if I got any of the terms wrong.

**Comment by EricJizbaMSFT** [comment]
ping @fiveisprime

**Comment by EricJizbaMSFT** [comment]
This feels out of place for a VS Code extension and more appropriately solved by CI/CD - it might even be possible already. Going to go ahead a close due to lack of activity
