### ISSUE TITLE
The deleted application setting which is being edited/renamed reappears after refreshing

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#504]
Repro Steps:
1. Right click one application setting and select 'Edit.../Rename...'.
2. Make sure the edit/rename box is open, delete this application setting.
3. After deleting successfully, press 'Enter'.
4. Refresh 'Application Settings' node and check the result.

Expect:
The deleted application setting doesn't reappear.

Actual:
The deleted application setting reappears. Please get the details from "\\trinlab2\BAQAFiles\CloudToolsTest\v-dantch\Video\actual.mp4"

**Comment by EricJizbaMSFT** [comment]
Closing this as wont-fix. I don't think many users will do this and I think it's debatable what the expected behavior is. On one hand, it's weird that the setting exists after you just deleted it, but edit and create are very similar behaviors when it comes to app settings.

**Comment by v-dantch** [comment]
Ok, got it. And thanks for your update.
