### ISSUE TITLE
User setting for enabling/disabling what prompts are shown for app creation

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#508]
Maybe we can have an object or array that will enable/disable creation prompts from being asked. For example:

`{ resourceGroups: false, appServicePlans: false, websiteOS: true }`
`[websiteOS, runtime]`

**Comment by EricJizbaMSFT** [comment]
Closing as we significantly refactored this experience with basic/advanced create since the issue was originally filed
