### ISSUE TITLE
Log files can be edited and saved successfully 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#515]
Repro Steps:
1. Drill down from Subscription -> web app -> Log Files, then open one log file.
2. Check whether the log file can be edited and saved or not.

Expect:
Fail to edit the log file and cannot save it directly but somewhere locally.

Actual:
Log files can be edited and saved directly.

**Comment by nturinski** [comment]
I think what you're describing is by-design.

Sorry, I might have described it poorly in the test case!  But all Log Files can be edited and saved locally, but the save will not update the remote log files (like what happens with the `Files` node).

Sorry for the confusion!  Am closing with the by-design label.

**Comment by v-dantch** [comment]
Hi Nathan, 

Thanks a lot for your update.
About edit, it is by design that the log files can be edited.

About saving,
   Does 'saved locally' means that the log files will be saved on PC? 
   Actually the remote log files can be updated not saved locally.  Please get the details from \\trinlab2\BAQAFiles\CloudToolsTest\v-dantch\Video\Save.mp4

**Comment by nturinski** [comment]
Oh wow, that is definitely not what happens on my machine.  Thanks for the video-- I'll investigate this further!
