### ISSUE TITLE
D1 ASP doesn't allow slots too, apparently?

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azureappservice#520]
Repro steps:
1. Scale a plan to the D1 service plan
1. Create a slot.
1. Receive divine error.

Action: appService.CreateSlot
Error type: Conflict
Error Message: Cannot complete the operation because the site will exceed the number of slots allowed for the 'Shared' SKU.

Version: 0.9.0
OS: win32

**Comment by fiveisprime** [comment]
S only. Neither F, B, nor D support slots as they are marked as "dev/test" plans. :(
