### ISSUE TITLE
Not able connect to the app service

### ISSUE THREAD

**Issue by AhmetCavus** [microsoft/vscode-azureappservice#528]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application after 240 seconds

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment]
Hi @AhmetCavus 

Thanks for reporting the issue.  Could you please give us some more information about your project?  Note that remote debugging currently only supports Node.js projects.

**Comment by EricJizbaMSFT** [comment]
@AhmetCavus Just wanted to let you know there was an outage around this time.  Could you try again and see if you are able to reproduce this issue?

Thanks
