### ISSUE TITLE
view logs (after deploy) doesn't take me to the app logs

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#530]
Testing out the new improved e2e experience...  Once deployment is done I get a notification that the site is deployed with two options: "View Logs" and "Browse Website".

![image](https://user-images.githubusercontent.com/1487073/42789476-5a591036-891a-11e8-804d-32a996bf5307.png)

My expectation when clicking no "View Logs" was that I would see my Application's logs, not the extension deployment logs (Output -> Azure App Service). I'm not sure why I would want to see those logs??

**Comment by fiveisprime** [comment]
This is two items:

- [ ] Change the button to "View Output" or similar, reserve the use of "logs" for the application logs
- [ ] Add a button to attach to the log stream "Steam App Log" or "Steam Logs"
