### ISSUE TITLE
Files icon are transparent when hovering the mouse over it

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#532]
Repro Steps:
1. Navigate to one web app -> 'Files' node.
2. Upload a folder containing one file at least elsewhere like VS.
3. Head back VS Code and expand the 'Files', then hover the mouse over one file.
4. Check whether the file icon displays well or not.

Expect:
Files icon are opaque.

Actual:
Files icon are transparent.
![compare](https://user-images.githubusercontent.com/34729092/42802779-69b93604-8993-11e8-9dfe-c344590d6b69.png)

**Comment by EricJizbaMSFT** [comment]
Closing this as by-design. According to @jinglouMSFT cloud explorer has plans to become more consistent with VS Code icons

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
