### ISSUE TITLE
Lack of folder icon for sub-folder under 'Files' node

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#534]
Repro Steps:
1. Navigate to one web app -> 'Files' node.
2. Upload a folder containing one subfolder at least elsewhere like VS.
3. Head back VS Code and expand the 'Files', then check whether all folders icon display well or not.

Expect:
All folders icon display well.

Actual:
Lack of folders icon for sub-folder.
![icon](https://user-images.githubusercontent.com/34729092/42802625-fe00e01a-8992-11e8-8823-f2d92fa93339.png)

**Comment by EricJizbaMSFT** [comment]
@nturinski  intentionally did not use an icon for subfolders and I agree with his reasoning. He wanted it to match VS Code's explorer view, which does not have icons for folders by default:
![screen shot 2018-07-17 at 10 39 35 am](https://user-images.githubusercontent.com/11282622/42835519-db3d69e8-89ad-11e8-85cd-e0f46277b05b.png)

Closing as by-design

**Comment by v-dantch** [comment]
Got it and thanks for your update.
