### ISSUE TITLE
Fail to open one web app using browser with error 'Cannot GET /'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#535]
Repro Steps:
1. Create a web app with Linux OS.
2. Right click this new web app and select 'Browse Website'.
3. Check whether the browser displays well or not.

Expect:
The website displays well.

Actual:
Display 'Cannot GET /'.
![error](https://user-images.githubusercontent.com/34729092/42804160-a24cfac4-8997-11e8-96e7-bc0a45379269.png)

More Info:
1. Display 'You do not have permission to view this directory or page' for web apps with Windows OS.
![errors](https://user-images.githubusercontent.com/34729092/42804166-a6223d12-8997-11e8-8cea-668704599d84.PNG)
2. I have logged in portal.

**Comment by fiveisprime** [comment]
This isn't an issue with the extension, is correctly opening the URL. These are both errors from the deployed app, which either 1) wasn't able to start (the first error) or 2) the app is crashing (the second error).

I recommend streaming the logs to figure out why the app isn't running correctly.
