### ISSUE TITLE
Entry not found

### ISSUE THREAD

**Issue by prabhatmuroor** [Microsoft/vscode-azureappservice#537]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment]
Hi @prabhatmuroor 

Thanks for reporting this issue.  I'm sorry that you're having issues deploying.  Could I ask you a few questions to begin investigating?

1. Did you create this web app in the Portal or the extension?
1. If this app was created in the extension, did you deploy immediately after creating?

Would you mind adding some repro steps so I could reproduce the error and investigate further?

Thank you!

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info
