### ISSUE TITLE
appService.showFile Issue

### ISSUE THREAD

**Issue by SpillChek2** [Microsoft/vscode-azureappservice#538]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.showFile
Error type: Error
Error Message: 'D:\home\LogFiles\kudu\trace\2018-07-19T19-04-34_fff6a3_017_GET_vfs-LogFiles-kudu-trace_pending.xml' not found.

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment]
Hi @SpillChek2,

Thanks for reporting this issue.  I believe this is happening because `2018-07-19T19-04-34_fff6a3_017_GET_vfs-LogFiles-kudu-trace_pending.xml` is currently being accessed.  After the file is no longer 'pending,' you should be able to view the file.

**Comment by SpillChek2** [comment]
Thank you @nturinski
