### ISSUE TITLE
Enable Try App Service flow from the extension

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#542]
Add a third option when a user isn't authenticated to Try App Service. See: https://azure.microsoft.com/en-us/try/app-service/web/?language=nodejs

Create a third option when a user isn't authenticated to Try App Service then direct into the flow.

**Comment by nturinski** [comment]
@fiveisprime Is the third option to just open this link with a node labeled `Try App Service`?

**Comment by fiveisprime** [comment]
We'll need to sit down and work out the requirements. It's related to https://github.com/Microsoft/vscode-azuretools/issues/227

My thinking is the try app service option uses the try app service API to provision a web app and retrieve the publishing profile then offload a git clone to VS Code. Once cloned and opened in VS Code, the extension shows a trial subscription node and the web app they have access to so they can make changes and deploy.

**Comment by fiveisprime** [comment]
Closing this since we have a free tier now. 🎉
