### ISSUE TITLE
Error on restarting web app while remote debugging

### ISSUE THREAD

**Issue by AlexTeixeira** [Microsoft/vscode-azureappservice#543]
Repro steps:
Trying to restart a Azure web app from a vs code that are in debug mode

Action: appService.Restart
Error type: Error
Error Message: Error: Unknown command 'getDebugAdapterMetadata'.

Version: 0.9.0
OS: darwin

**Comment by nturinski** [comment]
@AlexTeixeira 

Thanks for reporting this issue.  I've been able to reproduce it by starting remote debugging and then restarting the app.

@mrcrane Could you investigate this issue?

**Comment by AlexTeixeira** [comment]
Hi,

With the last update, I do not reproduce the error. I think it was an internal bug due to my using of VSCode (I have regulary 3 and more instances).

**Comment by mrcrane** [comment]
Closing this since the bug does not reproduce any longer.
