### ISSUE TITLE
Support deploy executable jar file to Linux Java SE image

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azureappservice#545]
The workflow might be:
1. Select/Create target web app
2. Choose the jar file (User can select the jar file in the current workspace or browse other one in the file explorer)
3. Deploy

**Comment by SummerSun** [comment]
@EricJizbaMSFT 
Please let me know if there is any concern, or I miss anything.

We will accomplish the proposed workflow with several steps:
- Add new runtime ```java|8-jre8``` to SiteRunTimeSteps
- Add right-click deploy support for ```.jar``` files
- Filter the current workspace to list all ```.jar``` files when deploying to Java SE runtime web app
  - This behavior will be similar to that deploy war files to java tomcat runtime web app
- Update the deploying workflow to support zip a single file add deploy it to the web app
  - In the current version, zip deploy only supports the directory, for executable jar file, we could just zip and deploy it to the target web app. And for other web app runtimes, such as node, similar scenarios will be useful to users as well.

**Comment by EricJizbaMSFT** [comment]
I don't see the user scenario for deploying a single file to node. I would just focus on the Java scenario but otherwise sounds fine

**Comment by jdneo** [comment]
Resolved in #579
