### ISSUE TITLE
[Suggestion]Make more sense to display 'Select Subscription(s)'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#546]
Repro Steps:
1. Press F1 -> Type 'Azure: Select Subscriptions'.
2. Check the placeholder.

Actual:
Display 'Select Subscriptions'.

Suggestion:
Display 'Select Subscription(s)'.
![suggestion](https://user-images.githubusercontent.com/34729092/43506237-02342d5a-9559-11e8-99fc-de51ba914a43.png)

**Comment by EricJizbaMSFT** [comment]
"The documentation (UX) team suggest that we don't use the parenthesis format." - @jinglouMSFT

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
