### ISSUE TITLE
Shall we show Windows web apps in the TreeView?

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-azureappservice#55]
Currently the app service view show both Windows & Linux web apps and there is no UI indication of the type of the app.

**Comment by whiskeyjay** [comment]
We could use different icons to differentiate Windows and Linux web apps. Similar to what the portal does for App Service Plans.

**Comment by chrisdias** [comment]
i think we still need to limit the commands available for windows app services (for now at least)

**Comment by EricJizbaMSFT** [comment]
Done
