### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by KevinGouji** [Microsoft/vscode-azureappservice#550]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: EADDRINUSE
Error Message: connect EADDRINUSE 20.188.98.74:443

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment]
Hi @KevinGouji,

Thanks for reporting this issue.  Has this issue been persistent?  Could you offer any more insights on to how you encountered this issue so that I could repro it on my machine?

Thank you!

**Comment by KevinGouji** [comment]
Hi Nathan,

I have resolved this problem because I pushed the wrong branch to the azure. It made a crash on the cloud.

Thanks for your help!

Best Regards,
Xihuang
Sent from Mail for Windows 10

**Comment by nturinski** [comment]
That's great to hear!

Thanks for following up with me.  I'll go ahead and close this issue then.
