### ISSUE TITLE
congelado

### ISSUE THREAD

**Issue by loquillo10** [Microsoft/vscode-azureappservice#552]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.showFile
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:2,$model3) has been disposed

Version: 0.9.0
OS: win32

**Comment by StephenWeatherford** [comment]
@loquillo10 Were you by chance double-clicking on a file in the explorer to open it?  Thx.

**Comment by loquillo10** [comment]
si así mismo era, pero ya gracias a Dios no hace..
