### ISSUE TITLE
congelado y con el problema

### ISSUE THREAD

**Issue by loquillo10** [Microsoft/vscode-azureappservice#553]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.showFile
Error type: Error
Error Message: TextEditor#edit not possible on closed editors

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
We're refactoring the file edit feature. Closing in favor of https://github.com/Microsoft/vscode-azuretools/issues/177
