### ISSUE TITLE
ran into this while streaming logs

### ISSUE THREAD

**Issue by zulkarnain-shah** [Microsoft/vscode-azureappservice#556]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Restart
Error type: Error
Error Message: unrecognized request

Version: 0.9.0
OS: darwin

**Comment by nturinski** [comment]
Hi @zulkarnain-shah,

Thanks for reporting this issue.  I haven't been able to reproduce this.  Could you provide more details on how this error occurred?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of info. Feel free to re-open with more info
