### ISSUE TITLE
Trying to deploy an Express webapp to an existing webapp on azure.

### ISSUE THREAD

**Issue by adrianvellamlt** [Microsoft/vscode-azureappservice#558]
Repro steps:
Trying to deploy an Express webapp to an existing webapp on azure.

Action: appService.Deploy
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{},"_listeners":null,"_isException":false,"_errorId":61}}

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment]
Hi @adrianvellamlt,

Thank you for reporting this issue.  Do you happen to know if you left VS Code running idle for over 6 hours?  I've been investigating this issue and suspect that your cached token may have expired, but I haven't been able to reproduce this issue.

**Comment by EricJizbaMSFT** [comment]
I fixed how we parse the error message so that it will actually print something useful in this PR: https://github.com/Microsoft/vscode-azuretools/pull/240. That should help - but I'll leave this issue open just in case you can give us more information that will help us repro this issue

**Comment by adrianvellamlt** [comment]
Sorry for the belated reply, but the task was rescheduled and I did not have time to replicate the error. However, I will be looking into it again this week. 
Thanks for your replies.

**Comment by EricJizbaMSFT** [comment]
Closing as we already adjusted how errors are parsed. If you get time to test again feel free to re-open if it's not working
