### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TechFrozen1** [Microsoft/vscode-azureappservice#559]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.fileEditor.onDidSaveTextDocument
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:3,$model12) has been disposed

Version: 0.9.0
OS: win32

**Comment by nturinski** [comment]
@TechFrozen1 Thanks for reporting the issue.  For now, you'll have to save your files prior to closing them if you need to save them, but this should be resolved with our new release due to this PR: https://github.com/Microsoft/vscode-azuretools/issues/177
