### ISSUE TITLE
Invalid Object Creating new deployment slot or viewing deployment slot

### ISSUE THREAD

**Issue by roxberry** [Microsoft/vscode-azureappservice#564]
Repro steps:
Expand Deployment Slots or Create new deployment slot from vscode

Action: appService.CreateSlot
Error type: ArgumentError
Error Message: Invalid Object.

Version: 0.9.0
OS: darwin

**Comment by bercht-a** [comment]
Here also

**Comment by sobpilot** [comment]
Same problem here. Can't deploy, now using FTP to copy up files.
![azureerror](https://user-images.githubusercontent.com/21143213/44230374-9267ab00-a160-11e8-9462-d5aeac22429a.PNG)

**Comment by roxberry** [comment]
Coded deployment steps as a workaround - should work, need to defined $PROJECTROOT, $RESOURCEGROUP, $SITENAME, $SLOTNAME for your environment. 

```
cd $PROJECTROOT

dotnet publish --configuration release  --output ./publish/  --runtime win7-x64 /p:MvcRazorCompileOnPublish=false

cd bin⁩/release⁩/netcoreapp2.0⁩/win7-x64⁩

zip -r publish.zip publish

az webapp deployment source config-zip --slot $SLOTNAME --resource-group $RESOURCEGROUP --name $SITENAME --src publish.zip
```

**Comment by nturinski** [comment]
I believe that this issue is resolved now.  If everybody who was running into this issue could verify that it's fixed, I'd really appreciate that!  Thanks for your patience while we resolved this issue.  I hope it didn't block anybody for too long.

**Comment by sobpilot** [comment]
It is working now. Thank you!

**Comment by roxberry** [comment]
works for me, gracias.
