### ISSUE TITLE
Deployment Slots Issue

### ISSUE THREAD

**Issue by bercht-a** [Microsoft/vscode-azureappservice#565]
Repro steps:
Tray to create a new deployment slot.
Same error when i expand the "Deplyoment Slots" Node in the tree-view

Action: appService.CreateSlot
Error type: ArgumentError
Error Message: Invalid Object.

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Closing as duplicate of https://github.com/Microsoft/vscode-azureappservice/issues/564
