### ISSUE TITLE
Remote Debugging WebApp Tunnel - 404 Error

### ISSUE THREAD

**Issue by coreyroth** [Microsoft/vscode-azureappservice#571]
Whenever, I try to use remote debugging on any of my azure web apps using node.js (windows), I get the following error that keeps repeating in the output window.

[WebApp Tunnel] Checking status, unexpected response: 404 - Not Found

Looking at my IIS logs, I can see that it is getting a 404 error message accessing the following file:
/AppServiceTunnel/Tunnel.ashx

VS Code is running on Mac OS X.

**Comment by EricJizbaMSFT** [comment]
Remote debugging is currently only supported when running on Linux in Azure. See here for more info: https://github.com/Microsoft/vscode-azureappservice#preview-features

@mrcrane we should be able to detect this situation and throw a better error message. Leaving the issue open to at least address that or potentially even support the Windows scenario.

**Comment by davidlbyrne** [comment]
Very excited about using this feature. This would be a huge victory if we could get support for windows App Services. What needs to be done. Perhaps I could contribute?

**Comment by mrcrane** [comment]
@EricJizbaMSFT There was a bug in the logic that checks to make sure that it is a node app running on Linux. I have submitted a PR to fix that.

At the moment we are relying on the Azure App Service team to create and support Kudu APIs for this extension to create a tunnel for the debugging port. The tunneling APIs only support Linux at the moment, although Windows support should be coming in the future (along with support for other languages). When that is delivered, it should be a trivial change to enable it in the extension here.

At the moment I don't know what their roadmap is or if it is possible to contribute on the App Services/Kudu side of things.
