### ISSUE TITLE
VS Code Crashes when you attempt a web app deployment - Linux

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-azureappservice#578]
When I click deploy to web app from the right click menu or from the icon the app crashes when the file navigator is launched. This happens with Ubuntu 18.04 and Kubuntu 18.04, deb install and through snaps or flatpak - the same results. I am assuming the issue is here and not with VS code.

I am not sure if there are logs I can provide? if so, point me there and I will upload them.

**Comment by EricJizbaMSFT** [comment]
There's a known issue in VS Code that's likely the cause. See here for more information: https://github.com/Microsoft/vscode/issues/52778

**Comment by EricJizbaMSFT** [comment]
We added a workaround for this a while ago (https://github.com/microsoft/vscode-azureappservice/pull/847) and seems like the VS Code bug has been closed at this point.
