### ISSUE TITLE
Add node for cosmos connections

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#582]
Like this (except for just the cosmos node for now):
![image](https://user-images.githubusercontent.com/11282622/44757574-b7ef9f80-aae4-11e8-97e1-0af3b24a4782.png)

Things that still need to be decided:
* The name of the node
* The icon for the node

This needs to be added under a feature flag. See the `appService.enableRemoteDebugging` setting as an example. https://github.com/Microsoft/vscode-azureappservice#preview-features

**Comment by Omelianenko** [comment]
What do you think about "Connected Utilities" or "Linked Services"? At least for the beginning?

**Comment by EricJizbaMSFT** [comment]
Personally I vote for "Connections"
