### ISSUE TITLE
[Suggestion]Add 'Disable File Logging' action on 'Log Files' node

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#595]
Repro Steps:
1. Drill down from one web app -> Log Files.
2. Right click 'Log Files' node and check the context menu.

Actual:
No ''Disable File Logging' display.

Suggestion:
Add 'Disable File Logging' action on 'Log Files' node.

**Comment by EricJizbaMSFT** [comment]
We probably don't need this because it automatically disables after a certain period of time.

Leaving this open for a little bit longer before we make a final decision, though

**Comment by EricJizbaMSFT** [comment]
Closing since it automatically disables logging after a certain period of time
