### ISSUE TITLE
rcrashed

### ISSUE THREAD

**Issue by TechFrozen1** [Microsoft/vscode-azureappservice#599]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.showFile
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:3,$model9) has been disposed

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
Close as dupe of https://github.com/Microsoft/vscode-azureappservice/issues/611
