### ISSUE TITLE
[Suggestion]Display 'Azure App Service: Delete App Setting...' when deleting one app setting using command

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#601]
Repro Steps:
1. F1 ->Type "Azure App Service: Delete..." to delete one app setting.
2. Check the result.

Actual:
Display 'Azure App Service: Delete...'.

Suggestion:
Display 'Azure App Service: Delete App Setting...' when deleting one app setting using command.
![suggestion](https://user-images.githubusercontent.com/34729092/44978431-438c8480-af5a-11e8-8e41-636da2498dd7.PNG)

**Comment by EricJizbaMSFT** [comment]
per @fiveisprime we should just remove "Delete App Setting" from the command palette
