### ISSUE TITLE
Support using extension behind proxy server

### ISSUE THREAD

**Issue by maheshbeeravelli** [Microsoft/vscode-azureappservice#602]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 0.9.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
As of right now we don't support being behind a proxy.

We would have to add support for these properties:
`http.proxy`
`http.proxyStrictSSL`
`http.proxyAuthorization`

**Comment by EricJizbaMSFT** [comment]
Extension support for proxies has been recently added in VS Code insiders. You're welcome to try it out. See here for more info: https://github.com/Microsoft/vscode-azure-account/issues/27#issuecomment-441998815

I'll leave this open for tracking

**Comment by EricJizbaMSFT** [comment]
Closing this as VS Code released proxy support for extensions:
https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions
