### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ivgreene** [Microsoft/vscode-azureappservice#617]
i need to re-enable my acct please

&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.CreateWebApp
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription '9b1133be-6bab-413c-be58-ee00912826d3' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.9.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Please follow the instructions here for how to re-enable your account:
https://docs.microsoft.com/en-us/azure/billing/billing-subscription-become-disable
