### ISSUE TITLE
Simplify App Service scenarios for Java runtime 

### ISSUE THREAD

**Issue by Matthew-Dong** [microsoft/vscode-azureappservice#618]
Suggest to simplify the scenario for creating a new Web App on deployment (blue button): 

1. Search the .target/ folder for .war or .jar. 
- If it’s found, users will fill up the “name”, “location” and choose “runtime” (list re-ordered for Java runtime) to create a new web app. 
- If nothing is found, it will fall back to full configuration to create a web app 
2. Create a web app using the defect parameters + users input. Will leverage the “az webapp up”. The default OS is Linux.
3. Once the web app is created, it will list related .war / .jar under .target/ folder for deployment. Users can browse as well. 
4. Optional to save the deployment config for future deployment 
5. Get the status of deployment in notification windows 
6. Optional to open the website in notification windows

**Comment by jdneo** [comment]
@EricJizbaMSFT @nturinski 

Seems this issue could be closed since we have enabled `Smart-Default` for Java scenario.
