### ISSUE TITLE
Display URL for repo when deployment source is set to LocalGit

### ISSUE THREAD

**Issue by burkeholland** [Microsoft/vscode-azureappservice#619]
When changing the deployment source to LocalGit, there is no way to know what URL to push your code to. Right now you can check the portal, or run the `deployment source configure-local-git` from the CLI which does display the repo URL.

Feature suggestion: Log out the URL for the git repo when the deployment source is changed to LocalGit.

**Comment by EricJizbaMSFT** [comment]
Thanks @burkeholland we can certainly log the url. Just want to make sure you know - deploying through VS Code will automatically check your deployment source and do a "git push" to the correct repo url if you have local git configured.
