### ISSUE TITLE
Wont let me choose to deploy to either windows/linux

### ISSUE THREAD

**Issue by leoporco** [microsoft/vscode-azureappservice#620]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: Unauthorized
Error Message: You tried creating a site in the 'Basic' SKU but your DreamSpark subscription can only create sites in the 'Free' SKU. You can upgrade your subscription to a pay-as-you-go subscription to create sites in any sku.  You can still create free sites with the upgraded subscription

Version: 0.9.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@leoporco as a workaround you can set the `appService.advancedCreation` setting to `true` and you should get prompted for the os

I'll leave this issue open to discuss our defaults, though. We currently default to 'linux' if you're deploying a node.js app, but we might need to reconsider that since linux doesn't support 'free'

**Comment by leoporco** [comment]
> @leoporco as a workaround you can set the `appService.advancedCreation` setting to `true` and you should get prompted for the os
> 
> I'll leave this issue open to discuss our defaults, though. We currently default to 'linux' if you're deploying a node.js app, but we might need to reconsider that since linux doesn't support 'free'

where exactly do I change the appService.advancedCreation?

**Comment by EricJizbaMSFT** [comment]
File -> Preferences -> Settings

![screen shot 2018-09-20 at 3 34 55 pm](https://user-images.githubusercontent.com/11282622/45850394-d6fbde80-bcea-11e8-8b45-718717ba73e3.png)

**Comment by EricJizbaMSFT** [comment]
Closing as we made Advanced creation much more discoverable since this was originally filed. It's no longer a setting - it's a separate command
