### ISSUE TITLE
required to login multiple times and need to typesubscription name multiple times, cache has no info

### ISSUE THREAD

**Issue by spandey01** [Microsoft/vscode-azureappservice#624]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.CreateWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @spandey01,

Have you been able to reproduce this issue?  Are there any steps that you could give me to repro this?  Are you leaving VS Code opened for long periods of time and then coming back?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
