### ISSUE TITLE
Deployment failed with no errors.

### ISSUE THREAD

**Issue by jon64digital** [Microsoft/vscode-azureappservice#625]
Repro steps:
Publish a node API using Azure App Service extension in VS Code.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "xxxxxxx" failed. See output channel for more details.

Version: 0.9.1
OS: win32

Notes:
There is nothing in my OUTPUT tab (not just no errors, nothing at all) when deploying. Previous deployments had succeeded.

**Comment by jon64digital** [comment]
I found the error in the Azure Portal, no idea why my output tab in VS Code was blank.

It wouldn't deploy because one of the file paths in my node_module directory was over 260 characters, but there was no easy way of seeing why it failed.

**Comment by nturinski** [comment]
Closing due to not being able to repro.  If anybody has a consistent repro, please let me know as I'd really want to fix this bug.
