### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by walcloud** [Microsoft/vscode-azureappservice#633]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.fileEditor.onDidSaveTextDocument
Error type: Error
Error Message: ETag does not represent the latest state of the resource.

Version: 0.9.1
OS:

**Comment by nturinski** [comment]
Hi @walcloud,

Sorry that you seem to be having issues with the file editor.  Do you have any repro steps for me to investigate this issue?  Did you happen to edit the file either via remotely or deployment and then try to save the document?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
