### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by spotakash** [Microsoft/vscode-azureappservice#635]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: EPERM
Error Message: EPERM: operation not permitted, open 'c:\Windows\System32\myapp\myExpressApp\.deployment'

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @spotakash,

What deployment method are you using?  Also you may not have write access in your System32 directory.  I'd recommend trying to create your project within your provided user folder: `C:\Users\YOURUSERNAME`.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to reopen with more info
