### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joelNguyenn1010** [Microsoft/vscode-azureappservice#636]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "seminar-uts" failed. See output channel for more details.

Version: 0.9.1
OS: darwin

**Comment by nturinski** [comment]
Hi @joelNguyenn1010,

Sorry that you're having problems deploying.  Could you answer some questions and hopefully we can resolve your issue.

1. What was the output (visible from the Output channel in VS Code) from your failed deployment?
1. Is your app a Windows or Linux OS?
1. What type of project are you deploying?

**Comment by joelNguyenn1010** [comment]
Dear Nathan
1. The error just show “error occur when deploy”.
2. This macos app
3. My app is a nodejs application that run on MacOS

**Comment by nturinski** [comment]
@joelNguyenn1010 Does your project happen to be open-sourced?  If you can direct me to your repo, I might be able to debug your issue.

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
