### ISSUE TITLE
issue with eventlog.xml opening

### ISSUE THREAD

**Issue by TechFrozen1** [Microsoft/vscode-azureappservice#638]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.showFile
Error type: Error
Error Message: Entry not found in cache.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
@TechFrozen1 

Thanks for reporting this issue.  Do you have repro steps for this?  If I drill the `Log Files` node and click the `eventlog.xml`, I seem to be able to view the file.  Has this issue persisted?

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
