### ISSUE TITLE
Improve the local git deployment experience

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#641]
Right now, this is a little too "black box" and causes some confusion. Areas where the extension could be more clear and improve:

* Provide some insight into what branch is being deployed and how 
* Explain that git push is being run when a deployment is happening
* Add the option to create the git remote

There needs to be some discussion and experimentation to get this right.

**Comment by fiveisprime** [comment]
From internal user:

> I didn't test the scenario of checking out another branch before deploying. Maybe this could be configurable as a setting? I'd also like more information about what's going on under the hood -- explicitly outputting what branch (or HEAD) was currently being deployed. Right now it's a bit of a mystery.

**Comment by fiveisprime** [comment]
It deploys whichever branch you have checked out; it's just pushing your local branch to Azure. There's also a new "Deployments" node that will show the history of commits that have been deployed so you can verify this by creating a new branch, committing a wip commit then deploying. The wip commit will show up as active in the deployments node 👌

**Comment by nnja** [comment]
Got it. The deployments node is really nice, especially the option to view deployment logs. 👍
