### ISSUE TITLE
Investigate "Cannot get /" immediately after deploy

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#644]
It can take a few seconds (there's actually a message that claims it's up to 10 seconds) for the container to come up. The extension should either be smart about when the app comes up and show the notification after the app is verified available or just wait ~10 seconds before showing the notification.

**Comment by fiveisprime** [comment]
I've dug into this and it appears that waiting a little longer to launch the site does result in a working site. I'll keep digging to determine a good debounce time.

**Comment by nturinski** [comment]
New issue for the notification has been added #825
