### ISSUE TITLE
add link to open output window on deploy

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-azureappservice#645]
every time i get this message i want to open the output window:

![image](https://user-images.githubusercontent.com/1487073/46909084-c56cb780-cee1-11e8-82f3-38179619e3ec.png)

it would be nice to have a button on this that would open it.  i think other prompts do this...

**Comment by EricJizbaMSFT** [comment]
Filed a bug on VS Code: https://github.com/Microsoft/vscode/issues/60979. We're using `window.withProgress` with `ProgressLocation.Notification` which doesn't support buttons at the moment.

The other prompts you're thinking of were more standard calls to `showInformationMessage` which have no concept of "progress" (but do support buttons).

**Comment by fiveisprime** [comment]
Let's do what the VS Code team did in dev containers

![image](https://user-images.githubusercontent.com/1186948/57709145-66118a00-761f-11e9-96c1-dd68a9919b7e.png)

Could do something like:

> Deploying to [app-name] (details)

**Comment by fiveisprime** [comment]
@nnja
