### ISSUE TITLE
Don't allow to rewrite "MONGO_URL" application setting if already exist

### ISSUE THREAD

**Issue by Omelianenko** [Microsoft/vscode-azureappservice#660]
Now if you add new mongo connection it silently rewrites "MONGO_URL" app setting. I think that some notification like ` "MONGO_URL" application setting is going to be rewritten, are you sure you want to do it?Yes|No` could help here.

**Comment by fiveisprime** [comment]
> This will overwrite your existing MONGO_URL (or COSMOS_ENDPOINT... etc.) Application Setting(s). Are you sure you want to make this connection?

Yes | Cancel
