### ISSUE TITLE
To clean or even to delete application settings after connection deleting

### ISSUE THREAD

**Issue by Omelianenko** [Microsoft/vscode-azureappservice#662]
When you delete the connection, "MONGO_URL" application setting stays the same, so in fact, it's still `connected`.
![image](https://user-images.githubusercontent.com/15349723/47119029-3e3f7c80-d21e-11e8-841e-e2285662b081.png)
![image](https://user-images.githubusercontent.com/15349723/47119074-6038ff00-d21e-11e8-9bf2-f207532ca17d.png)

**Comment by fiveisprime** [comment]
Prompt when removing the connect. Ideally this would include a lot more information, but I think this may get tougher as we add the SQL API.

> Do you want to also remove the Application Setting(s) that were created for this connection?

or

> Do you want to also remove the COSMOS_ENDPOINT, COSMOS_MASTER_KEY and COSMOS_DATABASE_ID Application Settings from [selected web app]?
