### ISSUE TITLE
Executing 'Configure Deployment Source…' pops up an error after selecting 'GitHub' though completing the login on GitHub 

### ISSUE THREAD

**Issue by v-haiz** [microsoft/vscode-azureappservice#672]
**Platform:** Window 10
**Extension version:** 0.9.2-alpha

**Repro Steps:**
1. Complete the login on GitHub. 
2. Create an app service in VS Code -> Right Click it and Select 'Configure Deployment Source...' -> Select the 'GitHub' source.
3. Check the result.

**Expect Result:**
Deployment source has been updated to 'GitHub' successfully.

**Actual Result:**
Pop up an error dialog though completing the login on GitHub.
![actual](https://user-images.githubusercontent.com/37653604/47421636-985ab780-d7b3-11e8-85a0-7cd82db4e9c9.PNG)

**Comment by EricJizbaMSFT** [comment]
The error makes sense to me. The learn more button could be improved. For example, I can't even remember if that takes the user to docs or to the portal to actually configure that.
