### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#677]
New experience for connecting to various deployment mechanisms (especially GitHub and local Git).

**Comment by nturinski** [comment]
Fixed via these PRs: 
https://github.com/Microsoft/vscode-azureappservice/pull/697
https://github.com/Microsoft/vscode-azuretools/pull/314
https://github.com/Microsoft/vscode-azuretools/pull/319
https://github.com/Microsoft/vscode-azuretools/pull/321
