### ISSUE TITLE
An error has occurred while deploying to azure app from vs code

### ISSUE THREAD

**Issue by geosigweb** [Microsoft/vscode-azureappservice#682]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @geosigweb 

Sorry you're having problems deploying. Do you have any more details about this error?

Is this a new web app?
What is the OS and runtime of the web app?
What type of project are you trying to deploy?
Is your project open-sourced? Do you have a GitHub link that I could use to help repro/debug this issue?
Thanks,
Nathan

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
