### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SamuelReis1990** [Microsoft/vscode-azureappservice#683]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: Error
Error Message: An error has occurred.

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @SamuelReis1990, 

Sorry you're having problems deploying.  Do you have any more details about this error?

1. Is this a new web app?
1. What is the OS and runtime of the web app?
1. What type of project are you trying to deploy?
1. Is your project open-sourced?  Do you have a GitHub link that I could use to help repro/debug this issue?

Thanks,
Nathan

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of response. Feel free to re-open with more info
