### ISSUE TITLE
Error Azure Remote Debugging on Node js

### ISSUE THREAD

**Issue by rijdz** [Microsoft/vscode-azureappservice#684]
Repro steps:
* Create webapp service using
`az webapp create --name <app_name> --resource-group <group_name> --plan <plan_name> --deployment-local-git`
* Start remote debugging

Action: appService.StartRemoteDebug
Error type: Error
Error Message: **Azure Remote Debugging is currently only supported for node on Linux.**

Version: 0.9.1
OS: darwin

**Comment by nturinski** [comment]
Hi @rijdz,

What OS and runtime is your web app?  Currently we only support remote debugging on Linux OS and Node runtime.  

If you'd like remote debugging on a different OS/runtime, please post an issue on our repo so others can upvote the feature!

**Comment by rijdz** [comment]
Yeah I think that's the problem.
I'm using Windows OS and Node for this instance.
But my problem already solved anyway. Thanks.

This issue can be closed.
