### ISSUE TITLE
Special characters on resource group names

### ISSUE THREAD

**Issue by lehtomar** [microsoft/vscode-azureappservice#686]
Issue Type: <b>Bug</b>

I have resource group named with character ä in Azure. It is working perfectly on Azure portal but on VScode in get following error:
"Error: "resourceGroupName" should satisfy the constraint  "Pattern":/^[-w._()]+[^.]$/"

Steps:
1. Create resource group with character ä
2. Create webapp in resource group
3. Try to open in Azure App Service Extension

Extension version: 0.9.1
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 11|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by nturinski** [comment]
Thanks for reporting this @lehtomar.  We'll investigate what regular expression the Portal is using to accept these special characters.

**Comment by lailai487** [comment]
me too...
Error Message: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+[^.]$/

Version: 0.14.0

**Comment by wwlorey** [comment]
Related: https://github.com/MicrosoftDocs/feedback/issues/1951

**Comment by alexweininger** [comment]
Any updates on this, where would I find the correct regex for resourceGroupName?
