### ISSUE TITLE
Error when creating web app

### ISSUE THREAD

**Issue by tsitsiflora** [Microsoft/vscode-azureappservice#690]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.CreateWebApp
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443

Version: 0.9.1
OS: linux

**Comment by nturinski** [comment]
Hi @tsitsiflora,

Sorry to hear you can't deploy to your app.  Would you mind giving me some more details to reproduce this issue?

Have you been able to repro?  Sometimes after creating a new web app and trying to deploy immediately, the web app is not available.  Have you tried redeploying?

Thanks,
Nathan

**Comment by tsitsiflora** [comment]
Hi Nathan,

Thank you for reaching out to me. Yes, I managed to deploy the site but I
have some questions.
1. I deployed a Django app and I am not sure which startup file to specify
under application settings because as of now the application is not running.
2. When I click Browse web app it keeps saying service unavailable. Is that
normal?

It'd be awesome if you can help me.

Thanks,

Tsitsi

**Comment by nturinski** [comment]
Hi @tsitsiflora, sorry for the late response!

1. Do you have a __init__.py for your web app?  I am not well-versed with Django, but I think that's where your initialization code should live.
1. As for the `Service unavailable` error, this tends to happen when a web app doesn't build correctly after deployment.  If you look at the logs via the Logs node, you might be able to investigate where in the build process it is failing.

If your project is hosted on an open-source platform, I can take a look at it and try to help debug it.
