### ISSUE TITLE
trying to resolve ico 503 error

### ISSUE THREAD

**Issue by Vonnie** [Microsoft/vscode-azureappservice#702]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: fatal: unable to access : The requested URL returned error: 500

Version: 0.9.1
OS: win32

**Comment by Vonnie** [comment]
having problems using for the first time visual Studio Code git & azure upload.
First upload had an error 503 on my favicon.ico. 
changed to use fire/favicon.ico where it is in the dist.

**Comment by EricJizbaMSFT** [comment]
@Vonnie FYI I deleted the git url from your original issue description. That full url had sensitive information that would've allowed other people to deploy to your app. If you want to be extra careful I recommend deleting that app and creating a new one

**Comment by Vonnie** [comment]
Thanks. I missed that.

I looked for sensitive info in the email about to send. Maybe because I was having difficulty trying to do my deport, I just did not see it. 

I do have another issue with Azure and Github.

Azure deploy with GitHub needs to authorize. To do this, I needed to give them my GitHub password. I reluctantly did.

Made the deploy work with the zip deploy method. Could not find a way to 'un'authorize GitHub in Azure.

Like your thoughts on this. Maybe it is okay the way it is.

Thanks, again.
Vonnie

**Comment by nturinski** [comment]
Hi @Vonnie,

Here are the steps to revoke Azure's GitHub authorization.  This has to be done on GitHub.

1. Go to your GitHub settings.
![image](https://user-images.githubusercontent.com/5290572/48734323-bc6eb480-ec0a-11e8-9836-b44acf6e77a3.png)
1. Go to your Applications.
![image](https://user-images.githubusercontent.com/5290572/48734401-f17b0700-ec0a-11e8-92b8-392bbfed5fd8.png)
1.  Click Authorized OAuth Apps, search for "Azure App Service," and click "Revoke." 
![image](https://user-images.githubusercontent.com/5290572/48734442-0788c780-ec0b-11e8-8de7-9a5138aa17e0.png)

Hope this helps!  Note if you want to Deploy via GitHub in the future, you will have to reauthorize.

**Comment by Vonnie** [comment]
Got it Thanks.

Another question. Is it okay to leave authorize to Azure without concern of security.

When it says with this auth, they have ability to look at and write to any software in my repository.

Or, does it only access the github address I give it.

Thanks for using your time,
Vonnie

**Comment by nturinski** [comment]
Hi @Vonnie,

It seems that Azure does not request write access to your repos:

![image](https://user-images.githubusercontent.com/5290572/49030415-dbba9400-f16c-11e8-9669-30d3417f547a.png)

According to GitHub, access to WebHooks means: `Hooks | Webhooks access allows apps to read or write hook configurations on repositories you manage.` (Source: https://help.github.com/articles/authorizing-oauth-apps/)

I hope that this helps!

**Comment by Vonnie** [comment]
This helps a great deal.

As shown in the link:
"read or write hook configurations on repositories you manage."

Therefore, this webhook of my software, not the software itself.

Thanks from a nervous github security neophyte.....

**Comment by nturinski** [comment]
No problem, @Vonnie, glad to help!  I'll go ahead and close this issue, but please feel free to re-open it if you have any other concerns or questions 😃
