### ISSUE TITLE
Azure Remote Debugging can be started multiple times

### ISSUE THREAD

**Issue by mrcrane** [Microsoft/vscode-azureappservice#707]
It is possible to issue the "Start Remote Debugging" command multiple times, giving an experience that is confusing to the user. Executing the command a second time will start the process of creating a tunnel proxy again, and in some cases it will even create multiple concurrent debugging sessions.

In particular, this may be an issue when establishing the tunnel is taking a long time, and the user is not seeing positive results. In this case we should display an error message if the user tries to start it again, such as 'Azure Remote Debugging is already started.'

**Comment by nturinski** [comment]
Closing as it is resolved by https://github.com/Microsoft/vscode-azureappservice/pull/710.
