### ISSUE TITLE
Add "View commit in Github" to deployment item

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#726]
[Feature request] If I right click on a deployment:
<img width="307" alt="screen shot 2018-11-21 at 1 25 35 pm" src="https://user-images.githubusercontent.com/11282622/48864053-0681a280-ed91-11e8-8585-f72b415fd1cc.png">
I want a command that lets me view that commit in GitHub.

**Comment by nturinski** [comment]
Command is implemented in azuretools, but need to register command in extension.
