### ISSUE TITLE
"Configure Deployment Source" should be on "Deployments" tree item

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#727]
Currently "Configure Deployment Source" lives in the web app tree item:
<img width="342" alt="screen shot 2018-11-21 at 1 31 32 pm" src="https://user-images.githubusercontent.com/11282622/48864330-d4247500-ed91-11e8-86e8-16ca27d4672c.png">

However it feels more natural on the Deployments tree item:
<img width="352" alt="screen shot 2018-11-21 at 1 31 37 pm" src="https://user-images.githubusercontent.com/11282622/48864346-e0103700-ed91-11e8-92e4-35740f026e53.png">

I'm not sure we want to remove it from the web app tree item since some people are used to it there, but I figure we could at least add it to Deployments.

**Comment by fiveisprime** [comment]
Agreed. This seems especially necessary once #753 is implemented.
