### ISSUE TITLE
Add ability to set up CI/CD workflow through VSTS

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-azureappservice#73]
In addition to deployment via zip, we should support setting up a CI/CD pipeline in Azure/VSTS.

**Comment by fiveisprime** [comment]
This should result in an [Azure DevOps Project](https://azure.microsoft.com/en-us/features/devops-projects/).

The portal experience is pretty good already and we currently support this via the "Continuous Delivery" context menu item. Should this effort be more focused on raising awareness of the feature or about setting up the project from within VS Code?

I'm going to walk through setting this up with GitHub and see what I think then..

**Comment by fiveisprime** [comment]
Closing this in favor of #1188
