### ISSUE TITLE
Remove the action 'Connect to Log Stream…' when the log streaming service is already active

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#734]
**Platform / OS Version:**  All
**Node.js** : V8.12.0
**Build Version:** [20181121.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=798&view=logs)

**Repro Steps:**
1. Drill down one web app service -> Logs.
2. Click 'Connect to Log Stream...'.
3. After the log streaming service is active, check whether the action disappears or not.

**Expect Experiment:**
The action 'Connect to Log Stream...' disappears after the log streaming is already active.

**Actual Experiment:**
The action 'Connect to Log Stream...' still shows.
![log](https://user-images.githubusercontent.com/34729022/48930987-e4be2200-ef2e-11e8-80e9-16a509851ee8.png)

**Comment by nturinski** [comment]
Hi @v-xuanzh.  Thanks for reporting this!

This is actually by-design as clicking the `Connect to Log Stream` node again will reveal the logstream and alert users that they are already connected.  But I'll discuss with the team to see if we want to change this behavior.

**Comment by EricJizbaMSFT** [comment]
Closing this as won't-fix. It pops up the log stream and warns the user that they're already connected. To us, that's a good enough experience
