### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by sivrami** [Microsoft/vscode-azureappservice#735]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN

Version: 0.9.1
OS: win32

**Comment by nturinski** [comment]
Hi @sivrami 

Sorry you're having problems deploying. Do you have any more details about this error?

1. Is this a new web app?
1. What is the OS and runtime of the web app?
1. What type of project are you trying to deploy?

Thanks,
Nathan
