### ISSUE TITLE
'Ctrl + S' works well when saving the deployment logs locally

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#741]
**OS:** Win10/ Mac
**Node.js**: V8.12.0
**Build Definition:** [20181128.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=970)

**Repro Steps:**
1. Drill down from one Linux web app -> 'Deployments' node -> Connect to a GitHub repository... .
2. Complete the connection according to the notifications(GitHub organization , project and branch).
3. Click 'View Deployment Logs'.
4. Saving the logs by'Ctrl + Shift + S' and 'Ctrl + S'.

**Expect:**
'Ctrl + S' doesn't work.

**Actual:**
Both 'Ctrl + Shift + S' and 'Ctrl + S' work well.
![image](https://user-images.githubusercontent.com/34729092/49207053-dc625d00-f3ee-11e8-9613-7822a1a37632.png)

**Comment by nturinski** [comment]
Hi @v-dantch,

Why do you expect that `Ctrl + S` wouldn't work?  I think we just want to prevent the user from editing their logs, but they should be able to save them locally if they want.  

Of course, I may not have taken something into consideration so please let me know if there is a concern about being able to save the Deployment Logs!

**Comment by v-dantch** [comment]
Hi @nturinski , I am very agree with you that we just want to prevent the users from editing their logs and they can save them locally.
What I mean:
'Ctr + S ' saves the logs directly in current editor.
'Ctrl + Shift + S' saves the logs locally.

Oops, I know where my fault. I ignore the logs are opened in a Untitled text.

Sorry for filing what a bad issue. Could you help to close this bug?

**Comment by nturinski** [comment]
No problem!  Thanks for your diligence in testing 😃
