### ISSUE TITLE
Configure deployment source when creating new slots

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#742]
When I create a new slot, I'm prompted to deploy and it's defaulting to package deploy even though my production slot is using GitHub. I have to say no to the deploy then choose to configure the deployment source to use a different branch on GitHub.

This should prompt me either with **all options** or **based on my production configuration**. For example, since my app is connected to GitHub, I expected to be prompted to choose a branch on my already configured repository. Maybe this should consider the decision to copy configuration.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azureappservice/pull/1027
