### ISSUE TITLE
getting error in text editor

### ISSUE THREAD

**Issue by savakar123** [Microsoft/vscode-azureappservice#746]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.showFile
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model17) has been disposed

Version: 0.9.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
Closing as this was fixed in 0.10.0
