### ISSUE TITLE
Prompting to select one web app to deploy when there is no opened folder even though 'appService.defaultWebAppToDeploy' has been set

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#748]
**OS**: All
**Node.js:** V10.13.0
**Build Definition**: [20181129.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1106)

**Repro Steps:**
1. Set 'appService.defaultWebAppToDeploy' with one valid full Azure web app id like below:
Azure id:
/subscriptions/92be7e56-8a60-427c-a3e3-0ebd54a827a1/resourceGroups/megantest/providers/Microsoft.Web/sites/window-1129
2. F1 ->Type and select 'Azure App Service: Deploy to Web App...'.
3. Check the result.

**Expect:**
Deploy to the default web app without asking to select.

**Actual:**
Prompt to select to one web app.
![image](https://user-images.githubusercontent.com/34729092/49278212-1733c600-f4bf-11e8-92c1-c7654c254b98.png)

**More Info:**
This issue doesn't reproduce when there is a opened folder.

**Comment by EricJizbaMSFT** [comment]
Not sure what @nturinski means - "defaultWebAppToDeploy" should apply whether or not there's zero or more than 1 workspaces

**Comment by nturinski** [comment]
@EricJizbaMSFT the setting is workspace specific, not on the user level.  It was specifically designed to work only when one workspace is opened because each workspace will have its own web app to deploy to.  We can change this behavior, but this isn't a bug.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.

**Comment by EricJizbaMSFT** [comment]
We would need to handle the "Reset Default" button when deploying
