### ISSUE TITLE
Deployments node should show deployments even if configured to "None"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#751]
None of these were done via Local Git, but they still show up after I switch to Local Git:
![screen shot 2018-11-30 at 11 32 45 am](https://user-images.githubusercontent.com/11282622/49310677-c8246b80-f493-11e8-88b1-af201d7364c5.png)

Which means we should be able to show deployments even if it's set to "None". "Redeploy" might not be super helpful since the message for each deployment is the same, but users can still at least view the logs

**Comment by EricJizbaMSFT** [comment]
Actually redeploy doesn't even work for zip deploys according to @nturinski, but I still think the logs are helpful

**Comment by nturinski** [comment]
You get an error that says `Repository could not be found` when you try to redeploy a zip deploy.  Is it worth changing that error message to something more descriptive? (It does make sense now that I know the context of it)

**Comment by nturinski** [comment]
Fixed by https://github.com/Microsoft/vscode-azuretools/pull/363
