### ISSUE TITLE
Deployments node should indicate current deployment source

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#753]
Open for discussion on _what_ we display, but here's my thoughts:

- None: `Deployments`
- Local git: `Deployments (Local Git)`
- Github: `Deployments (EricJizbaMSFT\node-todo)`

**Comment by fiveisprime** [comment]
I think "local git" may be confusing and "git" is common enough that it shouldn't be confusing. For "none" I think it should be scoped to the user's current perspective (e.g. they a directory open in a workspace) so either "directory" or "workspace." I want to be consistent in our terminology with VS Code.

* Node: `Deployments (Workspace)`
* Local Git: `Deployments (Git)`
* GitHub `Deployments (username/repo)`

**Comment by nturinski** [comment]
I was thinking it might be best to stick with the same terminology as the Portal?

![image](https://user-images.githubusercontent.com/5290572/54321084-bda66180-45ac-11e9-847a-6a0e55565e1b.png)
