### ISSUE TITLE
Creating a new Cosmos DB discontinues the processing of adding a new connection

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#758]
**OS**: All
**Node.js:** V10.13.0
**Build Definition**: [20181129.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1106)

**Repro Steps:**
1. Drill down a web app -> 'Connection' node.
2. Right click 'Cosmos DB' and select 'Add New Connection...'.
3. According to the notification, select a subscription-> Create a new Cosmos DB account.

**Expect:**
Prompt for account and databases before creating either.

**Actual:**
The processing discontinues and won't prompt to create a new database.

**Comment by nturinski** [comment]
Fixed with https://github.com/Microsoft/vscode-cosmosdb/pull/550
