### ISSUE TITLE
Error deploying nodejs api

### ISSUE THREAD

**Issue by sgentry** [Microsoft/vscode-azureappservice#759]
Repro steps:
I receive the following error when I attempt to deploy my nodejs api to our Windows app service plan.

Action: appService.Deploy
Error type: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
Error Message: unable to get local issuer certificate

Version: 0.10.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@sgentry are you behind a proxy? Can you try the latest version of VS Code insiders: https://code.visualstudio.com/insiders

They recently added a setting (`http.systemProxy`) which defaults to `force` and may fix your issue. See https://github.com/Microsoft/vscode-azure-account/issues/27 for more info.

**Comment by sgentry** [comment]
I'm not running through our proxy server to access Azure. I did try the insiders build and receive the same error. When I first tested this out 5 or 6 months ago, it worked great. Haven't used it since then and not sure what has changed.

**Comment by sgentry** [comment]
I'm starting to think I have an issue with single sign on. If I try doing a zip deploy from the Azure Portal, I get basic auth prompt even though I'm already logged into the portal. So probably not an issue with VS Code extension...

For example, I get an auth prompt hitting this: https://<my-app>.scm.azurewebsites.net/ZipDeployUI

**Comment by EricJizbaMSFT** [comment]
@sgentry let us know if you figure anything else out on this and please close if you discover it wasn't a problem with VS Code.

I'll leave this open for now since we're actively tracking the work on VS Code's side to support more proxy/cert stuff (as mentioned earlier)

**Comment by fiveisprime** [comment]
Got another report of this from the tutorial. They didn't leave an email so I'm not able to ask for more detail. :(

**Comment by EricJizbaMSFT** [comment]
Gonna close - sounds like it might be a problem with the web app instead of our extension and if it's a proxy problem, I'd recommend taking a closer look at VS Code's [proxy support](https://code.visualstudio.com/updates/v1_31#_network-proxy-support-for-extensions) and following up with VS Code directly.
