### ISSUE TITLE
Issue when restarting from azure extension in VS Code

### ISSUE THREAD

**Issue by capttaz1** [Microsoft/vscode-azureappservice#762]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Stop
Error type: Error
Error Message: Error: Unknown command 'getDebugAdapterMetadata'.

Version: 0.10.0
OS: darwin

**Comment by EricJizbaMSFT** [comment]
Closing due to lack of info. This was likely fixed as a part of #543
