### ISSUE TITLE
Duplicate web app names

### ISSUE THREAD

**Issue by mike-westaway** [Microsoft/vscode-azureappservice#768]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: ResourceNotFound
Error Message: The Resource 'Microsoft.Web/sites/gskwebappdemo' under resource group 'appsvc_rg_Linux_CentralUS' was not found.

Version: 0.10.0
OS: win32

I had a web app called webappdemo which I deleted and then created a new web app with the same name. VSC presented both in the drop down list. Selecting the first failed (because the web app was deleted). Selecting the first failed because it took the details from the wrong web app (again the deleted one).

**Comment by nturinski** [comment]
Hi @mike-westaway,

Thanks for reporting this issue.  Do you happen to know if the app had finished deleting before you had created a new web app with the same name?  

Is this error reproducible?  I haven't had any luck reproing it on my end.  

Does this error persist, or does a refresh get rid of the duplicate web app names?

**Comment by mike-westaway** [comment]
Hey Nathan,

I’ve just changed laptop so new VSC, etc

I’ll try and recreate the example and let you know
Might take a few days to get to it..

Regards,
  Mike

**Comment by nturinski** [comment]
@mike-westaway Hi there, just wanted to follow up and see if there was any update on this?
