### ISSUE TITLE
Validation of remote debugging feature for Node.js 10.1.0

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-azureappservice#774]
This issue tracks the validation of remote debugging feature for Node.js 10.1.0.

Scenarios:
- [x] Node app without any npm scripts - https://github.com/clarkio/simple-node-server
- [x] Node app with `NPM start` script - https://github.com/clarkio/simple-node-server
- ?

**Comment by fiveisprime** [comment]
I'm ready to sign off on this and get it shipped to the other images. @mrcrane & @dhanvikapila what are the next steps?

**Comment by mrcrane** [comment]
This is signed off and rolled out to all Node.js images with version >= 8.11
