### ISSUE TITLE
Operation Cancelled error when pressing Esc to cancel creating new web app

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#775]
Right click on App Service subscription to create a new Web App
Press ESC to cancel creating the site

Result:

![image](https://user-images.githubusercontent.com/1487073/49756021-58219c80-fc6e-11e8-8cfa-69309a638d80.png)

Not sure we need to have an error message when I press ESC.

**Comment by fiveisprime** [comment]
This is working correctly in stable.
