### ISSUE TITLE
Taking defaults for Create New Web App results in error

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#776]
Right click in App Service explorer on a subscription, choose "Create New Web App"

- provide a unique name
- take the defaults ...
  - Create new resource group
  - Linux
  - Node.js 10.10 (LTS ...)
  - Create new app service plan
  - Location: select Central US

Result:

![image](https://user-images.githubusercontent.com/1487073/49756345-c6665f00-fc6e-11e8-9b4e-a3ffd69415c1.png)

**Comment by fiveisprime** [comment]
I can repro this, there are no prompts for naming the plan or resource group.

**Comment by EricJizbaMSFT** [comment]
Are you guys testing on master, released, or webpacked? The webpacked extension has not even been put up for PR yet...

**Comment by fiveisprime** [comment]
Nope, on 0.10.0 from the marketplace. I made Chris uninstall and reinstall from prod

**Comment by EricJizbaMSFT** [comment]
I can't repro this and these errors are not common at all in telemetry. "uninstall and reinstall" doesn't usually do anything if the versions are the same. You have to actually go here and delete the extension folder before reinstalling:

- Windows %USERPROFILE%\.vscode\extensions
- macOS ~/.vscode/extensions
- Linux ~/.vscode/extensions

**Comment by fiveisprime** [comment]
Damn, I thought that was only an issue when moving ahead.. works for me, I'll update Chris'

**Comment by fiveisprime** [comment]
Confirmed working correctly in stable.

**Comment by EricJizbaMSFT** [comment]
Good to know, thanks. I do want to track these issues, but maybe just in OneNote or on GitHub with a "webpack" label until it makes it into master

**Comment by StephenWeatherford** [comment]
I've created this: https://microsoft.sharepoint.com/teams/azcode/_layouts/OneNote.aspx?id=%2Fteams%2Fazcode%2FSiteAssets%2Fazcode%20Notebook&wd=target%28Development.one%7CB171B793-3162-4BAC-8605-42D58625B875%2FWebpack%20Issues%7C56A53AF6-0EF2-4C69-8E42-721756C94D86%2F%29
onenote:https://microsoft.sharepoint.com/teams/azcode/SiteAssets/azcode%20Notebook/Development.one#Webpack%20Issues&section-id={B171B793-3162-4BAC-8605-42D58625B875}&page-id={56A53AF6-0EF2-4C69-8E42-721756C94D86}&end

I'll move my current issues there, too.
