### ISSUE TITLE
Support additional production plans

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#777]
Need to add support for P1V2, P2V2, and P3V2 in advanced mode.

![image](https://user-images.githubusercontent.com/1186948/49757963-84d7b300-fc72-11e8-95e9-2874b908d050.png)

**Comment by EricJizbaMSFT** [comment]
Hopefully we can do this dynamically instead of our hard-coded list

**Comment by EricJizbaMSFT** [comment]
Related issue: https://github.com/Microsoft/vscode-azureappservice/issues/54
