### ISSUE TITLE
Show the service's state

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-azureappservice#78]
We allow stopping, starting, etc. But we can't tell if the service is running or stopped right now. Add a state indicator.

![image](https://user-images.githubusercontent.com/1202528/30774859-4cbc819e-a057-11e7-9bcf-829527cb4b66.png)

**Comment by whiskeyjay** [comment]
Waiting on https://github.com/Microsoft/vscode/issues/34789 so I can properly refresh the state text upon start/stop command
