### ISSUE TITLE
Template for filing an issue on error from vs code includes junk characters on GitHub issue creation page

### ISSUE THREAD

**Issue by nnja** [Microsoft/vscode-azureappservice#782]
I got an error while using the app service extension. I clicked on the pop up that came up to open an issue. The page opened pre-filled in with the exact content below, including codes for less than (`&lt;`) and greater than (`&gt;`) which don't render well in the GitHub issue creation page and might make the editing process confusing for less technically savvy reporters.

```
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Delete
Error type: 429
Error Message: Cannot acquire exclusive lock to create, update or delete this site. Retry the request later.

Version: 0.10.0
OS: darwin
```

**Comment by nturinski** [comment]
@nnja Thanks for reporting this issue!

We had to add the codes for < and > since markdown will hide the symbols if they are between text (I guess because it's assuming it's an HTML tag?).  Do you think using \\< and \\> would be less confusing for reporters?

**Comment by nnja** [comment]
Are symbols necessary at all? Would it be possible to call attention to the sections that need to be filled in with plain text? Something like:

```
IMPORTANT!: Please be sure to remove any private information before submitting.
TODO: Enter steps to reproduce the issue
```
