### ISSUE TITLE
Unable to view files

### ISSUE THREAD

**Issue by marvoh** [Microsoft/vscode-azureappservice#784]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND caawiyeprodclient.scm.azurewebsites.net caawiyeprodclient.scm.azurewebsites.net:443

Version: 0.10.0
OS: win32

**Comment by nturinski** [comment]
@marvoh thanks for reporting this issue.  

This seems to be a deployment error, but your issue is titled unable to view the files. Could you clarify this? 

But in regards to the deployment failing, has this problem been reproducible?  Was this a new web app?
