### ISSUE TITLE
Pop up an error when creating a new web app without setting 'appService.advancedCreation' as true

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#786]
**Account**: Mooncake and Azure Germany
**OS:** Windows
**Build Version**:[20181216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1599)

**Repro Steps:**
1. Sign in with Mooncake/Azure Germany account.
2. Make sure 'appService.advancedCreation' is false.
3. F1 -> Type and select 'Azure App Service: Create New Web App...' -> Select one subscription -> Enter one valid name ->Select a location -> Select an OS.
4. Check the result.

**Expect:**
No error pops up.

**Actual:**
Pop up an error like below.
![image](https://user-images.githubusercontent.com/34729092/50080496-2ccb1e80-0227-11e9-8ac7-745146fe749f.png)

**More Info:**
1. This issue does not reproduce for Azure account.
2. This issue does not reproduce when selecting any one existing Resource Group with setting 'appService.advancedCreation' as true.

**Comment by nturinski** [comment]
https://github.com/Azure/azure-sdk-for-js/issues/1811
