### ISSUE TITLE
Failed to create app

### ISSUE THREAD

**Issue by occultknight** [Microsoft/vscode-azureappservice#787]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: Error
Error Message: "resourceGroupName" should satisfy the constraint - "Pattern": /^[-w._()]+$/

Version: 0.10.0
OS: darwin

**Comment by nturinski** [comment]
Hi @occultknight,

Sorry that you couldn't create your web app.  It seems like your resourceGroup has some special characters that we do not currently support.  Were you able to create an app and deploy to it?
