### ISSUE TITLE
Show the functions

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-azureappservice#79]
Show the name of the functions in the function app. we cant see them now,

![image](https://user-images.githubusercontent.com/1202528/30774868-68f8e06e-a057-11e7-86c1-a733903cbdac.png)

**Comment by whiskeyjay** [comment]
@johnpapa We have another extension coming explicitly for functions. The coming release of App Service extension will not show function apps at all. But thanks for the feedback, this will definitely help us on designing the function apps extension!
