### ISSUE TITLE
cannot connect deployments to private repos?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azureappservice#790]
I've got a private repo that i want to use as a deployment source for app service.  when browsing my repositories i can only see my public repos.  

Create a new web app
expand deployments node
choose "Connect to a GitHub repository..."
choose my personal account

result: only public repos are shown

**Comment by nturinski** [comment]
@chrisdias, it seems like Azure doesn't have authorization for private repos.  @fiveisprime mentioned that his access permissions were like that when he did this process a long time ago.  If you go to GitHub, deauthorize Azure from GitHub, and then reauthorize in the process, this may fix your problem.
