### ISSUE TITLE
Alert when creating in an app in a (B1) plan that already has three apps

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#795]
Perf starts to degrade when adding the fourth app to a plan. We can help in the following ways

1. Show the number of apps in a plan in the plan selection prompt
1. Warn when creating in a plan that already has three apps (for basic mode in B1 plans)

"The selected plan currently has _n_ apps. Deploying additional apps may degrade the performance on the apps in the plan. Are you sure you want to deploy to _plan_?"

**Comment by nturinski** [comment]
@fiveisprime 

Discussed this with @StephenWeatherford offline. What if we just created a new RG for each app in Basic creation?  So if I'm create naturins-app-01, it just creates a rg and asp with the same name.  I think when you're trying to go back and delete resources, it can be confusing to have a bunch of apps in one rg.

**Comment by StephenWeatherford** [comment]
Does basic creation use consumption or service plans?  If think you want to reduce usage of service plans, 'cause each is tied to a VM instance, right?  That doesn't preclude the fact that app services could be created in new RGs I don't think.
