### ISSUE TITLE
Add ability to mark an app setting as a "slot setting" for a slot

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#796]
Allow user to make an app setting in a deployment slot as a "slot setting" so that it stays with the slot. I need to think through the experience on this one.. maybe when creating an app setting for a slot, prompt to persist the setting to a particular slot?

The use case is a production slot with a `MONGO_URL` that points to the production db; staging slot has a `MONGO_URL` setting that points to the staging database. These settings need to be slot settings that stay associated with the slot when swapped.

**Comment by nturinski** [comment]
Included with the following PR #854
