### ISSUE TITLE
Improve deployment slot UI for basic SKU

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-azureappservice#804]
Leave the monotone icon, remove the "N/A for Basic..", and add a way to scale up the plan under the node for basic.

Similar to how deployments work, have a "Scale up to a production plan to use slots..." or something similar. Probably just link them into the scale up blade in the portal since it has all of the pricing and feature information. I don't think the extension can show all of that cleanly.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime we already have a scale up thing that links to the portal:
![screen shot 2019-01-08 at 9 32 35 am](https://user-images.githubusercontent.com/11282622/50848174-5956ef80-1328-11e9-95a7-53ddae452b83.png)

Do you just want the wording changed?
