### ISSUE TITLE
DPanchal

### ISSUE THREAD

**Issue by panchaldineshb** [Microsoft/vscode-azureappservice#805]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: 404
Error Message: An error has occurred.

Version: 0.10.0
OS: win32

**Comment by nturinski** [comment]
Closing as dupe https://github.com/Microsoft/vscode-azureappservice/issues/815
