### ISSUE TITLE
Disabling remote debugging through the context menu doesn't disconnect the debugger

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#811]
If I right-click "Disable Remote Debugging" while I'm debugging, I'm prompted to disable and restart the app. 

Expected: Disabling and confirming the prompt should also disconnect the debugger.

Actual: the debugger stays connected (even though it's not connected to anything)

//cc @mrcrane

**Comment by nturinski** [comment]
Related https://github.com/Microsoft/vscode-azureappservice/issues/889
