### ISSUE TITLE
Certification Error while trying to deploy

### ISSUE THREAD

**Issue by DrakeAnglin** [Microsoft/vscode-azureappservice#813]
Repro steps:
Trying to deploy to azure normally.

Action: appService.Deploy
Error type: UNABLE_TO_VERIFY_LEAF_SIGNATURE
Error Message: unable to verify the first certificate

Version: 0.10.0
OS: win32

**Comment by nturinski** [comment]
Hi @DrakeAnglin 

If you have the proper certificates, our extension may not support proxies.  Are you behind a corporate proxy?

This post might be relevant to your error: https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature
