### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by panchaldineshb** [Microsoft/vscode-azureappservice#815]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: 404
Error Message: An error has occurred.

Version: 0.10.0
OS: win32

**Comment by nturinski** [comment]
Hi @panchaldineshb,

Thanks for reporting this issue.  In order to assist you, I need a little bit more information:

1. What type of web app are you deploying to?
1. What is the runtime of your web app?
1. What type of project are you deploying?
