### ISSUE TITLE
The selected connection can be deleted successfully when the same connection has been deleted by others

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#817]
**OS:** All
**Node.js:** V10.14.0
**Build Version:** [20190112.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2047)

**Repro Steps:**

1. Make sure both the Cosmos DB and App Service extensions are installed -> Open two instances.

1. Drill down one web app -> Click 'Add one Cosmos DB Connection…'.

1. Select one subscription -> Account -> Database -> Enter a connection setting prefix -> 'Enter'.

1. Right click the added connection -> Select 'Remove Connection…' -> don't close the popped confirmation dialog.

1. Open the second instance -> Right click the same connection -> 'Remove Connection…' -> Click 'Delete' -> Back to the first instance -> Click 'Delete'

**Expect**:
An error occurs like 'The connection did not already exist'.

**Actual**:
The connection can be deleted successfully.

**Comment by nturinski** [comment]
Thanks for reporting this, but this seems like an unlikely user scenario.  In the event that a user does do this, this is harmless as the app settings get updated successfully either way.
