### ISSUE TITLE
[Suggestion]Replace 'Hidden Value' with '***' after trying to hid the setting value

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#818]
**OS:** All
**Node.js:** V10.14.0
**Build Version:** [20190112.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2047)

**Repro Steps:**
1. Drill down from one web app -> 'Application Settings' -> Add a new setting for it.
2. Make sure the current value is hidden -> Check the prompt text in the value of the location.

**Expect**:
The prompt text shows '***' in the value of the location.

**Actual**:
The prompt text shows 'Hidden Value'.

**Comment by nturinski** [comment]
Hi @v-xuanzh,

We are using 'Hidden Value' to stay consistent with how the portal displays app settings.  Thank you for your suggestion though!
