### ISSUE TITLE
SSL3_GET_RECORD:wrong version number:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:365:

### ISSUE THREAD

**Issue by tmoganedi86** [Microsoft/vscode-azureappservice#819]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: EPROTO
Error Message: write EPROTO 101057795:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:365:

Version: 0.10.0
OS: win32

**Comment by jsparks19** [comment]
Just realized this issue was reported under vscode-azureappservice - sorry for that oversight. I'm not using vscode-azureappservice so it seems like maybe this is a Node issue. I get this error when trying to make a REST call using Axios.
