### ISSUE TITLE
Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#822]
Repro steps:
1. Right click on the space below the list of files (aka below "test.zip" in the screenshot) and select "Deploy to Web App"

![screen shot 2019-01-16 at 3 41 12 pm](https://user-images.githubusercontent.com/11282622/51285843-3d48f300-19a5-11e9-9718-e8656d8c8144.png)

Action: appService.Deploy
Error type: TypeError
Error Message: Cannot read property 'client' of undefined

Version: 0.11.0
OS: darwin

**Comment by nturinski** [comment]
That's odd, isn't it supposed to deploy the root folder when you do that?

**Comment by EricJizbaMSFT** [comment]
Yes

**Comment by EricJizbaMSFT** [comment]
So this one only repros for me on insiders. Might be a VS Code bug.

**Comment by nturinski** [comment]
Yep, happens to me too, even with App Service v0.10.0 on the new Insiders.

**Comment by chrisdias** [comment]
Perhaps related: https://github.com/Microsoft/vscode/issues/66938

**Comment by EricJizbaMSFT** [comment]
Filed this issue on VS Code, which is the root cause: https://github.com/Microsoft/vscode/issues/66942

**Comment by EricJizbaMSFT** [comment]
Verified this has been fixed on latest insiders
