### ISSUE TITLE
App service deploy does not clear the previous deployment on the app service on azure.

### ISSUE THREAD

**Issue by cray2015** [Microsoft/vscode-azureappservice#826]
**Current behavior:** hi all I'm trying to deploy an angular app via the "Deploy to Web App" feature. it deploys the app however it does not clears the existing files/folders on the webapp.

**Excepted behavior:** The feature should clear the contents of the webapp before deploying the new files/folders.

**Comment by nturinski** [comment]
Hi @cray2015,

Could I ask how are you deploying your angular app?  Have you changed the deployment source?  Also, how are you checking to see the contents of the webapp have been cleared?

Thanks,
Nathan
