### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by shaktim9006143** [Microsoft/vscode-azureappservice#831]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND app2343.scm.azurewebsites.net app2343.scm.azurewebsites.net:443

Version: 0.11.0
OS: win32

**Comment by nturinski** [comment]
Hi @shaktim9006143,

Is this problem recurring?  Are you deploying a node project?  If so, this might be helpful: https://stackoverflow.com/questions/17690803/node-js-getaddrinfo-enotfound
