### ISSUE TITLE
Issure on Azure Web App

### ISSUE THREAD

**Issue by jpmtamorosp** [Microsoft/vscode-azureappservice#832]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.11.0
OS: win32

**Comment by nturinski** [comment]
Hi @jpmtamorosp,

Does this consistently repro?  If you try again later, does the deployment succeed?

**Comment by jpmtamorosp** [comment]
Thanks!
