### ISSUE TITLE
Combine notifications after creating web app (or slot)

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azureappservice#839]
Today I get two notifications after creating a web app:
![screen shot 2019-01-28 at 10 14 27 am](https://user-images.githubusercontent.com/11282622/51857052-1ca66480-22e6-11e9-9da0-cd7d05ed92a9.png)

I say we add a "Deploy" button to the bottom notification and just remove the top notification.

**Comment by nturinski** [comment]
This issue https://github.com/Microsoft/vscode-azureappservice/issues/899 kind of makes this irrelevant.
