### ISSUE TITLE
Already registered node

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#841]
I know we've seen this error before
``` Element with id /subscriptions/9b5c7ccb-9857-4307-843b-8875e83f65e9/resourceGroups/appsvc_rg_linux_centralus/providers/Microsoft.Web/sites/asdfasrewfsd-basic/Logs/Connect to Log Stream... is already registered ```

I think I might have repro steps:
1. Expand a node (I used File and Log Files)
1. Restart the app with the context menu

**Comment by EricJizbaMSFT** [comment]
Filed a bug on VS Code: https://github.com/Microsoft/vscode/issues/71698

**Comment by EricJizbaMSFT** [comment]
Closing since the VS Code bug was resolved and I can't repro on latest insiders
