### ISSUE TITLE
Getting this error when trying to deploy app

### ISSUE THREAD

**Issue by prashant214** [Microsoft/vscode-azureappservice#849]
Repro steps:
I am trying to deploy app on azure  using VS code  but getting below error.

Action: appService.Deploy
Error type: SELF_SIGNED_CERT_IN_CHAIN
Error Message: self signed certificate in certificate chain

Version: 0.11.0
OS: win32

**Comment by nturinski** [comment]
Hi @prashant214,

Are you on a network that is using a proxy?  That might be the cause of this error.

There is a similar issue in the Azure Functions repo here: https://github.com/Microsoft/vscode-azurefunctions/issues/493.  There is a link to an issue in the vscode repo that may help.
