### ISSUE TITLE
I can't control anything

### ISSUE THREAD

**Issue by JinHuaChun** [Microsoft/vscode-azureappservice#852]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.fileEditor.onDidSaveTextDocument
Error type: 409
Error Message: Could not write to local resource 'D:\home\site\wwwroot\_core\config.js' due to error 'The process cannot access the file 'D:\home\site\wwwroot\_core\config.js' because it is being used by another process.'.

Version: 0.12.0
OS: win32

**Comment by nturinski** [comment]
@JinHuaChun, sorry you're having this issue.

Could you please elaborate what you mean by this?  Also, do you know how to reproduce this error?

Thanks,
Nathan
