### ISSUE TITLE
After VS Code update I am unable to connect / sign in to Azure App Service Extension

### ISSUE THREAD

**Issue by mtawara** [Microsoft/vscode-azureappservice#856]
Visual Studio Code automatically updated, and now all of a sudden I am unable to sign in to Azure. The response I get when trying to run Azure: Sign-in is "You appear to be offline. Please check your network connection." 

I already have my proxies set up. It was working before Code updated. What can I do?

**Comment by nturinski** [comment]
Hi @mtawara,

I'm really sorry to hear that you're being blocked like this.  Unfortunately, our extensions leverage the vscode-azure-account extension to handle all authentication so I'm not sure what we can do on our end.

I recommend filing an issue here: https://github.com/Microsoft/vscode-azure-account.  I hope you get your environment up and running again soon!

**Comment by nturinski** [comment]
Closing as external.  Please follow up in the https://github.com/Microsoft/vscode-azure-account repo.
