### ISSUE TITLE
Error WHen Publishing

### ISSUE THREAD

**Issue by gbracey** [Microsoft/vscode-azureappservice#859]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
When picking the app in the App Service to deploy to, error happens.

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.12.0
OS: win32

**Comment by nturinski** [comment]
Hi @gbracey,

Your error seems very similar to this one: https://github.com/Microsoft/vscode-azureappservice/issues/430.

Please have a look at this thread.

Thanks!

**Comment by nturinski** [comment]
Closing as a duplicate
