### ISSUE TITLE
Publish Failed

### ISSUE THREAD

**Issue by gbracey** [Microsoft/vscode-azureappservice#860]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
Publish to app service using extension in VS Code.

Action: appService.Deploy
Error type: SELF_SIGNED_CERT_IN_CHAIN
Error Message: self signed certificate in certificate chain

Version: 0.12.0
OS: win32

**Comment by nturinski** [comment]
Hi @gbracey 

Are you on a network that is using a proxy? That might be the cause of this error.

There is a similar issue in the Azure Functions repo here: [Microsoft/vscode-azurefunctions#493](https://github.com/Microsoft/vscode-azurefunctions/issues/493). There is a link to an issue in the vscode repo that may help.
