### ISSUE TITLE
primer-problema

### ISSUE THREAD

**Issue by fraediaz** [Microsoft/vscode-azureappservice#864]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription '5afae49e-6c9e-4f4c-846d-5592131be47a' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.12.0
OS: win32

**Comment by nturinski** [comment]
Hi @fraediaz,

It looks like your subscription might be disabled.  You will have to log in with a different subscription or renew your subscription in order to deploy to your web app.

**Comment by nturinski** [comment]
This should aid you in renewing your subscription: https://docs.microsoft.com/en-us/azure/billing/billing-subscription-become-disable
