### ISSUE TITLE
deploy local git to Azure app service fail from Visual studio code

### ISSUE THREAD

**Issue by orangeboyincdev** [Microsoft/vscode-azureappservice#865]
Repro steps:
Python Flask App
App Service in Linux

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "SmartyDev01" failed. See output channel for more details.

Version: 0.12.0
OS: win32

**Comment by nturinski** [comment]
Hi @orangeboyincdev,

Sorry that your deployment failed.  Could you copy the details from the output channel for me?  This will be helpful for debugging your issue.

Thanks!
