### ISSUE TITLE
error on deploy

### ISSUE THREAD

**Issue by otvoiski** [Microsoft/vscode-azureappservice#868]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@otvoiski can you give more info:
1. Does this happen consistently?
1. Are you on normal Azure or a sovereign account like Azure Government, Azure China, Azure Germany, etc.?
1. Was this a brand new app or an existing app?
