### ISSUE TITLE
Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by LionelSlade** [Microsoft/vscode-azureappservice#870]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.CreateSlot
Error type: TypeError
Error Message: Cannot read property 'localeCompare' of undefined

Version: 0.12.0
OS: win32

**Comment by EricJizbaMSFT** [comment]
@LionelSlade can you give more information on this:
1. Did the error happen before the slot was created or after (aka if you refreshed the tree, was the new slot there)?
1. Do all your other slots show up normally in the tree?
1. Does this happen consistently?
