### ISSUE TITLE
.NET Core 2.2 isn't an option in Advanced Dropdown but it IS in the Portal

### ISSUE THREAD

**Issue by shanselman** [Microsoft/vscode-azureappservice#872]
.NET Core 2.2 isn't an option in Advanced Dropdown but it IS in the Portal. Isn't the extension supposed to get populated from the Portal?

It seems to be hardcoded here https://github.com/Microsoft/vscode-azuretools/blob/a76e8a8320003885cc1009ba02ae1c73e0ebc31f/appservice/src/createAppService/SiteRuntimeStep.ts but this gentleman implied it was dynamic https://github.com/Microsoft/vscode-azureappservice/issues/540#issuecomment-407219707

If it's in fact, static, then this PR fixes it. https://github.com/Microsoft/vscode-azuretools/pull/425

![image](https://user-images.githubusercontent.com/2892/53221039-63088e00-361c-11e9-8922-a900aeff8d9d.png)

![image](https://user-images.githubusercontent.com/2892/53221032-5b48e980-361c-11e9-8811-2109dcb4bd6e.png)

**Comment by EricJizbaMSFT** [comment]
Yeah currently hard-coded. We have an open issue to pull this list dynamically 
https://github.com/Microsoft/vscode-azureappservice/issues/724
