### ISSUE TITLE
getting an error when deploying to Azure from VSCode

### ISSUE THREAD

**Issue by sanjutvj** [Microsoft/vscode-azureappservice#873]
Repro steps:
<Enter steps to reproduce issue>

Action: appService.Deploy
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND outreach-report-v1.scm.azurewebsites.net outreach-report-v1.scm.azurewebsites.net:443

Version: 0.7.1
OS: win32

**Comment by EricJizbaMSFT** [comment]
@sanjutvj can you give more info:
1. Does this happen consistently?
1. Are you on normal Azure or a sovereign account like Azure Government, Azure China, Azure Germany, etc.?
1. Was this a brand new app or an existing app?

**Comment by sanjutvj** [comment]
Yes. I am getting this error consistently. This is new app and want to host
in normal Azure.

Thanks
Sanju John

**Comment by EricJizbaMSFT** [comment]
And how did you create this app? Through the portal, VS Code, or the az cli? I can't repro this, so I'm trying to figure out what's unique about this web app

You might also want to update your version of the App Service extension. The current version is 0.12.0 and version 0.7.1 (listed in your original comment) was from 10 months ago

**Comment by sanjutvj** [comment]
Thank you

Let me try by using latest version

Thanks
Sanju John

**Comment by EricJizbaMSFT** [comment]
FYI our minimum VS Code version is 1.24.0, so check your VS Code version if you're not seeing our latest extension
