### ISSUE TITLE
No location shows during creating a linux web app for Azure China accounts

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azureappservice#877]
**OS:** All
**Node.js** 10.13.0
**Build Version**:[20190225.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3547&view=results)

**Repro Step:**
1. Go to File -> Preferences -> Settings -> Type "appService.advancedCreation" and enable it.
2. Sign in with Azure China account -> Try to create a linux web app.
3. Check locations show well in the step "Select a location for new resources" or not.

**Expect:**
Locations show well.
![image](https://user-images.githubusercontent.com/41351993/53385062-1b855780-39b8-11e9-8377-c95f9c1d1b2a.png)

**Actual:**
No location shows.
![image](https://user-images.githubusercontent.com/41351993/53383582-238ec880-39b3-11e9-9d02-cdca4a38ca0e.png)

**More Info:**
This issue also  reproduces for Azure Germany accounts.

**Comment by v-dantch** [comment]
Add screenshot:
![image](https://user-images.githubusercontent.com/34729092/54327751-6f9f5700-45c8-11e9-8c1a-657aaf2e1a9f.png)
