### ISSUE TITLE
tried to create new web app through VS Code extension

### ISSUE THREAD

**Issue by jackborkhuu** [Microsoft/vscode-azureappservice#881]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
tried to create new web app through VS Code extension

Action: appService.CreateWebApp
Error type: 403
Error Message: Failed with code "403".

Version: 0.12.0
OS: win32

**Comment by nturinski** [comment]
Is this a new subscription?  is this a recurring problem?
