### ISSUE TITLE
Bug Always : and can not sign out Azure on Visual studio code : i confuse

### ISSUE THREAD

**Issue by akedevs** [Microsoft/vscode-azureappservice#882]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: Error
Error Message: Entry not found in cache.

Version: 0.12.0
OS: darwin

**Comment by nturinski** [comment]
This seems to be an issue relating to the azure-account extension.  Please file an issue here: https://github.com/Microsoft/vscode-azure-account
