### ISSUE TITLE
[Suggestion]Change 'Start Remote Debugging' to 'Enable Remote Debugging'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#889]
**OS**: All
**Build Version:** [20190306.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3743)
**Regression:** Not a regression

**Repro Steps:**
Right click one web app-->Check the context menu.

**Actual:**
Display 'Start Remote Debugging'.
![image](https://user-images.githubusercontent.com/34729092/53872029-2e98b880-3fb2-11e9-9984-8cc02d80d724.png)

**Suggestion:**
Change 'Start Remote Debugging' to 'Enable Remote Debugging'.

**Comment by nturinski** [comment]
Definitely need to change the 'Yes' confirmation buttons to Enable/Disable.  Also change "Disable Remote Debugging" context action to "Stop".
