### ISSUE TITLE
[Suggestion]Add a notification after 'Start Remote Debugging'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azureappservice#890]
**OS:** All
**Build Version**: [20190306.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3743)
**Regression:** Not a regression

**Repro Steps:**
1. Right click one web app-->Select 'Start Remote Debugging'.
2. Check the result.

**Actual:**
There is no notification after executing 'Start Remote Debugging'.

**Suggestion:**
Add a notification after 'Start Remote Debugging'. It will be more easy for the customers to check the result.

**Comment by nturinski** [comment]
TODO: Investigate VS Code debug to see if screen reader indicates that it has attached or not.

**Comment by wwlorey** [comment]
@nturinski VoiceOver on mac indicates 'attaching debugger' and 'debugging started' for remote debugging. Do we want to see/hear more prompts than that?

**Comment by v-dantch** [comment]
Verified this issue on Win 10 & Mac with [20191125.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12677), it displays "Attached!" after executing 'Start Remote Debugging'.
![image](https://user-images.githubusercontent.com/34729092/69726036-94d5f480-115a-11ea-9317-f5649ccc7ca4.png)
