### ISSUE TITLE
Expanding WebJobs node shows an error 'Failed with code:404'

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azureappservice#891]
**OS:** All
**Build Version**: [20190306.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3743)
**Regression:** Not a regression

**Steps to reproduce:**
1. Create a new web app with any OS.
2. Try to expand the created web app -> 'WebJobs' node.
3. Check the result.

**Expect:**
There is no error on 'WebJobs' node.

**Actual:**
There shows an error 'Failed with code:404' on 'WebJobs' node.
![image](https://user-images.githubusercontent.com/34729022/53872979-44a77880-3fb4-11e9-89a9-bc1b62998ee0.png)

**Comment by nturinski** [comment]
Will look at using the ARM api for using WebJobs
