### ISSUE TITLE
Application Settings are not completely swapped between production and Deployment Slots

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azureappservice#892]
**OS :** All
**Node.js :** v10.13.0
**Build Version :** [20190306.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3743)
**Repro Steps:**
1. Create a new web app with windows OS -> Add two new settings for it under 'Application Settings'.
2. Create a new slot under 'Deployment Slots' node -> Choose 'Don't clone configuration for an existing slot' -> Add two new settings under 'Application Settings'.
3. Right click the new deployment slot and select 'Swap Deployment Slot...' -> Select production.
4.  Refresh the web app after swapping successfully then check whether 'Application Settings' swapped completely or not.

**Expect:**
Application Settings are completely swapped.

**Actual:**
Application Settings are not completely swapped.

![image](https://user-images.githubusercontent.com/41351993/53873659-c989a500-403b-11e9-806c-8799e0ecd24f.png)

**Comment by nturinski** [comment]
@v-xianya Were you able to get this to reproduce consistently?  I wasn't able to.  Is it possible that the setting was toggled as a slot setting?

**Comment by v-xianya** [comment]
Hi @nturinski, Verified using build [20190325.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4388&view=results). This issue doesn't reproduce.

**Comment by nturinski** [comment]
Thanks @v-xianya!  I'll go ahead and close this then.
