### ISSUE TITLE
Error deploy app service azure 

### ISSUE THREAD

**Issue by jedaro** [Microsoft/vscode-azureappservice#893]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: appService.Deploy
Error type: UNABLE_TO_VERIFY_LEAF_SIGNATURE
Error Message: unable to verify the first certificate

Version: 0.12.0
OS: darwin

**Comment by nturinski** [comment]
Closing as external. VS Code has made some improvements to certs on Insiders and it was working for me there. See Microsoft/vscode#52880
