### ISSUE TITLE
What is this sorting?

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#895]
![Screen Shot 2019-03-08 at 6 38 24 PM](https://user-images.githubusercontent.com/11282622/54065173-747f9780-41d1-11e9-81c8-ce219e11b585.png)

**Comment by nturinski** [comment]
Uhhh....

![image](https://user-images.githubusercontent.com/5290572/54065184-e526b400-41d1-11e9-9a56-d81a81f9b708.png)

**Comment by EricJizbaMSFT** [comment]
I have a Node.js app open - which could be affecting the "recommended" values at the top of the list. What do you have open?

**Comment by nturinski** [comment]
A JavaScript function app

**Comment by nturinski** [comment]
Related to https://github.com/Microsoft/vscode-azureappservice/issues/880

It probably is related to the "recommended" values.

**Comment by EricJizbaMSFT** [comment]
Closing as dupe
