### ISSUE TITLE
Seeing "Operation cancelled." during local git deploy

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azureappservice#898]
Repro steps:

1. Attempt a local git deploy after your git history has diverged
2. Select cancel when prompted to force push

Expected: No error

Actual:
Action: appService.Deploy
Error type: Error
Error Message: Operation cancelled.

Version: 0.13.0
OS: darwin
VS Code Version: 1.33.0-insider

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:333:824733)
Generator.throw (<anonymous>)
a (dist/extension.bundle.js:333:824407)
```

</details>

**Comment by nturinski** [comment]
Closed with this PR https://github.com/microsoft/vscode-azureappservice/pull/1014 due to appservice package update

**Comment by EricJizbaMSFT** [comment]
Re-opening until this thread is addressed: https://github.com/microsoft/vscode-azuretools/pull/509#discussion_r286741086

**Comment by nturinski** [comment]
Closed with https://github.com/microsoft/vscode-azuretools/pull/513
