### ISSUE TITLE
Carnaval-bh

### ISSUE THREAD

**Issue by ViniciusFerreira97** [Microsoft/vscode-azureappservice#903]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: fatal: Not a git repository (or any of the parent directories): .git

Version: 0.13.0
OS: win32
VS Code Version: 1.32.1

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:333:824733)
Generator.throw (<anonymous>)
a (dist/extension.bundle.js:333:824407)
```

</details>

**Comment by nturinski** [comment]
Hi @ViniciusFerreira97,

Are you trying to deploy via Local Git?  The project that you are deploying must be a git repository in that case.  To create a git repository, you will have to install [Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

Then in a terminal, run the commands:
``git init
git add .
git commit -m 'First commit
``

Then try to deploy again.  Hopefully this will resolve your issue!
