### ISSUE TITLE
problemas

### ISSUE THREAD

**Issue by roberley** [Microsoft/vscode-azureappservice#910]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: "desenvolvimentoaph" is connected to a GitHub repository. Push to GitHub repository to deploy.

Version: 0.13.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:277:3372352)
Generator.next (<anonymous>)
module.exports.n (dist/extension.bundle.js:277:3370987)
new Promise (<anonymous>)
module.exports.n (dist/extension.bundle.js:277:3370764)
module.exports.t.deploy.i.window.withProgress (dist/extension.bundle.js:277:3372215)
c._withProgress (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:422:75)
c.withProgress (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:421:836)
Object.withProgress (AppData/Local/Programs/Microsoft VS extensionHostProcess.js:674:269)
Object.<anonymous> (dist/extension.bundle.js:277:3372058)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:277:3370820)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by nturinski** [comment]
Hi @roberley

If your app is connected to a GitHub repo, then you can push changes to that repo and your web-app will pick up those changes automatically. No deployments necessary! :)

If this is not your issue, please let me know.

**Comment by roberley** [comment]
Thanks, for the attention, I think I was able to configure azure to fetch
my application through github. I'm just having a portal https error to
access an API on my AWS virtual machine.

sorry for my bad English, I'm using google translator to write in English.

Em seg, 25 de mar de 2019 às 19:20, Nathan <notifications@github.com>
escreveu:

**Comment by nturinski** [comment]
You're very welcome :)

I'll go ahead and close this issue, but please re-open if you have more problems.
