### ISSUE TITLE
Error Message: The subscription '83b61996-ea4b-4a5c-923d-8e704124159f' what can i do?

### ISSUE THREAD

**Issue by WeRDiamondDogs** [Microsoft/vscode-azureappservice#912]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: ReadOnlyDisabledSubscription
Error Message: The subscription '83b61996-ea4b-4a5c-923d-8e704124159f' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled.

Version: 0.13.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
module.exports.Ps.a.pipeline (dist/extension.bundle.js:277:2546875)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:521656)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by nturinski** [comment]
Hi @WeRDiamondDogs,

Sorry for this issue.  If you were using a free 30-day trial, your trial may have expired.  I believe that this documentation will be helpful in resolving your issue: https://docs.microsoft.com/en-us/azure/billing/billing-subscription-become-disable.

If your problem isn't resolved by this, please re-open this issue with some more details on how I can assist you.
