### ISSUE TITLE
Could not write to local resource

### ISSUE THREAD

**Issue by chipimo** [Microsoft/vscode-azureappservice#914]
Repro steps:

1.
2.

Action: appService.fileEditor.onDidSaveTextDocument
Error type: 409
Error Message: Could not write to local resource '/home/site/wwwroot/hostingstart.html' due to error 'The process cannot access the file '/home/site/wwwroot/hostingstart.html' because it is being used by another process.'.

Version: 0.13.0
OS: win32
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
module.exports.o.pipeline (dist/extension.bundle.js:333:435311)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] (dist/extension.bundle.js:1:521621)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by nturinski** [comment]
HI @chipimo,

Thanks for reporting this issue.  It looks like you are trying to save your remote copy of `hostingstart.html` while it is being edited somewhere else.  Are you accessing this file somewhere else?
