### ISSUE TITLE
i can't stop progress. for delete webapp

### ISSUE THREAD

**Issue by YoonuchReal** [Microsoft/vscode-azureappservice#915]
Repro steps:

1.
2.

Action: appService.Delete
Error type: Conflict
Error Message: Cannot modify this site because another operation is in progress. Details: Id: 44702d3b-54a8-4c6c-9181-461b9b783958, OperationName: SwapSiteSlots, CreatedTime: 3/26/2019 8:39:19 AM, WebSystemName: websites, SubscriptionName: 4299c0ba-22e3-4b61-8170-b3b8343eb380, WebspaceName: busble-resource-SoutheastAsiawebspace, SiteName: busble, SlotName: development, ServerFarmName: , GeoOperationId: (null)

Version: 0.13.0
OS: darwin
VS Code Version: 1.32.3

<details>
<summary>Call Stack</summary>

```
module.exports.a.pipeline (dist/extension.bundle.js:277:1415325)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:521594)
$.module.exports.$.init.t._callback.t.callback.t.callback [as callback] (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by nturinski** [comment]
Hi @YoonuchReal,

Are you trying to cancel the delete operation on a web app after you have already confirmed that you want to delete it?  If so, unfortunately, there is nothing we can do to reverse the delete as it is a destructive command.

**Comment by YoonuchReal** [comment]
I can delete appService on next day. thank you.
