### ISSUE TITLE
Unable to debug remotely

### ISSUE THREAD

**Issue by gvsharma** [Microsoft/vscode-azureappservice#925]
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js version >= 8.11 on Linux.

Version: 0.13.0
OS: darwin
VS Code Version: 1.33.0

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.checkForRemoteDebugSupport (dist/extension.bundle.js:9:131094)
dist/extension.bundle.js:361:30424
Generator.next (<anonymous>)
o (dist/extension.bundle.js:361:29605)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by nturinski** [comment]
Hi @gvsharma,

Thanks for reporting this issue.  What type of app are you attempting to remote debug?

**Comment by gvsharma** [comment]
node application

**Comment by nturinski** [comment]
What version of node are you using? And are you using a Linux web app?  Currently remote debug is only supported on Linux web apps.
