### ISSUE TITLE
Reorganize Context Menu items on Apps

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#926]
If we add SSH, the menu will look like this:

https://user-images.githubusercontent.com/5290572/55519214-c0d0c280-562b-11e9-9867-4c7c12d130c6.png

This is way too cluttered so we should reorganize the context actions into more specific nodes.  Deploy/Change Deployment Source seem like the most obvious to me.

**Comment by EricJizbaMSFT** [comment]
Suggest looking at telemetry for these actions as well - and potentially removing any that have very low usage

**Comment by nturinski** [comment]
@fiveisprime Can we move `Continuous Delivery (Preview)` and `Generate CLI Script`?  The usage numbers are quite low and the web app context menu is getting pretty cluttered.

**Comment by nturinski** [comment]
Discussed offline, once we remove stop remote debugging and consolidate with ssh, it'll look fine.
