### ISSUE TITLE
Question about the hint message when creating web app

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode-azureappservice#929]
Maybe this is not an issue.

When I create a new Web App I can see a message showing: 

![WeChat Screenshot_20190409101536](https://user-images.githubusercontent.com/6193897/55769673-2ac9eb80-5ab4-11e9-8243-088023b76d1c.png)

May I ask what does `(3/1)` here stand for?

**Comment by jdneo** [comment]
Just tried with the version `0.13.0` from the marketplace and didn't see `(3/1)`. It must be something wrong with my local dev env.

Sorry for the confusion.

**Comment by EricJizbaMSFT** [comment]
That code hasn't been released yet, so you wouldn't see it on `0.13.0`. Let me know if you are still seeing it with the latest master from this repo. If you're working in the vscode-azuretools repo, make sure you're on the latest master from that repo as well

**Comment by jdneo** [comment]
The result by using the master branch: 
![image](https://user-images.githubusercontent.com/6193897/55927442-a3ad7c80-5c47-11e9-8263-094ab7e8e3a9.png)


For some unknown reason, VS Code will crash on my Mac. But it works fine on Windows

**Comment by EricJizbaMSFT** [comment]
Yeah that looks better. The numbers represent the number of steps executed. For example, creating the resource group and the app service plan are probably the first two steps
