### ISSUE TITLE
How to logout / change azure account?

### ISSUE THREAD

**Issue by nissejokke** [Microsoft/vscode-azureappservice#930]
Logged in with wrong azure account, how to logout / change account?

**Comment by EricJizbaMSFT** [comment]
@nissejokke open up the [command palette]:(https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette)
![Screen Shot 2019-04-10 at 8 34 11 AM](https://user-images.githubusercontent.com/11282622/55892620-77bcc900-5b6b-11e9-915c-0050387e3a97.png)

And search for "Sign out" to find the sign out command:
![Screen Shot 2019-04-10 at 8 34 25 AM](https://user-images.githubusercontent.com/11282622/55892621-77bcc900-5b6b-11e9-9327-24c779c90638.png)

**Comment by nissejokke** [comment]
Thank you!
