### ISSUE TITLE
Endless "Deploying to" with no error and no timeout

### ISSUE THREAD

**Issue by lonpalmer** [Microsoft/vscode-azureappservice#931]
Trying to deploy to web app produces endless spinner and endless "Deploying to..." message without timeout and without any progress or error messages.  Even if the deployment fails there should at least be a timeout and an error or some indication of the stalled step.

**Comment by EricJizbaMSFT** [comment]
@lonpalmer can you tell us the following:
1. What version of the extension are you on?
1. Can you copy the logs from the App Service output channel? That might help us figure out which step is stalling
![Screen Shot 2019-04-10 at 9 33 06 AM](https://user-images.githubusercontent.com/11282622/55896663-aa6abf80-5b73-11e9-88ea-c86b51c14c38.png)
1. Have you configured your web app for a non-default deployment source? Like local git?

**Comment by lonpalmer** [comment]
1. 0.13.0
2. I don't have the access to my previous logs and it's been working since I blew away my app service and redeployed it.  When I was looking at the output channel it was blank.  
3. No.  I didn't configure it for non-default.  

Another thing to note is that I gave up and Zip deployed through the Kudu tools. Not sure if I can get the logs any more.

**Comment by EricJizbaMSFT** [comment]
Okay let us know if this happens again and send us those deploy logs when it does

It could be related to this bug: https://github.com/Microsoft/vscode-azurefunctions/issues/1105. That only applies if you're deploying a typescript project and we're just waiting for the fix in TypeScript
