### ISSUE TITLE
Use CustomExecution to run SSH Task instead of Terminal

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azureappservice#932]
When this is in stable https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_33.md#custom-task-execution, should use it instead of `vscode.Terminal`

**Comment by nturinski** [comment]
This should also fix the `delay(3000)` that is required to enter into the password into the terminal.

**Comment by EricJizbaMSFT** [comment]
https://github.com/microsoft/vscode/issues/80375

**Comment by ejizba** [comment]
I ran into this again recently where I SSH'ed into my web app and it entered "Docker!" too quickly, so I had to do it myself (but that's not obvious to most users).

@neelip this would be a good feature for you to work on. Please assign it to yourself if/when you start it
