### ISSUE TITLE
Please help :( my first time deploying..

### ISSUE THREAD

**Issue by SHAHID786s** [microsoft/vscode-azureappservice#935]
Repro steps:

1.
2.

Action: appService.Stop
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND management.azure.com management.azure.com:443

Version: 0.13.0
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
```

</details>

**Comment by nturinski** [comment]
Hi @SHAHID786s,

Congrats on your first deployment!  🎉 
Sorry that it doesn't seem to be working. 😦   

It seems like you tried to `stop` your web app.  Is this by chance a brand new app?  Have you been able to reproduce this issue?

**Comment by SHAHID786s** [comment]
new app and the error is constant! I have deleted it deployed on different versions... still same issue I think. Also, how do I access different endpoints e.g. localhost:3000/user/me

**Comment by SHAHID786s** [comment]
Im pretty new to deploying I’ve got to do it for my dissertation. I’ve got a node app. I’ve removed node modules. I keep getting an error and I have tried different deploying on different node versions. Do I have to change anything in my node app before development beings e.g. port numbers ?? I’ve been trying this for 4 + hours

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nturinski** [comment]
So you've been able to successfully deploy to the web app, but it hasn't successfully been built the app?  
What runtime is your web app, Linux or Windows?  If Linux, what version of node are you using?  And what version of node is your project?  Are you using any frameworks?

Do you have a link to your project?  If it's open-sourced, I can take a look.

**Comment by SHAHID786s** [comment]
It’s not open source because it  is part of my dissertation, unfortunately. The app isn’t getting built successfully. Node 6.8.0 using express.js and Jade

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nturinski** [comment]
Do you know if the node_modules are getting installed on the app?  You can check this by looking at the `Files` node:

![image](https://user-images.githubusercontent.com/5290572/56057885-d96c6700-5d14-11e9-8b01-7ac82856f04f.png)

If the `node_modules` aren't present, then you can either `npm install` prior to deploying or make sure your project has a `.deployment` file that is generated for you if you hit yes to this confirmation dialog.

![image](https://user-images.githubusercontent.com/5290572/56058127-6b746f80-5d15-11e9-8aad-c60f52d72808.png)


I'd also recommend looking at the `Log Files`.  There may be some indication of why your project is failing to build.

**Comment by SHAHID786s** [comment]
I’ve done that gonna still hack at it see where I go..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by SHAHID786s** [comment]
I fixed the error had to update node and a few other things I can’t remember. I think the logs are fine >>>>>


[cid:image002.png@01D4F179.460E0DD0]



But when the webpage open now I get the following>>>

[cid:image004.png@01D4F179.4565E6F0]























Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nturinski** [comment]
@SHAHID786s, unfortunately, I can't see any of your screenshots.  Could you attach them directly in GitHub? I think it's having issues with attachments from mail.

**Comment by SHAHID786s** [comment]
I will do when I have 5 minutes really busy atm. Another thing.. I added a web config file and changed node.process.env to development. Then my error message was internal server error and there were no errors on the log file in azure

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nturinski** [comment]
Hmm, if that isn't working, you may be able to change it to a development environment by adding an app setting.  I believe the key would be `NODE_ENV` and the value is `development`

![image](https://user-images.githubusercontent.com/5290572/56232820-7a6d6180-6036-11e9-8eeb-0e43de4eedde.png)

**Comment by SHAHID786s** [comment]
is it under add new setting?

**Comment by nturinski** [comment]
Yes, click `Add New Setting...` and it'll ask for key and value inputs.
