### ISSUE TITLE
First time deploying to azure web app, Django fails

### ISSUE THREAD

**Issue by Yishaiaz** [microsoft/vscode-azureappservice#936]
hey, I've been trying for a long time to deploy my Django web app to azure web apps with no success. 
I'm using djnago2.1 and python 3.7. 
I followed the azure documentation and tutorials, and I'm now using the visual studio code plugin to deploy to my web app.
I had many issues, but I'm struggling with this one.

the output stream is :

5:02:25 PM SkypickHoldings: Deploying Local Git repository to "SkypickHoldings"...
3:46:07 PM SkypickHoldings: Updating branch 'master'.
3:50:52 PM SkypickHoldings: Updating submodules.
3:50:52 PM SkypickHoldings: Preparing deployment for commit id '5cb86f234a'.
3:50:53 PM SkypickHoldings: Oryx-Build: Running kudu sync...
3:50:53 PM SkypickHoldings: Command: kudusync -v 50 -f /home/site/repository -t /home/site/wwwroot -n /home/site/deployments/5cb86f234a8b61b75b69df07a61acdf50d238f7f/manifest -p /opt/Kudu/KuduConsole/Scripts/firstDeploymentManifest -i ".git;.hg;.deployment;.deploy.sh"
3:50:54 PM SkypickHoldings: Kudu sync from: '/home/site/repository' to: '/home/site/wwwroot'
3:50:54 PM SkypickHoldings: Ignoring: .deployment
3:50:54 PM SkypickHoldings: Deleting file: 'hostingstart.html'
3:50:54 PM SkypickHoldings: Ignoring: .git
3:50:54 PM SkypickHoldings: Copying file: '.vscode/launch.json'
3:50:54 PM SkypickHoldings: Copying file: '.vscode/settings.json'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/custom_azure.py'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/db.sqlite3'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/manage.py'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/requirements.txt'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/activate'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/activate.csh'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/activate.fish'
3:50:54 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/activate.ps1'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/activate.xsh'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/activate_this.py'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/asadmin'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/bundle_image'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/cfadmin'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/chardetect'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/cq'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/cwutil'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/django-admin'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/django-admin.py'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/dynamodb_dump'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/dynamodb_load'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/easy_install'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/easy_install-3.6'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/elbadmin'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/fetch_file'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/glacier'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/instance_events'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/jp.py'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/kill_instance'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/launch_instance'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/list_instances'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/lss3'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/misaka'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/mturk'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/pip'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/pip3'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/pip3.6'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/pyami_sendmail'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/pyjwt'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/python'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/python-config'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/python3'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/python3.6'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/route53'
3:50:55 PM SkypickHoldings: Copying file: 'Skypick_Holdings_Main_Site/HoldingsENv/bin/rst2html.py'
3:50:55 PM SkypickHoldings: Omitting next output lines...
3:50:55 PM SkypickHoldings: **Error: ENOENT: no such file or directory, stat '/home/site/repository/Skypick_Holdings_Main_Site/HoldingsENv/include/python3.6m'**
3:50:55 PM SkypickHoldings: \n/opt/Kudu/KuduConsole/Scripts/starter.sh kudusync -v 50 -f /home/site/repository -t /home/site/wwwroot -n /home/site/deployments/5cb86f234a8b61b75b69df07a61acdf50d238f7f/manifest -p /opt/Kudu/KuduConsole/Scripts/firstDeploymentManifest -i ".git;.hg;.deployment;.deploy.sh"
3:50:56 PM SkypickHoldings: App container will begin restart within 10 seconds.
**Deployment to "SkypickHoldings" completed.**

I get the deployment completed, but the url only shows the standard azure Django app service.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/38314286/56140041-c078e580-5fa2-11e9-9b88-7f10e533df86.png">

I'd love to hear any other method to deploy to azure a Django web application(a website) that will work, because I tried so many and failed so far.

**Comment by nturinski** [comment]
Sorry that you're having problems @Yishaiaz.  I'm not sure why, but it seems like you're missing a python3.6m file.

@qubitron Do you have any idea what's going wrong here?

**Comment by qubitron** [comment]
When App Service can't detect the startup file for the app you get this generic page. It looks like manage.py is in `Skypick_Holdings_Main_Site/manage.py`, so instead you will either have to deploy the `Skypick_Holdings_Main_Site` folder as the root or [configure your startup command](https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-configure-python#django-app). 

Note that requirements.txt should be in the root so that App Service can install dependencies your app needs. To speed up deployment, you should also add your virtual environment to the skip files list in your settings.json:
```
"appService.zipIgnorePattern": [
    ".vscode{,/**}",
    "HoldingsENv{,/**}"
],
```

/cc @kraigb we may want to clarify some of these gotchas in the docs

**Comment by kraigb** [comment]
@qubitron Thanks, I'll do that.
