### ISSUE TITLE
Show app setting value as a child node of the key

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#94]
Today we have the key and value in the same node separated by a colon. I propose we display the value as a child node of the key for a few reasons:

1. If the key and/or value has a colon it can be hard to distinguish where one starts and the other ends
![screen shot 2017-10-03 at 9 38 51 am](https://user-images.githubusercontent.com/11282622/31137040-c71a92d6-a81e-11e7-81e8-783f6929fadb.png)
1. People often put secrets in application settings. This way they could look at all of their keys and individually show/hide the value as desired.
1. I see users changing values more often than keys. I was actually suprised when I clicked 'edit' and the key popped up. This way we could have an edit action on each node with only one input box each.

**Comment by whiskeyjay** [comment]
I have a fix for 1 and 3 since they make a lot sense to me. For 2, I believe most settings are not secrets, an extra step to see the value seems a bit unnecessary; and real secrets should be kept in KeyVault instead of app settings (environment variables in the container).
