### ISSUE TITLE
UNable to debug remotely

### ISSUE THREAD

**Issue by himsoftware** [microsoft/vscode-azureappservice#940]
Repro steps:

1.
2.

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Unable to establish connection to application: WebApp is stopped, try sending a request to start it up

Version: 0.13.0
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
TunnelProxy.<anonymous> (dist/extension.bundle.js:333:934898)
Generator.throw (<anonymous>)
a (dist/extension.bundle.js:333:931125)
```

</details>

**Comment by nturinski** [comment]
Hi @himsoftware,

Sorry that you're having this issue.  Has this problem consistently reproed?  If it is due the Web App being stopped, could you try restarting it, waiting a minute, and then try remote debugging?
