### ISSUE TITLE
Problem deploying to Azure

### ISSUE THREAD

**Issue by Neikson** [microsoft/vscode-azureappservice#941]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: object
Error Message: getaddrinfo ENOTFOUND nkwebapipoc.scm.azurewebsites.net nkwebapipoc.scm.azurewebsites.net:443

Version: 0.13.0
OS: linux
VS Code Version: 1.33.1

**Comment by nturinski** [comment]
Hi @Neikson,

Sorry that you're having issues deploying with the extension.  Could you answer a few questions for me, please?

1. Does this happen consistently?
1. Are you on normal Azure or a sovereign account like Azure Government, Azure China, Azure Germany, etc.?
1. Was this a brand new app or an existing app?
