### ISSUE TITLE
Improve smart defaults for .NET Core apps

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azureappservice#945]
- Use Linux by default
- Create settings.json with...
  - `preDeploy` of `dotnet publish`
  - `deploySubpath` set to correct path `bin/Debug/<framework version>/publish`

Note that users with Omnisharp may already have the publish task created. This requires the user to confirm they want to add the config files.

**Comment by bradygaster** [comment]
mentioning @timheuer and @spboyer here as i discussed this with them too and they may have addendum.

**Comment by timheuer** [comment]
```
"appService.deploySubpath": "bin\\Debug\\<fwversion>\\publish",
"appService.preDeployTask": "publish"
```
Even with these defaults the ```deploySubpath``` setting changes based on user interaction so that needs to be hardened once set or confirming overwriting more than it does today.

**Comment by EricJizbaMSFT** [comment]
We could potentially add support for a special variable (something like `${targetFramework}`) that automatically parses your csproj to get the value and replaces it when deploying. Should be easy enough in most cases, although not sure what we'd do if they have multiple csproj files or a weird folder structure

**Comment by timheuer** [comment]
That would be helpful @EricJizbaMSFT but we'd have to do it on first deploy.  We don't want to assume every csproj is something that will be deployed to Azure, otherwise we could do all this in Omnisharp extension today on startup.

**Comment by EricJizbaMSFT** [comment]
@timheuer I may have missed some context here, but I was already assuming all this logic would be in the appservice extension, not omnisharp

**Comment by timheuer** [comment]
@EricJizbaMSFT no you are right...just meant at the time of parsing the csproj file can't annoy the non-Azure customer :-).  I am pretty sure we are saying the same things, just differently.  VS Code has a nice means to enable setting vars and inspecting things on startup of an extension in a workspace which would have made inspecting the csproj easier...but we wouldn't want to do that in this case IMO at that sequence.

**Comment by fiveisprime** [comment]
Another test case: `$ dotnet new mvp` fails to deploy today.

**Comment by spboyer** [comment]
@fiveisprime what is the framework? 
can you `dotnet --info`

**Comment by fiveisprime** [comment]
This was also reported by a customer. My result is:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18908
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by spboyer** [comment]
@bradygaster

**Comment by bradygaster** [comment]
I can try this again, but AFAIK, each time i've tried, the way with which i achieve success is to manually `dotnet publish`, then to right-click the actual publish folder, and *then* publish that to my App Service. that works every time, but i know those steps.

**Comment by spboyer** [comment]
@fiveisprime - what are the replication steps for your failure?

**Comment by timheuer** [comment]
Yes any pre-compiled option will hit this experience.

**Comment by fiveisprime** [comment]
Followed Brady's steps and got it deployed. Thanks :)

**Comment by timheuer** [comment]
if you set the settings that I note above now, then the extension will deploy correctly each time now as well.

**Comment by bradygaster** [comment]
in a perfect world, the stuff @timheuer mentions would be automatic if possible. ideally, i could do this:

```
dotnet new mvc -o MyNewMvcApp
cd MyNewMvcApp
code .
```

Then, i'd right-click anywhere in the explorer view and select `publish` and it'd "just work."

**Comment by nturinski** [comment]
Hi @bradygaster @timheuer 

I've been working on this, but ran into a snag when deploying.  I've been creating a netcoreapp2.0 with `dotnet new mvc -o newapp`, running `publish`, and then deploying it to a Linux Web app with the .Net Core 2.0 runtime, but it fails to recognize the .dll.

Here's the error from the log stream:
![image](https://user-images.githubusercontent.com/5290572/60550517-21c86f00-9cdd-11e9-9220-ad336fdc73dd.png)

And here is the web app's directory.  The newapp.dll is definitely there.

![image](https://user-images.githubusercontent.com/5290572/60550482-f8a7de80-9cdc-11e9-9090-fd5b418fdd10.png)

Any ideas what I'm doing wrong here?

**Comment by bradygaster** [comment]
adding @spboyer to the discussion as well

**Comment by timheuer** [comment]
Does the app run when you run on the listening port?

**Comment by nturinski** [comment]
@timheuer Do you I run `dotnet run` locally?  If so, yes, it seems to run fine.

**Comment by bradygaster** [comment]
@nturinski can you hop onto the portal blade and customize the startup command to run the `dotnet newapp.dll` command?

**Comment by timheuer** [comment]
I see the log error, I'm just wondering when you actually browse to the deployed site if it works or if there are further error messages?

**Comment by nturinski** [comment]
@bradygaster That did it.  Is there a way we can make this easier for the user?  I remember @fiveisprime and you had discussed that after a `publish` and deploy, it used to just work.  Do you know what's changed?

@timheuer Oh, no there's only a 404 error response.

**Comment by timheuer** [comment]
you should absolutely not need to do that in the portal...hmmm, i'm hastily trying now, but also in a meeting and can't quickly repro what you're seeing.

**Comment by fiveisprime** [comment]
I believe that was only working because I was using basic creation, which deploys .NET apps to Windows. This seems to be a problem that's specific to Linux.
