### ISSUE TITLE
Don't know what is this?

### ISSUE THREAD

**Issue by intakhab** [microsoft/vscode-azureappservice#948]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "my-test-project" failed. See output channel for more details.

Version: 0.13.0
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> (dist/extension.bundle.js:1:473283)
Generator.next (<anonymous>)
o (dist/extension.bundle.js:1:471302)
process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by nturinski** [comment]
Hi @intakhab 

Could you please list repro steps for your issue?  Useful information would also be the type of project you are deploying, whether or not this is a new web app, and if it has a Linux or Windows runtime.

Thanks!
