### ISSUE TITLE
Stuck with message "There is a deployment currently in progress"

### ISSUE THREAD

**Issue by djdrost** [microsoft/vscode-azureappservice#952]
Repro steps:

1. Click Deploy to Web App
2. It will try to deploy and it gets stuck with the message - "There is a deployment currently in progress. Please try again when it completes.".  The other deployment never finished - I've waited for close to a day  

Action: appService.Deploy
Error type: 409
Error Message: There is a deployment currently in progress. Please try again when it completes.

Version: 0.13.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
module.exports.s.pipeline (dist/extension.bundle.js:333:389153)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.s.pipe.a [as _callback] (dist/extension.bundle.js:1:521632)
$.module.exports.$.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
$.emit (events.js:182:13)
$.<anonymous> (dist/extension.bundle.js:253:18274)
$.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by nturinski** [comment]
Hi @djdrost,

Sorry you're running into issues.  

This is a bizarre error.  If it's an option, I'd try to just make a fresh app and redeploy to that one.  

If that isn't an option, there is a way to cancel deployments via the Azure CLI  or the [API](https://docs.microsoft.com/en-us/rest/api/resources/deployments/cancel).  Unfortunately, we do not support this in the extension right now.

**Comment by djdrost** [comment]
Hi, i did create a new app amd it works.  I won't use deployments through
continous deploymemt since this causes the issue.  Deploying from zip works
great

**Comment by nturinski** [comment]
@djdrost I'm glad you found a workaround!

If you don't mind, what do you mean by

> deployments through
continous deploymemt

I'd like to investigate how to resolve this issue in the future.
