### ISSUE TITLE
The disabled "Deployment Slots" node DOES NOT list alphabetically

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azureappservice#954]
**Build Version:** [20190423.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=5292)
**OS**: All

**Repro Steps:**
1. Create a new web app with basic app service plan to make sure "Deployment Slots" node is disabled.
2. Check its order.

**Expect:**
It is in a random order.

**Actual:**
It does not list alphabetically.
![image](https://user-images.githubusercontent.com/34729092/56574258-a5484000-6577-11e9-8a24-c996c555fd9d.png)

**Comment by nturinski** [comment]
@v-dantch Thanks for reporting.  I should have told you before testing, but this is actually a design choice.  

I felt that because the deployment slots are disabled, it made more sense to put them at the bottom since the user cannot interact with the node and it was cluttering their UI.

**Comment by v-dantch** [comment]
Hi @nturinski, got it. Thanks for your update and confirmation. 
It is more user-friendly for the users that put the disabled nodes at the bottom.
And another question needs to confirm with you---for the disabled nodes like "WebJobs" and "Deployment Slots", is there necessary to list in order?

**Comment by nturinski** [comment]
Yeah, I should probably organize them in alphabetical order.  I've made an issue for that here :)
https://github.com/Microsoft/vscode-azureappservice/issues/955

**Comment by v-dantch** [comment]
High Five :)

**Comment by nturinski** [comment]
✋
