### ISSUE TITLE
Zip Deloy with no workspace open fails silently

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#96]
If I try 'Local Git Deploy' with no folder open, it fails with message 'You have not yet opened a folder to deploy.'.  The zip deploy doesn't have any message

**Comment by whiskeyjay** [comment]
It does say "no open folder".

https://github.com/Microsoft/vscode-azureappservice/blob/b917e0871a996d52e9eaa5b5aec166d4724148af/src/webAppZipPublisher.ts#L68

**Comment by EricJizbaMSFT** [comment]
This was one of the weird cases where VS Code doesn't show an error message even if you throw an error. I looked into this more and @StephenWeatherford accidentally or intentionally fixed it here: https://github.com/Microsoft/vscode-azureappservice/commit/2080e73adf45413d3e28f7659161ee5b7bd3b7d7#diff-09218c96a79c602b2a5e9dd9dfc1898aR123
