### ISSUE TITLE
not deploy!!!!

### ISSUE THREAD

**Issue by miguelito15tk** [Microsoft/vscode-azureappservice#967]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 0.13.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
onErrorNT (internal/child_process.js:406:16)
process._tickCallback (internal/process/next_tick.js:63:19)
Object.<anonymous> (dist/extension.bundle.js:333:824733)
Generator.throw (<anonymous>)
a (dist/extension.bundle.js:333:824407)
```

</details>

**Comment by nturinski** [comment]
Hi @miguelito15tk,

Sorry that you're having issues here.  Could you give me repro steps to help resolve this issue?

**Comment by nturinski** [comment]
@miguelito15tk 

Are you trying to deploy via Git?  This error seems like the error you might have from not having Git installed on your machine.

Could you try typing `git --version` in your VS Code terminal and tell me what you get?

**Comment by miguelito15tk** [comment]
git version 2.21.0.windows.1

**Comment by nturinski** [comment]
Could you provide some more details?

1. Repro steps
1. What is your deployment source? (You can see this on the Deployments node)
1. Is this a new web app?

**Comment by miguelito15tk** [comment]
Thank you!! **@nturinski**  I have  always solved my problem.
