### ISSUE TITLE
Zip/Git deploy should support multi-root workspaces

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azureappservice#97]
VSCode 1.17 introduces multi-root workspaces. However, our Zip deploy and Local Git deploy always use the "first" folder. Instead we should show a quick pick if there are multiple workspace roots

**Comment by whiskeyjay** [comment]
Zip deploy supports multiple workspace
https://github.com/Microsoft/vscode-azureappservice/blob/2ce5f8f0011c15657f7c68cc0dc297354e1c8b39/src/webAppZipPublisher.ts#L51

Git deploy needs to add support for multiple workspace.
