### ISSUE TITLE
Entry not found in cache error when entering a globally unique name for a new web app

### ISSUE THREAD

**Issue by nnja** [Microsoft/vscode-azureappservice#974]
Repro steps:

1. Open the command palette
2. Select: Azure App Service: Create New Web App...
3. Enter any value
4. Hit return

Other considerations:
- I have `"appService.advancedCreation": true` set in my settings
- I'm logged in and have successfully used the extension in the past

Action: appService.CreateWebApp
Error type: Error
Error Message: Entry not found in cache.

Version: 0.13.1
OS: darwin
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError (dist/extension.js:1:49013)
b.<anonymous> (dist/extension.js:229:176642)
dist/extension.js:229:171257
dist/extension.js:229:43312
dist/extension.js:229:41305
dist/extension.js:229:40927
i.module.exports.i.find (dist/extension.js:229:75420)
module.exports.find.init.then (dist/extension.js:229:22917)
```

</details>

**Comment by nnja** [comment]
I also see the following in my sidebar

![image](https://user-images.githubusercontent.com/2030983/57051016-8e22e580-6c3c-11e9-9488-1c8e237bed12.png)

**Comment by nturinski** [comment]
Hi @nnja

This seems to be related to this issue: https://github.com/Microsoft/vscode-azure-account/issues/53

Unfortunately, I'm not sure there's a lot our team can do about this bug, but I think the workaround is logging out and then logging back in. ☹️ 

In the command palette, that's `Azure: Sign Out` and `Azure: Sign In`

**Comment by nnja** [comment]
I uninstalled and reinstalled the extension, and it seems to have resolved itself.

Is there any way to detect and fix this state from the extension itself for a better user experience?

**Comment by nturinski** [comment]
Just for clarification, when you say you uninstalled/reinstalled the extension, are you referring to App Service or the Account Extension??

We could try to catch the error and resign the user out/in maybe. @fiveisprime Would this be too jarring of a user experience?

**Comment by nturinski** [comment]
Closing as external.  We are currently tracking this issue: https://github.com/Microsoft/vscode-azure-account/issues/53

**Comment by nnja** [comment]
@nturinski -- I uninstalled and reinstalled the Azure App Service extension. That cleared the error.

I didn't touch the Account extension, and I did not log out.

**Comment by fiveisprime** [comment]
> We could try to catch the error and resign the user out/in maybe. @fiveisprime Would this be too jarring of a user experience?

Yeah, I don't like that at all. Does a reload work? I'd be fine with a button as part of the error that would exec a reload for them.
