### ISSUE TITLE
deployment issue React azure webapp

### ISSUE THREAD

**Issue by amaraba2** [microsoft/vscode-azureappservice#985]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)

Version: 0.14.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Process.ChildProcess._handle.onexit child_process.js:229:19
onErrorNT child_process.js:406:16
process._tickCallback next_tick.js:63:19
Object.<anonymous> extension.bundle.js:332:350444
a extension.bundle.js:332:350118
```

</details>

**Comment by nturinski** [comment]
Hi @amaraba2,

The error seems to indicate that you are trying to do a local git deploy.  If so, do you have Git installed?

If that isn't the issue, could you please add repro steps so that I can further assist you?
