### ISSUE TITLE
cannot depoy app to azure after core lib  upgrade

### ISSUE THREAD

**Issue by antsh85** [microsoft/vscode-azureappservice#986]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Failed to get status of deployment.

Version: 0.14.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:332:350444
a extension.bundle.js:332:350118
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @antsh85

Does this error recur? Could you provide repro steps, please?

**Comment by antsh85** [comment]
hi, so repro is easy, I 
select "Azure" module on the left side
App service -> subscriptions -> select my app -> deploy to Web app
deployment starts and then fails after a bit

**Comment by nturinski** [comment]
@antsh85 

Could you answer a few questions?
1. Is this a new web app?
1. What OS is your web app?
1. What runtime is your web app?
1. What is your deployment source config? (such as Local Git)
