### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by farrukhkhanacce** [microsoft/vscode-azureappservice#987]
Repro steps:

1.
2.

Action: appService.Deploy
Error type: Error
Error Message: Deployment to "rpa-assessment-roi" failed. See output channel for more details.

Version: 0.14.0
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:477324
o extension.bundle.js:1:475315
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @farrukhkhanacce,

Sorry for your issue.  Does this reproduce consistently?  Could you provide repro steps, please?
