### ISSUE TITLE
Failed to create app 

### ISSUE THREAD

**Issue by cohenisca** [microsoft/vscode-azureappservice#993]
Repro steps:

1.
I'm trying to create a new app web and it's an error message I get:
No available instances to satisfy this request. App Service is attempting to increase capacity. Please retry your request later. If urgent, this can be mitigated by deploying this to a new resource group.
what can I do?
2.

Action: appService.Deploy
Error type: Conflict
Error Message: No available instances to satisfy this request. App Service is attempting to increase capacity. Please retry your request later. If urgent, this can be mitigated by deploying this to a new resource group.

Version: 0.13.1
OS: win32
VS Code Version: 1.24.1

<details>
<summary>Call Stack</summary>

```
l.pipeline (dist/extension.bundle.js:277:3295017)
s (dist/extension.bundle.js:277:112563)
s (dist/extension.bundle.js:165:26036)
dist/extension.bundle.js:165:27276
o (dist/extension.bundle.js:223:7054)
dist/extension.bundle.js:165:24957
$.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:1:521667)
$.t._callback.t.callback.t.callback (dist/extension.bundle.js:253:5461)
emitTwo (events.js:106:13)
$.emit (events.js:194:7)
$.<anonymous> (dist/extension.bundle.js:253:18274)
emitOne (events.js:101:20)
$.emit (events.js:191:7)
IncomingMessage.<anonymous> (dist/extension.bundle.js:253:17116)
Object.onceWrapper (events.js:293:19)
emitNone (events.js:91:20)
IncomingMessage.emit (events.js:188:7)
endReadableNT (_stream_readable.js:975:12)
_combinedTickCallback (internal/process/next_tick.js:80:11)
process._tickCallback (internal/process/next_tick.js:104:9)
```

</details>

**Comment by nturinski** [comment]
Hi @cohenisca,

Sorry that you're having issues creating an app.  How many web apps do you have allocated to one plan?  If you have more than 3 web apps to one app service plan, you might experience performance issues.

If you go into your app settings `(ctrl + ,)` you can change your user settings.  Turn on the following setting:

`"appService.advancedCreation": true,`

Once you've done that, try to create the web app again and create a new app service plan when prompted.  Hopefully this will resolve your issue.

**Comment by nipunsahni** [comment]
Hello, We are experiencing the same issue above when trying to deploy web app & app service plan using VSTS. We have not tried using the ARM Template, however, this seems to be happening in UK South & UK West locations specifically. The same code\job works in other locations without any issues.

**Comment by nturinski** [comment]
Hi @nipunsahni

Hmm, have you tried creating new resource groups/app service plans in UK South & UK West locations?  Are they empty or are there running web apps associated with these rgs?
