### ISSUE TITLE
Unable to Azure Remote Debugging on macos via vscode Azure extension

### ISSUE THREAD

**Issue by syedadeel2** [microsoft/vscode-azureappservice#996]
After reading this link and follow all the instructions
https://code.visualstudio.com/docs/azure/remote-debugging

I'm getting this error:
Azure Remote Debugging is currently only supported for Node.js version >= 8.11 on Linux. I tried to install the same version but no luck. It's the same on windows as well. Below is the stack

Action: appService.StartRemoteDebug
Error type: Error
Error Message: Azure Remote Debugging is currently only supported for Node.js version >= 8.11 on Linux.

Version: 0.14.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.34.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.checkForRemoteDebugSupport extension.bundle.js:1:490774
extension.bundle.js:360:30589
o extension.bundle.js:360:29771
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by nturinski** [comment]
Hi @syedadeel2

Does your web app happen to be Node LTS?
