### ISSUE TITLE
An error occurs when selecting "Connect to a GitHub Repository…" under "Deployments" node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azureappservice#997]
**OS:** Win10 / Mac
**Build Version:** [20190519.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6115)
**Regression:**  Previous release (0.14.0)

**Repro Steps:**
1. Expand one web app -> Expand node "Deployments".
2. Select "Connect to a GitHub Repository...".
3. Check the result.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/41351993/58008894-ece2cd00-7b1f-11e9-8c0f-26d533f11eb3.png)

**Comment by nturinski** [comment]
Hi @v-xianya,

Thanks for your work and reporting this!  

I wasn't actually able to reproduce this error by following your repro steps.  Could you confirm that these are the exact steps to repro?

**Comment by v-xianya** [comment]
Hi @nturinski ,
Thanks for your updates. This issue still reproduce in my side.
 
Maybe you could try to reproduce this issue on the new created web app "Azure Tools Manual Testing 1 -> testforissue1" .

**Comment by nturinski** [comment]
Unfortunately, I do not have access to that web app and can't create any new resources in that subscription.

Do you have GitHub authorized with Azure??

**Comment by v-xianya** [comment]
Hi @nturinski , I am so sorry.

I have added you as a Contributor role to "Azure Tools Manual Testing 1" subscription. Could you help to 

try again? Thanks a lot!
